### ISSUE TITLE
doesitarm.com very laggy while scrolling

### ISSUE THREAD

**Issue by tyrann0us** [ThatGuySam/doesitarm#1]
Hi! If you scroll https://doesitarm.com, it's scrolls very "laggy".

macOS 10.15.7 (19H2)
Chrome 86.0.4240.111

Great service though!

**Comment by ThatGuySam** [comment]
I think my cool hipster Neumorphic Shadows I'm trying to do are too heavy for Chrome. 

I'll see if I can up those FPS

**Comment by ThatGuySam** [comment]
@tyrann0us Let me know if that helps

**Comment by tyrann0us** [comment]
Thanks @ThatGuySam! It's definitely better.
