### ISSUE TITLE
JabRef

### ISSUE THREAD

**Issue by Siedlerchr** [ThatGuySam/doesitarm#1001]
### The official name of the app

JabRef

### Is there a supported version available on a stable release channel?

Yes

### Proposed App Status

✅ Yes, Native Apple Silicon Support

### Proposed App Category

Science and Research Software

### Related Issue Tracker Links or discussion

https://github.com/JabRef/jabref

### An Official App Download Page

https://www.fosshub.com/JabRef.html

### Full Screenshot with the App and Activity Monitor(if self reporting) or Silicon Info

<img width="1571" alt="JabRefARM" src="https://user-images.githubusercontent.com/320228/210437595-e48bca08-a997-46e4-aef9-7e2f46f5ad26.png">

### Additional Context

A free reference manager that helps you to discover, collect, organize and cite your scholarly literature and research efficiently.

![jabref-mainscreen](https://user-images.githubusercontent.com/320228/210436906-b0c102e5-03fe-4630-9bbe-12c38fb33be3.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/jabref

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by Siedlerchr** [comment]
Just released. Version 5.11 (all previous versions since 5.8 were also for arm)
<img width="1573" alt="grafik" src="https://github.com/ThatGuySam/doesitarm/assets/320228/ffc79f12-d7fd-4070-b8a1-3d9e1db28c41">
