### ISSUE TITLE
Navicat Premium依然不能原生支持m1

### ISSUE THREAD

**Issue by saowu** [ThatGuySam/doesitarm#1003]
### The official name of the app

navicat-premium 16.1.3

### Is there a supported version available on a stable release channel?

Yes

### Proposed App Status

✳️ Yes, works via Translation or Virtualization

### Related Issue Tracker Links or discussion

https://github.com/ThatGuySam/doesitarm/issues/161

### An Official App Download Page

https://www.navicat.com.cn/download/navicat-premium

### Full Screenshot with the App and Activity Monitor(if self reporting) or Silicon Info

![screenshot-20230106-095659](https://user-images.githubusercontent.com/33569619/210914177-c992e498-7c48-4079-8bb9-d3296d1b5831.png)

**Comment by ThatGuySam** [comment]
Thanks for the update! 

It looks like the site already says that Navicat works via Rosetta 2 Translation: 
https://doesitarm.com/app/navicat-premium

**Comment by saowu** [comment]
![image](https://user-images.githubusercontent.com/33569619/216207330-3fcbb5ab-35aa-475c-b1fd-07aeeb9a4ea0.png)
可以更新一下信息

**Comment by ThatGuySam** [comment]
@saowu Those are based on scans and can only show Native and Unknown, not Rosetta support
