### ISSUE TITLE
Textify

### ISSUE THREAD

**Issue by yellow8-vom** [ThatGuySam/doesitarm#101]
**The official name of the app**
Textify - Image to Text PDF

**Proposed App Status**
✅ Full Native Apple Silicon Support

**Related Issue Tracker Link or discussion**
https://forums.macrumors.com/threads/textify-text-recognition-ocr-made-easy-and-accurate-1-product-of-the-day-ph.2245225/page-2?post=29016938#post-29016938

**An Official App Download Link**
https://apps.apple.com/app/id1522041836

**Comment by ThatGuySam** [comment]
Thanks for the App Request! This looks good to go!

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/textify

Feel free to browse through the other issues to help with missing info on other apps.

**Comment by yellow8-vom** [comment]
Thank you Sam!

**Comment by ThatGuySam** [comment]
Welcome!
