### ISSUE TITLE
iBoostUp

### ISSUE THREAD

**Issue by mariazx** [ThatGuySam/doesitarm#1010]
### The official name of the app

iBoostUp

### Is there a supported version available on a stable release channel?

No

### Proposed App Status

✅ Yes, Native Apple Silicon Support

### Proposed App Category

System Tools

### Related Issue Tracker Links or discussion

https://www.iboostup.com/download

### An Official App Download Page

https://www.iboostup.com/download

### Additional Context

https://apps.apple.com/au/app/iboostup/id484829041?mt=12

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise, I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/iboostup

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
