### ISSUE TITLE
BuhoCleaner

### ISSUE THREAD

**Issue by AskFeeds** [ThatGuySam/doesitarm#1013]
### The official name of the app

BuhoCleaner

### Is there a supported version available on a stable release channel?

Yes

### Proposed App Status

✅ Yes, Native Apple Silicon Support

### Proposed App Category

[Productivity Tools](https://github.com/ThatGuySam/doesitarm/blob/master/README.md#productivity-tools)

### Related Issue Tracker Links or discussion

https://doesitarm.com/app/buhocleaner

### An Official App Download Page

https://www.drbuho.com/buhocleaner/download

### Full Screenshot with the App and Activity Monitor(if self reporting) or Silicon Info

![Screenshot_2023-03-13_at_5_33_52_PM](https://user-images.githubusercontent.com/33158015/224662478-f9c01742-8877-45d8-9bab-a4faecf02493.jpg)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/buhocleaner

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
