### ISSUE TITLE
Oracle SQL Developer

### ISSUE THREAD

**Issue by wklope** [ThatGuySam/doesitarm#1014]
### The official name of the app

[Oracle SQL Developer](https://www.oracle.com/database/sqldeveloper/)

### Is there a supported version available on a stable release channel?

Yes

### Proposed App Status

✅ Yes, Native Apple Silicon Support

### Proposed App Category

Developer Tools

### Related Issue Tracker Links or discussion

[The download page](https://www.oracle.com/database/sqldeveloper/technologies/download/) lists x86-64 and aarch64 binaries.

### An Official App Download Page

https://www.oracle.com/database/sqldeveloper/technologies/download/

### Additional Context

Support for Arm was added in release 20.2. The current release is 23.1, which ships with its own copy of Oracle JDK 11 built for Arm.

**Comment by ThatGuySam** [comment]
Thanks for the report! 

App is now live on the site! 

https://doesitarm.com/app/oracle-sql-developer

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
