### ISSUE TITLE
Roblox Player

### ISSUE THREAD

**Issue by WEcompany36** [ThatGuySam/doesitarm#1019]
### The official name of the app

Roblox

### Is there a supported version available on a stable release channel?

Yes

### Proposed App Status

✅ Yes, Native Apple Silicon Support

### Related Issue Tracker Links or discussion

https://devforum.roblox.com/t/how-to-get-the-native-version-of-roblox-roblox-studio-for-apple-silicon/2459091

### An Official App Download Page

https://www.roblox.com/download

### Full Screenshot with the App and Activity Monitor(if self reporting) or Silicon Info

![Screenshot 2023-07-13 at 12 26 35 PM (2)](https://github.com/ThatGuySam/doesitarm/assets/79947933/03f5241f-b3b3-4f3d-bf98-058def67c0c4)

### Additional Context

Roblox and Roblox Studio are both supported with Apple Silicon. As of right now, it is a slow rollout so not everyone will have it. There are links here to download the Apple Silicon version: https://devforum.roblox.com/t/how-to-get-the-native-version-of-roblox-roblox-studio-for-apple-silicon/2459091

**Comment by WEcompany36** [comment]
Roblox has officially released it to everyone: https://devforum.roblox.com/t/native-support-for-apple-silicon-better-performance-and-improved-battery-life/2478678/9

**Comment by ThatGuySam** [comment]
@WEcompany36 Thanks for the report! 

Update is now live on the site! 

https://doesitarm.com/app/roblox-player

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
