### ISSUE TITLE
Wondershare uniconverter

### ISSUE THREAD

**Issue by ehsan58** [ThatGuySam/doesitarm#1020]
### The official name of the app

Wondershare uniconverter

### Is there a supported version available on a stable release channel?

Yes

### Proposed App Status

M1 compatible 

### Related Issue Tracker Links or discussion

Old version trsted on the repo

### Full Screenshot with the App and Activity Monitor(if self reporting) or Silicon Info

https://videoconverter.wondershare.com/mac/macbook-m1.html

**Comment by ThatGuySam** [comment]
@ehsan58 Thanks for the report! 

Update is now live on the site! 

https://doesitarm.com/app/wondershare-filmora

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
