### ISSUE TITLE
Celeste

### ISSUE THREAD

**Issue by pixelomer** [ThatGuySam/doesitarm#1021]
### The official name of the app

Celeste

### Is there a supported version available on a stable release channel?

Yes

### Proposed App Status

✳️ Runs well with Rosetta as of version 1.4.0.0

### Related Issue Tracker Links or discussion

https://github.com/ThatGuySam/doesitarm/issues/598#issuecomment-942900676
https://github.com/AbeJellinek/celeste-on-m1/issues/5
https://celeste.ink/wiki/Version_history

### An Official App Download Page

https://mattmakesgames.itch.io/celeste

### Full Screenshot with the App and Activity Monitor(if self reporting) or Silicon Info

![Screenshot](https://github.com/ThatGuySam/doesitarm/assets/37103802/de6c990a-10a7-4af9-91eb-31e556c12637)

### Additional Context

[The original report for this game](https://github.com/ThatGuySam/doesitarm/issues/598) was incorrect. The linked GitHub repository does not add native Apple Silicon support to the game. Rather, it replaces existing Intel binaries with newer Intel binaries to make the game work with Rosetta.

**Comment by ThatGuySam** [comment]
@pixelomer Thanks for the report! 
Update is now live on the site! 

https://doesitarm.com/app/celeste

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by iwa** [comment]
hey! im the one who opened the original issue, little note on what you said:

> The linked GitHub repository does not add native Apple Silicon support to the game. Rather, it replaces existing Intel binaries with newer Intel binaries to make the game work with Rosetta.

it's not quite that, manually replacing the libs with arm64-compiled ones worked on 1.3, but they made some internal changes with the 1.4 update of the game, thus breaking the workaround
so we're not replacing Intel libs with newer Intel libs, we're still adding arm64-compiled libs, but as they're no longer used by the game, they're just sitting there, thus being useless and the game still running through Rosetta

no impact on the information given tho, the game is still running fine through Rosetta, just wanted to give the precision to explain how things evolved! 😉

**Comment by pixelomer** [comment]
> hey! im the one who opened the original issue, little note on what you said:
> 
> > The linked GitHub repository does not add native Apple Silicon support to the game. Rather, it replaces existing Intel binaries with newer Intel binaries to make the game work with Rosetta.
> 
> it's not quite that, manually replacing the libs with arm64-compiled ones worked on 1.3, but they made some internal changes with the 1.4 update of the game, thus breaking the workaround so we're not replacing Intel libs with newer Intel libs, we're still adding arm64-compiled libs, but as they're no longer used by the game, they're just sitting there, thus being useless and the game still running through Rosetta
> 
> no impact on the information given tho, the game is still running fine through Rosetta, just wanted to give some precisions to explain how things evolved! 😉

I'm not sure if I understand what you are saying but you can't just replace the libraries of an x86_64 executable with arm64 builds to make it run natively. The executable won't launch if you do this because you cannot mix arm64 with x86_64.
