### ISSUE TITLE
PDF Expert

### ISSUE THREAD

**Issue by hsing0527** [ThatGuySam/doesitarm#103]
PDF Expert does it arm

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by istvan60** [comment]
Download link: https://pdfexpert.com/lp-free-apple-btn?utm_source=google&utm_medium=cpc&utm_campaign=pdf-lp-mac_test_two-ww&utm_google-campaign=pdf-lp-mac_test_two-ww&utm_content=481823594802&utm_term=pdf&gclid=CjwKCAiAnvj9BRA4EiwAuUMDf-wTP6DC5pSDrhWFpri2VJlW2dl6ygHyYF0hOSGj483tTdQmDAflCxoC7sgQAvD_BwE

Needs testing.

**Comment by istvan60** [comment]
Allegedly it works with Rosetta2 seamlessly:

https://forums.macrumors.com/threads/adobe-pdf-reader-can-not-be-installed-on-m1.2271696/post-29313072

**Comment by ThatGuySam** [comment]
Looks we need a screenshot. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by syhily** [comment]
**The official name of the app**
PDF Expert

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support as of 2.5.15

**Related Issue Tracker Link or discussion**
https://pdfexpert.com/beta/changelog

**An Official App Download Page**
https://pdfexpert.com/downloads

**Comment by ThatGuySam** [comment]
Looks like Apple Silicon support is still in beta and v2.5.15 is currently missing from the normal changelog: 

https://pdfexpert.com/changelog

**Comment by raphaelgurtner** [comment]
Changelog doesn't mention anything and can only report from an intel mac but Silicon reports universal binary for version 2.5.16

<img width="1467" alt="image" src="https://user-images.githubusercontent.com/24231518/104038856-e530da00-51d5-11eb-9d8d-fe03eadde5df.png">

**Comment by moffpage** [comment]
Why is it still an issue though? @ThatGuySam please update info
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/33549573/119227875-fb5e8780-bb31-11eb-9606-2f0232841b3e.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/119227878-fbf71e00-bb31-11eb-8e97-28ed8275f6ac.png">

**Comment by ThatGuySam** [comment]
Thanks, @moffpage!

App is now live on the site! 

https://doesitarm.com/app/pdf-expert/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
