### ISSUE TITLE
Please add Q-emuLator

### ISSUE THREAD

**Issue by mhwal** [ThatGuySam/doesitarm#104]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**The official name of the app**
Q-emuLator for macOS

**Proposed App Status**
What's the current app status based off of current discussion
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend 

**Related Issue Tracker Link or discussion**
This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes. 

**An Official App Download Link**
This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site. 

http://www.terdina.net/ql/MacQL.html

![B55C289F-3FDF-4237-879B-481CA8C355F1](https://user-images.githubusercontent.com/74457935/99148454-ff43b580-2687-11eb-848e-caa32e2855d9.jpeg)

**Additional context**
Add any other context or screenshots about the app request here.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by moffpage** [comment]
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/33549573/123591747-324d4a80-d80e-11eb-8048-4b6750e4c07c.png">
Works via Rosetta 2

**Comment by ThatGuySam** [comment]
@moffpage Excellent! 

We'll use the following status:
✳️ Yes, works via Rosetta 2 translation

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/q-emulator/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
