### ISSUE TITLE
Add Julia Language

### ISSUE THREAD

**Issue by pawelostr** [ThatGuySam/doesitarm#106]
**The official name of the app**
Julia Language

**Proposed App Status**
Native - not yet.
Rosetta - one report it works in discussion below.

**Related Issue Tracker Link or discussion**
https://github.com/JuliaLang/julia/issues/36617

**An Official App Download Link**
https://julialang.org/downloads/

**Additional context**

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Status for this will be:
✅ Yes, it works via Rosetta 2

**Comment by ThatGuySam** [comment]
This is now ready to go!

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/julia-language/

Feel free to browse through the other issues to help with missing info on other apps.
