### ISSUE TITLE
Add Clang

### ISSUE THREAD

**Issue by pawelostr** [ThatGuySam/doesitarm#107]
**The official name of the app**
LLVM Clang

**Proposed App Status**
Reported working using Rosetta 2.
No info on native support.

**Related Issue Tracker Link or discussion**
Couldn't find anything better than that, but it appears to be from an Apple Engineer:
https://developer.apple.com/forums/thread/649992

**An Official App Download Link**
https://releases.llvm.org/download.html

**Additional context**

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

We can report the status as: 
✳️ Yes, it works via Rosetta 2

**Comment by ThatGuySam** [comment]
This is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/llvm-clang

Feel free to browse through the other issues to help with missing info on other apps.
