### ISSUE TITLE
Inkscape

### ISSUE THREAD

**Issue by jibaku** [ThatGuySam/doesitarm#11]
It would be nice to add https://inkscape.org

I've found this but it's more related to Big Sur than to ARM
https://gitlab.com/inkscape/inkscape/-/issues/1669

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by jibaku** [comment]
**The official name of the app**
Inkscape

**Proposed App Status**
I think it was never tested, nor discussed

Related Issue Tracker Link or discussion
Official post: Nothing found

An Official App Download Link
https://inkscape.org | https://formulae.brew.sh/cask/inkscape

**Comment by xanekka** [comment]
Works fine with Rosetta.

**Comment by ThatGuySam** [comment]
Wonderful! Let's drop a screenshot or a link to use as a source and we'll be able to move to the next step

You can find a screenshot example on #176

**Comment by xanekka** [comment]
<img width="808" alt="Screen Shot 2020-11-20 at 11 32 10 PM" src="https://user-images.githubusercontent.com/11390681/99867561-a5ac2100-2b88-11eb-8b9e-1a0a0684c12d.png">

**Comment by ThatGuySam** [comment]
Status: ✳️ Yes, works via Rosetta 2

**Comment by ThatGuySam** [comment]
This is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/inkscape

Feel free to browse through the other issues to help with missing info on other apps.
