### ISSUE TITLE
Arduino IDE

### ISSUE THREAD

**Issue by Spirik** [ThatGuySam/doesitarm#110]
**The official name of the app**
Arduino IDE

**Proposed App Status**
✳️ Reported working via Rosetta with native support currently in development

**Related Issue Tracker Link or discussion**
Official repository issue: https://github.com/arduino/Arduino/issues/10836

**An Official App Download Link**
https://www.arduino.cc/en/software

**Comment by ThatGuySam** [comment]
Let’s change the verbiage of the status to be:

Reported working via Rosetta with native support currently in development

**Comment by Spirik** [comment]
> Let’s change the verbiage of the status to be:

Done.

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by Spirik** [comment]
Done: https://github.com/ThatGuySam/doesitarm/pull/171 .

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/arduino-ide/

Feel free to browse through the other issues to help with missing info on other apps.
