### ISSUE TITLE
Python 2 & 3 are compatible

### ISSUE THREAD

**Issue by Maxmad68** [ThatGuySam/doesitarm#111]
Good morning,
Python (2.7.16 & 3.8.2) work well on my DTK, and are universal builds.
Here is a screenshot of an SSH connection to the DTK, using Python.
I didn’t try some C libraries, such as Numpy or Scipy, so I can’t tell for those ones.

![18593090-F04D-40CB-9658-036CA02A34EC](https://user-images.githubusercontent.com/17316839/99182151-708c7280-2733-11eb-86ae-ca4fdef419fb.png)

**Comment by ThatGuySam** [comment]
Thanks for the Update!

Is that running native or via Rosetta?

**Comment by ThatGuySam** [comment]
Looks it’s reported working on v2.7.16, v3.8.2, and v3.9

**Comment by ThatGuySam** [comment]
Update is live! 

https://doesitarm.com/app/python/

Thanks for the help and feel free to browse through https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+Reported+Status%22 if your time permits. 

DTK devs are always welcome here. 

![IMG_0110](https://user-images.githubusercontent.com/2830379/99191094-058d6c80-2730-11eb-895c-7ab732277222.png)
