### ISSUE TITLE
Please add IBM SPSS

### ISSUE THREAD

**Issue by istvan60** [ThatGuySam/doesitarm#113]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**The official name of the app**
IBM SPSS

**Proposed App Status**
No information on this

**An Official App Download Link**
https://www.ibm.com/account/reg/hu-en/signup?formid=urx-19774 This is a link to download the demo

**Additional context**
It's JAVA based.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

If you find a tracker link such as an Issue or Discussion feel free to add it

**Comment by EddieFua** [comment]
How can I to download spss on my new computer of apple silicon? And can I operate normally? Thank you

**Comment by ThatGuySam** [comment]
@EddieFua Looks like you'll have to create an account but since it's just for testing you can use one of those temporary email sites.

**Comment by ThatGuySam** [comment]
@istvan60 @sdavern Is there a sample project file we can use to verify the usability of the app once we start it up on an Apple Silicon machine?

**Comment by sdavern** [comment]
Hiya, here’s a link to some sample files:
https://study.sagepub.com/aldrich3e/student-resources/ibm®-spss-®-sample-files

Thanks for your help!

**Comment by grimfrost** [comment]
Is this app working as expected and stable? Can you please confirm this?

**Comment by ThatGuySam** [comment]
@grimfrost That's what we're working on. I have a private report that there are install issues. If I can get additional reports to confirm then we'll go ahead and publish the status.

**Comment by ThatGuySam** [comment]
I've pinned this issue so it can get priority since there's a lot of people asking

**Comment by sdavern** [comment]
https://community.ibm.com/community/user/datascience/blogs/todd-peterson1/2020/11/20/spss-statistics-on-macos-big-sur-110

It works!

**Comment by ThatGuySam** [comment]
@sdavern I can’t seem to view that post. 

Do I need an account to see it?

**Comment by sdavern** [comment]
I don't think so, I've attached a PDF of the page anyway.
[SPSS Statistics - IBM Data Science Community.pdf](https://github.com/ThatGuySam/doesitarm/files/5584855/SPSS.Statistics.-.IBM.Data.Science.Community.pdf)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/ibm-spss/

Feel free to browse through the other issues to help with missing info on other apps.
