### ISSUE TITLE
Please add CorelDraw 2019

### ISSUE THREAD

**Issue by istvan60** [ThatGuySam/doesitarm#114]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**The official name of the app**
CorelDraw 2019

**Proposed App Status**
No idea, has to be tested under Rosetta 2

**An Official App Download Link**
https://www.corel.com/akdlm/6763/downloads/free/trials/GraphicsSuite/2020/F4g6tt98/CDGS2020.dmg (link to the demo)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Feel free to add a tracker link if you find one

**Comment by harryzcy** [comment]
CorelDraw 2021 supports Apple Silicon now. https://9to5mac.com/2021/03/09/coreldraw-graphics-suite-2021-apple-silicon-mac-ipad-app/.
CorelDraw 2019 probably will never have native support.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/coreldraw/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
