### ISSUE TITLE
Add CotEditor(PR is ready)

### ISSUE THREAD

**Issue by EddaAkikusa** [ThatGuySam/doesitarm#119]
**The official name of the app**
CotEditor

**Proposed App Status**
As the update of 4.0.0, it adds native support to Apple Silicon

**Related Issue Tracker Link or discussion**
Nope.

**An Official App Download Link**
[App Store](https://apps.apple.com/cn/app/coteditor/id1024640650)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/coteditor/

Thanks again for the Pull Request. 

You the real MVP

<img width="1792" alt="Screen Shot 2020-11-16 at 11 44 44 AM" src="https://user-images.githubusercontent.com/2830379/99288431-34bfde80-2801-11eb-8b51-fc607fe48541.png">
