### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by jibaku** [ThatGuySam/doesitarm#12]
Work in progress : https://github.com/python/cpython/pull/22855

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ThatGuySam** [comment]
Added!

https://doesitarm.com/app/python/
