### ISSUE TITLE
Add Ulysses

### ISSUE THREAD

**Issue by EddaAkikusa** [ThatGuySam/doesitarm#120]
**The official name of the app** 
Ulysses

**Proposed App Status**
It provides native support because the latest version (aka version 21) is distributed in universal binary format.

**Related Issue Tracker Link or discussion**
Nope. The compatibility is not even motioned by the developer.

**An Official App Download Link**
[App Store](https://apps.apple.com/cn/app/ulysses/id1225570693?mt=12)

**Additional context**

<img width="585" alt="QQ20201116-135905@2x" src="https://user-images.githubusercontent.com/4312700/99217821-ed8f1900-2813-11eb-9137-faede4fbb140.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

**Comment by iLtc** [comment]
They briefly mentioned in their newsletter that the new version runs on the M1 Macs, but I can't find any confirmation in their release notes or blogs.

![image](https://user-images.githubusercontent.com/4352234/99720856-5bd61480-2a7c-11eb-910a-e1ca1afb5511.png)

The only source I can find is an article from MacRumors:

https://www.macrumors.com/2020/11/13/apple-silicon-macs-universal-apps/

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/ulysses/

Feel free to browse through the other issues to help with missing info on other apps.

**Comment by LER0ever** [comment]
@ThatGuySam Does not seem to be m1 native as of v21.

In their official release note, they only said that it "runs" on m1 macs, by which they meant through Rosetta 2 I assume.

<img width="1266" alt="Screen Shot 2020-12-23 at 5 36 22 PM" src="https://user-images.githubusercontent.com/10568668/102982454-7dc42a80-4545-11eb-9a0a-cec66295e90a.png">

**Comment by ThatGuySam** [comment]
@LER0ever Interesting. 

The MacRumors article says it has a Universal Binary but I can't find anything on Ulysses' official site or app listing about Universal or Native support

https://ulysses.app/releases/

<img width="658" alt="Screen Shot 2020-12-23 at 11 57 05 AM" src="https://user-images.githubusercontent.com/2830379/103025058-aaad1900-4516-11eb-8e44-cc400dcaa1bd.png">
<img width="643" alt="Screen Shot 2020-12-23 at 11 57 14 AM" src="https://user-images.githubusercontent.com/2830379/103025077-b0a2fa00-4516-11eb-895e-e5d0007265d6.png">

**Comment by ThatGuySam** [comment]
I've downgrade Ulysses to "✳️ Yes, works via Rosetta 2" for now

**Comment by EddaAkikusa** [comment]
<img width="1123" alt="QQ20201224-091317@2x" src="https://user-images.githubusercontent.com/4312700/103048045-4d71a000-45c8-11eb-8464-9aff65a193de.png">
It's good to me.
