### ISSUE TITLE
Add DOSBox

### ISSUE THREAD

**Issue by EddaAkikusa** [ThatGuySam/doesitarm#121]
**The official name of the app**
DOSBox

**Proposed App Status**
It's believed that it should work with Rosetta 2 well. Native support is being worked on.

**Related Issue Tracker Link or discussion**
[Project Ticket 149](https://sourceforge.net/p/dosbox/feature-requests/149/)

**An Official App Download Link**
[Site](https://sourceforge.net/projects/dosbox/)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

It looks like that Ticket Confirms it works on Rosetta 2 so we'll give it the following status: 
✳️ Yes, it works via Rosetta 2

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.
