### ISSUE TITLE
Charles Web Debugging Proxy

### ISSUE THREAD

**Issue by wilsonjwz** [ThatGuySam/doesitarm#122]
**The official name of the app**
Charles Web Debugging Proxy

**Is there a supported version available on a stable release channel?**
Unknown

**Proposed App Status**
🔶 Unknown, more info needed

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
None yet

**An Official App Download Page**
https://www.charlesproxy.com/download/

**Additional context**
None yet

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
None yet

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by aruis** [comment]
Charles is ok, Rosetta 2 is work.
![截屏2020-12-29 上午8 43 17](https://user-images.githubusercontent.com/1785495/103251062-13cadb80-49b2-11eb-8cbd-4e3bcd3df781.png)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/charles-web-debugging-proxy/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
