### ISSUE TITLE
Anaconda

### ISSUE THREAD

**Issue by nandanosql** [ThatGuySam/doesitarm#123]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**The official name of the app**
What's the full official name of the app
Anaconda

**Proposed App Status**
What's the current app status based off of current discussion or testing
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend 

**Related Issue Tracker Link or discussion**
This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes. 

**An Official App Download Link**
This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site. 
https://www.anaconda.com/

**Additional context**
Add any other context or screenshots about the app request here.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by bharadwaj6** [comment]
Works with Rosetta 2

<img width="922" alt="Screenshot 2021-01-02 at 15 07 23" src="https://user-images.githubusercontent.com/1695154/103454674-5cfd9100-4d0c-11eb-89b1-eaa6ae2ad46d.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/anaconda/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by raphaelgurtner** [comment]
Anaconda is now available for M1 as of 2022-05-06 (date of the blog article here: https://www.anaconda.com/blog/new-release-anaconda-distribution-now-supporting-m1)

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/24231518/172540478-ed9c5b81-6fe8-4a39-a151-35f6b6dd1dec.png">
<img width="906" alt="image" src="https://user-images.githubusercontent.com/24231518/172541219-c26e4acc-d911-43e0-a082-7215d7c6b7ed.png">

**Comment by ThatGuySam** [comment]
@raphaelgurtner Thanks for the update! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by amandaallissa** [comment]
@raphaelgurtner  Thank you for your help! 
App is now updated on the site!

https://doesitarm.com/app/anaconda/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
