### ISSUE TITLE
Powershell Core

### ISSUE THREAD

**Issue by KaiserThaws** [ThatGuySam/doesitarm#125]
**The official name of the app**
Powershell Core

**Proposed App Status**
Not yet supported only works on Intel-based Macs

**Related Issue Tracker Link or discussion**
N/A

**An Official App Download Link**
https://github.com/PowerShell/PowerShell

**Additional context**
N/A

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by thunderstorm99** [comment]
Powershell Core works fine via Rosetta 2. See attached screenshot.
![Screen Shot 2020-12-01 at 20 40 16](https://user-images.githubusercontent.com/3219279/100788621-9f823400-3415-11eb-9a25-b0aba9361387.png)

**Comment by ThatGuySam** [comment]
@thunderstorm99 You're a beautiful person! 

Status: ✳️ Yes, works via Rosetta 2

**Comment by ThatGuySam** [comment]
We can now add this to the list. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/powershell-core/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by kai-h** [comment]
This also works for PowerShell remote sessions, e.g. to administer Office 365, if you do the following:
Install PowerShell from the x86_64 package release on GitHub
https://github.com/powershell/powershell/releases

Then, install OpenSSL as a Universal binary with MacPorts
https://www.macports.org
```
sudo port install openssl10 +universal
```

**Comment by amadejpapez** [comment]
The latest 7.2.0 preview offers an M1 native build (https://github.com/PowerShell/PowerShell/releases/download/v7.2.0-preview.9/powershell-7.2.0-preview.9-osx-arm64.tar.gz) and they have closed the GitHub issue https://github.com/PowerShell/PowerShell/issues/15146 so this should come with the next release. :)

**Comment by ThatGuySam** [comment]
@amadejpapez Great catch! Update is now live on the site! 

https://doesitarm.com/app/powershell-core/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
