### ISSUE TITLE
SubEthaEdit

### ISSUE THREAD

**Issue by monkeydom** [ThatGuySam/doesitarm#127]
**The official name of the app**
SubEthaEdit

**Proposed App Status**
v5.1.5 - Available both in App Store and on Web: https://subethaedit.net
Also available as brew cask install `brew cask install SubEthaEdit`

**Related Issue Tracker Link or discussion**
https://github.com/subethaedit/SubEthaEdit/releases/tag/SubEthaEdit-MacFull-5.1.5

**An Official App Download Link**
https://subethaedit.net/SubEthaEdit.zip

**Comment by monkeydom** [comment]
How can I provide reported status?
It is in the release notes
https://github.com/subethaedit/SubEthaEdit/blob/releases/ChangeLog.md

A consistent status line would be:

✅ Yes, full native support as of 5.1.5 - [Release Notes](https://github.com/subethaedit/SubEthaEdit/blob/releases/ChangeLog.md)

**Comment by monkeydom** [comment]
<img width="174" alt="image" src="https://user-images.githubusercontent.com/5106/99422955-594eb000-2900-11eb-8f0a-2e6563d23c43.png">

**Comment by monkeydom** [comment]
Added Pull Request #164

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/subethaedit/

Feel free to browse through the other issues to help with missing info on other apps.
