### ISSUE TITLE
TensorFlow

### ISSUE THREAD

**Issue by ThatGuySam** [ThatGuySam/doesitarm#128]
**The official name of the app**
TensorFlow

**Proposed App Status**
No status yet. Needs testing but based on the issue discussion devs seem optimistic about compatibility

**Related Issue Tracker Link or discussion**
https://github.com/tensorflow/tensorflow/issues/44751

**An Official App Download Link**
https://www.tensorflow.org/

**Additional context**
Add any other context or screenshots about the app request here.

**Comment by KovalevArtem** [comment]
New Mac-optimized TensorFlow 2.4 fork lets you speed up training on Macs, resulting in up to 7x faster performance on platforms with the new M1 chip!
https://blog.tensorflow.org/2020/11/accelerating-tensorflow-performance-on-mac.html

**Comment by ThatGuySam** [comment]
We can go ahead and give it the following status: 
✅ Yes, Full Native Apple Silicon Support as of v2.4.0

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/tensorflow/

Feel free to browse through the other issues to help with missing info on other apps.

**Comment by KovalevArtem** [comment]
https://machinelearning.apple.com/updates/ml-compute-training-on-mac
