### ISSUE TITLE
Expandrive

### ISSUE THREAD

**Issue by jc0b** [ThatGuySam/doesitarm#129]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**The official name of the app**
Expandrive

**Proposed App Status**
Based off of contact with Expandrive, the application doesn't currently run on Apple Silicon. Version 7.6.5 doesn't support Apple Silicon, newer versions should.

**Related Issue Tracker Link or discussion**
https://www.expandrive.com/release-notes/expandrive/

**An Official App Download Link**
https://www.expandrive.com/download-expandrive/

**Additional context**
None.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to find a tracker link. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it.

**Comment by moffpage** [comment]
How is their release notes page doesn't fit as being a tracker link? Btw, at the moment (late may 2021) it still doesn't support Apple Silicon

**Comment by ThatGuySam** [comment]
@moffpage A tracker link can be anything use to determine updates on the app's support

Can you drop a screenshot of the error state or message that happens when you run the app?

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/expandrive/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
