### ISSUE TITLE
Beamer

### ISSUE THREAD

**Issue by hellojole** [ThatGuySam/doesitarm#132]
**The official name of the app**
Beamer

**An Official App Download Link**
https://beamer-app.com/

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/beamer/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by tjluoma** [comment]
It now works via Rosetta (formerly it crashed immediately on Apple Silicon)

**Comment by ThatGuySam** [comment]
@tjluoma That's good news! 

Next, we'll need someone with an M1 to provide a screenshot or a note from the developer. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by tjluoma** [comment]
https://beamer-app.com/release-notes/3.5.html

> Release Notes for Beamer 3.5
> Adds support for Apple Silicon Macs
> Fixes layout issues on macOS Big Sur

It is not yet _native_ on Apple Silicon but here's a screenshot of it _running_ on an M1 Mac:

![CleanShot 2021-03-22 at 18 02 32@2x](https://user-images.githubusercontent.com/26965/112064177-f16fd680-8b38-11eb-9ed5-59605bb83f31.png)

**Comment by ThatGuySam** [comment]
Looks like the latest version of the app is not native so it's probably a safe guess that they've gotten it working via Rosetta 2 translation. 
<img width="1792" alt="Screen Shot 2021-03-23 at 9 46 09 AM" src="https://user-images.githubusercontent.com/2830379/112165383-b31bfb00-8bbc-11eb-96d5-4eb69a7637b4.png">

**Comment by ThatGuySam** [comment]
We'll use the following status: 
✳️ Yes, works via Rosetta 2 Translation
