### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by SWOOI** [ThatGuySam/doesitarm#134]

**Comment by SWOOI** [comment]
New app request

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by qu1gl3s** [comment]
I'll jump in and fill in these details.

The official name of the app: Zoom

Proposed App Status: Yes, works via Rosetta 2

Proposed App Category: Social and communication

Related Issue Tracker Link or discussion: Nothing available, no word from Zoom.

An Official App Download Link: https://zoom.us/download

Additional context: (I have a DTK and have been testing Zoom, don't have any issues to address)

**Comment by iLtc** [comment]
The virtual background feature is not working on my DTK. Not sure if they will fix it.

**Comment by ThatGuySam** [comment]
And we're live!

https://doesitarm.com/app/zoom/

Thanks for the help! Feel free to looks through other issues that have missing info

**Comment by KovalevArtem** [comment]
https://twitter.com/JensenPat/status/1326295788343881728

**Comment by mahenzon** [comment]
https://twitter.com/JensenPat/status/1341046946761375744

https://support.zoom.us/hc/en-us/articles/360053176572-New-updates-for-December-21-2020

Support for Apple Silicon processors - macOS
Zoom desktop client will better support computers with ARM CPUs. A separate installer is available for download in the Zoom Download Center.

**Comment by ThatGuySam** [comment]
Update is live! 

https://doesitarm.com/app/zoom/
