### ISSUE TITLE
Dashlane

### ISSUE THREAD

**Issue by apsylone** [ThatGuySam/doesitarm#136]
**The official name of the app**
Dashlane

**An Official App Download Link**
https://www.dashlane.com/

Release Notes
https://support.dashlane.com/hc/en-us/articles/360014075719-macOS-app-updates

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by moffpage** [comment]
You can close this issue, I'm gonna update the info within a request soon

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/dashlane/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
