### ISSUE TITLE
flutter

### ISSUE THREAD

**Issue by w88quan** [ThatGuySam/doesitarm#138]
The official name of the app
Flutter

link
https://flutter.dev

See the issue tracker
https://github.com/flutter/flutter/issues

An Official App Download Link
https://flutter.dev/docs/get-started/install

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by w88quan** [comment]
@> Thanks for the App Request!
> 
> The next step is to collect the missing info.
> 
> I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it.
> 
> You can reference what all it needs here:
> [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)



> Thanks for the App Request!
> 
> The next step is to collect the missing info.
> 
> I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it.
> 
> You can reference what all it needs here:
> [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)



> Thanks for the App Request!
> 
> The next step is to collect the missing info.
> 
> I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it.
> 
> You can reference what all it needs here:
> [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by w88quan** [comment]
> Thanks for the App Request!
> 
> The next step is to collect the missing info.
> 
> I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it.
> 
> You can reference what all it needs here:
> [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

I'm using translation software, which is probably inaccurate. Thanks for the trouble

**Comment by ThatGuySam** [comment]
If you’re using Rosetta 2 that still counts otherwise we can leave the issue open for someone else who may come along and have more information on it

**Comment by tonyunreal** [comment]
**The official name of the app**
Flutter

**Proposed App Status**
Yes, building and running through desktop works via Rosetta 2. Attaching to an iOS simulator on Apple Silicon is broken at the moment (see links below). Running locally through an Android Emulator currently impossible.

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
Summary: https://github.com/flutter/flutter/issues/60118
iOS Simulator issue: https://github.com/flutter/flutter/issues/64502
Android Emulator issue: https://github.com/flutter/flutter/issues/69227

**An Official App Download Link**
https://flutter.dev/docs/get-started/install/macos

**Comment by ThatGuySam** [comment]
Let’s give it the following status: 
✳️ Yes, works via Rosetta 2 with native support in development

**Comment by ThatGuySam** [comment]
This is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/flutter/

Feel free to browse through the other issues to help with missing info on other apps.
