### ISSUE TITLE
Update Rust Status

### ISSUE THREAD

**Issue by ibraheemdev** [ThatGuySam/doesitarm#139]
Rust's status should be "Runs natively on Apple Silicon". The linked issue states that the Intel targets can run on Rosetta, but there is also a native arm target available with tier 2 support.

**Comment by ThatGuySam** [comment]
Are these builds available via homebrew or the Rust website download page. 

Basically, just available without using preview builds

**Comment by EddaAkikusa** [comment]
There is a native `nightly-aarch64-apple-darwin` toolchain can be installed via `rustup`.
I'm using an Intel-based Mac now.
```
# rustup toolchain install nightly-aarch64-apple-darwin
info: syncing channel updates for 'nightly-aarch64-apple-darwin'
689.0 KiB / 689.0 KiB (100 %) 391.7 KiB/s in  1s ETA:  0s
info: latest update on 2020-11-17, rust version 1.50.0-nightly (f5230fbf7 2020-11-16)
info: downloading component 'cargo'
  3.5 MiB /   3.5 MiB (100 %)   1.2 MiB/s in  2s ETA:  0s
info: downloading component 'clippy'
  1.5 MiB /   1.5 MiB (100 %)   1.5 MiB/s in  2s ETA:  0s
info: downloading component 'rust-std'
 17.8 MiB /  17.8 MiB (100 %)   3.5 MiB/s in  6s ETA:  0s
info: downloading component 'rustc'
 41.8 MiB /  41.8 MiB (100 %)   4.6 MiB/s in 12s ETA:  0s
info: downloading component 'rustfmt'
  1.9 MiB /   1.9 MiB (100 %) 762.3 KiB/s in  2s ETA:  0s
info: installing component 'cargo'
info: Defaulting to 500.0 MiB unpack ram
info: installing component 'clippy'
info: installing component 'rust-std'
 17.8 MiB /  17.8 MiB (100 %)   7.5 MiB/s in  2s ETA:  0s
info: installing component 'rustc'
 41.8 MiB /  41.8 MiB (100 %)   9.8 MiB/s in  4s ETA:  0s
info: installing component 'rustfmt'

  nightly-aarch64-apple-darwin installed - (error reading rustc version)

info: checking for self-updates
```
and
```
# pwd
/Users/alpine/.rustup/toolchains/nightly-aarch64-apple-darwin/bin
# file rustc 
rustc: Mach-O 64-bit executable arm64
```

**Comment by ibraheemdev** [comment]
@ThatGuySam the official way to download rust is with rustup. Rustup supports native apple silicon with the nightly channel, and the stable channel is just waiting on the next rustup release. The status should be something like: "Native support for nightly, stable releases coming soon"


[Nightly installation instructions](https://github.com/shepmaster/rust/blob/silicon/silicon/README.md)

**Comment by ThatGuySam** [comment]
Update is live!

https://doesitarm.com/app/rust/
