### ISSUE TITLE
Sketchup

### ISSUE THREAD

**Issue by harold2508** [ThatGuySam/doesitarm#14]
Sketchup on M1? I’ll it arm?

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ThatGuySam** [comment]
Looks they aren’t planning on being ready for the launch but it may still work via Rosetta

https://forums.sketchup.com/t/sketchup-for-apple-silicon-macs/129447

**Comment by ThatGuySam** [comment]
Download link

https://www.sketchup.com/

**Comment by tokamac** [comment]
> https://forums.sketchup.com/t/sketchup-for-apple-silicon-macs/129447

This was the old (June 2020) thread when the transition to Apple Silicon was unveiled. Current thread is: 
https://forums.sketchup.com/t/the-new-m1-processor/141946

**Comment by ThatGuySam** [comment]
It looks like the status is that's it's supported via Rosetta

**Comment by ThatGuySam** [comment]
This is good to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/sketchup/

Feel free to browse through the other issues to help with missing info on other apps.
