### ISSUE TITLE
Oracle jdk

### ISSUE THREAD

**Issue by xueson-lk** [ThatGuySam/doesitarm#140]
Want to add Oracle JDK

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by moffpage** [comment]
Which JDK? E.g. JDK 11 has arm64 support, JDK 8 doesn't as far as I know at the moment

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/oracle-jdk/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
