### ISSUE TITLE
Keybase

### ISSUE THREAD

**Issue by marty331** [ThatGuySam/doesitarm#143]
**The official name of the app**
Keybase

**Proposed App Status**
Unknown

**Related Issue Tracker Link or discussion**
Has not been reported - https://keybase.io/docs/bug_reporting

**An Official App Download Link**
https://keybase.io/download

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by marty331** [comment]
I've opened this issue with Keybase, hopefully we can get an answer soon. - https://github.com/keybase/keybase-issues/issues/3968

**Comment by rakleed** [comment]
**The official name of the app**
Keybase

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️  Yes, works via Translation or Virtualization

**Proposed App Category**
Social and Communication

**Related Issue Tracker Links or discussion**
https://github.com/keybase/keybase-issues/issues/3968, https://github.com/keybase/keybase-issues/issues/4054

**An Official App Download Page**
https://keybase.io/docs/the_app/install_macos

**Additional context**


**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![image](https://user-images.githubusercontent.com/19418601/150031227-8783c213-d765-45a5-88a4-a71ad34402f0.png)

**Comment by ThatGuySam** [comment]
Thanks for the patience on this! App is now live on the site! 

https://doesitarm.com/app/keybase/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
