### ISSUE TITLE
SecureCRT

### ISSUE THREAD

**Issue by zgr0629** [ThatGuySam/doesitarm#145]
**The official name of the app**
SecureCRT

**Proposed App Status**
Not tested yet. But expected works via Rosetta 2.

**Related Issue Tracker Link or discussion**
VanDyke Product Director's reply: [https://forums.vandyke.com/showthread.php?t=14277](https://forums.vandyke.com/showthread.php?t=14277)

**An Official App Download Link**
https://www.vandyke.com/download/index.html

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ThatGuySam** [comment]
App listing is up! 

https://doesitarm.com/app/securecrt/

**Comment by Ender519** [comment]
Be aware, as of Version 9.2.0 (build 2712) - Beta Release - March 3, 2022 the app is native to M1

**Comment by ThatGuySam** [comment]
Thanks, @Ender519! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App native support is now live on the site! 

https://doesitarm.com/app/securecrt/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
