### ISSUE TITLE
GrandPerspective

### ISSUE THREAD

**Issue by Marc66** [ThatGuySam/doesitarm#146]
**The official name of the app**
GrandPerspective

**Proposed App Status**
Full Native Apple Silicon Support

**Related Issue Tracker Link or discussion**
http://grandperspectiv.sourceforge.net/

**An Official App Download Link**
https://sourceforge.net/projects/grandperspectiv/files/latest/download
https://itunes.apple.com/us/app/grandperspective/id1111570163?mt=12

**Additional context**
![2_5_1-FoldersBujumbura](https://user-images.githubusercontent.com/11850067/99366376-d0f8ec80-28b8-11eb-9f6c-7b3cf1bd7642.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.
