### ISSUE TITLE
Update on Docker Support

### ISSUE THREAD

**Issue by stevapple** [ThatGuySam/doesitarm#147]
Waiting for underlying projects to be supported.

Here's a link about it: https://www.docker.com/blog/apple-silicon-m1-chips-and-docker

**Comment by ThatGuySam** [comment]
I put 

🚫 Not yet, but it’s in development

**Comment by tonyunreal** [comment]
A temporary workaround:
https://finestructure.co/blog/2020/11/27/running-docker-on-apple-silicon-m1

**Comment by ThatGuySam** [comment]
@tonyunreal Added! That will be a welcome relief for a lot of people.
