### ISSUE TITLE
Keka

### ISSUE THREAD

**Issue by Marc66** [ThatGuySam/doesitarm#148]
**The official name of the app**
Keka

**Proposed App Status**
Full Native Apple Silicon Support

**Related Issue Tracker Link or discussion**
https://github.com/aonez/Keka/releases

**An Official App Download Link**
https://mas.keka.io/
https://www.keka.io/
https://github.com/aonez/Keka/releases

**Additional context**
![Keka-512x512](https://user-images.githubusercontent.com/11850067/99367100-cf7bf400-28b9-11eb-8a3f-e61503b987b7.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.
