### ISSUE TITLE
WPS

### ISSUE THREAD

**Issue by zrshizr** [ThatGuySam/doesitarm#149]
The official name of the app:
WPS Office for Mac

Proposed App Status:
Full Native Apple Silicon Suppor

An Official App Download Link:
https://www.wps.cn/product/wpsmac/

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by tonyunreal** [comment]
**The official name of the app**
WPS Office

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Yes, full native Apple Silicon support

**Proposed App Category**
Productivity Tools

**An Official App Download Page**
https://apps.apple.com/cn/app/wps-office/id1443749478?l=en&mt=12

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Screen Shot 2020-12-02 at 1 03 18 PM](https://user-images.githubusercontent.com/3460639/100830629-10b9f980-349f-11eb-966e-915cc700b55f.png)
![Screen Shot 2020-12-02 at 1 03 28 PM](https://user-images.githubusercontent.com/3460639/100830639-14e61700-349f-11eb-9ea8-a976fc7e7ba2.png)

**Comment by tonyunreal** [comment]
This one is added in 3944381f529a01e49b337401e8865670dbd952a3

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/wps-office/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
