### ISSUE TITLE
Traktor Pro 3

### ISSUE THREAD

**Issue by brignolij** [ThatGuySam/doesitarm#15]
it would be nice to add Traktor Pro 3
https://www.native-instruments.com/fr/products/traktor/dj-software/traktor-pro-3/

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ThatGuySam** [comment]
Based on this discussion looks like no one has checked it yet

https://www.native-instruments.com/forum/threads/mac-os-big-sur-arm-windows-arm-other-arm-platforms.417971/

We’ll fix that

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/traktor-pro-3/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
