### ISSUE TITLE
Eclipse IDEA or IDE

### ISSUE THREAD

**Issue by kangzhaotong** [ThatGuySam/doesitarm#150]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**The official name of the app**
What's the full official name of the app

**Proposed App Status**
What's the current app status based off of current discussion or testing
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend 

**Related Issue Tracker Link or discussion**
This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes. 

**An Official App Download Link**
This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site. 

**Additional context**
Add any other context or screenshots about the app request here.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by moffpage** [comment]
Lmao seems like nobody cares about it. Nah, it doesn't have Apple Silicon support yet. When I first downloaded it, it was crashing for me and then I deleted it, now it requires me to have some JDK and I don't want to install it. Anyways...
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/119294981-86956580-bc77-11eb-8b46-4a3bfab25c50.png">

**Comment by ThatGuySam** [comment]
Thanks @moffpage 

App is now live on the site! 

https://doesitarm.com/app/eclipse-ide/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by moffpage** [comment]
Eclipse was updated to 4.21 with native Apple Silicon support included: https://twitter.com/ism1ready/status/1415577512491556867?s=21

Btw there’re two issues related to Eclipse IDE, anyways I think we can ignore both since the support is already being implemented
