### ISSUE TITLE
Mac QQ

### ISSUE THREAD

**Issue by zrshizr** [ThatGuySam/doesitarm#151]
The official name of the app:
Mac QQ

Proposed App Status:
Full Native Apple Silicon Suppor

An Official App Download Link:
https://im.qq.com/macqq/
other v 6.7.0 通用版(Intel+Apple Silicon)   |   2020.11.10

**Comment by Syakmoon** [comment]
问题是对方有QQ号吗

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

This is now live!

https://doesitarm.com/app/qq/
