### ISSUE TITLE
Steam

### ISSUE THREAD

**Issue by Zlitus** [ThatGuySam/doesitarm#153]
**The official name of the app**
Steam

**Proposed App Status**
✳️ Yes, it works via Rosetta 2, tested it myself on a MacBook Pro M1

**An Official App Download Link**
https://store.steampowered.com/about/

**Additional context**
It is quite slow and use a lot of CPU, but work good, I tested the game “The Dungeon of Naheulbeuk - The amulet of Chaos” witch work fine with much (much much) better performances than on my MacBook Pro 13" 2016.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

We'll give it the following status: 
✳️ Yes, it works via Rosetta 2, tested on MacBook Pro M1

Drop a screenshot in this issue and then feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by Zlitus** [comment]
Thank you 👍
Here a few screenshots: https://imgur.com/a/JNgXFzS

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is live!

https://doesitarm.com/app/steam

@Zlitus You the real MVP

**Comment by miaolingru** [comment]
it won't run on DTK 
11.1beta
screenshot: https://imgur.com/yLo26fz

**Comment by ThatGuySam** [comment]
Sometimes it will work on the Launch M1's but not the DTK since they have the beta OS. 

For now, we'll wait to see if another report like this comes up.

**Comment by tonyunreal** [comment]
It didn't run for the first couple of times for me, the auto-update screen showed up fine, then the client just plain quit. Clicked the icon in Applications several times and it eventually run.

**Comment by ThatGuySam** [comment]
@tonyunreal Is that on an M1 or a DTK?

**Comment by Zlitus** [comment]
> It didn't run for the first couple of times for me, the auto-update screen showed up fine, then the client just plain quit. Clicked the icon in Applications several times and it eventually run.

On my 2nd M1 Macbook, I've the same issue.
- I download Steam, I put it in application, it didn't launch and tell me to put it on the trash.
- I retried many times, always the same message.
- I download it again, same.
- I download it again, and "pouf", it magically worked.
