### ISSUE TITLE
Ocenaudio

### ISSUE THREAD

**Issue by uncertainquark** [ThatGuySam/doesitarm#154]
**The official name of the app**
Ocenaudio

**Proposed App Status**

**An Official App Download Link**
https://www.ocenaudio.com/

**Additional context**
Audio tools

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by moffpage** [comment]
<img width="1257" alt="image" src="https://user-images.githubusercontent.com/33549573/123618517-18b9fc00-d82a-11eb-86a9-2a932c0cbc56.png">
Works via Rosetta 2

**Comment by ThatGuySam** [comment]
@moffpage Awesome! 

We'll use the following status:
✳️ Yes, works via Rosetta 2 translation

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/ocenaudio/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by Forst** [comment]
Runs natively on M1 since version 3.10.3: [changelog](https://www.ocenaudio.com/changelog)

Released on February 5th, 2021.

```
Content-Disposition: attachment; filename="ocenaudio_bigsur_arm64_3.10.3.dmg"
Last-Modified: Fri, 05 Feb 2021 19:29:22 GMT
```

Proof:
![Screenshot 2021-11-18 at 23 00 45](https://user-images.githubusercontent.com/369699/142504015-15b2c988-dde3-49f6-b8e4-3a351793ea96.png)

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/ocenaudio/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
