### ISSUE TITLE
Maccy

### ISSUE THREAD

**Issue by uncertainquark** [ThatGuySam/doesitarm#155]
**The official name of the app**
Maccy

**Proposed App Status**

**An Official App Download Link**
https://maccy.app/

**Additional context**
Productivity tools

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/maccy/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
