### ISSUE TITLE
Ableton Live

### ISSUE THREAD

**Issue by enyo** [ThatGuySam/doesitarm#156]
**The official name of the app**
Ableton Live

**Proposed App Status**
✳️ Can run well enough via Rosetta or some other caveat

**Related Issue Tracker Link or discussion**
https://www.reddit.com/r/ableton/comments/jrtpv6/ableton_live_11_on_apple_silicon_m1_processor/gbvxj9r?context=3

**An Official App Download Link**
https://www.ableton.com/en/live/

**Additional context**
![image](https://user-images.githubusercontent.com/133277/99387045-9ea8b880-28d3-11eb-826a-d9556c01e215.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

We'll report this as: 
✳️ Yes, it works via Rosetta 2

**Comment by ThatGuySam** [comment]
This is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/ableton/

Feel free to browse through the other issues to help with missing info on other apps.
