### ISSUE TITLE
Surge Mac

### ISSUE THREAD

**Issue by Blankwonder** [ThatGuySam/doesitarm#157]
**The official name of the app**
Surge Mac

**Proposed App Status**
✅ Yes, full native support as of v4.0

**An Official App Download Link**
https://nssurge.com

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Were you able to find a tracker link we can provide to verify the status?

**Comment by Blankwonder** [comment]
![Image 11-18-20 at 10 49 AM](https://user-images.githubusercontent.com/634138/99476629-dd01ae80-298b-11eb-9c66-b00b470eae19.jpg)

file Surge
Surge: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]
Surge (for architecture x86_64):	Mach-O 64-bit executable x86_64
Surge (for architecture arm64):	Mach-O 64-bit executable arm64

Please let me know if you need more information.

**Comment by ThatGuySam** [comment]
That's plenty! 

We'll use this issue page as the tracker link

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/surge/

Feel free to browse through the other issues to help with missing info on other apps.
