### ISSUE TITLE
Update on Photoshop Support

### ISSUE THREAD

**Issue by kklobe** [ThatGuySam/doesitarm#158]
Beta available:

https://feedback.photoshop.com/conversations/photoshop-beta/photoshop-for-mac-arm-is-here/5fb359d3ca9d527a59c4677e

**Comment by ThatGuySam** [comment]
Update is live!

https://doesitarm.com/app/photoshop/

**Comment by ThatGuySam** [comment]
Update is live! 

https://doesitarm.com/app/photoshop/
