### ISSUE TITLE
Aptana Studio

### ISSUE THREAD

**Issue by pclavelloux** [ThatGuySam/doesitarm#16]

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ThatGuySam** [comment]
Looks like there an open issue related to Apple Silicon
https://jira.appcelerator.org/browse/TIMOB-28153


Download Link
http://www.aptana.com/

**Comment by ThatGuySam** [comment]
Release Notes
https://github.com/aptana/studio3/releases
https://github.com/aptana/studio3/wiki/Release-Notes

**Comment by moffpage** [comment]
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/33549573/123598917-d9ce7b00-d816-11eb-9bfe-fe8def7579da.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/123598921-da671180-d816-11eb-8db8-dc681970b36c.png">
Yes, works via Rosetta2

**Comment by ThatGuySam** [comment]
@moffpage Excellent! 

We'll use the following status:
✳️ Yes, works via Rosetta 2 translation

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
It's about time!! 

App is now live on the site! 

https://doesitarm.com/app/aptana-studio/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
