### ISSUE TITLE
Postman, the API development tool.

### ISSUE THREAD

**Issue by triplec316** [ThatGuySam/doesitarm#160]
The official name of the app
Postman

Proposed App Status

Related Issue Tracker Link or discussion
N/A

An Official App Download Link
https://dl.pstmn.io/download/latest/osx

Additional context

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by thunderstorm99** [comment]
Postman seems to work just fine via Rosetta 2. Screenshot added below.
![Screen Shot 2020-12-01 at 20 35 45](https://user-images.githubusercontent.com/3219279/100788115-f0ddf380-3414-11eb-9540-8e6b2d3934d1.png)

**Comment by ThatGuySam** [comment]
@thunderstorm99 ⚡️⚡️⚡️

Status: ✳️ Yes, works via Rosetta 2

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/postman/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
