### ISSUE TITLE
Navicat Premium

### ISSUE THREAD

**Issue by wtry** [ThatGuySam/doesitarm#161]
**The official name of the app**

**navicat**

**Proposed App Status**

Proposed App Category {What category should the app go under}

**Developer Tools**

An Official App Download Link {This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site.}

https://www.navicat.com/download/direct-download?product=navicat_premium_en.dmg&location=1

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ThatGuySam** [comment]
This one needs someone with an M1 to provide a screenshot. Also, let's test Navicat Essentials just to be through
https://www.navicat.com/en/products/navicat-essentials
https://www.navicat.com/en/products/navicat-premium

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by ameeno** [comment]
Works with rosetta. heres a screenshot 
<img width="1440" alt="Screenshot 2021-01-13 at 22 04 38" src="https://user-images.githubusercontent.com/388653/104515917-64b21500-55eb-11eb-8608-699bbb89a418.png">

**Comment by ThatGuySam** [comment]
@ameeno Fantastic, there's been a big demand for this on and 3 others issues.

**Comment by ThatGuySam** [comment]
For status, we can put: 
✳️ Yes, works via Rosetta 2

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/navicat-premium/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
