### ISSUE TITLE
DxO PhotoLab 4 - Photo t

### ISSUE THREAD

**Issue by vincentme** [ThatGuySam/doesitarm#162]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**Proposed App**
DxO PhotoLab 4

**Proposed App Status**
No

**Related Issue Tracker Link or discussion**
This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes. 

**An Official App Download Link**
This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site. 

**Additional context**
Add any other context or screenshots about the app request here.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by moffpage** [comment]
This app is rather confusing, cause there're multiple articles like: https://www.dpreview.com/news/9669882236/dxo-photolab-version-4-1-released-brings-native-apple-m1-support-and-more
However the official website (https://support.dxo.com/hc/en-us/articles/360054010571-State-of-DxO-PhotoLab-compatibility-with-the-Apple-Silicon-M1) states this: 
<img width="639" alt="image" src="https://user-images.githubusercontent.com/33549573/123621536-2329c500-d82d-11eb-90ef-fc14f9e5bd3b.png">
And it indeed downloads an Intel build:
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/33549573/123621604-363c9500-d82d-11eb-9171-ad77b9f02729.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/123621611-376dc200-d82d-11eb-933f-f91e3c0a75c5.png">

**Comment by ThatGuySam** [comment]
@moffpage this is one of the big reasons we do this so people can get clearer information. Some developers will say "Native App Support" but mean that their app is going from not working to Rosetta 2

We'll use the following status:
✳️ Yes, works via Rosetta 2 translation

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/dxo-photolab/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
