### ISSUE TITLE
Gradle Java Build Tools

### ISSUE THREAD

**Issue by gloryhui** [ThatGuySam/doesitarm#163]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**The official name of the app**
What's the full official name of the app

**Proposed App Status**
What's the current app status based off of current discussion or testing
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend 

**Related Issue Tracker Link or discussion**
This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes. 

**An Official App Download Link**
This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site. 

**Additional context**
Add any other context or screenshots about the app request here.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by moffpage** [comment]
Gradle 7.0 already had Apple Silicon support: https://twitter.com/gradle/status/1339958143963582465?s=20

**Comment by hannesa2** [comment]
Gradle 6.9 comes with Apple Silicon support too https://docs.gradle.org/6.9/release-notes.html

**Comment by moffpage** [comment]
Well, that just proves that this issue should be closed :D

**Comment by ThatGuySam** [comment]
@moffpage I agree! 

We'll use the following status:
✅ Yes, Native Apple Silicon Support as of v6.9

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/gradle-build-tool/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
