### ISSUE TITLE
Update on Firefox Support

### ISSUE THREAD

**Issue by gcp** [ThatGuySam/doesitarm#169]
Here's a link about it: https://bugzilla.mozilla.org/show_bug.cgi?id=1648496#c2

Nightlies with Apple Silicon support were released last week.

**Comment by ThatGuySam** [comment]
Can't get much more official than a legit Mozilla team member. 

Update is live!

https://doesitarm.com/app/firefox/

**Comment by ThatGuySam** [comment]
@gcp Btw do you know groovecoder. He and some other Mozillians work at my coworking space.

**Comment by gcp** [comment]
We've probably met a few times over the years but we don't usually end up working together much :)

**Comment by ThatGuySam** [comment]
Yeah, it's a big team. 

Let me know as soon as the Apple Silicon builds are publicly available and I'll get the listing updated with haste.
