### ISSUE TITLE
Filezilla

### ISSUE THREAD

**Issue by pclavelloux** [ThatGuySam/doesitarm#17]

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ThatGuySam** [comment]
It doesn’t seem like there is a current active issue or discussion that I was able to find so we’ll just use the fact that there not a Macos ARM64 build on the downloads page to say no native support yet. 
https://filezilla-project.org/download.php?show_all=1


Download Link
https://filezilla-project.org/download.php?type=client

**Comment by iLtc** [comment]
Hi @ThatGuySam, for the Rosetta Testing, can I do it on DTK? Or does it has to be done on one of the three new Macs?

**Comment by ThatGuySam** [comment]
DTK is perfectly fine as long as it has the latest Rosetta updates for obvious reasons.

**Comment by iLtc** [comment]
I can confirm it works on my DTK. However, I can't find any official announcement or discussion.

![Screen Shot 2020-11-18 at 4 41 24 PM](https://user-images.githubusercontent.com/4352234/99591845-6087c380-29bd-11eb-8c8a-d895f2c17c61.png)
