### ISSUE TITLE
Update on Spotify Support

### ISSUE THREAD

**Issue by rene-d** [ThatGuySam/doesitarm#172]
It works with Rosetta2. Cannot find an official link or confirmation, just verified on my MBP 13 M1.

https://www.macg.co/logiciels/2020/11/apple-m1-les-apps-pretes-et-celles-qui-ne-le-sont-pas-encore-117707#spotify🔶

**Comment by ThatGuySam** [comment]
Update is live on the site! 

https://doesitarm.com/app/spotify/

Feel free to browse through the other issues to help with missing info on other apps.

**Comment by christophut4** [comment]
it does crash sometimes

**Comment by dionvl** [comment]
Apple Silicon release now available in beta: https://community.spotify.com/t5/Live-Ideas/Desktop-Developer-Add-support-for-Apple-Silicon-ARM64-on-Mac/idc-p/5229689

**Comment by EmperorYP7** [comment]
@dionvl, you mean this one? https://community.spotify.com/t5/Live-Ideas/Desktop-Developer-Add-support-for-Apple-Silicon-ARM64-on-Mac/idc-p/5229689

**Comment by dionvl** [comment]
@EmperorYP7 Yes, that links to the same thread

**Comment by ThatGuySam** [comment]
I've added the beta link to the Spotify listing. 

https://doesitarm.com/app/spotify/

Feel free to comment on this issue once Native Support drops into the stable channel.
