### ISSUE TITLE
MySQL (App Request)

### ISSUE THREAD

**Issue by Kreller99** [ThatGuySam/doesitarm#173]
Does MySQL client + server work on the new Arm Macbooks?

**Comment by pawelostr** [comment]
Both MySQL Community Server and Workbench from https://dev.mysql.com/downloads/ work fine

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ThatGuySam** [comment]
@pawelostr Any chance you can drop screenshots just to be extra through. 

Also, I assume this is without Rosetta 2

**Comment by pawelostr** [comment]
<img width="1067" alt="Zrzut ekranu 2020-11-19 o 19 15 18" src="https://user-images.githubusercontent.com/26488603/99706788-df532e00-2a9b-11eb-80e7-6399eeb16267.png">
<img width="1136" alt="Zrzut ekranu 2020-11-19 o 19 16 44" src="https://user-images.githubusercontent.com/26488603/99706799-e37f4b80-2a9b-11eb-8980-d3c7152e335d.png">

@ThatGuySam unfortunately Rosetta

**Comment by pawelostr** [comment]
<img width="1136" alt="Zrzut ekranu 2020-11-19 o 19 16 44" src="https://user-images.githubusercontent.com/26488603/99707059-407b0180-2a9c-11eb-87e3-f0a4a5c6e421.png">
<img width="1067" alt="Zrzut ekranu 2020-11-19 o 19 15 18" src="https://user-images.githubusercontent.com/26488603/99707072-4375f200-2a9c-11eb-8d02-85038c816041.png">

@ThatGuySam Unfortunately Rosetta

**Comment by ThatGuySam** [comment]
Thanks perfectly fine. 

Status: ✳️ Yes, works via Rosetta 2

We'll use this page as the tracker link

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
Apps are now live on the site! 

https://doesitarm.com/app/mysql-community-server/
https://doesitarm.com/app/mysql-workbench/

Feel free to browse through the other issues to help with missing info on other apps.

**Comment by erlingmidtt** [comment]
it doesn't work for me

**Comment by ThatGuySam** [comment]
@erlingmidtt Can you add a Youtube Video or screenshot of the issue so we can provide context as to why it doesn't work

**Comment by erlingmidtt** [comment]
> @erlingmidtt Can you add a Youtube Video or screenshot of the issue so we can provide context as to why it doesn't work

hello there wasn't much to film, it would just go straight to the standard mac os crash message when trying to open the program. i did manage to sort it out by downloading the older 8.0.21 build instead of the 8.0.23.

**Comment by ThatGuySam** [comment]
Did both have Rosetta 2 enabled?

**Comment by ThatGuySam** [comment]
You can manually enable it or disable it under "Get Info"

**Comment by erlingmidtt** [comment]
> You can manually enable it or disable it under "Get Info"
i don't have that option, only open in low resolution or lock, but they're both x86 apps so i'm guessing that rosetta 2 is enabled with both by default.

**Comment by ThatGuySam** [comment]
Actually, that makes sense because you wouldn't need the option for Intel-only apps. 

Do you know of any other reports of similar issues? I hate to report that there are issues based on a single environment.

**Comment by erlingmidtt** [comment]
> Actually, that makes sense because you wouldn't need the option for Intel-only apps.
> 
> Do you know of any other reports of similar issues? I hate to report that there are issues based on a single environment.

not as far as i know, don't really know why this would be specific to me though so idk, you could try installing the 8.0.23 build and test. the 8.0.22 build seems to be working fine for me so i'm guessing it's specific to to the newest build

**Comment by calvinfreese** [comment]
Hey, 
I'm, also facing this issue. I've tried installing MySQL Workbench 8.0.22 and 8.0.23 and receive the same error for both.
I don't have an issue with MySQL community server though.

<img width="231" alt="Screen Shot 2021-01-19 at 7 43 57 PM" src="https://user-images.githubusercontent.com/46834593/105115700-e8a64a00-5a8e-11eb-9fac-db38dc8abc4d.png">

<img width="640" alt="Screen Shot 2021-01-19 at 7 46 30 PM" src="https://user-images.githubusercontent.com/46834593/105115784-0f648080-5a8f-11eb-8873-798a3386b74e.png">


<img width="912" alt="Screen Shot 2021-01-19 at 7 42 35 PM" src="https://user-images.githubusercontent.com/46834593/105115482-85b4b300-5a8e-11eb-8539-b223dff4a4da.png">

**Comment by ThatGuySam** [comment]
@calvinfreese Are you able to get any of the older versions to work at all?

**Comment by calvinfreese** [comment]
> @calvinfreese Are you able to get any of the older versions to work at all?

@ThatGuySam - I was able to get version 8.0.21 of workbench to open last night some time after i made the above post.

**Comment by ThatGuySam** [comment]
Alright, I've updated the app page with a note about the working version

https://doesitarm.com/app/mysql-workbench/

**Comment by lq920320** [comment]
![image](https://user-images.githubusercontent.com/18696549/107111988-3bee0a00-688f-11eb-91ee-f5b2938e6ae7.png)

It's not work for me, workbench version is 8.0.21, and 8.0.22, 8.0.23 have the same problem.

**Comment by gazrogers** [comment]
I've just downloaded and successfully run v8.0.28 on my M1 MacBook Pro (it's using Rosetta 2).
<img width="1440" alt="Screenshot 2022-03-31 at 10 08 30" src="https://user-images.githubusercontent.com/427217/161019940-d33b26cb-ea4c-453b-9fe7-4315d9121bdf.png">
