### ISSUE TITLE
Update on Bear

### ISSUE THREAD

**Issue by ethanhogq** [ThatGuySam/doesitarm#174]
**The official name of the app**
Bear

**Proposed App Status**
Runs via Rosetta with native support currently in development

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
https://twitter.com/BearNotesApp/status/1328271208748638213

**An Official App Download Link**
https://apps.apple.com/ca/app/bear/id1091189122?mt=12

**Additional context**
Just attempted to run Bear under M1 and seems to be working just fine under Rosetta 2.

**Comment by KovalevArtem** [comment]
Bear is ready for the new M1 MacBook Air, MacBook Pro, and Mac mini.
https://blog.bear.app/2020/11/bear-gets-new-widgets-and-ready-for-big-sur/
