### ISSUE TITLE
MongoDB Explorer (New App Request)

### ISSUE THREAD

**Issue by GauthamramRavichandran** [ThatGuySam/doesitarm#175]
**The official name of the app:** Robo 3T or Studio 3T

**Related Issue Tracker link:** https://github.com/Studio3T/robomongo/issues/1782

**Official site:** https://robomongo.org/

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by GauthamramRavichandran** [comment]
Big Sur Commit: https://github.com/Studio3T/robomongo/commit/583d43c054115c22ebdc82b8563c240068ac9f3d

**Comment by ThatGuySam** [comment]
@GauthamramRavichandran What's the timeline for that hitting stable releases?

**Comment by GauthamramRavichandran** [comment]
There's no mention of a deadline for the stable release,

**Comment by GauthamramRavichandran** [comment]
v1.4.3 released for macOS Big Sur, could someone test this on M1?

**Comment by ameeno** [comment]
uses rosetta, no issues so far.

**Comment by ThatGuySam** [comment]
@ameeno Awesome! 

Next, we'll need an M1 screenshot. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by muuvmuuv** [comment]
Yep can confirm, uses Rosetta 2 on my Mac mini M1.

**Comment by muuvmuuv** [comment]
I can create a screenshot once I am at home.

**Comment by muuvmuuv** [comment]
Can someone mention me so it appears in my notifications that I don't forget it xD?

**Comment by ThatGuySam** [comment]
@muuvmuuv, you're a gentleman and a scholar

**Comment by muuvmuuv** [comment]
Mac mini M1 16 GB Ram with a medium large database connected:

![Bildschirmfoto 2021-02-19 um 14 21 57](https://user-images.githubusercontent.com/11534760/108509843-1107ab00-72be-11eb-88bd-11a33e59890e.png)

**Comment by ThatGuySam** [comment]
@muuvmuuv Beautiful!

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/robo-3t-formerly-robomongo/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by imrefazekas** [comment]
It requires rosetta still ...

**Comment by ThatGuySam** [comment]
@imrefazekas Good catch! 

Now fixed! 

https://doesitarm.com/app/robo-3t-formerly-robomongo/
