### ISSUE TITLE
Elpass

### ISSUE THREAD

**Issue by Blankwonder** [ThatGuySam/doesitarm#176]
**The official name of the app**
Elpass

**Proposed App Status**
✅ Yes, full native support as of v.1.1.10

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**

![Image 11-18-20 at 10 58 AM](https://user-images.githubusercontent.com/634138/99477252-17b81680-298d-11eb-9014-5020f86333c3.jpg)

file Elpass
Elpass: Mach-O universal binary with 2 architectures: [x86_64:Mach-O 64-bit executable x86_64] [arm64]
Elpass (for architecture x86_64):	Mach-O 64-bit executable x86_64
Elpass (for architecture arm64):	Mach-O 64-bit executable arm64

**An Official App Download Link**
https://elpass.app/

**Comment by ThatGuySam** [comment]
This looks great! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/elpass/

Feel free to browse through the other issues to help with missing info on other apps.
