### ISSUE TITLE
Cocos Creator

### ISSUE THREAD

**Issue by BillScott1024** [ThatGuySam/doesitarm#177]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**The official name of the app**
Cocos Creator

**Proposed App Status**
Hope anyone to test on M1 MacBook Pro

**Proposed App Category**
Develop, Game

**Related Issue Tracker Link or discussion**
{This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes.}

**An Official App Download Link**
https://www.cocos.com/products#CocosCreator

**Additional context**
{Add any other context or screenshots about the app request here.}

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by LittleZzUni** [comment]
App Download Link : https://download.cocos.com/CocosDashboard/v1.0.10/CocosDashboard-v1.0.10-darwin-092110.dmg

**Comment by ThatGuySam** [comment]
@LittleZzUni Let's use this download link so people know what they are putting on their computer before the click:
https://www.cocos.com/en/creator/download

**Comment by ThatGuySam** [comment]
Thanks for the patience on this! Update is now live on the site! 

https://doesitarm.com/app/cocos-creator/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
