### ISSUE TITLE
Jamf Protect

### ISSUE THREAD

**Issue by mwollnik99** [ThatGuySam/doesitarm#178]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**The official name of the app**
Jamf Protect

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Security or maybe Management

**Related Issue Tracker Link or discussion**
https://docs.jamf.com/jamf-protect/administrator-guide/Release_History.html

**An Official App Download Link**
Downloadable through the Jamf Protect portal for customers

**Additional context**
{Add any other context or screenshots about the app request here.}

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

We'll use this as the download link
https://www.jamf.com/

**Comment by ThatGuySam** [comment]
We can put this under Productivity Tools and if we get enough similar apps to this we'll create a new category

**Comment by ThatGuySam** [comment]
This is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/jamf-protect/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
