### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by liuduoios** [ThatGuySam/doesitarm#179]
**The official name of the app**
Carthage

**Proposed App Status**
Hope anyone to test on M1 MacBook Pro

**Proposed App Category**
Develop

**An Official App Download Link**
https://github.com/Carthage/Carthage

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ThatGuySam** [comment]
Native according to Homebrew
https://formulae.brew.sh/formula/carthage#default


Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by amandaallissa** [comment]
@liuduoios Thank you for info. 
App is now live on the site! 

https://doesitarm.com/formula/carthage

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
