### ISSUE TITLE
Mobile develop tools Xcode, charles,postman

### ISSUE THREAD

**Issue by BeautifulMomo** [ThatGuySam/doesitarm#183]
Mobile develop tools Xcode, charles,postman

**Comment by Bjornftw** [comment]
Please, submit the missing information with the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md).

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I can confirm that Xcode works under Apple Silicon since it's made by Apple. 

As for Charles and Postman you can find existing issues that are in progress

Feel free to browse through those or other issues if you find new info that can help move them along
