### ISSUE TITLE
Bandizip

### ISSUE THREAD

**Issue by EddaAkikusa** [ThatGuySam/doesitarm#186]
**The official name of the app**
Bandizip

**Proposed App Status**
Native Apple Silicon support since 7.0.2

**Proposed App Category**
Utilities?

**Related Issue Tracker Link or discussion**
Change log in App Store

**An Official App Download Link**
[App Store](https://apps.apple.com/cn/app/bandizip-%E5%8E%8B%E7%BC%A9%E5%92%8C%E8%A7%A3%E5%8E%8B%E7%BC%A9/id1265704574?mt=12)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

We can put this under Productivity Tools until there are more apps like it

**Comment by ThatGuySam** [comment]
This is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/bandizip/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
