### ISSUE TITLE
Tailscale

### ISSUE THREAD

**Issue by Shanduur** [ThatGuySam/doesitarm#187]
**The official name of the app**
TailScale

**Proposed App Status**
Should be running through Rosetta fine, but it's not officially supported.

**Proposed App Category**
Productivity Tools / Developer Tools

**Related Issue Tracker Link or discussion**
https://github.com/tailscale/tailscale/issues/943

**An Official App Download Link**
https://tailscale.com/download

**Additional context**
None

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

This can go under Productivity Tools.

**Comment by ThatGuySam** [comment]
Looks like haven't responded in that issue yet, so we'll need to get confirmation on Rosetta 2 support

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/tailscale/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
