### ISSUE TITLE
VMware

### ISSUE THREAD

**Issue by wdoooo0000** [ThatGuySam/doesitarm#188]

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by zhongdongy** [comment]
[VMware Fusion](https://twitter.com/VMwareFusion) announced a private tech preview request link: https://t.co/udQsATVuFA?amp=1 [link](https://twitter.com/mikeroySoft/status/1435710030389547012?s=20). And the public tech preview should be available in a few days.

**Comment by ThatGuySam** [comment]
Thanks for the patience on this! Update is now live on the site! 

https://doesitarm.com/app/vmware-fusion/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
