### ISSUE TITLE
Laggy performance

### ISSUE THREAD

**Issue by mandrean** [ThatGuySam/doesitarm#190]
Hi! Great website, but still very laggy (#1)

Same with either Chrome or Safari on a freshly rebooted MBP 15", quad core i7, 16 GB RAM, 2GB VRAM.

Smooth in Firefox! Hah.

**Comment by ThatGuySam** [comment]
Yeah, I need to tweak the shadow rendering again and maybe not render so many dom elements, I'll try to find some time for some performance work

**Comment by ThatGuySam** [comment]
@mandrean How's it working for you now after the updates?

**Comment by mandrean** [comment]
Better, thanks!
