### ISSUE TITLE
Microsoft Teams support

### ISSUE THREAD

**Issue by psomhorst** [ThatGuySam/doesitarm#191]
**The official name of the app**
Microsoft Teams

**Proposed App Status**
No, not working at all but support is in development

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**

**An Official App Download Link**

**Additional context**
Some media outlets claim Microsoft is working on a native version, without supporting their claims.

**Comment by pawelostr** [comment]
By 'not working at all' do you mean not working under Rosetta 2? Can't find anything about it not working.

**Comment by psomhorst** [comment]
I can't find anything about it working properly. I'm not able to test it myself yet. Anyone who has seen it working can change it to working.

**Comment by pawelostr** [comment]
Just tested, works great using Rosetta.

**Comment by ThatGuySam** [comment]
Thanks, @pawelostr and thanks for the App Request @psomhorst 

We'll use this issue page as our tracker link

**Comment by ThatGuySam** [comment]
@pawelostr When you can, can you provide a screenshot

**Comment by ThatGuySam** [comment]
We'll use this as the download link
https://www.microsoft.com/en-us/microsoft-365/microsoft-teams/group-chat-software

**Comment by pawelostr** [comment]
<img width="1440" alt="Zrzut ekranu 2020-11-19 o 19 35 26" src="https://user-images.githubusercontent.com/26488603/99708837-a2d50180-2a9e-11eb-9f70-f1b4452ad33e.png">

Rosetta of course

**Comment by ThatGuySam** [comment]
Beautiful!

Status: ✳️ Yes, works via Rosetta 2

Category: Social and communication

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/microsoft-teams/

Feel free to browse through the other issues to help with missing info on other apps.
