### ISSUE TITLE
Citrix Workspace

### ISSUE THREAD

**Issue by psomhorst** [ThatGuySam/doesitarm#193]
**The official name of the app**
Citrix Workspace

**Proposed App Status**
No, not working at all but support is in development

**Proposed App Category**
Productivity

**Related Issue Tracker Link or discussion**
https://discussions.citrix.com/topic/411196-will-citrix-viewer-run-on-new-apple-hardware-with-apple-silicon-m1/

**An Official App Download Link**

**Additional context**

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

It looks like someone from that discussion is using Citrix Workspace via Rosetta 2 so we can give it the following status: 
✳️ Yes, works via Rosetta 2

**Comment by ThatGuySam** [comment]
We can use this as the download link: 
https://www.citrix.com/downloads/workspace-app/mac/workspace-app-for-mac-latest.html

**Comment by ThatGuySam** [comment]
This is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/citrix-workspace/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by tthoma24** [comment]
@ThatGuySam this has been updated to run as a Universal app.
