### ISSUE TITLE
Fantastical

### ISSUE THREAD

**Issue by rddvries** [ThatGuySam/doesitarm#194]
**The official name of the app**
Fantastical

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity

**Related Issue Tracker Link or discussion**
https://www.macrumors.com/2020/11/12/fantastical-update-for-macos-big-sur-apple-silicon/

**An Official App Download Link**
https://flexibits.com/fantastical

**Comment by ThatGuySam** [comment]
Looks great! This is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by iLtc** [comment]
Fantastical has been added in #243.
