### ISSUE TITLE
Notion

### ISSUE THREAD

**Issue by JulienPhlpt** [ThatGuySam/doesitarm#195]
**The official name of the app**
Notion

**Proposed App Status**
No, not yet supported only works on Intel-based Macs

**Proposed App Category**
Productivity Tools

**An Official App Download Link**
https://www.notion.so/desktop

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by JulienPhlpt** [comment]
I received a mail from Notion Support.

**Proposed App Status**
⏹ No, browser support is available right now. We’ll have more updates on desktop app support in the coming weeks.

**Comment by ThatGuySam** [comment]
We'll use "Notion Desktop" as the app name so we don't have to clarify browser support. 

Status: ⏹ No, not yet but support is in development

**Comment by ThatGuySam** [comment]
This is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by JulienPhlpt** [comment]
I made a new PR( #286) for this.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/notion-desktop/

Feel free to browse through the other issues to help with missing info on other apps.

**Comment by tinymachine** [comment]
@ThatGuySam Notion Desktop latest stable (2.0.8) is working fine for me via Rosetta 2.
<img width="898" alt="Screen Shot 2020-11-22 at 11 03 50 PM" src="https://user-images.githubusercontent.com/171986/99936032-fe112900-2d16-11eb-8f3d-98a8e1bd6627.png">

**Comment by ThatGuySam** [comment]
@tinymachine Updated!
