### ISSUE TITLE
Post-it®

### ISSUE THREAD

**Issue by carlo-** [ThatGuySam/doesitarm#197]
**The official name of the app**
Post-it®

**Proposed App Status**
✳️ Runs via Rosetta, with native support coming soon

**Proposed App Category**
Productivity

**An Official App Download Link**
https://apps.apple.com/app/post-it/id1475777828

**Additional context**
I will update the issue myself once the new version with native Apple Silicon support is released.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like we've already got this listed at #160 feel to add any new info there

**Comment by ThatGuySam** [comment]
Whoops! wrong "Post" app

Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by carlo-** [comment]
@ThatGuySam Here's the Activity Monitor screenshot as requested. Unfortunately I can't provide an issue tracker link or similar, as we don't have anything public; however, I can update this issue myself when we release, as I'm one of the developers.

<img width="852" alt="Screenshot 2020-11-18 at 13 20 55" src="https://user-images.githubusercontent.com/7290609/99956475-5fbcac00-2d86-11eb-8657-da6a6a7b4028.png">

**Comment by ThatGuySam** [comment]
@carlo-  Awesome! 

Based on that screenshot, it looks like your native support is currently in Beta. 

Is that accurate?

**Comment by carlo-** [comment]
@ThatGuySam yes, it’s an internal beta. We’ll release it (as a stable version) by the end of the year.

**Comment by ThatGuySam** [comment]
This is ready to go. 

* [Post-it®](https://apps.apple.com/app/post-it/id1475777828) - ✳️ Runs via Rosetta, with native support coming soon - [Source](https://github.com/ThatGuySam/doesitarm/issues/197#issuecomment-732100064)

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/post-itr/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
