### ISSUE TITLE
Kicad

### ISSUE THREAD

**Issue by MrThanlon** [ThatGuySam/doesitarm#199]
**The official name of the app**
Kicad

**Proposed App Status**
Native - not yet.
Rosetta - no idea.

**Proposed App Category**
https://kicad.org/img/kicad_logo_small.png
![](https://kicad.org/img/kicad_logo_small.png)

**Related Issue Tracker Link or discussion**

**An Official App Download Link**
https://kicad.org/download/macos/

**Additional context**

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by thunderstorm99** [comment]
I can confirm that from a cursory glance kicad seems to be running fine via rosetta 2. Eeschema, Pcbnew as well as the 3D Viewer work fine. Raytracing in 3D Viewer also works.

**Comment by ThatGuySam** [comment]
@thunderstorm99 Nice! Let's get a screenshot we can use as the source link then we can move to the next stage. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an Activity Monitor example on #176

**Comment by thunderstorm99** [comment]
@ThatGuySam there we go. Hope all info is included. If there's anything I missed, let me know.
![Screen Shot 2020-12-01 at 07 22 03](https://user-images.githubusercontent.com/3219279/100705004-c81f1500-33a6-11eb-9a97-2a00f1be4ef5.png)

**Comment by ThatGuySam** [comment]
Thanks @thunderstorm99 !!

Status: ✳️ Yes, works via Rosetta 2

We’ll use that screenshot comment as the source link. 


Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/kicad-eda/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
