### ISSUE TITLE
Enpass

### ISSUE THREAD

**Issue by poudi7** [ThatGuySam/doesitarm#20]
**Enpass**

🚫 No, not yet.

Blog: 
https://www.enpass.io/blog/ 

Download:
https://www.enpass.io
https://apps.apple.com/fr/app/enpass-password-manager/id732710998?mt=12

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)
