### ISSUE TITLE
Sourcetree

### ISSUE THREAD

**Issue by juanjovn** [ThatGuySam/doesitarm#200]
**The official name of the app**
Sourcetree

**Proposed App Category**
Developer Tools

**An Official App Download Link**
https://www.sourcetreeapp.com

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by tonyunreal** [comment]
**The official name of the app**
SourceTree

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
Yes, works via Rosetta 2

**Proposed App Category**
Developer Tools

*An Official App Download Page**
https://www.sourcetreeapp.com/

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Screen Shot 2020-12-02 at 2 53 09 PM](https://user-images.githubusercontent.com/3460639/100839017-7f528380-34ae-11eb-9fd4-f4e8736fed3d.png)
![Screen Shot 2020-12-02 at 2 53 17 PM](https://user-images.githubusercontent.com/3460639/100839087-9abd8e80-34ae-11eb-88ad-f2bfd41f5270.png)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/sourcetree/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
