### ISSUE TITLE
XQuartz

### ISSUE THREAD

**Issue by MrThanlon** [ThatGuySam/doesitarm#204]
**The official name of the app**
XQuartz

**Proposed App Status**
Native - no idea.
Rosetta - no idea.

**Proposed App Category**
https://www.xquartz.org/Xlogo.png
![](https://www.xquartz.org/Xlogo.png)

**Related Issue Tracker Link or discussion**

**An Official App Download Link**
https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.11.dmg

**Additional context**

**Comment by exgphe** [comment]
XQuartz 2.8.0 now has native Apple Silicon support.
See official release page https://www.xquartz.org/releases/index.html

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/xquartz/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
