### ISSUE TITLE
Pixelmator Pro

### ISSUE THREAD

**Issue by KovalevArtem** [ThatGuySam/doesitarm#205]
**The official name of the app**
Pixelmator Pro

**Proposed App Status**
![image](https://user-images.githubusercontent.com/36500228/99541436-e0179180-29c1-11eb-9f53-ba7e11f350ed.png)

**Proposed App Category**
Photo Tools

**An Official App Download Link**
https://apps.apple.com/app/id1289583905

**Additional context**
https://www.pixelmator.com/pro/

**Comment by frictionlessDevelopments** [comment]
Hey there, this seems to have been already added.
https://doesitarm.com/app/pixelmator-pro/

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/pixelmator-pro/

Feel free to browse through the other issues to help with missing info on other apps.
