### ISSUE TITLE
VLC

### ISSUE THREAD

**Issue by loopion** [ThatGuySam/doesitarm#21]

**Comment by ThatGuySam** [comment]
VLC is listed here: https://doesitarm.com/app/vlc/

Is there an update to it that you're aware of?

**Comment by loopion** [comment]
No. Just was wondering sorry.

**Comment by ThatGuySam** [comment]
Well thanks for the inquiry, anyway! 

If you think of an app that people would want to know is support on Apple SIlicon feel free to put in a new App Request

**Comment by Zlitus** [comment]
Hello,

I tested it on my MacBook Pro M1, it work fine with Rosetta2.
https://imgur.com/a/eHDPFef

**Comment by ThatGuySam** [comment]
Update is live!

https://doesitarm.com/app/vlc/

**Comment by Zlitus** [comment]
Should not it be with ✳️ instead of ✅ in case of Rosetta?

**Comment by ThatGuySam** [comment]
Whoops! 

Yes, you are correct

**Comment by ThatGuySam** [comment]
Updated!

https://doesitarm.com/app/vlc/

Good catch!
