### ISSUE TITLE
Update on Firefox Support

### ISSUE THREAD

**Issue by Bessarion** [ThatGuySam/doesitarm#210]
Per the release notes, Firefox does not have full native Apple Silicon support, just support to run via Rosetta.

"For the recently released Apple devices built with Apple Silicon CPUs, you can use Firefox 83 and future releases without any change. This release (83) will support emulation under Apple’s Rosetta 2 that ships with macOS Big Sur. We are working toward Firefox being natively-compiled for these CPUs in a future release."

https://www.mozilla.org/en-US/firefox/83.0/releasenotes/

**Comment by ThatGuySam** [comment]
Updated!

**Comment by richiksc** [comment]
@ThatGuySam - you updated it to say "full native Apple Silicon support as of v83," but the Firefox changelog says that it only has Rosetta support in 83 with native support coming in a future release (presumably v84).

**Comment by ThatGuySam** [comment]
Ha! You’re all good! 

And plus I wouldn’t put it past me to accidentally edit the wrong line.
