### ISSUE TITLE
Cinema 4D

### ISSUE THREAD

**Issue by KovalevArtem** [ThatGuySam/doesitarm#212]
**The official name of the app**
Cinema 4D

**Proposed App Status**
Yes
https://www.maxon.net/en/article/cinema-4d-r23-sp1-now-available

**Proposed App Category**
Video and Motion Tools

**An Official App Download Link**
https://www.maxon.net/en/downloads

**Additional context**
https://www.maxon.net/en/article/maxon-cinema-4d-immediately-available-for-m1-powered-macs

**Comment by ThatGuySam** [comment]
This is ready to update. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
Update is live! 

https://doesitarm.com/app/cinema-4d/
