### ISSUE TITLE
TensorFlow

### ISSUE THREAD

**Issue by richiksc** [ThatGuySam/doesitarm#214]
**The official name of the app**
TensorFlow

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
Official Blog Post: https://blog.tensorflow.org/2020/11/accelerating-tensorflow-performance-on-mac.html

**An Official App Download Link**
https://github.com/apple/tensorflow_macos

**Additional context**
Must be downloaded from Apple's tensorflow_macos fork.

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

TensorFlow is listed here: https://doesitarm.com/app/tensorflow/

Feel free to browse through the other issues that are missing info. I need all the help I can get.
