### ISSUE TITLE
Wechat Devtools

### ISSUE THREAD

**Issue by kangzhaotong** [ThatGuySam/doesitarm#217]
**The official name of the app**
Wechat Devtools

**Is there a supported version available on a stable release channel?**
Unknown

**Proposed App Status**
🔶 App has not yet been reported to be native to Apple Silicon

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
https://developers.weixin.qq.com/miniprogram/dev/devtools/stable.html
English version but far behind

**An Official App Download Page**
https://developers.weixin.qq.com/miniprogram/dev/devtools/download.html

**Additional context**
This software is built upon nw.js, which itself still doesn't support native Apple Silicon build. See nwjs/nw.js#7620

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
...

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by exgphe** [comment]
The official name of the app
Weixin DevTools

Proposed App Status
🔶 Unknown, more info needed

Proposed App Category
Developer Tools

Related Issue Tracker Link or discussion
https://developers.weixin.qq.com/miniprogram/dev/devtools/stable.html
[English version but far behind](https://developers.weixin.qq.com/miniprogram/en/dev/devtools/stable.html)

An Official App Download Link
https://developers.weixin.qq.com/miniprogram/dev/devtools/download.html

Additional context
This software is built upon nw.js, which itself still doesn't support native Apple Silicon build. See https://github.com/nwjs/nw.js/issues/7620

**Comment by ThatGuySam** [comment]
@exgphe Thanks for info! 

App is now live on the site! 

https://doesitarm.com/app/wechat-devtools/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/wechat-devtools/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
