### ISSUE TITLE
EasyConnect 

### ISSUE THREAD

**Issue by MrXuCh** [ThatGuySam/doesitarm#219]

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by Qetesh** [comment]
截止到标准版本7.6.9R1，暂时还不支持ARM架构的MAC终端使用EC客户端。

**Comment by Qetesh** [comment]
> 截止到标准版本7.6.9R1，暂时还不支持ARM架构的MAC终端使用EC客户端。

As of the standard version 7.6.9R1, it does not support the use of EC clients for ARM-based MAC terminals.

**Comment by ThatGuySam** [comment]
@Qetesh That's good to know. 

Can you provide a tracker link or Screenshot we can use as our source?

**Comment by Qetesh** [comment]
![Image of EasyConnect](http://qetesh.io/WX20201125-084758@2x.png)

**Comment by ThatGuySam** [comment]
Thanks, @Qetesh !

I hate to ask for another favor but is there any chance we can get a screenshot that includes Activity Monitor on the same screen so we can see the Architecture column? If we have that we can use it as our source link.

You can find an example on #176 (but it's in English)

**Comment by Qetesh** [comment]
Sorry, I don’t have a Silicon MacBook.

**Comment by ThatGuySam** [comment]
@Qetesh All good! There is another...

**Comment by ThatGuySam** [comment]
I've added this to the list as "🔶 Unknown, more info needed" and used this issue as a Contribute link so people can find it via the site and provide any info they have.

**Comment by robby927** [comment]
EasyConnect can run in the M1 macbook

**Comment by ThatGuySam** [comment]
@robby927 Nice! Drop a screenshot so we have a source link add we'll ship it! 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by Qetesh** [comment]
The official name of the app
EasyConnect

Is there a supported build available on a public/release channel?
Yes

Proposed App Status
✳️ Runs via iPadOS app

Proposed App Category
productivity-tools

An Official App Download Page
https://apps.apple.com/us/app/easyconnect/id440460214#?platform=ipad

Full Screenshot with the App and Activity Monitor(if self reporting) or Silicon Info
![Image of EasyConnect](https://www.qetesh.io/WeChat7ea6ae276616c1e679a3cfc162b00e63.png)

**Comment by ThatGuySam** [comment]
@Qetesh Looks great! 

This is ready to add to the list! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by Qetesh** [comment]
sangfor's easyconnect can run in the M1 macbook

**Comment by ThatGuySam** [comment]
@Qetesh Any chance you could drop a screenshot we can use as a verification link

If you can be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version.

You can find an example on #358

**Comment by Eric-Guo** [comment]
It works as Intel version, tested on M1 Pro, MacOS 12.3.1 without any issue.

<img width="1181" alt="Screen Shot 2022-05-01 at 15 39 25" src="https://user-images.githubusercontent.com/1131536/166136867-7625e5eb-911f-4107-b5ee-dd3898dfa634.png">

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/easyconnect/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
