### ISSUE TITLE
Things

### ISSUE THREAD

**Issue by cyberkurumin** [ThatGuySam/doesitarm#22]

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by frictionlessDevelopments** [comment]
**The official name of the app**
Things 3

**Proposed App Status**
❓ No announcements yet

**Related Issue Tracker Link or discussion**
N/A

**An Official App Download Link**
https://culturedcode.com/things/mac/appstore/

**Comment by KovalevArtem** [comment]
_Apple has announced three brand new Macs running on their very own Apple M1 chips – a MacBook Air, MacBook Pro, and Mac mini. As of today’s release – 3.13.2 – Things fully supports the new architecture in these machines._
https://culturedcode.com/things/blog/2020/11/new-things-for-macos-big-sur/
