### ISSUE TITLE
Aliwangwang

### ISSUE THREAD

**Issue by Jerry-Ge** [ThatGuySam/doesitarm#221]
Instant Messenging for Taobao

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by moffpage** [comment]
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/33549573/123615584-42bdef00-d827-11eb-9918-7a8588db131d.png">
<img width="333" alt="image" src="https://user-images.githubusercontent.com/33549573/123615593-45b8df80-d827-11eb-8126-aff083d2cc67.png">
Works via Rosetta 2

**Comment by ThatGuySam** [comment]
Thanks, @moffpage 

We'll use the following status:
✳️ Yes, works via Rosetta 2 translation

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/aliwangwang/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
