### ISSUE TITLE
Google Backup and Sync

### ISSUE THREAD

**Issue by HaowenZhang** [ThatGuySam/doesitarm#222]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**The official name of the app**
Google Backup and Sync

**Proposed App Status**
Unknown

**Proposed App Category**
Productivity

**Related Issue Tracker Link or discussion**

**An Official App Download Link**
https://www.google.com/intl/en_gh/drive/download/

**Additional context**

**Comment by pawelostr** [comment]
It crashes. It may be due to me denying all asked privileges. I can log in, but when choosing folders to sync and accepting I get error 8B227910.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ThatGuySam** [comment]
Got a report that it may be working now

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/google-backup-and-sync/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
