### ISSUE TITLE
Dash

### ISSUE THREAD

**Issue by ETiV** [ThatGuySam/doesitarm#225]
**The official name of the app**
Dash

**Proposed App Status**
Unknown

**Proposed App Category**
Developer Tools  / Productivity Tools

**Related Issue Tracker Link or discussion**
N/A

**An Official App Download Link**
https://kapeli.com/dash

**Comment by ThatGuySam** [comment]
#
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by alexruetz** [comment]
Dash is working under Rosetta
<img width="1200" alt="Bildschirmfoto 2020-11-27 um 10 55 41" src="https://user-images.githubusercontent.com/3075960/100436103-2db98b80-309f-11eb-973a-d0383d56d2f7.png">

Couldn't find any information about an upcoming or planned M1 update

**Comment by ThatGuySam** [comment]
Status: ✳️ Yes, works via Rosetta 2

**Comment by ThatGuySam** [comment]
We're ready to add this to the list! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/dash-for-macos/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by ykmind** [comment]
> Status: ✳️ Yes, works via Rosetta 2

I find that there is a problem with snippet on M1 Mac.
That is, when you use snippet, instead of a written statement, you delete the whole line

**Comment by ThatGuySam** [comment]
@ykmind Added link. 

Mind posting a screen recording or screenshot?
