### ISSUE TITLE
emacs

### ISSUE THREAD

**Issue by ptc-cprodan** [ThatGuySam/doesitarm#226]
**The official name of the app**
emacs

**Proposed App Status**
Not working due to problems with Guille. 

**Proposed App Category**
{What category should the app go under}

**Related Issue Tracker Link or discussion**
https://twitter.com/mnt_io/status/1327180165735215105?s=20

**An Official App Download Link**
https://www.gnu.org/software/emacs/

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

This can go under Developer Tools for now

**Comment by ThatGuySam** [comment]
Looks like we still need it's status on Rosetta 2

**Comment by bharadwaj6** [comment]
Both terminal and GUI versions run on Rosetta 2

<img width="1222" alt="Screenshot 2021-01-02 at 16 17 14" src="https://user-images.githubusercontent.com/1695154/103455786-fda47e80-4d15-11eb-97f2-92e172d04764.png">

**Comment by ThatGuySam** [comment]
Thanks, @bharadwaj6!

App is now live on the site! 

https://doesitarm.com/app/emacs/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by LER0ever** [comment]
Emacs is already running natively as of v27. Installed via homebrew formulae [`homebrew-emacs-plus`](https://github.com/d12frosted/homebrew-emacs-plus), screenshot below showing aarch64.

Ref: https://github.com/d12frosted/homebrew-emacs-plus/issues/284

<img width="1128" alt="Screen Shot 2021-01-06 at 11 14 44 AM" src="https://user-images.githubusercontent.com/10568668/103724901-65a5de00-5010-11eb-9d59-4bf7fb34e741.png">

**Comment by bharadwaj6** [comment]
Thanks for the update @LER0ever, didn't know about emacs plus. Just checked and it is running natively.


<img width="688" alt="Screenshot 2021-01-06 at 12 51 21" src="https://user-images.githubusercontent.com/1695154/103740769-e1f2ee00-501d-11eb-86e0-02317cead73f.png">

Updated the same here: https://github.com/ThatGuySam/doesitarm/pull/505

**Comment by ThatGuySam** [comment]
@djhworld Thanks for the report! 

Update is live! 

https://doesitarm.com/app/emacs/
