### ISSUE TITLE
Add Bitwarden

### ISSUE THREAD

**Issue by pawelostr** [ThatGuySam/doesitarm#229]
**The official name of the app**
Bitwarden 

**Proposed App Status**
Works under Rosetta 2 (incl. Safari extension)

**Proposed App Category**
Productivity

**Related Issue Tracker Link or discussion**
None
**An Official App Download Link**
Bitwarden.com
**Additional context**
personally tested

**Comment by ThatGuySam** [comment]
Thanks for the update! 

I've applied and it should be deployed within minutes
