### ISSUE TITLE
iTerm

### ISSUE THREAD

**Issue by djerfy** [ThatGuySam/doesitarm#23]
https://github.com/gnachman/iTerm2/pull/421

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by frictionlessDevelopments** [comment]
The official name of the app
iTerm2

Proposed App Status
[✅ Should be working](https://github.com/gnachman/iTerm2/pull/421#issuecomment-656161773)

Related Issue Tracker Link or discussion
[gnachman/iTerm2#421](https://github.com/gnachman/iTerm2/pull/421) was merged to master.

An Official App Download Link
https://iterm2.com/downloads.html
