### ISSUE TITLE
MAMP

### ISSUE THREAD

**Issue by Baffos** [ThatGuySam/doesitarm#231]
**The official name of the app**
MAMP

**An Official App Download Link**
https://www.mamp.info/en/mamp/mac/

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by NicolasSy** [comment]
<img width="1003" alt="Capture d’écran 2020-11-22 à 12 16 38" src="https://user-images.githubusercontent.com/6407613/99902276-dee5ad80-2cbc-11eb-84a3-6d9c75f99295.png">

It works via Rosetta 2.

I could run a WordPress installation.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/mamp/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
