### ISSUE TITLE
Rhino 7 for Mac

### ISSUE THREAD

**Issue by h1storia** [ThatGuySam/doesitarm#232]
**The official name of the app**
Rhino 7 

**Proposed App Status**
Official version launched recently

**Related Issue Tracker Link or discussion**
Official system requirement said "Do not support ARM based mac", link here: https://www.rhino3d.com/7/system-requirements/

**An Official App Download Link**
https://www.rhino3d.com/download/rhino-for-mac/evaluation

**Comment by ThatGuySam** [comment]
Thanks for App Request! 

Looks like it's saying it doesn't work on ARM for Windows. 

We'll look for a secondary verification to be sure.

**Comment by ThatGuySam** [comment]
We'll close this issue as duplicate in favor of the first issue #60
