### ISSUE TITLE
Lastpass Mac App

### ISSUE THREAD

**Issue by xanekka** [ThatGuySam/doesitarm#233]

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by xanekka** [comment]
The official name of the app {Lastpass Password Manager}

Proposed App Status {Partially working with Rosetta. Safari extension not working.}

Proposed App Category {Productivity Tools}

Related Issue Tracker Link or discussion {unknown}

An Official App Download Link {https://apps.apple.com/us/app/lastpass-password-manager/id926036361?mt=12}

**Comment by ThatGuySam** [comment]
Nice! We just need a screenshot or link we can use as a source we'll be good to go

**Comment by ThatGuySam** [comment]
You can find a screenshot example on #176

**Comment by xanekka** [comment]
<img width="852" alt="Screen Shot 2020-11-20 at 11 27 02 PM" src="https://user-images.githubusercontent.com/11390681/99867524-4d751f00-2b88-11eb-9116-7a60d8807ba2.png">

**Comment by ThatGuySam** [comment]
Status: ✳️ Yes, works via Rosetta 2

**Comment by ThatGuySam** [comment]
This is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by xanekka** [comment]
Safari extension working. Requires uninstall of the Mac App Store app and installing the Lastpass Mac app from their website.
https://community.logmein.com/t5/Support-Discussions/macOS-Big-Sur-Safari-14-0-1-Official-Support/m-p/256549

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/lastpass/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
