### ISSUE TITLE
Notability for Mac

### ISSUE THREAD

**Issue by xanekka** [ThatGuySam/doesitarm#235]

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by raphaelgurtner** [comment]
duplicate of #417 and already [live](https://doesitarm.com/app/notability/)

**Comment by ThatGuySam** [comment]
@raphaelgurtner Good catch! 

Closing this issue now. 

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
