### ISSUE TITLE
Airmail

### ISSUE THREAD

**Issue by KovalevArtem** [ThatGuySam/doesitarm#236]
**The official name of the app**
Airmail

**Proposed App Status**
Yes

**Proposed App Category**
Productivity

**Related Issue Tracker Link or discussion**
{This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes.}

**An Official App Download Link**
https://apps.apple.com/app/apple-store/id918858936

**Additional context**
https://apps.apple.com/app/apple-store/id918858936
![image](https://user-images.githubusercontent.com/36500228/99694375-681e9980-2a9d-11eb-9b7b-c5619e3a4388.png)

**Comment by ThatGuySam** [comment]
Looks great. 

Status: ✅ Yes, full native support as of v4.5.1

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/airmail/

Feel free to browse through the other issues to help with missing info on other apps.

**Comment by KovalevArtem** [comment]
<img width="583" alt="Снимок экрана 2020-12-03 в 22 18 39" src="https://user-images.githubusercontent.com/36500228/101077318-bbbcd700-35b5-11eb-9b36-25acc92d1306.png">
✅ Yes, Full Native Apple Silicon Support
