### ISSUE TITLE
AdBlock Pro for Safari

### ISSUE THREAD

**Issue by KovalevArtem** [ThatGuySam/doesitarm#237]
**The official name of the app**
AdBlock Pro for Safari

**Proposed App Status**
Yes

**Proposed App Category**
Utilities

**An Official App Download Link**
https://apps.apple.com/app/id1018301773

**Additional context**
![image](https://user-images.githubusercontent.com/36500228/99695384-8fc23180-2a9e-11eb-96d9-dd16dce95471.png)

Official site
https://adblockersafari.com/

**Comment by ThatGuySam** [comment]
Beautiful!

Status: ✅ Yes, full native support as of v8.1.0

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/adblock-pro-for-safari/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
