### ISSUE TITLE
Reeder

### ISSUE THREAD

**Issue by djerfy** [ThatGuySam/doesitarm#24]

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by frictionlessDevelopments** [comment]
**The official name of the app**
Reeder 5

**Proposed App Status**
❓ No announcements

**Related Issue Tracker Link or discussion**
No announcements yet

**An Official App Download Link**
https://itunes.apple.com/app/id1529448980

**Comment by djerfy** [comment]
Ready for Big Sur, release 5.0.4 👍

**Comment by ThatGuySam** [comment]
Perfect! 

Do you know id there's any kind of URL we can use as a source for the update support?

**Comment by ThatGuySam** [comment]
Next, we'll need someone with an M1 to provide a screenshot. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by moffpage** [comment]
Please close this issue, I'm gonna request an update, it has Apple Silicon support

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/reeder/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
