### ISSUE TITLE
GitKraken

### ISSUE THREAD

**Issue by alexmorbo** [ThatGuySam/doesitarm#244]
**The official name of the app**
GitKraken

**Proposed App Status**
I dont know

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
Can't find issue tracker for this soft.

**An Official App Download Link**
https://www.gitkraken.com/git-client

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by thunderstorm99** [comment]
It seems to run fine via Rosetta 2. See screenshot below.
![Screen Shot 2020-12-01 at 20 09 03](https://user-images.githubusercontent.com/3219279/100785853-89727480-3411-11eb-8788-6a33c4c503cc.png)

**Comment by ThatGuySam** [comment]
@thunderstorm99 Beautiful!

Status: ✳️ Yes, works via Rosetta 2

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/gitkraken/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
