### ISSUE TITLE
Mattermost 

### ISSUE THREAD

**Issue by alexmorbo** [ThatGuySam/doesitarm#245]
**The official name of the app**
Mattermost

**Proposed App Status**
Need to test

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
https://github.com/mattermost/desktop/issues/1365

**An Official App Download Link**
https://mattermost.com/download/

**Additional context**
Mattermost team says, that it might work, need to test.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

We'll see if we can find another tracker or test it ourselves

**Comment by alexruetz** [comment]
I can confirm that it is working with Rosetta

**Comment by ThatGuySam** [comment]
@alexmorbo Great! Let's get a screenshot that we can use as the source link and we'll move to the next stage

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an Activity Monitor example on #176

**Comment by svewag** [comment]
![image](https://user-images.githubusercontent.com/155578/100524707-89c50280-31ba-11eb-9350-89f0bcfbbc76.png)

**Comment by ThatGuySam** [comment]
Thanks, @svewag !!

Status: ✳️ Yes, works via Rosetta 2

We'll use that screenshot as the Source link

**Comment by ThatGuySam** [comment]
This is now ready to add. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/mattermost/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by BentEngbers** [comment]
There is now a beta build available for m1!
https://github.com/mattermost/desktop/releases
I am currently using it, and it seems to work fine.

**Comment by m0t1x** [comment]
Latest version for M1:https://releases.mattermost.com/desktop/5.0.2/mattermost-desktop-5.0.2-mac-m1.dmg

**Comment by ThatGuySam** [comment]
@m0t1x Thanks for the update! 

It is now live on the site! 

https://doesitarm.com/app/mattermost/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
