### ISSUE TITLE
RingCentral

### ISSUE THREAD

**Issue by zplzk2** [ThatGuySam/doesitarm#251]
**The official name of the app**
RingCentral

**Proposed App Status**
Unknown / unclear / no explicit information found on google.

**Proposed App Category**
Productivity Tools

**An Official App Download Link**
https://app.ringcentral.com/download/RingCentral.pkg
or
https://apps.apple.com/us/app/id715886894

**Comment by mikkoxutvu** [comment]
Duplicated with https://github.com/ThatGuySam/doesitarm/issues/86
My apology.

**Comment by zplzk2** [comment]
Duplicated with https://github.com/ThatGuySam/doesitarm/issues/86
My apology.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by zplzk2** [comment]
**The official name of the app**
RingCentral

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✳️ Yes, works via Rosetta 2

**Additional context**
Tested on an M1 MacBook Pro. Basic meeting functions (video / audio) work okay. Got frozen once in the settings page but recovered automatically after a few seconds.
App Version: 20.4.22.331 Web, 20.4.20.2686 Mac

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="926" alt="image" src="https://user-images.githubusercontent.com/198267/100675502-ee4ba300-331b-11eb-8039-f2cfd7906464.png">

**Comment by ThatGuySam** [comment]
That's beautiful! Thanks, @zplzk2 

We'll use this as the download link so people know what they are downloading from: https://www.ringcentral.com/desktop-app.html

This is ready to add to the list. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/ringcentral/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
