### ISSUE TITLE
IBM SPSS Statistics 

### ISSUE THREAD

**Issue by sdavern** [ThatGuySam/doesitarm#252]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**IBM SPSS Statistics**
{What's the full official name of the app}

https://www.ibm.com/account/reg/ie-en/signup?formid=urx-19774

{This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site.}

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Good news! We’re in-progress already!

You check out the existing issue at #113
