### ISSUE TITLE
Electron

### ISSUE THREAD

**Issue by tonyunreal** [ThatGuySam/doesitarm#253]
**The official name of the app**
Electron

**Proposed App Status**
Yes, Full native support for Apple Silicon (since 11.0.0), also runs under Rosetta 2 if your app needs it (see links below)

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
Apple Silicon Announcement: https://www.electronjs.org/blog/apple-silicon
Rosetta 2 Bug Ticket: https://github.com/electron/electron/pull/26570

**An Official App Download Link**
https://www.electronjs.org/releases/stable

**Comment by ThatGuySam** [comment]
For status we’ll put:
✅ Yes, full native support as of v11.0

**Comment by ThatGuySam** [comment]
This is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/electron/

Feel free to browse through the other issues to help with missing info on other apps.
