### ISSUE TITLE
Xcode

### ISSUE THREAD

**Issue by tonyunreal** [ThatGuySam/doesitarm#254]
**The official name of the app**
Xcode

**Proposed App Status**
Yes, full native support since 12.2

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
https://developer.apple.com/documentation/xcode-release-notes/xcode-12_2-release-notes

**An Official App Download Link**
https://apps.apple.com/us/app/xcode/id497799835
https://developer.apple.com/download/more/

**Comment by ThatGuySam** [comment]
Looks great!

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/xcode/

Feel free to browse through the other issues to help with missing info on other apps.
