### ISSUE TITLE
Parallels Desktop

### ISSUE THREAD

**Issue by popbones** [ThatGuySam/doesitarm#255]
**The official name of the app**
Parallels Desktop

**Proposed App Status**
⏹ No, not working at all but support is in development

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
https://www.parallels.com/blogs/parallels-desktop-apple-silicon-mac/

**An Official App Download Link**
https://www.parallels.com

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/parallels-desktop/

Feel free to browse through the other issues to help with missing info on other apps.
