### ISSUE TITLE
Moon FM - The Podcast App

### ISSUE THREAD

**Issue by gaodeng** [ThatGuySam/doesitarm#257]
**The official name of the app**
Moon FM

**Proposed App Status**
✅    Yes, Full Native Apple Silicon Support as of v2.0.3

**Proposed App Category**
Entertainment and Media Apps

**An Official App Download Link**
https://apps.apple.com/us/app/moon-fm-premium-podcast-app/id1465712037?mt=12

**Comment by ThatGuySam** [comment]
This looks great! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/moon-fm/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
