### ISSUE TITLE
Microsoft Edge

### ISSUE THREAD

**Issue by david30xie** [ThatGuySam/doesitarm#260]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**The official name of the app**
Microsoft Edge

**Proposed App Status**
will soon support Apple's M1 chips, source: https://www.windowscentral.com/microsoft-edge-will-soon-support-apples-m1-chips

**Proposed App Category**
Browser

**Related Issue Tracker Link or discussion**
https://www.windowscentral.com/microsoft-edge-will-soon-support-apples-m1-chips

**An Official App Download Link**
https://www.microsoft.com/en-us/edge

**Additional context**
{Add any other context or screenshots about the app request here.}

**Screenshot with Activity Monitor(if self reporting)**
{As screenshot with Activity Monitor open showing the App's architecture type}

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this article states that Edge also already works on Rosetta 2
https://www.techradar.com/news/microsoft-edge-is-also-getting-an-apple-m1-upgrade

**Comment by ThatGuySam** [comment]
Status: ✳️ Yes, works via Rosetta 2 with native support in development

**Comment by ThatGuySam** [comment]
This is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by tonyunreal** [comment]
Apparently it worked so bad under Rosetta for Forbes that they recommended against buying M1 Macs.
https://forums.macrumors.com/threads/forbes-goes-in-hard-with-damming-review-on-m1-pro.2270718/

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/microsoft-edge/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
