### ISSUE TITLE
MathFlash Fun Desktop Edition

### ISSUE THREAD

**Issue by duckida** [ThatGuySam/doesitarm#264]
**The official name of the app**
MathFlash Fun Desktop Edition

**Proposed App Status**
Works with Rosetta, porting in progress

**Proposed App Category**
Education

**Related Issue Tracker Link or discussion**
Don't have one 

**An Official App Download Link**
https://apps.apple.com/us/app/mathflash-fun-desktop-edition/id1516195356

**Screenshot with Activity Monitor(if self reporting)**

<img width="263" alt="Screen Shot 2020-11-20 at 8 22 08 AM" src="https://user-images.githubusercontent.com/61168649/99823651-7d311200-2b09-11eb-9b31-ed1c62a13d7f.png">

The app is a math practice app and it is based on Mac Catalyst.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

We can only list so many apps on the site. 

If you can give me a compelling reason why this should be on the list I'll be happy to add it.

**Comment by duckida** [comment]
> Thanks for the App Request!
> 
> We can only list so many apps on the site.
> 
> If you can give me a compelling reason why this should be on the list I'll be happy to add it.

1. It is good for distance learning
2. It works on Mac and there is an iOS version available!

**Comment by moffpage** [comment]
Wanted to give an update on this, it supports Apple Silicon natively:
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/33549573/123606527-cc1cf380-d81e-11eb-9aa8-1811940a9a52.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/123606529-cd4e2080-d81e-11eb-97ee-a87a94c61d1a.png">
<img width="1008" alt="image" src="https://user-images.githubusercontent.com/33549573/123606592-dccd6980-d81e-11eb-9cb2-efcee58619f3.png">

Haha, @ThatGuySam could you please close this issue with either submission to your website or denying.

**Comment by ThatGuySam** [comment]
Sounds good to me! Approved! 

We'll use the following status:
✅ Yes, Full Native Apple Silicon Support

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/mathflash-fun-desktop-edition/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
