### ISSUE TITLE
News Explorer 1.9.11

### ISSUE THREAD

**Issue by elemans** [ThatGuySam/doesitarm#265]
**The official name of the app**
News Explorer

**Proposed App Status**
Yes, Full Native Apple Silicon Support

**Proposed App Category**
Entertainment and Media Apps

**An Official App Download Link**
https://apps.apple.com/us/app/news-explorer/id1032670789

**Additional context**
https://betamagic.nl/news/2020/2020_09.html

**Screenshot with Activity Monitor(if self reporting)**

<img width="1440" alt="Screenshot 2020-11-20 at 17 35 10" src="https://user-images.githubusercontent.com/1911797/99825111-e2f7bb00-2b56-11eb-914e-e7afb86f2ee6.png">

**Comment by ThatGuySam** [comment]
That's beautiful! This is ready to go! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by iLtc** [comment]
`News Explorer` has been added in #285.
