### ISSUE TITLE
Asset Catalog Creator

### ISSUE THREAD

**Issue by Megatron1000** [ThatGuySam/doesitarm#269]
The official name of the app
Asset Catalog Creator

Proposed App Status
Yes, Full native support for Apple Silicon

Proposed App Category
Developer Tools

Related Issue Tracker Link or discussion
www.bridgetech.io

An Official App Download Link
https://apps.apple.com/us/app/asset-catalog-creator-pro/id809625456?mt=12

**Comment by ThatGuySam** [comment]
Thanks for the App Request! This looks good to go!

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.
