### ISSUE TITLE
DxO PhotoLab 4

### ISSUE THREAD

**Issue by lafonjm** [ThatGuySam/doesitarm#27]
**The official name of the app**
DxO PhotoLab 4

**Proposed App Status**
What's the current app status based off of current discussion or testing
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend 

**Related Issue Tracker Link or discussion**
This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes. 

**An Official App Download Link**
https://www.dxo.com/fr/dxo-photolab/download/

**Additional context**
Add any other context or screenshots about the app request here.

**Comment by ThatGuySam** [comment]
Looks like the download page only mentions Intel processors for Mac requirements so far

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/dxo-photolab/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
