### ISSUE TITLE
App Preview Video Converter

### ISSUE THREAD

**Issue by Megatron1000** [ThatGuySam/doesitarm#272]
The official name of the app
App Preview Video Converter

Proposed App Status
Yes, Full native support for Apple Silicon

Proposed App Category
Developer Tools

Related Issue Tracker Link or discussion
www.bridgetech.io

An Official App Download Link
https://apps.apple.com/us/app/app-preview-video-converter/id1137451860

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

This one too!

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.
