### ISSUE TITLE
VMware Fusion

### ISSUE THREAD

**Issue by chriscrossen** [ThatGuySam/doesitarm#273]

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by alexruetz** [comment]
VMware Fusion is currently not working but they are working on it. It is unknown yet when it will be ready.
Source: [Twitter](https://twitter.com/VMwareFusion/status/1326229094648832000)

**Comment by ThatGuySam** [comment]
Status: ⏹ No, not working at all but support is in development

**Comment by ThatGuySam** [comment]
Downlaod Link
https://www.vmware.com/products/fusion.html

**Comment by ThatGuySam** [comment]
This is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/vmware-fusion/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by zhongdongy** [comment]
The public tech preview is now available: https://customerconnect.vmware.com/downloads/get-download?downloadGroup=FUS-PUBTP-2021H1

Product: VMware Fusion Public Tech Preview 21H1
Version: e.x.p
Release Date: 2021-09-22
Build Number: 18656771

**Comment by zhongdongy** [comment]
I've tested Ubuntu Server 21.04 (ARM64) and it is working fine so far. But x86/x64 virtual machines (which I created using my Intel chip MBP 16) cannot be opened. An error prompt shows:

> This virtual machine cannot be powered on because it requires the X86 machine architecture, which is incompatible with this Arm machine architecture host.
  See KB-84273.
