### ISSUE TITLE
PDF Viewer

### ISSUE THREAD

**Issue by KovalevArtem** [ThatGuySam/doesitarm#274]
**The official name of the app**
PDF Viewer

**Proposed App Status**
Yes

**Proposed App Category**
Productivity

**Related Issue Tracker Link or discussion**

**An Official App Download Link**
https://apps.apple.com/app/id1120099014

**Additional context**
https://pdfviewer.io/blog/2020/pdf-viewer-5-1-for-ipad-iphone-mac/
![image](https://user-images.githubusercontent.com/36500228/99847750-9bd6ed80-2b89-11eb-8a89-f1db8ae0b2f7.png)

**Comment by ThatGuySam** [comment]
For status we'll say: 
✅ Yes, Full Native Apple Silicon Support

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/pdf-viewer/

Feel free to browse through the other issues to help with missing info on other apps.
