### ISSUE TITLE
Vysor 

### ISSUE THREAD

**Issue by KovalevArtem** [ThatGuySam/doesitarm#275]
**The official name of the app**
Vysor 

**Proposed App Status**
Yes

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**

**An Official App Download Link**
https://www.vysor.io/download/

**Additional context**
_Vysor works on Apple Silicon (the new MacBooks and Mac mini) without any additional changes! Very cool._
https://twitter.com/vysorapp/status/1329298424278093825

**Comment by ThatGuySam** [comment]
Status: ✅ Yes, Full Native Apple Silicon Support

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/vysor

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by snooprat** [comment]
It is not native, please check it.

**Comment by ThatGuySam** [comment]
@snooprat What's the issue it's having?

**Comment by snooprat** [comment]
@ThatGuySam I installed vysor latest version 1.3.4, it is still intel version, not native.
<img width="630" alt="image" src="https://user-images.githubusercontent.com/3624479/102446551-0b48db80-4069-11eb-8a63-7fdea634ccc9.png">

**Comment by ThatGuySam** [comment]
@snooprat Updated! 

https://doesitarm.com/app/vysor/
