### ISSUE TITLE
Geekbench

### ISSUE THREAD

**Issue by KovalevArtem** [ThatGuySam/doesitarm#276]
**The official name of the app**
Geekbench

**An Official App Download Link**
https://www.geekbench.com/download/mac/

**Comment by ThatGuySam** [comment]
Status: ✅ Yes, full native support as of v5.3

https://www.geekbench.com/blog/2020/11/geekbench-53/

**Comment by ThatGuySam** [comment]
This is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.
