### ISSUE TITLE
Update on Sublime Text Support

### ISSUE THREAD

**Issue by saagarjha** [ThatGuySam/doesitarm#279]
Here's a link about it: https://forum.sublimetext.com/t/arm-build/5882/87

(The forum post is about arm64 *Linux* support)

**Comment by ThatGuySam** [comment]
Interesting, how do you think we should update the page?

**Comment by saagarjha** [comment]
I think saying it works under Rosetta would probably be accurate for now.

**Comment by ThatGuySam** [comment]
I'm not able to find the supported builds on a public channel. 

Is there a link I can provide for people to download the ARM builds?

**Comment by saagarjha** [comment]
I don't think there is one for Darwin; that's what I'm trying to say. Sublime Text seems to be Intel-only for now and it runs under Rosetta.

**Comment by ThatGuySam** [comment]
Ah gotcha, I was misunderstanding the request. 

I'll update that right away.

**Comment by ThatGuySam** [comment]
New Status:
✳️ Yes, works via Rosetta 2 with native builds being tested

Is that what you're thinking?

**Comment by saagarjha** [comment]
I don't think there are native builds being tested right now, at least not externally. I'm sure they'll make one at some point, but I think it's Rosetta-only for now.

**Comment by ThatGuySam** [comment]
Updated! 

https://doesitarm.com/app/sublime-text/
