### ISSUE TITLE
Spark

### ISSUE THREAD

**Issue by dems54** [ThatGuySam/doesitarm#28]
**The official name of the app**
What's the full official name of the app

**Proposed App Status**
What's the current app status based off of current discussion or testing
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend 

**Related Issue Tracker Link or discussion**
This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes. 

**An Official App Download Link**
This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site. 

**Additional context**
Add any other context or screenshots about the app request here.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ThatGuySam** [comment]
@dems54 Is this for Spark Mail? 
https://sparkmailapp.com/

**Comment by ThatGuySam** [comment]
Spark Mail is now live on the site!

https://doesitarm.com/app/spark-mail/

Feel free to comment on this issue for any future updates.

Until then, you're welcome to browse through the other M1 Issues to help with missing info on other apps.
