### ISSUE TITLE
emacs

### ISSUE THREAD

**Issue by yibie** [ThatGuySam/doesitarm#280]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**emacs**
The extensible, customizable, self-documenting real-time display editor.

**Proposed App Status**
{What's the current app status based off of current discussion or testing
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend}

**Proposed App Category**
{What category should the app go under}

**Related Issue Tracker Link or discussion**
{This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes.}

**An Official App Download Link**
https://www.gnu.org/software/emacs/

**Additional context**
{Add any other context or screenshots about the app request here.}

**Screenshot with Activity Monitor(if self reporting)**
{As screenshot with Activity Monitor open showing the App's architecture type}

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Good news! This is already in progress on #226
