### ISSUE TITLE
VMWare Console

### ISSUE THREAD

**Issue by Botts85** [ThatGuySam/doesitarm#281]
**The official name of the app**
VMWare Console

**Is there a supported build available on a public/release channel?**
No

**Proposed App Status**
🚫 No, not yet supported only works on Intel-based Macs

**Proposed App Category**
Productivity

**An Official App Download Link**
https://apps.apple.com/ca/app/vmware-remote-console/id1230249825?mt=12

**Additional context**
App will not install with legacy .pkg installer, and Mac App Store will not allow VMWare Console to be installed on Apple Silicon.
<img width="932" alt="Screen Shot 2020-11-20 at 5 57 14 PM" src="https://user-images.githubusercontent.com/13722323/99863112-e9d3fd00-2b59-11eb-8c95-eba4d3739481.png">
<img width="617" alt="Screen Shot 2020-11-20 at 5 57 08 PM" src="https://user-images.githubusercontent.com/13722323/99863116-eb052a00-2b59-11eb-9174-4d0bb55392f8.png">

**Comment by ThatGuySam** [comment]
Let's use this issue page as one of the tracker links.

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/vmware-remote-console/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
