### ISSUE TITLE
Welly BBS

### ISSUE THREAD

**Issue by ytang** [ThatGuySam/doesitarm#283]
**The official name of the app**
Welly BBS

**Is there a supported build available on a public/release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support as of Version 2020.9

**Proposed App Category**
Social and communication

**Related Issue Tracker Link or discussion**
https://apps.apple.com/us/app/id1521402269

**An Official App Download Link**
https://apps.apple.com/us/app/id1521402269

**Screenshot with Activity Monitor(if self reporting)**
![Image 11-20-20 at 11 57 PM](https://user-images.githubusercontent.com/88049/99867974-61bb1b00-2b8c-11eb-8c8e-c74e803fce8c.jpg)

**Comment by ThatGuySam** [comment]
This looks great!

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/welly-bbs/

Feel free to browse through the other issues to help with missing info on other apps.
