### ISSUE TITLE
Sketch (design app) has an ARM version

### ISSUE THREAD

**Issue by joeyjungle** [ThatGuySam/doesitarm#287]
**The official name of the app**
Sketch

**Is there a supported build available on a public/release channel?**
Yes, Sketch v70 (latest release on main branch)

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**Related Issue Tracker Link or discussion**
{This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes.}

**An Official App Download Link**
Release notes: https://www.sketch.com/updates/

**Additional context**
{Add any other context or screenshots about the app request here.}

**Screenshot with Activity Monitor(if self reporting)**
{As screenshot with Activity Monitor open showing the App's architecture type}

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/sketch/

Feel free to browse through the other issues to help with missing info on other apps.
