### ISSUE TITLE
Handbrake

### ISSUE THREAD

**Issue by djerfy** [ThatGuySam/doesitarm#29]
**The official name of the app**
Handbrake

**Proposed App Status**
Universal application available in release 1.4 (not yet available)

**Related Issue Tracker Link or discussion**
https://github.com/HandBrake/HandBrake/pull/3176

**An Official App Download Link**
https://handbrake.fr/

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Is this an update to the current listing? 

https://doesitarm.com/app/handbrake/

**Comment by djerfy** [comment]
Sorry, I don't saw when I created this issue. I close it, it's ok for me. Thanks
