### ISSUE TITLE
Please add Charles Proxy

### ISSUE THREAD

**Issue by aceontech** [ThatGuySam/doesitarm#292]

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ThatGuySam** [comment]
Merging this into https://github.com/ThatGuySam/doesitarm/issues/122
