### ISSUE TITLE
GitHub Desktop

### ISSUE THREAD

**Issue by harryzcy** [ThatGuySam/doesitarm#293]
**The official name of the app**
GitHub Desktop

**Is there a supported build available on a public/release channel?**
No

**Proposed App Status**
⏹ No, not working at all but support is in development

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
desktop/desktop#10128

**Comment by ThatGuySam** [comment]
Download link
https://desktop.github.com/

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by harryzcy** [comment]
This issue comment mentioned that GitHub Desktop works under Rosetta: https://github.com/ThatGuySam/doesitarm/issues/54#issuecomment-730356477

**Comment by pawelostr** [comment]
App opens, push/pull/commit works, Activity Monitor says it runs under Rosetta

<img width="1072" alt="Zrzut ekranu 2020-11-22 o 08 30 23" src="https://user-images.githubusercontent.com/26488603/99897832-29573200-2c9d-11eb-918f-62c72cc91014.png">

**Comment by NicolasSy** [comment]
The desktop app seems to run fine under Rosetta 2 but sometimes it becomes unresponsive.

I don't know if it just stops reacting to clicks or if it's really frozen. 

Has anyone else encountered this problem?

**Comment by jbotte** [comment]
I couldn't even get it working under rosetta two, what build runs for you under it NicolasSy?

**Comment by ThatGuySam** [comment]
Even @NicolasSy is having issues. 

@pawelostr Are you experiencing any similar issues?

**Comment by pawelostr** [comment]
GitHub desktop 2.6.0, Xcode whatever is in the App Store, latest Xcode clt, whatever rosetta version I was prompted to install a week ago, git 2.24.3 (from clt).

In the last half an hour created test repo, committed & pushed a few times, no issues so far, no freezes etc. Not using git for anything serious currently so better testing probably won't happen.

**Comment by SamTolmay** [comment]
I have been using it for about a day under Rosetta without any issues, also v2.6.0.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/github-desktop/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by jbotte** [comment]
Still does not work for me. 
<img width="958" alt="Screen Shot 2020-11-29 at 11 34 48 PM" src="https://user-images.githubusercontent.com/2279461/100569253-79388900-329b-11eb-8b08-d248b6016a38.png">

**Comment by pawelostr** [comment]
@jbotte But are you actually trying to run it on Apple Silicon, i.e. Apple M1 processor?

**Comment by jbotte** [comment]
maybe it's because i'm on DTK but it's still apple silicon

**Comment by ThatGuySam** [comment]
@jbotte I think you're exactly right. 

I've heard reports that the Rosetta 2 that shipped with the DTK's does not support as many apps as the one that shipped with the full release.

**Comment by Regi24** [comment]
Apple Silicon beta available here https://central.github.com/deployments/desktop/desktop/latest/darwin-arm64?env=beta
