### ISSUE TITLE
balenaEtcher

### ISSUE THREAD

**Issue by harryzcy** [ThatGuySam/doesitarm#294]
**The official name of the app**
balenaEtcher

**Proposed App Status**
Unknown, possibly working with Rosetta or not working at all.

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
balena-io/etcher#3300
https://forums.balena.io/t/development-on-apple-silicon/185450

**An Official App Download Link**
https://github.com/balena-io/etcher/releases

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by tonyunreal** [comment]
The interface works under Rosetta at least. Will test flashing to a usb drive later.

![Screen Shot 2020-12-02 at 1 58 14 PM](https://user-images.githubusercontent.com/3460639/100834366-ba50b900-34a6-11eb-9e05-0be774785757.png)
![Screen Shot 2020-12-02 at 1 58 22 PM](https://user-images.githubusercontent.com/3460639/100834387-bfae0380-34a6-11eb-911f-ffb87842b912.png)

**Comment by tonyunreal** [comment]
First time flashing failed because of permission issues, second try worked like a charm.

![Screen Shot 2020-12-03 at 11 05 53 AM](https://user-images.githubusercontent.com/3460639/100958871-1a536800-3558-11eb-81d0-72a602f088a6.png)

**Comment by ThatGuySam** [comment]
Perfect!!

Status: ✳️ Yes, works via Rosetta 2

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/balenaetcher/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
