### ISSUE TITLE
Amphetamine

### ISSUE THREAD

**Issue by harryzcy** [ThatGuySam/doesitarm#295]
**The official name of the app**
Amphetamine

**Proposed App Status**
Yes, Full native support for Apple Silicon

**Proposed App Category**
Productivity

**An Official App Download Link**
https://apps.apple.com/us/app/amphetamine/id937984704

**Additional context**
It's explicitly said in "What's New" section on App Store that "Amphetamine is now a Universal app" starting from version 5.1

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/amphetamine

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
