### ISSUE TITLE
coconutBattery

### ISSUE THREAD

**Issue by tonyunreal** [ThatGuySam/doesitarm#296]
**The official name of the app**
coconutBattery

**Is there a supported build available on a public/release channel?**
Yes

**Proposed App Status**
Yes, full native support as of v3.9.2

**Proposed App Category**
Productivity Tools

**An Official App Download Link**
https://www.coconut-flavour.com/coconutbattery/

**Comment by ThatGuySam** [comment]
This is ready to go! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.
