### ISSUE TITLE
VMWare Horizon Client

### ISSUE THREAD

**Issue by whitebark** [ThatGuySam/doesitarm#297]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**The official name of the app**
VMWare Horizon Client

**Is there a supported build available on a public/release channel?**
No

**Proposed App Status**
Yes, works via Rosetta 2

**Proposed App Category**
Business / Remote Desktop

**Related Issue Tracker Link or discussion**
n/a

**An Official App Download Link**
https://my.vmware.com/en/web/vmware/downloads/info/slug/desktop_end_user_computing/vmware_horizon_clients/horizon_8

**Additional context**
Tested and working via Rosetta 2 on Apple M1

**Screenshot with Activity Monitor(if self reporting)**
<img width="1121" alt="Screen Shot 2020-11-21 at 3 54 51 PM" src="https://user-images.githubusercontent.com/59623140/99889409-03d11680-2c12-11eb-914f-9a15669dd4b3.png">

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/vmware-horizon-client/

Feel free to browse through the other issues to help with missing info on other apps.

**Comment by fredtanxo** [comment]
VMware Horizon Client is now natively support apple silicon since version 2209, build 8.7.0 (20615470)

Release Notes: https://docs.vmware.com/en/VMware-Horizon-Client-for-Mac/2209/rn/vmware-horizon-client-for-mac-2209-release-notes/index.html

**Comment by ThatGuySam** [comment]
@fredtanxo Listing updated! 

https://doesitarm.com/app/vmware-horizon-client/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
