### ISSUE TITLE
redis-server

### ISSUE THREAD

**Issue by whitebark** [ThatGuySam/doesitarm#298]
**The official name of the app**
redis (redis-server)

**Is there a supported build available on a public/release channel?**
Yes

**Proposed App Status**
Yes, Full Native Apple Silicon Support

**Proposed App Category**
Development (in-memory data structure store)

**Related Issue Tracker Link or discussion**
n/a

**An Official App Download Link**
https://redis.io/download

**Additional context**
`wget https://download.redis.io/releases/redis-6.0.9.tar.gz `
`tar xzf redis-6.0.9.tar.gz`
`cd redis-6.0.9`
`make`

**Screenshot with Activity Monitor(if self reporting)**
<img width="1121" alt="Screen Shot 2020-11-21 at 4 00 38 PM" src="https://user-images.githubusercontent.com/59623140/99889460-bc975580-2c12-11eb-80c6-b20ac9143190.png">

**Comment by ThatGuySam** [comment]
Beautiful!  

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site thanks to @tonyunreal ! 

https://doesitarm.com/app/redis/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by svewag** [comment]
I have problems running `redis-server` on M1 with Big Sur
see https://github.com/redis/redis/issues/8062

**Comment by whitebark** [comment]
@svewag As stated in this issue, redis is tested and working natively on M1, not through x86 brew arch flags. See Additional Context above to compile redis manually. Once compiled you can copy the binaries (redis-server and redis-cli) into /usr/local/bin to replace the brew x86 binaries that do not work.

**Comment by svewag** [comment]
I followed these instructions
- wget https://download.redis.io/releases/redis-6.0.9.tar.gz
- tar xzf redis-6.0.9.tar.gz
- cd redis-6.0.9
- make

But then `./src/redis-server` and `make test` outputs segmentation fault errors

**Comment by svewag** [comment]
`sudo ./src/redis-server` is working perfectly
