### ISSUE TITLE
Tower

### ISSUE THREAD

**Issue by djerfy** [ThatGuySam/doesitarm#30]
**The official name of the app**
Tower

**Proposed App Status**
🥇 Tower 6 works on Big Sur 

**Related Issue Tracker Link or discussion**
Official post: https://www.git-tower.com/blog/tower-mac-6/

This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes. 

**An Official App Download Link**
https://www.git-tower.com/mac

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/tower/

Feel free to browse through the other issues to help with missing info on other apps.

**Comment by matthewruzzi** [comment]
This app does not show up when searching for `git tower`.
