### ISSUE TITLE
Rogue Amoeba Apps

### ISSUE THREAD

**Issue by ThatGuySam** [ThatGuySam/doesitarm#300]
**The official name of the app**
Airfoil
Audio Hijack
Farrago
Fission
Loopback
Piezo
SoundSource

**Is there a supported build available on a public/release channel?**
Mixed

**Proposed App Status**
Mixed

**Proposed App Category**
Music and Audio Tools

**Related Issue Tracker Link or discussion**
https://rogueamoeba.com/status/

**An Official App Download Link**
https://rogueamoeba.com/

**Additional context**
Various apps but support is clearly reported by the developer

**Screenshot with Activity Monitor(if self reporting)**
None

**Comment by ThatGuySam** [comment]
Release Notes

Airfoil: https://rogueamoeba.com/airfoil/mac/releasenotes.php

Audio Hijack: https://rogueamoeba.com/audiohijack/releasenotes.php

Farrago: https://rogueamoeba.com/farrago/releasenotes.php

Fission: https://rogueamoeba.com/fission/releasenotes.php

Loopback: https://rogueamoeba.com/loopback/releasenotes.php

Piezo: https://rogueamoeba.com/piezo/releasenotes.php

SoundSource: https://rogueamoeba.com/soundsource/releasenotes.php

**Comment by ThatGuySam** [comment]
https://weblog.rogueamoeba.com/2020/11/16/rogue-amoeba-software-updates-for-macos-11-big-sur-and-m1-chip-based-macs/

Farrago, Fission
Run under Rosetta


Airfoil, Audio Hijack, Loopback, Piezo, and SoundSource
Can not run, not supported

**Comment by ThatGuySam** [comment]
Here is how we’ll set up the lines

* [Airfoil](https://rogueamoeba.com/airfoil/mac/) - ⏹ No, not yet but support is in development - [Release Notes](https://rogueamoeba.com/airfoil/mac/releasenotes.php) [Official Post](https://weblog.rogueamoeba.com/2020/11/16/rogue-amoeba-software-updates-for-macos-11-big-sur-and-m1-chip-based-macs/) 

* [Audio Hijack](https://rogueamoeba.com/audiohijack/) - ⏹ No, not yet but support is in development - [Release Notes](https://rogueamoeba.com/audiohijack/releasenotes.php) [Official Post](https://weblog.rogueamoeba.com/2020/11/16/rogue-amoeba-software-updates-for-macos-11-big-sur-and-m1-chip-based-macs/) 

* [Farrago](https://rogueamoeba.com/farrago/) - ✳️ Yes, works via Rosetta 2 as of v1.5.3 - [Release Notes](https://rogueamoeba.com/farrago/releasenotes.php) [Official Post](https://weblog.rogueamoeba.com/2020/11/16/rogue-amoeba-software-updates-for-macos-11-big-sur-and-m1-chip-based-macs/) 

* [Fission](https://rogueamoeba.com/fission/) - ✳️ Yes, works via Rosetta 2 as of v2.6 - [Release Notes](https://rogueamoeba.com/fission/releasenotes.php) [Official Post](https://weblog.rogueamoeba.com/2020/11/16/rogue-amoeba-software-updates-for-macos-11-big-sur-and-m1-chip-based-macs/) 

* [Loopback](https://rogueamoeba.com/loopback/) - ⏹ No, not yet but support is in development - [Release Notes](https://rogueamoeba.com/loopback/releasenotes.php) [Official Post](https://weblog.rogueamoeba.com/2020/11/16/rogue-amoeba-software-updates-for-macos-11-big-sur-and-m1-chip-based-macs/) 

* [Piezo](https://rogueamoeba.com/piezo/) - ⏹ No, not yet but support is in development - [Release Notes](https://rogueamoeba.com/piezo/releasenotes.php) [Official Post](https://weblog.rogueamoeba.com/2020/11/16/rogue-amoeba-software-updates-for-macos-11-big-sur-and-m1-chip-based-macs/) 

* [SoundSource](https://rogueamoeba.com/soundsource/) - ⏹ No, not yet but support is in development - [Release Notes](https://rogueamoeba.com/soundsource/releasenotes.php) [Official Post](https://weblog.rogueamoeba.com/2020/11/16/rogue-amoeba-software-updates-for-macos-11-big-sur-and-m1-chip-based-macs/)

**Comment by Kurville** [comment]
https://weblog.rogueamoeba.com/2020/12/17/all-rogue-amoeba-apps-now-have-official-support-for-the-new-m1-macs/

**Comment by ThatGuySam** [comment]
@Kurville Good catch!

Updated: https://doesitarm.com/app/airfoil/
