### ISSUE TITLE
Wolfram Mathematica

### ISSUE THREAD

**Issue by FreemanArthur** [ThatGuySam/doesitarm#301]
**The official name of the app**
Wolfram Mathematica

**Is there a supported build available on a public/release channel?**
Not for native Apple Silicon

**Proposed New App Status**
✳️ Yes, works via Rosetta 2 as of v12

**Related Issue Tracker Link or discussion**
https://community.wolfram.com/groups/-/m/t/2118125#_19_message_2121051

**An Official App Download Link**
https://www.wolfram.com/mathematica/

**Additional context**
Works under Rosetta 2, however, a native version is highly likely in the future. 

Listed as supported on the official system requirements page - https://www.wolfram.com/mathematica/system-requirements.html

**Screenshot with Activity Monitor(if self reporting)**

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by harryzcy** [comment]
The official name is Wolfram Mathematica (there's a typo in the title)

App website link: https://www.wolfram.com/mathematica/

On the system requirement page (https://www.wolfram.com/mathematica/system-requirements.html), it's said that "Compatibility will be confirmed after full testing on the new Apple Silicon hardware finishes." So I assume that page would be updated once they finish the testing.

**Comment by ThatGuySam** [comment]
Okay, so now we'll need to check for Rosetta support on the M1

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/wolfram-mathematica/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
