### ISSUE TITLE
Mac Ports

### ISSUE THREAD

**Issue by geirnoklebye** [ThatGuySam/doesitarm#302]
**The official name of the app**
Mac Ports

**Is there a supported build available on a public/release channel?**
Yes

**Proposed App Status**
Full Native Apple Silicon Support

**Proposed App Category**
Developer Tool

**Related Issue Tracker Link or discussion**
Mac Ports supports 1000s of open source packages and libraries. If available, it will pull down a native version and install. If not it will pull down the source code and compile a native version. Obviously, for older versions of ports, they may not compile at all. 
Requires Xcode command line tools installed on the system.

**An Official App Download Link**
https://www.macports.org/install.php

**Additional context**

**Screenshot with Activity Monitor(if self reporting)**

**Comment by tonyunreal** [comment]
It appears that the ports that haven't adapt to the arm64 architecture will be compiled and installed as x86_64 binaries, allowing them to run with Rosetta 2, though I haven't test MacPorts at all. See [this ticket](https://trac.macports.org/ticket/61430) for reference.

Also I believe this one is different from the Homebrew situation, where the entire installation has to be either arm64 or x86_64, although [multiple installations on the same machine also work](https://soffes.blog/homebrew-on-apple-silicon).

**Comment by ThatGuySam** [comment]
Based on @tonyunreal's ticket link, we'll use the following status:
✳️ Yes, works via Rosetta 2

**Comment by ThatGuySam** [comment]
We'll keep an eye on the releases to see when full native support drops: 
https://github.com/macports/macports-base/releases

We'll also use that in out tracker links so people can report it manually

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site thanks to @tonyunreal ! 

https://doesitarm.com/app/macports/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
