### ISSUE TITLE
Update on OBS

### ISSUE THREAD

**Issue by tonyunreal** [ThatGuySam/doesitarm#303]
**The official name of the app**
OBS

**Is there a supported build available on a public/release channel?**
Yes

**Proposed New App Status**
Yes, works via Rosetta 2

**Related Issue Tracker Link or discussion**
MacRumors discussion: https://forums.macrumors.com/threads/so-hows-m1-for-streamers-obs-streamlabs-obs-etc.2269239/

**An Official App Download Link**
https://obsproject.com/download

**Comment by ThatGuySam** [comment]
Update is live!

https://doesitarm.com/app/obs/
