### ISSUE TITLE
esri cityengine

### ISSUE THREAD

**Issue by baniasthbird** [ThatGuySam/doesitarm#305]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**The official name of the app**
{What's the full official name of the app}

**Is there a supported build available on a public/release channel?**
{Yes/No}

**Proposed App Status**
{What's the current app status based off of current discussion or testing
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend}

**Proposed App Category**
{What category should the app go under}

**Related Issue Tracker Link or discussion**
{This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes.}

**An Official App Download Link**
{This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site.}

**Additional context**
{Add any other context or screenshots about the app request here.}

**Screenshot with Activity Monitor(if self reporting)**
{As screenshot with Activity Monitor open showing the App's architecture type}

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by moffpage** [comment]
https://community.esri.com/t5/arcgis-cityengine-documents/announcement-deprecation-of-macos-version-of-arcgis-cityengine/ta-p/1038521
<img width="833" alt="image" src="https://user-images.githubusercontent.com/33549573/123615797-7567e780-d827-11eb-818c-04a58eb74b39.png">

I think we should close this issue and create a new one if there'll be a beta or early access or some about that

**Comment by ThatGuySam** [comment]
Good find @moffpage!

We'll use the following status:
🚫 No, not supported, and no plans for support

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/arcgis-cityengine/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
