### ISSUE TITLE
Atom

### ISSUE THREAD

**Issue by tinymachine** [ThatGuySam/doesitarm#307]
**The official name of the app**
Atom

**Is there a supported build available on a public/release channel?**
Yes

**Proposed New App Status**
✳️ Yes, works via Rosetta 2

**Related Issue Tracker Link or discussion**
([The issue](https://github.com/atom/atom/issues/21078) cited as evidence that Atom doesn't work is still open, but I'm able to open the current stable release (1.53.0) with no trouble on an M1 MacBook Air via Rosetta 2.

**An Official App Download Link**
https://atom.io

**Additional context**
{Add any other context or screenshots about the app request here.}

**Screenshot with Activity Monitor(if self reporting)**
<img width="898" alt="Screen Shot 2020-11-22 at 10 51 10 PM" src="https://user-images.githubusercontent.com/171986/99935285-39aaf380-2d15-11eb-90bd-5aaef734df49.png">

**Comment by ThatGuySam** [comment]
Update is live!

https://doesitarm.com/app/atom/
