### ISSUE TITLE
Alfred

### ISSUE THREAD

**Issue by djerfy** [ThatGuySam/doesitarm#31]
**The official name of the app**
Alfred

**Proposed App Status**
In progress, beta available here: https://www.alfredapp.com/universal/

**Related Issue Tracker Link or discussion**
Official post: https://www.alfredapp.com/blog/announcements/alfred-ready-for-apple-m1-chip/

**An Official App Download Link**
https://www.alfredapp.com/universal/

**Comment by ThatGuySam** [comment]
Alfred is live!

https://doesitarm.com/app/alfred/
