### ISSUE TITLE
Gephi

### ISSUE THREAD

**Issue by maria-rosa** [ThatGuySam/doesitarm#311]
**The official name of the app**
Gephi

**Proposed App Status**
No current status. Reported issue with Big Sur: https://github.com/gephi/gephi/issues/2222

**Proposed App Category**
Productivity Tools

**An Official App Download Link**
https://gephi.org/users/download/

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by moffpage** [comment]
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/123592756-77be4780-d80f-11eb-98ab-3b02ef024849.png">
Idk why Finder doesn't show architecture, but it runs under Rosetta 2:
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/33549573/123592813-8ad11780-d80f-11eb-8b82-6407366af876.png">

**Comment by ThatGuySam** [comment]
Gracias, @moffpage! 

We'll use the following status:
✳️ Yes, works via Rosetta 2 translation

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/gephi/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
