### ISSUE TITLE
iMazing 2

### ISSUE THREAD

**Issue by 549876099** [ThatGuySam/doesitarm#312]
**The official name of the app**
iMazing 2

**Is there a supported build available on a public/release channel?**
Yes

**Proposed App Status**
Yes, works via Rosetta 2 with native support in development
https://downloads.imazing.com/mac/iMazing/2.13.1.14452/release-notes.html

**Proposed App Category**
Productivity Tools

**An Official App Download Link**
https://imazing.com/download

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/imazing-2

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
