### ISSUE TITLE
QGIS, Needs M1 Testing

### ISSUE THREAD

**Issue by nap1218** [ThatGuySam/doesitarm#313]
**The official name of the app**
QGIS

**Is there a supported build available on a public/release channel?**
Yes

**Proposed App Status**
Unknown

**Proposed App Category**
Geospatial mapping

**Related Issue Tracker Link or discussion**
https://www.reddit.com/r/QGIS/comments/hgsfv1/qgis_for_apple_silicon_macs/

**An Official App Download Link**
https://qgis.org/en/site/forusers/download.html

**Additional context**

**Screenshot with Activity Monitor(if self reporting)**

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ThatGuySam** [comment]
Looks like there's an open issue on the QGIS repo
https://github.com/qgis/QGIS/issues/41224

**Comment by jesstelford** [comment]
Was able to test this just now on an M1 MacBook Air, here are the results:

---

**The official name of the app**
QGIS

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Yes, works via Translation or Virtualization

**Proposed App Category**
Geospatial mapping

**Related Issue Tracker Link or discussion**
https://github.com/qgis/QGIS/issues/41224

**An Official App Download Page**
https://qgis.org/en/site/forusers/download.html

**Additional context**
Tested version: `3.16.4-Hannover`

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="898" alt="Screen Shot 2021-03-19 at 1 29 32 pm" src="https://user-images.githubusercontent.com/612020/111723432-a1361180-88b7-11eb-94f3-a6a6ba2fc826.png">

**Comment by ThatGuySam** [comment]
@jesstelford you're a gentleman and scholar, thank you. 

This is one of the most requested apps that we haven't been able to report on yet. 

It's super critical to people in certain industries and they'll be very delighted to know they can safely switch to the new Apple Silicon hardware without losing on their most important tools.

**Comment by jesstelford** [comment]
🤩 My pleasure!

It should be noted that all I did was load the application and click around a bit. I've never used it before and am not sure if there's a particular workflow that should be tested or not.

Having said that, it loaded first time without any issues, and so far every other application I've run under Rosetta 2 has been flawless.

**Comment by ThatGuySam** [comment]
It might not seem like a lot but there are industries all over that want the improved performance of the new Macs but need solid verification before making a purchase of, possibly, multiple thousands of dollars. 

However, there are too many random apps that these people critically depend on to do their work for Apple to be able to guarantee functionality, for now. 

So your screenshot may be the best verification someone has to know an upgrade is safe enough.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/qgis/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
