### ISSUE TITLE
Tidal

### ISSUE THREAD

**Issue by ftpmorph** [ThatGuySam/doesitarm#314]
**The official name of the app**
TIDAL

**Is there a supported build available on a public/release channel?**
No

**Proposed App Status**
Works via Rosetta 2 but has random force quits as of version 2.23.0.488. No public beta available.

**Proposed App Category**
Music streaming

**Related Issue Tracker Link or discussion**
Can't find any.

**An Official App Download Link**
https://tidal.com/download

**Additional context**
<img width="372" alt="Screenshot 2020-11-24 at 7 37 18 pm" src="https://user-images.githubusercontent.com/67348935/100143003-94b32680-2e8c-11eb-9ba8-17dd0e89b15d.png">

**Screenshot with Activity Monitor(if self reporting)**
<img width="634" alt="Screenshot 2020-11-24 at 7 36 58 pm" src="https://user-images.githubusercontent.com/67348935/100142992-8e24af00-2e8c-11eb-9a1f-917fe51fc50e.png">

**Comment by pawelostr** [comment]
I'm getting the same force quits for no reason.

**Comment by ftpmorph** [comment]
Hopefully this is fixed soon. In the meantime at least you can use the web player. Chrome and Chromium based browsers with Widevine support are confirmed to work. But IIRC the max quality via the web app is HiFi, no Master. Happy to be corrected on that if I am mistaken.

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/tidal

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by ftpmorph** [comment]
Update was pushed out this morning that seems to improve stability issues in Rosetta 2. Currently going through a playlist with no problems. It still shows a force close error every time you quit the app (rather ironically) but during use seems more stable.

Not 100% sure if this is just placebo so far though, I'll put in an PR with an update if I can use it throughout the day without it randomly force quitting on me.

Version number is still 2.23.0.488 but with a new build date of 2020-11-25 and the release notes viewable within the app include "various bug fixes." No further info and no official forums either unfortunately.

I did find a Tidal bug report page if anyone else wants to make sure they're aware of the issues with Rosetta 2: https://tidal.com/bugreport/

<img width="507" alt="Screenshot 2020-11-26 at 7 39 57 am" src="https://user-images.githubusercontent.com/67348935/100321462-a1ce3380-2fba-11eb-9a3f-e3e09f719fa8.png">

**Comment by ftpmorph** [comment]
You couldn't make this up... their bug report form doesn't work! 😂

<img width="723" alt="Screenshot 2020-11-26 at 8 02 34 am" src="https://user-images.githubusercontent.com/67348935/100323634-f6bf7900-2fbd-11eb-9039-4bb56e4494cd.png">
