### ISSUE TITLE
IVPN

### ISSUE THREAD

**Issue by ftpmorph** [ThatGuySam/doesitarm#315]
**The official name of the app**
IVPN

**Is there a supported build available on a public/release channel?**
No

**Proposed App Status**
Works 100% fine via Rosetta 2, but no ARM build yet.

**Proposed App Category**
Productivity (?)

**Related Issue Tracker Link or discussion**
Official GitHub profile: https://github.com/ivpn
Official changelog on GitHub: https://github.com/ivpn/desktop-app-ui/blob/master/CHANGELOG_macos.md
Official blog: https://www.ivpn.net/blog/

**An Official App Download Link**
https://www.ivpn.net/apps-macos/

**Additional context**
N/A

**Screenshot with Activity Monitor(if self reporting)**
<img width="620" alt="Screenshot 2020-11-24 at 7 48 11 pm" src="https://user-images.githubusercontent.com/67348935/100143971-02ac1d80-2e8e-11eb-9818-ff0c5eccfb7c.png">

**Comment by ThatGuySam** [comment]
Status: ✳️ Yes, works via Rosetta 2

Productivity Tools is good for now. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/ivpn

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by yashendra2797** [comment]
IVPN now has an M1 native app as explained in this update: https://twitter.com/ivpnnet/status/1457747085986566149?s=20

This is a separate binary however and IVPN doesn't intend to switch to universal binaries anytime soon

**Comment by ThatGuySam** [comment]
@yashendra2797 Thanks for the update! 

It is now live on the site! 

https://doesitarm.com/app/ivpn/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
