### ISSUE TITLE
NordVPN

### ISSUE THREAD

**Issue by jonathantneal** [ThatGuySam/doesitarm#317]
**The official name of the app**
NordVPN

**Is there a supported build available on a public/release channel?**
No

**Proposed App Status**
⏹ No, not working at all but support is in development

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
N/A

**An Official App Download Link**
https://nordvpn.com/download/nordvpn-site/

**Additional context**
From my conversation with NordVPN Customer Support:

> Unfortunately, we do not have any information at this time whether NordVPN works with Rosetta.
> However, you can set up NordVPN without the app using this tutorial:
https://support.nordvpn.com/Connectivity/macOS/1133051642/How-to-connect-to-NordVPN-with-IKEv2-IPSec-on-macOS.htm
> We are still planning to make the NordVPN app compatible with Silicon. :)
> However, we would rather not give you an estimation of when this happens, when we do not actually have one for certain.
> Telling you that it will take 5 days and if in reality it ends up taking 2 months - would be bad for both sides involved.
> We understand that waiting is rather frustrating, and I can only apologize in the name of the company.
> Do not hesitate to contact us whenever in need! Have an amazing day and stay safe. :)

**Screenshot with Activity Monitor(if self reporting)**
N/A

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

It looks like they gave a non-answer on Rosetta support see we'll need to get a screenshot ourselves.

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an Activity Monitor example on #176

**Comment by ThatGuySam** [comment]
Looks we need a screenshot. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by yarseyah** [comment]
<img width="1000" alt="Screenshot 2020-12-01 at 22 38 50" src="https://user-images.githubusercontent.com/2149775/100806819-0b21cc80-3429-11eb-9194-430b3321496e.png">

**Comment by yarseyah** [comment]
With `About this Mac` too

<img width="1174" alt="Screenshot 2020-12-01 at 23 03 06" src="https://user-images.githubusercontent.com/2149775/100807222-dd895300-3429-11eb-8eab-881d82c2dc7e.png">

**Comment by ThatGuySam** [comment]
@yarseyah Beautiful!!

* [NordVPN](https://nordvpn.com/download/nordvpn-site/) - ✳️ Yes, works via Rosetta 2 - [Source](https://github.com/ThatGuySam/doesitarm/issues/317#issuecomment-736876490)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/nordvpn/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
