### ISSUE TITLE
AmorphousDiskMark

### ISSUE THREAD

**Issue by tonyunreal** [ThatGuySam/doesitarm#321]
**The official name of the app**
AmorphousDiskMark

**Is there a supported build available on a public/release channel?**
Yes

**Proposed App Status**
Yes, full native Apple Silicon support as of v3.1

**Proposed App Category**
Productivity Tools

**An Official App Download Link**
https://apps.apple.com/us/app/amorphousdiskmark/id1168254295

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/amorphousdiskmark/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
