### ISSUE TITLE
Suggestion: Silicon Info, shows which architecture an app is running in the toolbar without Activity Monitor

### ISSUE THREAD

**Issue by ftpmorph** [ThatGuySam/doesitarm#325]
Rather than having to open up Activity Monitor to screenshot the architecture an app is running on this is much more convenient and clean.

Propose we can be allowed to use it for submitting new apps and/or have it be suggested in the template.

Here's the GitHub project: https://github.com/billycastelli/Silicon-Info

(I have no affiliation with the project or the dev, just thought it was a useful little app to be aware of for our purposes.)

**Comment by ThatGuySam** [comment]
Added!
