### ISSUE TITLE
[BUG] - Incorrect links after selecting tabs

### ISSUE THREAD

**Issue by gijo-varghese** [ThatGuySam/doesitarm#327]
### How to reproduce the issue
1. Open https://doesitarm.com/
2. Click on the tab 'Developer tools'
3. From the list, click on 'Android Studio'. But the link is https://doesitarm.com/app/macports (MacPorts)

![image](https://user-images.githubusercontent.com/23092846/100218432-c2ef3f80-2f3a-11eb-85f5-45069b070f5d.png)

**Comment by ThatGuySam** [comment]
Fixed! 

Looks there was an issue between the sorted on the rendered HTML and in the browser. 

It should be working as expected now.

**Comment by gijo-varghese** [comment]
Great!
