### ISSUE TITLE
VirtualBox

### ISSUE THREAD

**Issue by ClNevil** [ThatGuySam/doesitarm#33]
**The official name of the app**
What's the full official name of the app

**Proposed App Status**
What's the current app status based off of current discussion or testing
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend 

**Related Issue Tracker Link or discussion**
This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes. 

**An Official App Download Link**
This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site. 

**Additional context**
Add any other context or screenshots about the app request here.

**Comment by bunyipdown** [comment]
The download link is https://www.virtualbox.org/wiki/Downloads

**Comment by steve1878** [comment]
The official name of the app
VirtualBox

Proposed App Status
🚫 No, not yet supported only works on Intel-based Macs and most likely will never run on Apple Silicon

Related Issue Tracker Link or discussion
Discussion (https://forums.virtualbox.org/viewtopic.php?f=8&t=98742)

An Official App Download Link
Download for Intel-based Macs (https://www.virtualbox.org/wiki/Downloads)

Additional context
VirtualBox on Apple Silicon is of very limited use as it does not emulate Intel hardware.

**Comment by steve1878** [comment]
Corresponding pull request: https://github.com/ThatGuySam/doesitarm/pull/557

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/virtualbox/

Thanks, @steve1878 for the pull request!

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
