### ISSUE TITLE
Flycut

### ISSUE THREAD

**Issue by SamTolmay** [ThatGuySam/doesitarm#330]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**The official name of the app**
General Arcade Flycut (Clipboard manager)

**Is there a supported build available on a public/release channel?**
Yes

**Proposed App Status**
Yes, works via Rosetta 2

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
None

**An Official App Download Page**
https://apps.apple.com/za/app/flycut-clipboard-manager

**Additional context**
App was last updated 9 mo ago according to Apple App Store Page

**Full Screenshot with the App and Activity Monitor(if self reporting)**
<img width="1440" alt="Screenshot 2020-11-25 at 14 33 46" src="https://user-images.githubusercontent.com/23532753/100228779-dfd04680-2f2b-11eb-90a2-46ef1f7648b6.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! This looks great!

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/flycut/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
