### ISSUE TITLE
Vivaldi Browser

### ISSUE THREAD

**Issue by ftpmorph** [ThatGuySam/doesitarm#331]
**The official name of the app**
Vivaldi

**Is there a supported build available on a public/release channel?**
No, but one is in development

**Proposed App Status**
Working via Rosetta 2, Apple Silicon build in progress

**Proposed App Category**
Productivity 

**Related Issue Tracker Link or discussion**
Official tweet confirming it's being worked on but no ETA: https://twitter.com/vivaldibrowser/status/1331214812689428482
Official blog: https://vivaldi.com/blog/
Official snapshot builds: https://vivaldi.com/blog/desktop/snapshots/
Thread on the official forum: https://forum.vivaldi.net/topic/52866/apple-silicon

**An Official App Download Page**
https://vivaldi.com/download/

**Full Screenshot with the App and Activity Monitor(if self reporting)**
<img width="617" alt="Screenshot 2020-11-25 at 2 47 00 pm" src="https://user-images.githubusercontent.com/67348935/100245674-39d30b00-2f30-11eb-9c53-d47f7fa6d00d.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/vivaldi/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
