### ISSUE TITLE
Cyberduck

### ISSUE THREAD

**Issue by ftpmorph** [ThatGuySam/doesitarm#333]
**The official name of the app**
Cyberduck

**Is there a supported build available on a public/release channel?**
No

**Proposed App Status**
Works via Rosetta 2, Apple Silicon build in development

**Proposed App Category**
Developer tools

**Related Issue Tracker Link or discussion**
Official blog: https://blog.cyberduck.io/
Confirmation a native ARM build is in the works: https://blog.cyberduck.io/2020/11/10/big-sur/#disqus_thread (in Disqus comments)

**An Official App Download Page**
https://cyberduck.io/download/

**Full Screenshot with the App and Activity Monitor(if self reporting)**
<img width="615" alt="Screenshot 2020-11-25 at 5 32 10 pm" src="https://user-images.githubusercontent.com/67348935/100262918-bc65c580-2f44-11eb-9dff-cf27b16b393b.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/cyberduck

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by marcotini** [comment]
<img width="732" alt="Screenshot 2021-11-25 at 19 08 40" src="https://user-images.githubusercontent.com/3670558/143486918-e1995615-8057-45c0-a773-4dd723e8d42b.png">
<img width="1224" alt="Screenshot 2021-11-25 at 19 09 27" src="https://user-images.githubusercontent.com/3670558/143486927-db004242-8601-4682-8c15-3640c38bd842.png">

**Comment by dkocher** [comment]
> https://blog.cyberduck.io/2021/11/25/embracing-apple-silicon/

**Comment by ThatGuySam** [comment]
@marcotini  @dkocher Thanks for the update!

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
Thanks for the patience on this! Update is now live on the site! 

https://doesitarm.com/app/cyberduck/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
