### ISSUE TITLE
Secrets

### ISSUE THREAD

**Issue by bsunarjo** [ThatGuySam/doesitarm#335]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**The official name of the app**
Secrets

**Is there a supported build available on a public/release channel?**
Yes

**Proposed App Status**
Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
https://outercorner.com/blog/2020/11/password-autofill-now-on-macos-big-sur/

**An Official App Download Page**
https://itunes.apple.com/app/secrets/id973049011?mt=12&at=1001lmS6&ct=website

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

This looks good to go!

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/secrets-for-mac/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
