### ISSUE TITLE
Wireshark

### ISSUE THREAD

**Issue by alexruetz** [ThatGuySam/doesitarm#336]
**The official name of the app**
Wireshark

**Is there a supported build available on a public/release channel?**
No

**Proposed App Status**
✳️ Yes, works via Rosetta 2

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
Couldn't find a issue for the apple silicon transition

**An Official App Download Page**
https://www.wireshark.org

**Full Screenshot with the App and Activity Monitor(if self reporting)**
<img width="1440" alt="Bildschirmfoto 2020-11-25 um 20 40 21" src="https://user-images.githubusercontent.com/3075960/100274304-787fba00-2f5e-11eb-9365-943c8e94dc4b.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/wireshark

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
