### ISSUE TITLE
Signal Messenger

### ISSUE THREAD

**Issue by ftpmorph** [ThatGuySam/doesitarm#337]
Creating a PR for this now, just making this issue so I can document a source for it working on Rosetta 2 as well as some info and a list of resources.

**The official name of the app**
Signal

**Is there a supported build available on a public/release channel?**
No

**Proposed App Status**
Runs on Rosetta 2, no problems

**Proposed App Category**
Social and communication

**Related Issue Tracker Link or discussion**
Official blog: https://www.signal.org/blog/
Twitter: https://twitter.com/signalapp
GitHub repo: https://github.com/signalapp/Signal-Desktop
GitHub releases with changelogs: https://github.com/signalapp/Signal-Desktop/releases

**An Official App Download Page**
https://www.signal.org/download/

**Additional context**
The Signal Desktop app is an Electron powered JS app running in a browser container so ARM support will depend on Electron.

**Full Screenshot with the App and Activity Monitor(if self reporting)**
<img width="614" alt="Screenshot 2020-11-25 at 10 01 38 pm" src="https://user-images.githubusercontent.com/67348935/100285979-d82f9280-2f69-11eb-9ee7-1491b5131faa.png">

**Comment by ftpmorph** [comment]
Closing since this is now added but I'll put in a PR when an ARM build is released :)

**Comment by coldnrainy** [comment]
There is now a build working natively!

https://github.com/dennisameling/Signal-Desktop/releases - download page

https://github.com/signalapp/Signal-Desktop/issues/4461 - original thread

Very exciting. Thank you @dennisameling

**Comment by darkBuddha** [comment]
why is it not merged?

**Comment by coldnrainy** [comment]
Merged with what? The original Signal?

**Comment by ThatGuySam** [comment]
Not sure if I want to say "Works on Apple Silicon" if the native build isn't done by the official author. 

Perhaps we could just link to the Unofficial Native Build for people that want to try it.

**Comment by lawxen** [comment]
We can dowanload the official build here https://support.signal.org/hc/en-us/articles/360007318471-Signal-Beta

**Comment by SebDanielsson** [comment]
Signal Official now runs natively on Apple Silicon since version v5.27.1.
https://github.com/signalapp/Signal-Desktop/releases/tag/v5.27.1

**Comment by coldnrainy** [comment]
https://doesitarm.com/app/signal/

Just want to confirm that Signal runs natively. It's been updated to 5.29 now, and I'm running it natively. I switched from the unofficial build successfully. The page for this app hasn't been updated yet.

**Comment by ThatGuySam** [comment]
Thanks for the patience on this! Update is now live on the site(finally)! 

https://doesitarm.com/app/signal/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
