### ISSUE TITLE
Ardour DAW

### ISSUE THREAD

**Issue by MiCkSoftware** [ThatGuySam/doesitarm#34]
Is ardour working ?

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

Once I’m able, I’ll do some research online and see what I can find out

**Comment by ThatGuySam** [comment]
Looks like there is a beta native Apple Silicon version available
https://discourse.ardour.org/t/ardour-for-apple-m1-arm-pre-release/105174/18

**Comment by ThatGuySam** [comment]
Works via Rosetta 2
https://discourse.ardour.org/t/ardour-for-apple-m1-arm-pre-release/105174/8

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/ardour/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
