### ISSUE TITLE
Rekordbox

### ISSUE THREAD

**Issue by janyksteenbeek** [ThatGuySam/doesitarm#340]
**The official name of the app**
Rekordbox

**Is there a supported build available on a public/release channel?**
No

**Proposed App Status**
:no_entry_sign: No, not yet supported only works on Intel-based Macs
_No official support yet. Discussions on Reddit say that the app works partially_

**Proposed App Category**
Music Tools

**Related Issue Tracker Link or discussion**

- https://www.pioneerdj.com/en/news/2020/compatibility-for-new-macs-with-m1-chip/
- https://www.reddit.com/r/mac/comments/jw4ocl/has_anyone_tried_rekordbox_6_any_pioneer_dj/

**An Official App Download Page**

- https://rekordbox.com/nl/download/

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

It looks like we need confirmation on support under Rosetta 2. 

Feel to drop a screenshot or another tracker link to confirm. 


For a screenshot: be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an Activity Monitor example on #176

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/rekordbox/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
