### ISSUE TITLE
Clion

### ISSUE THREAD

**Issue by BookmanHan** [ThatGuySam/doesitarm#341]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**The official name of the app**
JetBrains Clion

**Is there a supported build available on a public/release channel?**
Yes

**Proposed App Status**
Nothing

**Proposed App Category**
Developer Tool

**Related Issue Tracker Link or discussion**
No

**An Official App Download Page**
https://www.jetbrains.com/clion/

**Additional context**

**Full Screenshot with the App and Activity Monitor(if self reporting)**

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/clion/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
