### ISSUE TITLE
Processing

### ISSUE THREAD

**Issue by xmc1214** [ThatGuySam/doesitarm#342]
**The official name of the app**
Processing

**Is there a supported build available on a public/release channel?**
Yes

**An Official App Download Page**
https://processing.org/

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by moffpage** [comment]
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/33549573/123584138-a7b31e00-d802-11eb-9f56-a0f38c6b0d9c.png">
<img width="333" alt="image" src="https://user-images.githubusercontent.com/33549573/123585952-d67ec380-d805-11eb-8425-6fda0238b5f0.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/123585945-d41c6980-d805-11eb-8977-bc0644042796.png">
Both 4.0 alpha 5 and 3.5.4 builds run through Rosetta 2 and ship as Intel packages.

**Comment by ThatGuySam** [comment]
Thanks, @moffpage! 

We'll use the following status: 
✳️ Yes, works via Rosetta 2 translation

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/processing-ide/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
