### ISSUE TITLE
archicad 24 can work well with rosseta2

### ISSUE THREAD

**Issue by LiuLianJie** [ThatGuySam/doesitarm#343]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**The official name of the app**
archicad

**Is there a supported build available on a public/release channel?**
yes

**Proposed App Status**
✳️ Yes, works via Rosetta 2

**Proposed App Category**
3D and Architecture

**Related Issue Tracker Link or discussion**
I can run it well on my MacBook air m1

**An Official App Download Page**
https://graphisoft.com

**Additional context**

**Full Screenshot with the App and Activity Monitor(if self reporting)**

**Comment by ThatGuySam** [comment]
Thanks for the update! 

If you can drop a screenshot so we can use it as a source link. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an Activity Monitor example on #176

**Comment by moffpage** [comment]
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/33549573/123621295-df36c000-d82c-11eb-93c4-d7359b91a39e.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/123621302-e067ed00-d82c-11eb-9b75-8d20f63293ef.png">
Works via Rosetta 2

**Comment by ThatGuySam** [comment]
@moffpage Fantastic!! 

We'll use the following status:
✳️ Yes, works via Rosetta 2 translation

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/archicad/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
