### ISSUE TITLE
MKVToolNix

### ISSUE THREAD

**Issue by ftpmorph** [ThatGuySam/doesitarm#344]
**The official name of the app**
MKVToolNix 51.0.0

**Is there a supported build available on a public/release channel?**
No

**Proposed App Status**
Working via Rosetta 2

**Proposed App Category**
Video tools

**Related Issue Tracker Link or discussion**
https://mkvtoolnix.download/
https://mkvtoolnix.download/community.html

**An Official App Download Page**
https://mkvtoolnix.download/downloads.html#macosx

**Additional context**
As noted on the official download page: "I don't own a Mac. While I do provide binaries I do not offer support for macOS. I don't use that platform, have no programming experience with it whatsoever, and I have neither the time nor the motivation to hunt down issues on it."

It therefore seems unlikely that supporting Apple Silicon is anywhere on the dev's priorities.

However, I have tested it under Rosetta 2 and it's running smoothly without issues, just as solid as under Linux which is the primary supported platform for the software.

**Full Screenshot with the App and Activity Monitor(if self reporting)**
<img width="246" alt="Screenshot 2020-11-27 at 6 12 06 am" src="https://user-images.githubusercontent.com/67348935/100418252-5aa77780-307a-11eb-8216-9e11f3e106be.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/mkvtoolnix/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
