### ISSUE TITLE
RetroArch

### ISSUE THREAD

**Issue by tonyunreal** [ThatGuySam/doesitarm#348]
**The official name of the app**
RetroArch

**Is there a supported build available on a public/release channel?**
No

**Proposed App Status**
Yes, works via Rosetta 2 with native support in development

**Proposed App Category**
Entertainment and Media Apps

**Related Issue Tracker Link or discussion**
See this pull request: https://github.com/libretro/RetroArch/pull/11627

**An Official App Download Page**
https://www.retroarch.com/?page=platforms

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Screen Shot 2020-12-02 at 1 44 22 PM](https://user-images.githubusercontent.com/3460639/100833300-a73ce980-34a4-11eb-9d5a-ba79fd44b227.png)
![Screen Shot 2020-12-02 at 1 44 28 PM](https://user-images.githubusercontent.com/3460639/100833317-ad32ca80-34a4-11eb-8f16-ff76c8ea8dc6.png)

**Comment by ThatGuySam** [comment]
Let's get that screenshot! 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an Activity Monitor example on #176

**Comment by tonyunreal** [comment]
Added screenshots to OP.

**Comment by tonyunreal** [comment]
This one is added in 03cda06f4985ae1dc9a89943af6ed000fa619b3b

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/retroarch/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by tonyunreal** [comment]
The latest unreleased version of RetroArch supports Apple Silicon natively. There is more information in [their latest blog post on their 2021 roadmap](https://www.libretro.com/index.php/retroarch-2021-hardware-roadmap-q1q2/). 

To test this version early, one can clone or pull the latest code from [the official repo](https://github.com/libretro/RetroArch) and use pkg/apple/RetroArch_Metal.xcodeproj to compile a build. This will run as an arm64 binary, and the built-in core updater should pull cores from http://buildbot.libretro.com/nightly/apple/osx/arm64/ .

Out of the cores I tested, FB Neo (Arcade), Gambatte (Gameboy), Beetle PCE (Turbografx / PC Engine), Mesen (NES / Famicom), mGBA (Gameboy Advance), Opera (3DO), Snes9x (SNES / Super Famicom) ran perfectly. Emulator cores for modern consoles probably need more work before they are available though, as JIT recompilers need to adapt to Apple's new memory protection mechanism introduced in Apple Silicon / macOS 11 and macOS 11.2.

**Comment by ThatGuySam** [comment]
@tonyunreal Sounds like it's primed to be a killer emulation option for Apple Silicon

**Comment by moffpage** [comment]
You can update the website:
https://www.libretro.com/index.php/category/apple-silicon/ - Blog Post
https://www.libretro.com/index.php/retroarch-for-apple-mac-m1-softlaunches-today/ - Blog Post
https://retroarch.com/?page=platforms - Official Website for direct download
https://www.reddit.com/r/macgaming/comments/ldgpew/native_retroarch_comes_for_apple_silicon_very_soon/ - Reddit forum

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/retroarch/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
