### ISSUE TITLE
please check  the Gopro Fusionstudio app

### ISSUE THREAD

**Issue by ilgikim** [ThatGuySam/doesitarm#349]
**The official name of the app**
Fusion studio app

**Is there a supported build available on a public/release channel?**
 YES

**Proposed App Status**
This is a program that combines the footage taken with the front and rear cameras of GoPro Fusion into one video. Works normally in Windows and Mac environments.
However, I only own Windows, so I couldn't do the task in the Mac environment.

**Proposed App Category**
360 degree video Editing

**Related Issue Tracker Link or discussion**
Few days ago, actually I got a computer (3900X, 32G ram, express ver 4.0 samsung 980 nvme ssd) but 360 video switching time is almost same my last computer(E2-1220v2, 16G ram, sata3 ssd) and my new computer has a lot of sound of fan for cooling. So I'm thinking to but m1 mac book air. BEFORE buying I want to know that app is available on M1 macbook air.

**An Official App Download Page**
https://gopro.com/ko/kr/shop/softwareandapp/gopro-fusion-studio-%EC%95%B1/fusion-studio.html

sample file download page
https://drive.google.com/file/d/1Ktgi3sdk-egsWtBJ_H9P2fiHreGc4JmF/view?usp=sharing

**Additional context**
I wonder if the fusion studio app runs normally on the M1 MacBook. Furthermore, I will also send you sample files and guides. Compared to my computer, I am curious about the time it takes for stitching.

**Full Screenshot with the App and Activity Monitor(if self reporting)**
The gopro fusion app runs on Windows and Mac x64 environments.
![2121](https://user-images.githubusercontent.com/75131259/100494416-ca098e00-3184-11eb-9091-d9305011b849.jpg)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks we need a screenshot. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an Activity Monitor example on #176

**Comment by ilgikim** [comment]
![12344](https://user-images.githubusercontent.com/75131259/100496658-1068e800-3199-11eb-83f7-48ce82ace876.jpg)
Here you are

is this right?

**Comment by ThatGuySam** [comment]
@ilgikim That looks like Windows.

**Comment by ThatGuySam** [comment]
You can use this app to check Applications running on an Apple Silicon computer https://github.com/billycastelli/Silicon-Info/releases/tag/1.0.3

**Comment by ilgikim** [comment]
thank you sir~!

**Comment by ThatGuySam** [comment]
@ilgikim You're very welcome

**Comment by moffpage** [comment]
Fusion Studio 1.3 have been installed through Install Manager but I couldn't get it working (Application haven't opened a window, didn't respond at all), however VR Player works, may create a separate issue for it:
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/33549573/123580920-9830d680-d7fc-11eb-9c2a-b57e8d52fdd5.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/123580922-98c96d00-d7fc-11eb-9ce1-c45b7827145d.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/123580919-9830d680-d7fc-11eb-8231-60e237fb2699.png">

Of course it works via Rosetta 2, see screenshots above and this:
<img width="1192" alt="image" src="https://user-images.githubusercontent.com/33549573/123580944-a7b01f80-d7fc-11eb-8ba5-f4d82b193664.png">
<img width="1224" alt="image" src="https://user-images.githubusercontent.com/33549573/123580965-b4347800-d7fc-11eb-9a1c-e94dda66a565.png">
https://community.gopro.com/t5/GoPro-Apps-for-Mobile/GoPro-iOS-app-on-M1-Mac-Apple-Silicon/td-p/868516

**Comment by ThatGuySam** [comment]
@moffpage We can go ahead and list both apps from here. 

Apps are now live on the site! 

https://doesitarm.com/app/gopro-fusion-studio/
https://doesitarm.com/app/gopro-vr-player/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by moffpage** [comment]
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/33549573/124209093-b7847800-db0a-11eb-95d9-7cc1406f5a47.png">
Do you have info to prove they aren't interested in providing support for Apple Silicon?

**Comment by ThatGuySam** [comment]
It's because they are discontinuing the app entirely

https://gopro.com/en/us/news/fusion-end-of-life

**Comment by moffpage** [comment]
Oh, didn't know that. Thanks for provided info!
