### ISSUE TITLE
Postbox

### ISSUE THREAD

**Issue by francoisBouchet** [ThatGuySam/doesitarm#35]
url: https://www.postbox-inc.com/

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by bharadwaj6** [comment]
Works via Rosetta 2

<img width="1224" alt="Screenshot 2021-01-02 at 16 06 48" src="https://user-images.githubusercontent.com/1695154/103455599-891d1000-4d14-11eb-9065-49d4795f3a8f.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/postbox/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
