### ISSUE TITLE
Hearts of Iron IV 

### ISSUE THREAD

**Issue by shatyuka** [ThatGuySam/doesitarm#350]
**The official name of the app**
Hearts of Iron IV

**Is there a supported build available on a public/release channel?**
Yes

**Proposed New App Status**
✳️ Yes, works via Rosetta 2

**Related Issue Tracker Link or discussion**
https://applesilicongames.com

**An Official App Download Link**
https://store.steampowered.com/app/394360/Hearts_of_Iron_IV/

**Additional context**
I have test this game in person, and it works well on my MacBook Pro 13'' M1 16GB.
I also submitted a detailed report to **Apple Silicon Games**.

**Comment by ThatGuySam** [comment]
Fantastic! Thanks for the update! 

We automatically pull from Thomas' list so it should update on our site a little bit after his
