### ISSUE TITLE
 Heroes of the Storm

### ISSUE THREAD

**Issue by ZinkLu** [ThatGuySam/doesitarm#352]
**The official name of the app** 
Heroes of the Storm

**Is there a supported build available on a public/release channel?**
No

**Proposed App Status** 
Yes, works via Rosetta 2

**Proposed App Category** 
games

**Related Issue Tracker Link or discussion**

**An Official App Download Page** 
https://heroesofthestorm.com/

**Additional context**

**Full Screenshot with the App and Activity Monitor(if self reporting) or Silicon Info**

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

You can submit Games to [Apple Silicon Games](https://applesilicongames.com/) which we pull from automatically.
