### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by simon04** [ThatGuySam/doesitarm#353]
Please specify a license for this repository, possibly a different one for the web app and the content...

**Comment by ThatGuySam** [comment]
What kind of license setup have you seen similar apps use?

**Comment by simon04** [comment]
You might find the following https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository

Wikidata [data is licensed CC0](https://www.wikidata.org/wiki/Wikidata:Copyright), awesome.re [is licensed CC0](https://github.com/sindresorhus/awesome/blob/main/license). I'd say, a permissive license such as CC0, ISC, or MIT would be well suited...

**Comment by ThatGuySam** [comment]
I was leaning towards GPL-2.0 since it requires that the Source is disclosed which helps grow the repo and site in the future. 
https://tldrlegal.com/license/gnu-general-public-license-v2

Is there a more public style license that still requires attribution?

**Comment by simon04** [comment]
OpenStreetMap uses the ODbL, https://opendatacommons.org/licenses/odbl/

**Comment by ThatGuySam** [comment]
I think your right that there should be 2 licenses: 

A data/db style license for the list

A software license for the web application

**Comment by ThatGuySam** [comment]
License added! 

This list is now under Creative Commons Attribution 4.0 International License

The code is under Apache License, Version 2.0
