### ISSUE TITLE
VeraCrypt

### ISSUE THREAD

**Issue by KovalevArtem** [ThatGuySam/doesitarm#355]
**The official name of the app**
VeraCrypt

**Proposed App Status**
?

**Proposed App Category**
?

**Related Issue Tracker Link or discussion**
https://github.com/veracrypt/VeraCrypt/issues/702

**An Official App Download Page**
https://www.veracrypt.fr/en/Downloads.html

**Additional context**
![image](https://user-images.githubusercontent.com/36500228/100539640-e838c200-3248-11eb-88a1-e74983da9826.png)
https://github.com/veracrypt/VeraCrypt/releases/tag/VeraCrypt_1.24-Update8_MacOSX

**Comment by ThatGuySam** [comment]
Status: ✅ Yes, Full Native Apple Silicon Support

Category: Productivity Tools (for now)

**Comment by ThatGuySam** [comment]
Good find!

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ftpmorph** [comment]
Looks like it's actually not native Apple Silicon yet, just has issues with macOS Big Sur fixed so it runs via Rosetta 2 so far: https://github.com/veracrypt/VeraCrypt/issues/702#issuecomment-734507631

**Comment by ThatGuySam** [comment]
@ftpmorph Good catch!

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/veracrypt/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
