### ISSUE TITLE
TG Pro

### ISSUE THREAD

**Issue by KovalevArtem** [ThatGuySam/doesitarm#356]
**The official name of the app**
TG Pro

**Is there a supported build available on a public/release channel?**
Yes

**Proposed App Status**
Full support

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
?

**An Official App Download Page**
https://www.tunabellysoftware.com/tgpro/

**Additional context**
![image](https://user-images.githubusercontent.com/36500228/100539815-0ce16980-324a-11eb-9145-7f4922d8443a.png)
https://twitter.com/tunabelly/status/1332030922586284037

![image](https://user-images.githubusercontent.com/36500228/100539819-1b2f8580-324a-11eb-9664-cdb877d8870e.png)
https://twitter.com/tgproapp/status/1332031617385304065

![image](https://user-images.githubusercontent.com/36500228/100539823-22569380-324a-11eb-83c4-ab5583b33719.png)
https://www.tunabellysoftware.com/tgpro/releasenotes/

**Comment by ThatGuySam** [comment]
That's clean! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/tg-pro/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
