### ISSUE TITLE
Vuo

### ISSUE THREAD

**Issue by smokris** [ThatGuySam/doesitarm#358]
**The official name of the app**
[Vuo](https://vuo.org/)

**Is there a supported build available on a public/release channel?**
Yes

**Proposed App Status**
✳️ Runs via Rosetta with native support currently in development

**Proposed App Category**
Video and Motion Tools

**Related Issue Tracker Link or discussion**
https://vuo.org/comment/7265#comment-7265  
https://vuo.org/comment/7781#comment-7781

**An Official App Download Page**
https://vuo.org/download

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Screen Shot 2020-11-29 at 11 51 25 AM](https://user-images.githubusercontent.com/190164/100548246-58d7e280-3239-11eb-8ef8-c0a269ee52dc.png)

**Comment by ThatGuySam** [comment]
This looks great! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by smokris** [comment]
Great, thanks.  I just submitted PR #394.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/vuo/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
