### ISSUE TITLE
Blackmagic Disk Speed Test

### ISSUE THREAD

**Issue by KovalevArtem** [ThatGuySam/doesitarm#359]
**The official name of the app**
Blackmagic Disk Speed Test

**Is there a supported build available on a public/release channel?**
Yes

**Proposed App Status**
Yes

**Proposed App Category**
?

**An Official App Download Page**
https://apps.apple.com/app/id425264550

**Additional context**
![image](https://user-images.githubusercontent.com/36500228/100552135-3de78b80-3296-11eb-9a84-3669f86d050e.png)

**Comment by ThatGuySam** [comment]
Looks like we need to figure out if it's running via Rosetta or Natively. 

We'll need a link or a screenshot. 

For the screenshot, be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an Activity Monitor example on #176

**Comment by thunderstorm99** [comment]
@ThatGuySam Screenshot added.
![Screen Shot 2020-12-01 at 07 32 13](https://user-images.githubusercontent.com/3219279/100705553-a70af400-33a7-11eb-88ca-f30618b71520.png)

**Comment by ThatGuySam** [comment]
@thunderstorm99 Thank you, good sir. 

Status: ✅ Yes, Full Native Apple Silicon Support

This is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/blackmagic-disk-speed-test/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
