### ISSUE TITLE
RStudio

### ISSUE THREAD

**Issue by aperigord** [ThatGuySam/doesitarm#36]
**The official name of the app**
RStudio

**Proposed App Status**
What's the current app status based off of current discussion or testing
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend 

**Related Issue Tracker Link or discussion**
This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes. 

**An Official App Download Link**
This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site. 

**Additional context**
Add any other context or screenshots about the app request here.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by aperigord** [comment]
---
name: RStudio Request
about: RStudio (a powerful GUI for R, pretty used in datascience alongside Python librairies)
title: RStudio
labels: RStudio App Request
assignees: 
---

**RStudio**
RStudio is an open-source GUI/IDE for R (also Markdown, Python and other things).
It is a standard application in the DataScience world (alongside Python and its dedicated librairies of course)
The more important focus now should be on the GUI/IDE RStudio (the RStudio company handles also RStudio Servers, Shiny Servers and various custom packages for R)

Reference website : https://rstudio.com

**Proposed App Status**
Not sure at all

**Related Issue Tracker Link or discussion**
I found this test to run RStudio on a RaspberryPi (then using the ARM compilation).
However it seems slow and difficult to handle with newer version of the software
https://github.com/dashaub/ARM-RStudio

**An Official App Download Link**
https://rstudio.com/products/rstudio/download/

**Additional context**
![image](https://user-images.githubusercontent.com/17827065/98950281-1738ff00-24f9-11eb-9538-396575174b6a.png)

**Comment by istvan60** [comment]
Apparently R developers are working on the issue:

https://developer.r-project.org/Blog/public/2020/11/02/will-r-work-on-apple-silicon/

But I suppose, since that blog post a FORTRAN compiler came out 
https://www.nag.com/news/first-fortran-compiler-apple-silicon-macs

Still there is no solution yet, but there are lots of posts on the topic
https://news.ycombinator.com/item?id=25057985
https://www.researchgate.net/post/Data_science_R_and_SPSS_26_under_Rosetta_2_Apple_silicon_M1
https://developer.apple.com/forums/thread/649933

**Comment by ThatGuySam** [comment]
Here's the status we'll use: 

✳️ Runs via Rosetta with native support currently in development

**Comment by ThatGuySam** [comment]
This is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by istvan60** [comment]
> Here's the status we'll use:
> 
> ✳️ Runs via Rosetta with native support currently in development

Does it? Based on the comments and the info I've found in the links above it seem that it does not work yet. And even if RStudio works, R might not....

**Comment by ThatGuySam** [comment]
Perhaps I am mistaken. 

The [R Project](https://developer.r-project.org/Blog/public/2020/11/02/will-r-work-on-apple-silicon/) article states: 

> The new platform will include Rosetta 2, a dynamic translation framework which runs binaries built for 64-bit Intel Macs using just-in-time, dynamic translation of binary code. The good news is that R seems to be working fine with the dynamic translation

I assumed that meant it works via Rosetta. 

Are there user reports of issues on Rosetta?

I can't seem to find anything like that in the articles above, however, I may have missed something.

**Comment by istvan60** [comment]
Since [QWebEngine does not run in Rosetta2](https://bugreports.qt.io/browse/QTBUG-86405) the [expectation is that current x64 builds of RStudio will NOT run on the new ARM Macs via Rosetta2](https://github.com/rstudio/rstudio/issues/8362).

So a print screen and/or YouTube video is needed for confirmation :D

**Comment by ThatGuySam** [comment]
Good call. 

Since DTK devs aren't allowed to record anything on their screen we'll have to wait for someone with an M1

**Comment by istvan60** [comment]
New info:
https://forums.macrumors.com/threads/big-sur-working-not-working-apps.2242312/page-3?post=28598008#post-28598008 

User jjnote says RStudio works under Rosetta2, but there is no solid proof.....

**Comment by Aloereed** [comment]
<img width="1920" alt="截屏2020-11-20 上午11 59 18" src="https://user-images.githubusercontent.com/58137529/99756344-e293fb80-2b27-11eb-9b80-f6187f4e845c.png">
Rstudio runs well under rosetta2 with both R 3.6 and 4.0

**Comment by ThatGuySam** [comment]
@Aloereed Fantastic!

Status: ✳️ Yes, runs via Rosetta 2 with native support in development

We can use this issue page as one of the Tracker links

**Comment by ThatGuySam** [comment]
This is ready to add. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

If there is another update to RStudio we can add it here or start a new issue

**Comment by istvan60** [comment]
> <img alt="截屏2020-11-20 上午11 59 18" width="1920" src="https://user-images.githubusercontent.com/58137529/99756344-e293fb80-2b27-11eb-9b80-f6187f4e845c.png">
> 
> Rstudio runs well under rosetta2 with both R 3.6 and 4.0

This is great!

And did you notice any drastic change in perforemnace, or issues with packages that require external software e.g. java (xlsx etc.)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/rstudio/

Feel free to browse through the other issues to help with missing info on other apps.

**Comment by Aloereed** [comment]
> > <img alt="截屏2020-11-20 上午11 59 18" width="1920" src="https://user-images.githubusercontent.com/58137529/99756344-e293fb80-2b27-11eb-9b80-f6187f4e845c.png">
> > Rstudio runs well under rosetta2 with both R 3.6 and 4.0
> 
> This is great!
> 
> And did you notice any drastic change in perforemnace, or issues with packages that require external software e.g. java (xlsx etc.)?

xlsx package works well.

**Comment by istvan60** [comment]
...should belong to the Science and Research Software section.

**Comment by ThatGuySam** [comment]
@istvan60 Updated!

**Comment by istvan60** [comment]
Hi Guys,

Here are some [benchmark results](https://forums.macrumors.com/threads/data-science-r-and-spss-26-etc-under-rosetta-2-apple-silicon-m1.2269302/?post=29326680#post-29326680) leman and I just did.

**Comment by OceansDeep0219** [comment]
When will release the new version that will support the Native Apple Silicon (M1) ?
