### ISSUE TITLE
Sound Control

### ISSUE THREAD

**Issue by KovalevArtem** [ThatGuySam/doesitarm#361]
**The official name of the app**
Sound Control

**Is there a supported build available on a public/release channel?**
Yes

**Proposed App Status**
Apple Silicon Support

**Proposed App Category**
Music and Audio Tools

**An Official App Download Page**
https://staticz.com/soundcontrol/

**Additional context**
![image](https://user-images.githubusercontent.com/36500228/100556940-dd1c7b00-32b6-11eb-855a-d630ef72df85.png)

**Comment by ThatGuySam** [comment]
Looks like we need to figure out if the current version works on Rosetta 2. 

We'll need a link or a screenshot.

For the screenshot, be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version.

You can find an Activity Monitor example on #176

**Comment by moffpage** [comment]
Version 2.6.0 already had native support for Apple Silicon Macs. Current version at the moment of writing this was 2.6.3. 
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/33549573/123579379-99143900-d7f9-11eb-8f07-f2e7fd9f3e72.png">
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/33549573/123579379-99143900-d7f9-11eb-8f07-f2e7fd9f3e72.png">
<img width="741" alt="image" src="https://user-images.githubusercontent.com/33549573/123579392-a03b4700-d7f9-11eb-967d-cdcfec92f5eb.png">

**Comment by ThatGuySam** [comment]
Thanks, @moffpage!

App is now live on the site! 

https://doesitarm.com/app/sound-control/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
