### ISSUE TITLE
Day One Journal

### ISSUE THREAD

**Issue by KovalevArtem** [ThatGuySam/doesitarm#364]
**The official name of the app**
Day One Journal

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✳️ Yes, works via Rosetta 2

**An Official App Download Page**
https://apps.apple.com/app/id1055511498

**Additional context**
![image](https://user-images.githubusercontent.com/36500228/100660906-bbc59880-3363-11eb-9b6b-0557f6ec55b4.png)
https://twitter.com/dayoneapp/status/1332727758447734784?s=20

**Comment by ThatGuySam** [comment]
Looks good! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/day-one-journal/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
