### ISSUE TITLE
PDFelement

### ISSUE THREAD

**Issue by Jessie1225** [ThatGuySam/doesitarm#366]
**The official name of the app**
PDFelement

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Yes, fully supported ARM and Intel Chip

**Proposed App Category**
Productivity

**Related Issue Tracker Link or discussion**
Official post: https://pdf.wondershare.com/macos/pdfelement-ready-for-apple-m1-chip.html

**An Official App Download Page**
https://pdf.wondershare.com/pdf-editor-mac/

**Additional context**
PDFelement for iOS can also work on the Macs that support using M1 Chip.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! This is ready to go! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by Jessie1225** [comment]
Hi, could you please help us add it because I am not good at the code. Thanks!

**Comment by ThatGuySam** [comment]
@Jessie1225 Ofcourse! 

App is now live on the site! 

https://doesitarm.com/app/pdfelement/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by Jessie1225** [comment]
@ThatGuySam  Thank you so much and happy Christmas!
