### ISSUE TITLE
Pixelmator Classic

### ISSUE THREAD

**Issue by tonyunreal** [ThatGuySam/doesitarm#367]
**The official name of the app**
Pixelmator Classic

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
Yes, works via Rosetta 2, no native upgrade planned

**Proposed App Category**
Photo and Graphic Tools

**An Official App Download Page**
https://apps.apple.com/cn/app/pixelmator-classic/id407963104?l=en&mt=12

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Screen Shot 2020-12-02 at 11 43 57 AM](https://user-images.githubusercontent.com/3460639/100827187-20354480-3497-11eb-8abd-dc6dc0a9c9b8.png)
![Screen Shot 2020-12-02 at 11 48 42 AM](https://user-images.githubusercontent.com/3460639/100827195-24f9f880-3497-11eb-9897-7ec01a698fac.png)

**Comment by ThatGuySam** [comment]
Good find!

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/pixelmator-classic/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
