### ISSUE TITLE
QQ音乐 (QQMusic)

### ISSUE THREAD

**Issue by tonyunreal** [ThatGuySam/doesitarm#368]
**The official name of the app**
QQ音乐

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
Yes, works via Rosetta 2

**Proposed App Category**
Entertainment and Media Apps

**An Official App Download Page**
https://apps.apple.com/cn/app/qq%E9%9F%B3%E4%B9%90-%E8%AE%A9%E7%94%9F%E6%B4%BB%E5%85%85%E6%BB%A1%E9%9F%B3%E4%B9%90/id595615424?l=en&mt=12

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Screen Shot 2020-12-02 at 12 10 24 PM](https://user-images.githubusercontent.com/3460639/100827501-d6992980-3497-11eb-87ba-9fd2e3cd432d.png)
![Screen Shot 2020-12-02 at 11 58 03 AM](https://user-images.githubusercontent.com/3460639/100827505-dac54700-3497-11eb-9cd0-e9714f16128f.png)

**Comment by ThatGuySam** [comment]
Looks good to go! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by tonyunreal** [comment]
This one is added in 3944381f529a01e49b337401e8865670dbd952a3

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/qqqq-music/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
