### ISSUE TITLE
WeChat

### ISSUE THREAD

**Issue by tonyunreal** [ThatGuySam/doesitarm#369]
**The official name of the app**
WeChat

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
Yes, works via Rosetta 2

**Proposed App Category**
Social and communication

**An Official App Download Page**
https://apps.apple.com/cn/app/wechat/id836500024?l=en&mt=12

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Screen Shot 2020-12-02 at 12 57 54 PM](https://user-images.githubusercontent.com/3460639/100830350-680b9a00-349e-11eb-99a4-2dfc2de0146b.png)
![Screen Shot 2020-12-02 at 12 58 42 PM](https://user-images.githubusercontent.com/3460639/100830351-6c37b780-349e-11eb-9b5f-260228cb53fe.png)

**Comment by ThatGuySam** [comment]
You’re on fire! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by tonyunreal** [comment]
This one is added in 3944381f529a01e49b337401e8865670dbd952a3

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/wechat/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/wechat/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by marcscode90** [comment]
The mac store version (3.2.0) is now universal

**Comment by ThatGuySam** [comment]
@marcscode90 We've got it in the queue to add https://github.com/ThatGuySam/doesitarm/issues/759

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.
