### ISSUE TITLE
COMSOL Multiphysics

### ISSUE THREAD

**Issue by fendou1997** [ThatGuySam/doesitarm#370]
does the software comsol can be used in m1

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ThatGuySam** [comment]
No mention of Apple Silicon on their requirements page yet
https://www.comsol.com/system-requirements

**Comment by ThatGuySam** [comment]
Report from Reddit of working on M1
https://www.reddit.com/r/mac/comments/kfp8tg/comsol_with_m1/glvd947?utm_source=share&utm_medium=web2x&context=3

Report from COMSOL Forums of working on M1
https://www.comsol.com/forum/thread/272202/new-apple-m1-machines-and-rosetta-2-intel-emulator?last=2021-02-04T17:09:35Z

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/comsol-multiphysics/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by dnoan** [comment]
Version 6.0 has native M1 support. See https://www.comsol.com/release/6.0 But capabilities require Rosetta 2 according to https://www.comsol.com/forum/thread/272202/new-apple-m1-machines-and-rosetta-2-intel-emulator?last=2021-02-04T17:09:35Z
