### ISSUE TITLE
LibreOffice

### ISSUE THREAD

**Issue by yxt0531** [ThatGuySam/doesitarm#371]
**The official name of the app**
LibreOffice

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Yes, works via Rosetta 2

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
https://www.collaboraoffice.com/desktop/update-on-libreoffice-support-for-arm-based-macs/

**An Official App Download Page**
https://www.libreoffice.org/download/download/

**Additional context**
LibreOffice Base also works with ARM Zulu Builds of OpenJDK installed. (Tested with version 8u275b01)

**Full Screenshot with the App and Activity Monitor(if self reporting) or Silicon Info**
![Screen Shot 2020-12-02 at 2 51 14 pm](https://user-images.githubusercontent.com/32425498/100839222-d35d6800-34ae-11eb-96f3-60ecf6c0e575.png)
![Screen Shot 2020-12-02 at 2 51 54 pm](https://user-images.githubusercontent.com/32425498/100839240-d8221c00-34ae-11eb-98e9-f729526c6ddc.png)
![Screen Shot 2020-12-02 at 2 52 15 pm](https://user-images.githubusercontent.com/32425498/100839243-da847600-34ae-11eb-8e58-c7a878c43d46.png)

**Comment by ThatGuySam** [comment]
This looks fantastic! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/libreoffice/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
