### ISSUE TITLE
Tablecruncher

### ISSUE THREAD

**Issue by stefanfis** [ThatGuySam/doesitarm#372]
**The official name of the app**
[Tablecruncher](https://tablecruncher.com)

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
https://tablecruncher.com/blog/

**An Official App Download Page**
https://tablecruncher.com/download/

**Additional context**
Apple Silicon support has been introduced with version 1.5.1 released Nov 23, 2020.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![image](https://user-images.githubusercontent.com/49155318/100865447-a05baa00-3497-11eb-8746-b27922de5e00.png)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/tablecruncher/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
