### ISSUE TITLE
Razer Synapse 2.0

### ISSUE THREAD

**Issue by HenkPoley** [ThatGuySam/doesitarm#373]
**The official name of the app**
Razer Synapse 2.0

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
No, not yet supported only works on Intel-based Macs

**Proposed App Category**
Entertainment and Media Apps

**Related Issue Tracker Link or discussion**
None

**An Official App Download Page**
https://www.razer.com/synapse-2

**Additional context**
Driver can't run on Apple Silicon (or even Big Sur?)

The app 'works', but does not find any Razer hardware devices (computer mice, headphones, etc.). Synapse is normally used to adapt the RGB lights, and potentially other device settings.

A third-party 'user-mode USB' replacement software that sort of works, it changes the DPI but not the light on my mouse: https://github.com/1kc/razer-macos

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
..

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Let's get a screenshot of the empty list of Razer hardware in the Application's UI

It's not _technically_ confirmation but it's the best we can do for now and someone can rebut the status if they can provide a screenshot of the base application working without any workarounds

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by ThatGuySam** [comment]
Let's also link to #376 as an alternative app once this and it are live on the site

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/razer-synapse/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
