### ISSUE TITLE
Razer macOS

### ISSUE THREAD

**Issue by HenkPoley** [ThatGuySam/doesitarm#376]
**The official name of the app**
Razer macOS

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Yes, works via Rosetta 2

**Proposed App Category**
Entertainment and Media Apps

**Related Issue Tracker Link or discussion**
None / https://github.com/1kc/razer-macos/issues

**An Official App Download Page**
https://github.com/1kc/razer-macos/releases

**Additional context**
This app can change the color of Razer hardware RGB lighting, and DPI settings of Razer mice.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
..

**Comment by ThatGuySam** [comment]
Thanks for the App Request!  

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
Let's also link #373 to this as an alternative app once this and it are live on the site

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/razer-macos/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
