### ISSUE TITLE
Update Notion with full Apple silicon support

### ISSUE THREAD

**Issue by jonsamp** [ThatGuySam/doesitarm#378]
**The official name of the app**
Notion

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**Related Issue Tracker Link or discussion**
https://twitter.com/NotionHQ/status/1333867094463582208?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Etweet

**An Official App Download Page**
https://www.notion.so/desktop

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1735" alt="Screen Shot 2020-12-02 at 1 55 20 PM" src="https://user-images.githubusercontent.com/6455018/100918088-08b18800-34a6-11eb-87ae-e2e9b0109727.png">

**Comment by ThatGuySam** [comment]
Update is Live!

https://doesitarm.com/app/notion-desktop/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
