### ISSUE TITLE
PrusaSlicer

### ISSUE THREAD

**Issue by thunderstorm99** [ThatGuySam/doesitarm#379]
**The official name of the app**
PrusaSlicer

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
✳️ Yes, works via Rosetta 2

**Proposed App Category**
3D and Architecture

**Related Issue Tracker Link or discussion**
None

**An Official App Download Page**
https://github.com/prusa3d/PrusaSlicer/releases

**Additional context**
Tested on 2.3.0 beta 1

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Screen Shot 2020-12-02 at 21 06 46](https://user-images.githubusercontent.com/3219279/100925692-9f9c3580-34e2-11eb-8297-8558d4b157e1.png)

**Comment by ThatGuySam** [comment]
This looks awesome! 

Let's also add a link to the Native Beta download: https://github.com/prusa3d/PrusaSlicer/releases

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by thunderstorm99** [comment]
Just a quick hint. The DMG file from https://github.com/prusa3d/PrusaSlicer/releases is still intel only. The code can be compiled natively (according to the comments) using another package (wxWidgets 3.1.4) than what was used in all builds seen on github (wxWidgets 3.1.3).

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/prusaslicer/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by xarbit** [comment]
@ThatGuySam  PrusaSlicer 2.3.1 is now officially supported on Apple Silicon and universal binaries are released

**Comment by ThatGuySam** [comment]
@xarbit Thanks for the report! The update is now live on the site! 

https://doesitarm.com/app/prusaslicer/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
