### ISSUE TITLE
Axure 9

### ISSUE THREAD

**Issue by TomatoFryEggs** [ThatGuySam/doesitarm#38]
The official name of the app
Axure9

Proposed App Status
None

Related Issue Tracker Link or discussion
Official Forums: https://forum.axure.com/t/is-there-any-play-for-arm-mac/69405

An Official App Download Link
https://www.axure.com/download

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by TomatoFryEggs** [comment]
The official name of the app
Axure9

Proposed App Status
-

Related Issue Tracker Link or discussion
Official Forums: https://forum.axure.com/t/is-there-any-play-for-arm-mac/69405

An Official App Download Link
https://www.axure.com/download

**Comment by TomatoFryEggs** [comment]
> Thanks for the App Request!
> 
> I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

Thank you for your response.

I have added the necessary info.

**Comment by ThatGuySam** [comment]
Great! 

Looks like we just need to figure out the current status and we'll be good to go

**Comment by ThatGuySam** [comment]
It looks like there's not much in the way of discussion on this so we'll need to test it ourselves on an Apple Silicon machine

**Comment by Eric-Chan** [comment]
> It looks like there's not much in the way of discussion on this so we'll need to test it ourselves on an Apple Silicon machine

I'm also looking forward to the test results!

**Comment by tonyunreal** [comment]
**The official name of the app**
Axure RP 9

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
Yes, works via Rosetta 2

**Proposed App Category**
Productivity Tools

**An Official App Download Page**
https://www.axure.com/download

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Screen Shot 2020-12-02 at 12 39 01 PM](https://user-images.githubusercontent.com/3460639/100829183-b79c9680-349b-11eb-8378-f27606981bc4.png)
![Screen Shot 2020-12-02 at 12 39 07 PM](https://user-images.githubusercontent.com/3460639/100829199-c08d6800-349b-11eb-9438-daca5783fee9.png)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/axure-rp-9/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
