### ISSUE TITLE
MacDown

### ISSUE THREAD

**Issue by tonyunreal** [ThatGuySam/doesitarm#382]
**The official name of the app**
MacDown

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
Yes, works via Rosetta 2

**Proposed App Category**
Developer Tools

**An Official App Download Page**
https://macdown.uranusjr.com

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Screen Shot 2020-12-03 at 10 39 35 AM](https://user-images.githubusercontent.com/3460639/100956791-3b19be80-3554-11eb-91ef-0c901bb37d17.png)
![Screen Shot 2020-12-03 at 10 39 42 AM](https://user-images.githubusercontent.com/3460639/100956798-40770900-3554-11eb-8e10-6f91ba5dbe91.png)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/macdown/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
