### ISSUE TITLE
Bigger Picture 1.3.0

### ISSUE THREAD

**Issue by adib** [ThatGuySam/doesitarm#383]
**The official name of the app**

[Bigger Picture](https://biggerpicture.app/)

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ 

**Proposed App Category**
`Photo and Graphic Tools`

**Related Issue Tracker Link or discussion**

[BiggerPicture 1.3.0 Release Notes](https://basilsalad.com/kitchen/bigger-picture-big-sur/)

{This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes.}

**An Official App Download Page**

 - [Bigger Picture Download Page](https://biggerpicture.app/download/)
 - [Mac App Store](https://itunes.apple.com/app/bigger-picture/id1406088493?mt=12&at=10lvzo&ct=BiggerPictureApp&ls=1)

**Additional context**

> BiggerPicture uses recent advancements in artificial intelligence to increase image resolutions without causing pixelations or blur.

[Press Kit](https://biggerpicture.app/press/)

<img width="469" alt="Screen Shot 2020-12-03 at 20 08 27" src="https://user-images.githubusercontent.com/176081/101016158-595adb00-35a3-11eb-8390-fcbb0ffca29f.png">

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

<img width="255" alt="Screen Shot 2020-12-03 at 20 07 10" src="https://user-images.githubusercontent.com/176081/101016028-34fefe80-35a3-11eb-8af8-56077015a7cc.png">

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Status: ✅ Yes, Full Native Apple Silicon Support

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/biggerpicture/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by adib** [comment]
Thanks!
-- 
Sasmito Adibowo
https://basilsalad.com
