### ISSUE TITLE
Pelemay

### ISSUE THREAD

**Issue by KovalevArtem** [ThatGuySam/doesitarm#384]
**The official name of the app**
Pelemay

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Developer Tools

**An Official App Download Page**
https://github.com/zeam-vm/pelemay/releases

**Additional context**
![image](https://user-images.githubusercontent.com/36500228/101078450-3f2af800-35b7-11eb-8a72-dc5f2a060e0c.png)
https://twitter.com/zacky1972/status/1334523162550124548

![image](https://user-images.githubusercontent.com/36500228/101078488-4fdb6e00-35b7-11eb-8181-31cffbfbe65b.png)
https://github.com/zeam-vm/pelemay/releases/tag/0.0.14

**Comment by ThatGuySam** [comment]
Looks great! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/pelemay/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
