### ISSUE TITLE
Jetpack Compose

### ISSUE THREAD

**Issue by KovalevArtem** [ThatGuySam/doesitarm#385]
**The official name of the app**
Jetpack Compose

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Developer Tools

**An Official App Download Page**
https://developer.android.com/jetpack/compose

**Additional context**
https://www.xda-developers.com/jetpack-compose-for-desktop-swing-interoperability-layer-apple-silicon/

**Comment by ThatGuySam** [comment]
Wonderful! This is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/jetpack-compose-for-desktop/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
