### ISSUE TITLE
Twitch

### ISSUE THREAD

**Issue by tonyunreal** [ThatGuySam/doesitarm#387]
**The official name of the app**
Twitch

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
Yes, works via Rosetta 2

**Proposed App Category**
Entertainment and Media Apps

**An Official App Download Page**
https://www.twitch.tv/downloads/

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Screen Shot 2020-12-04 at 7 47 26 AM](https://user-images.githubusercontent.com/3460639/101104168-7de79f00-3605-11eb-9d3a-886902fa160b.png)
![Screen Shot 2020-12-04 at 7 47 32 AM](https://user-images.githubusercontent.com/3460639/101104178-84761680-3605-11eb-9797-fc6cc15674ae.png)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/twitch/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by bharadwaj6** [comment]
Now runs natively as Twitch Studio Beta.

https://www.twitch.tv/broadcast/studio

<img width="934" alt="Screenshot 2022-09-25 at 19 41 39" src="https://user-images.githubusercontent.com/1695154/192148101-3e60f3a3-e8f0-4d49-bf3d-3f070c1f97e4.png">
