### ISSUE TITLE
KeeWeb 

### ISSUE THREAD

**Issue by KovalevArtem** [ThatGuySam/doesitarm#389]
**The official name of the app**
KeeWeb 

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
https://github.com/keeweb/keeweb/issues/1640

**An Official App Download Page**
https://keeweb.info

**Additional context**
![image](https://user-images.githubusercontent.com/36500228/101200506-74971a80-3677-11eb-88a7-28707cc6004a.png)
https://twitter.com/kee_web/status/1334885117584609295

**Comment by ThatGuySam** [comment]
Clean! This is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/keeweb/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
