### ISSUE TITLE
Cinebench

### ISSUE THREAD

**Issue by frictionlessDevelopments** [ThatGuySam/doesitarm#39]
**The official name of the app**
Cinebench

**Proposed App Status**
What's the current app status based off of current discussion or testing
✅

**Related Issue Tracker Link or discussion**
Version 23.200

**An Official App Download Link**
https://apps.apple.com/app/cinebench/id1438772273?l=en&mt=12

**Comment by KovalevArtem** [comment]
Version 23.200
![image](https://user-images.githubusercontent.com/36500228/99589922-b8deb580-29fd-11eb-8a16-c179370ab95b.png)

**Comment by KovalevArtem** [comment]
https://www.maxon.net/en/article/maxon-updates-its-powerful-benchmarking-software-cinebench

**Comment by frictionlessDevelopments** [comment]
Hm, as much as I'll like to add this to the list. I'm unsure what category it'll fall under. @ThatGuySam any suggestions?

**Comment by KovalevArtem** [comment]
![image](https://user-images.githubusercontent.com/36500228/99708585-1252ed00-2aaf-11eb-859b-9af890412160.png)

**Comment by ThatGuySam** [comment]
That is a bit of a weird one. 

For now, we'll put it under Video and Motion Tools since I don't think most Designers and Photographers are going to use it as much. 

We may need to create a new category later on though.

**Comment by ThatGuySam** [comment]
This one's ready to go. 

Status: ✅ Yes, full native support as of v23.200

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/cinebench/

Feel free to browse through the other issues to help with missing info on other apps.
