### ISSUE TITLE
Mongodb

### ISSUE THREAD

**Issue by couchwolve** [ThatGuySam/doesitarm#391]
Is mongodb running on new m1 chip?

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by couchwolve** [comment]
well, the MongoDB is working fine on the m1.
[MongoDb](https://www.youtube.com/watch?v=b_S3CjGRQis)
here is the link for the video......forward to 3:48

**Comment by ThatGuySam** [comment]
@couchwolve Good find! 

App is now live on the site! 

https://doesitarm.com/app/mongodb/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
