### ISSUE TITLE
A couple of syntax errors

### ISSUE THREAD

**Issue by sammer2001** [ThatGuySam/doesitarm#397]
I noticed that on pages for apps that only support Rosetta the site says that the app "works via Rosetta 2, but no Emulation yet" which is a contradiction. Rosetta 2 is the emulator, I think you mean it's not available natively.

**Comment by ThatGuySam** [comment]
Ha! Good catch! 

That is technically correct but "Emulation", in that case, is referring to emulating Android Devices on Apple SIlicon for Android Studio which is a critical function for app developers who don't own a physical Android device. 

You can see the context for the add here: https://github.com/ThatGuySam/doesitarm/issues/48#issuecomment-737661111

That emulation not _should_ only appear on that Android Studio page. 

Let me know if it's showing up on others.

**Comment by sammer2001** [comment]
My bad didn't think of that.

**Comment by ThatGuySam** [comment]
All good! 

Thanks for taking the time contribute and feel free to take a look through the other apps we're reviewing: https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+Tracker+Link%22
