### ISSUE TITLE
Synology Drive Client

### ISSUE THREAD

**Issue by aungnay** [ThatGuySam/doesitarm#399]
**The official name of the app**
{Synology Drive Client}

**Is there a supported version available on a stable release channel?**
{Yes}

**Proposed App Status**
{Yes, works via Rosetta 2}

**Proposed App Category**
{Productivity Tools}

**An Official App Download Page**
{https://www.synology.com/en-global/support/download}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1072" alt="Screen Shot 2020-12-07 at 12 07 55 AM" src="https://user-images.githubusercontent.com/23125573/101312018-c16a2500-3820-11eb-9334-e503e56fb718.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like the Architecture isn't visible in the screenshot. 

Feel free to drop another M1 Screenshot

**Comment by aungnay** [comment]
<img width="1072" alt="Screen Shot 2020-12-09 at 8 37 08 PM" src="https://user-images.githubusercontent.com/23125573/101709892-56a62d00-3a5e-11eb-89d6-4697271d82d4.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/synology-drive-client/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
