### ISSUE TITLE
IA Writer

### ISSUE THREAD

**Issue by xcetos** [ThatGuySam/doesitarm#40]
**The official name of the app**
IA Writer

**Proposed App Status**
✅ Full Native Apple Silicon Support

**Related Issue Tracker Link or discussion**
/

**An Official App Download Link**
https://apps.apple.com/us/app/ia-writer/id775737172

**Additional context**
The IA Writer Team officially announced this message in a [Twitter](https://twitter.com/iawriter/status/1326284671005696009?s=21).

**Comment by ThatGuySam** [comment]
Thanks for the App Request this looks great!

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/ia-writer

Feel free to browse through the other issues to help with missing info on other apps.
