### ISSUE TITLE
ONLYOFFICE

### ISSUE THREAD

**Issue by Marc66** [ThatGuySam/doesitarm#404]
**The official name of the app**
ONLYOFFICE

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
https://twitter.com/only_office/status/1336326912990277632

**An Official App Download Page**
https://www.onlyoffice.com/download-desktop.aspx?from=desktop

**Additional context**
![textdocument](https://user-images.githubusercontent.com/11850067/101548627-7715af00-39ac-11eb-9701-a30a70e64559.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

This looks good to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/onlyoffice/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by gaganyadav80** [comment]
OnlyOffice is natively supported on m1 Macs.

**Comment by ThatGuySam** [comment]
@gaganyadav80 Thanks for the tip! 

App Update is now live on the site! 

https://doesitarm.com/app/onlyoffice/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
