### ISSUE TITLE
IDA Pro

### ISSUE THREAD

**Issue by iHTCboy** [ThatGuySam/doesitarm#405]
**The official name of the app**
IDA Pro

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
✳️ Yes, works via Rosetta 2

**Proposed App Category**
Developer Tools

**An Official App Download Page**
[IDA Freeware Download Page – Hex Rays](https://www.hex-rays.com/products/ida/support/download_freeware/)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![image](https://user-images.githubusercontent.com/11418363/101587452-3440ef00-3a1f-11eb-95f1-40ab6251a41e.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/ida-pro/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by amadejpapez** [comment]
Looks like IDA offers native M1 builds since 7.6:

https://hex-rays.com/products/ida/news/7_6/
https://hex-rays.com/ida-free/

**Comment by ThatGuySam** [comment]
Thanks for the tip! Update is now live on the site! 

https://doesitarm.com/app/ida-pro/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
