### ISSUE TITLE
Stepmania 5.3 OutFox

### ISSUE THREAD

**Issue by Scraticus** [ThatGuySam/doesitarm#406]
**The official name of the app**
[Stepmania 5.3 OutFox](https://projectmoon.dance)

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native [Apple Silicon Support](https://projectmoon.dance/releases/5.3-20201208-m1)
✳️ Yes, works via Rosetta 2 (Our Normal Intel Release)

**Proposed App Category**
Games - Music Games

**Related Issue Tracker Link or discussion**
https://github.com/TeamRizu/OutFox/releases/tag/OF4.9.5 
There is a public nightly build of our tested build.

**An Official App Download Page**
https://projectmoon.dance/downloads 

**Additional context**
[StepMania is a multi-mode rhythm game engine.
](https://en.wikipedia.org/wiki/StepMania)
![unknown](https://user-images.githubusercontent.com/11047768/101570554-96253880-39ce-11eb-9357-b13431a1ab61.png)

**Full Screenshot with the App and Activity Monitor(if self reporting) 
![Screenshot_2020-12-08_at_22 03 24](https://user-images.githubusercontent.com/11047768/101570350-2020d180-39ce-11eb-8640-31ea14e972b7.png)

We are in the process of finalising the build so it won't be a nightly moving forwards, but we are super happy to support this new machine and it's been an adventure. We have a small input issue with controllers which we are working on right now, but for keyboard use it is fine and works as designed.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

We pull games from AppleSiliconGames.com

You can submit the game with the link to this issue and doesitarm.com will automatically pull it when it's added: 
https://docs.google.com/forms/d/e/1FAIpQLSfcqcUL5sOSICN46H8Ry9anBj7RTRkz5cKE1PdA6zeAqOfWdA/viewform

**Comment by Scraticus** [comment]
Thanks so much for the quick reply, will get it added to their database now.
