### ISSUE TITLE
Simple Comic

### ISSUE THREAD

**Issue by tonyunreal** [ThatGuySam/doesitarm#407]
**The official name of the app**
Simple Comic

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
Yes, works via Rosetta 2

**Proposed App Category**
Photo and Graphic Tools

**An Official App Download Page**
http://dancingtortoise.com/simplecomic/

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![simplecomic](https://user-images.githubusercontent.com/3460639/101585604-107baa00-3a1b-11eb-9d94-5d63449d16c1.jpg)
![Screen Shot 2020-12-09 at 12 31 17 PM](https://user-images.githubusercontent.com/3460639/101585633-1e312f80-3a1b-11eb-9be6-90b280771634.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/simple-comic/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by tonyunreal** [comment]
[This Community fork](https://github.com/MaddTheSane/Simple-Comic) runs natively on Apple Silicon. I'll submit a PR with a dedicated entry.

![Screen Shot 2021-01-15 at 2 02 30 PM](https://user-images.githubusercontent.com/3460639/104687736-b74e1700-573a-11eb-8d79-442a03134f54.png)

**Comment by ThatGuySam** [comment]
Community Fork is now live

https://doesitarm.com/app/simple-comic-community-fork/
