### ISSUE TITLE
Box Drive

### ISSUE THREAD

**Issue by elibooklover** [ThatGuySam/doesitarm#408]
**The official name of the app**
{Box Drive}

**Is there a supported version available on a stable release channel?**
{No}

**Proposed New App Status**
{⏹ No, not working at all but support is in development}

**Related Issue Tracker Link or discussion**
{https://support.box.com/hc/en-us/community/posts/360051323454-Box-Drive-s-system-extension-failed-to-load?page=1#community_comment_1500000009302}

**An Official App Download Page**
{https://www.box.com/resources/downloads}

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/box-drive/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
