### ISSUE TITLE
Backblaze

### ISSUE THREAD

**Issue by henry-morris** [ThatGuySam/doesitarm#409]
Backblaze ([homepage](https://www.backblaze.com), [Wikipedia](https://en.wikipedia.org/wiki/Backblaze)) is a cloud back-up provider. Their helper application runs in the background backing-up files and can be configured in System Preferences.

It [would seem they are developing M1 support](https://www.reddit.com/r/backblaze/comments/jyl049/apple_m1_silicon/) but as yet it's not released. It would appear that the app works via Rosetta 2 though.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Next, we'll need to confirm M1 support with a screenshot. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by tennis888** [comment]
![Uploading 102067586...]

![Uploading 102067605...]

**Comment by tennis888** [comment]
![image](https://user-images.githubusercontent.com/70786043/102067586-44e5d080-3e36-11eb-961d-84f3bcdb2619.jpeg)


![Uploading 102067605...]

**Comment by tennis888** [comment]
![Uploading 102069190...]

**Comment by ThatGuySam** [comment]
@tennis888 Whoops! Looks like that upload didn't quite finish :)

**Comment by danielmeskin** [comment]
I can see the images correctly, but just in case, here's Silicon Info for the installer: 
![CleanShot 2021-02-11 at 19 03 50](https://user-images.githubusercontent.com/33349740/107714812-e903c080-6c9b-11eb-97bd-21a775960bba.png)
And Activity Monitor for the backup process:
![CleanShot 2021-02-11 at 19 05 07](https://user-images.githubusercontent.com/33349740/107714915-1fd9d680-6c9c-11eb-92a1-1125527ce06d.png)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/backblaze/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by mjvdvlugt** [comment]
I'm afraid Backblaze actually runs on Rosetta, see the screenshot below. Also mentioned on: https://help.backblaze.com/hc/en-us/articles/217666318-Supported-Operating-Systems .
<img width="1214" alt="Schermafbeelding 2021-02-13 om 21 00 51" src="https://user-images.githubusercontent.com/22216538/107860312-01f8a700-6e3f-11eb-8b08-552450f09237.png">

**Comment by mikeelston** [comment]
`backupd` is Apple Time Machine not backblaze.  Backblaze is not yet native on Apple Silicone

**Comment by danielmeskin** [comment]
@mikeelston great catch, sorry for any confusion my image may have caused. I was working off of the original images posted in the issue so I assumed they were correct.

**Comment by ThatGuySam** [comment]
Update is live! 

https://doesitarm.com/app/backblaze/

**Comment by ThatGuySam** [comment]
App is now native

https://www.reddit.com/r/backblaze/comments/ms6bod/latest_backblaze_macos_client_702494_apple/

![image](https://user-images.githubusercontent.com/2830379/115055998-e42fd880-9ea7-11eb-8cf7-ed592bdbf4c1.png)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/backblaze/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
