### ISSUE TITLE
Update on VS Code Support

### ISSUE THREAD

**Issue by wydinhk** [ThatGuySam/doesitarm#41]
Code insiders now supports Apple Silicon. Here's a link about it:
https://code.visualstudio.com/docs/?dv=darwinarm64&build=insiders

**Comment by frictionlessDevelopments** [comment]
**The official name of the app**
Visual Studio Code

**Proposed App Status**
Work in Progress

**Related Issue Tracker Link or discussion**
[microsoft/vscode#106770](https://github.com/microsoft/vscode/issues/106770).

**An Official App Download Link**
https://iterm2.com/downloads.html

**Comment by hkesarwani27** [comment]
Will android studio and netbeans work on apple silicon ?

**Comment by ThatGuySam** [comment]
Is the insiders build like a nightly version?

**Comment by photovirus** [comment]
> Is the insiders build like a nightly version?

I think it's more like beta. 

Nightly is “explorer” builds, as I can see from their github.

**Comment by ThatGuySam** [comment]
Update is live! 

https://doesitarm.com/app/vs-code/

**Comment by tinymachine** [comment]
@ThatGuySam FYI latest stable (1.51.1) also works fine via Rosetta 2, so you might want to change status from ⏹ to ✳️, with clarification that native support is available via Insiders?

<img width="898" alt="Screen Shot 2020-11-22 at 11 09 55 PM" src="https://user-images.githubusercontent.com/171986/99936378-d7072700-2d17-11eb-9e1c-4788dc17683d.png">

**Comment by ThatGuySam** [comment]
@tinymachine VS Code status updated!

**Comment by darakshan** [comment]
[This tweet](https://twitter.com/code/status/1338886895867224070?lang=en) from Visual Studio seems to suggestion that the latest "insider" build for Apple Silicon is pretty stable.  It is working for me, but VSCode is pretty complex and I'm a lightweight user.
<img width="1440" alt="Screen Shot 2020-12-27 at 10 51 43 PM" src="https://user-images.githubusercontent.com/2638451/103194991-2cde6a00-4896-11eb-8025-9cbc648fb56e.png">
