### ISSUE TITLE
Evernote

### ISSUE THREAD

**Issue by austin-schaefer** [ThatGuySam/doesitarm#411]
**The official name of the app**
Evernote

**Is there a supported version available on a stable release channel?**
No, as far as I can tell. No mention of M1 or Apple Silicon in release notes.

**Proposed App Status**
Rosetta 2 (but I don't own an M1 Mac, so I'm going off Reddit posts here https://www.reddit.com/r/Evernote/comments/jvxz81/evernote_on_apple_silicon_m1_macbook_pro/)

**Proposed App Category**

Productivity Tools

**Related Issue Tracker Link or discussion**

https://discussion.evernote.com/forums/topic/131507-apple-silicon-m1-version-of-evernote-10/

**An Official App Download Page**

https://evernote.com/download

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info]

Don't own M1 Mac :/

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks we need an M1 screenshot. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by austin-schaefer** [comment]
Hey @ThatGuySam ! Unfortunately I don't own an M1 Mac. I'm just a user of the site who's shopping around for an M1.

**Comment by ThatGuySam** [comment]
@austin-schaefer All good. We'll leave this open for someone else to come along with a test or more info

**Comment by aardWolf64** [comment]
It's Intel still... got it from the App Store

<img width="1319" alt="Screen Shot 2020-12-18 at 1 56 50 PM" src="https://user-images.githubusercontent.com/5569308/102656099-fb003180-4138-11eb-880d-81d6152fce86.png">

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

For status, we'll say: ✳️ Yes, works via Rosetta 2

And also we'll link to that screenshot as verification

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/evernote/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by marezezelj** [comment]
Evernote now optimized for M1:
https://discussion.evernote.com/forums/topic/141189-evernote-for-mac-is-now-optimized-for-m1-apple-silicon/

**Comment by ThatGuySam** [comment]
@marezezelj Thanks for the update! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/evernote/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
