### ISSUE TITLE
Drafts

### ISSUE THREAD

**Issue by austin-schaefer** [ThatGuySam/doesitarm#412]
**The official name of the app**

Drafts

**Is there a supported version available on a stable release channel?**

Yes

**Proposed App Status**

✅ Yes, Full Native Apple Silicon Support per https://twitter.com/draftsapp/status/1326263191601618945

**Proposed App Category**

Productivity Tools

**Related Issue Tracker Link or discussion**

See Twitter thread https://twitter.com/draftsapp/status/1326263191601618945

**An Official App Download Page**

https://itunes.apple.com/app/id1236254471?ls=1&mt=8&at=11l4Cf&ct=site

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info]

Don't have an M1 Mac to test.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/drafts/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
