### ISSUE TITLE
SnagIt

### ISSUE THREAD

**Issue by austin-schaefer** [ThatGuySam/doesitarm#413]
**The official name of the app**

SnagIt / SnagIt 2020

**Is there a supported version available on a stable release channel?**

No*

**Proposed App Status**

✳️ Yes, works via Rosetta 2 BUT with video capture not working

**Proposed App Category**

Productivity

**Related Issue Tracker Link or discussion**

Official SnagIt support doc https://support.techsmith.com/hc/en-us/articles/360052555611-Snagit-and-Apple-Silicon-Compatibility-Info that mentions lack of native/video support

**An Official App Download Page**

https://www.techsmith.com/download/snagit/

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info]

Don't have an M1 Mac so unable to provide

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.netlify.app/app/snagit/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
