### ISSUE TITLE
Cisco AnyConnect Secure Mobility Client

### ISSUE THREAD

**Issue by aungnay** [ThatGuySam/doesitarm#416]
**The official name of the app**
{Cisco AnyConnect Secure Mobility Client}

**Is there a supported version available on a stable release channel?**
{Yes}

**Proposed App Status**
{Yes, works via Rosetta 2}

**Proposed App Category**
{Productivity Tools}

**An Official App Download Page**
{https://www.cisco.com/c/en/us/support/security/anyconnect-secure-mobility-client-v4-x/model.html}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1483" alt="Screen Shot 2020-12-09 at 10 45 55 PM" src="https://user-images.githubusercontent.com/23125573/101718981-59118280-3a70-11eb-9b86-2a604d6f780a.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/cisco-anyconnect-secure-mobility-client/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by marcscode90** [comment]
https://www.cisco.com/c/en/us/td/docs/security/vpn_client/anyconnect/anyconnect410/release/notes/release-notes-anyconnect-4-10.html#:~:text=native%20macos%20arm64%20support—a%20single%20macos%20installer%20supports%20both%20x86_64%20and%20apple%20silicon%20(m1%20chip)%20natively%20(without%20rosetta)

**Comment by ThatGuySam** [comment]
@marcscode90 Thanks for the update! 

Update is now live on the site! 

https://doesitarm.com/app/cisco-anyconnect-secure-mobility-client/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
