### ISSUE TITLE
Notability

### ISSUE THREAD

**Issue by aungnay** [ThatGuySam/doesitarm#417]
**The official name of the app**
{Notabilityp}

**Is there a supported version available on a stable release channel?**
{Yes}

**Proposed App Status**
{Yes, works via Rosetta 2}

**Proposed App Category**
{Productivity Tools}

**An Official App Download Page**
{https://www.gingerlabs.com/}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="2142" alt="Screen Shot 2020-12-09 at 10 57 05 PM" src="https://user-images.githubusercontent.com/23125573/101719724-e903fc00-3a71-11eb-85cc-fa50d96ea5e1.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

This one looks good too.

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/notability/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by YIMINGMA** [comment]
Good news! The newest Mac App Store version of Notability now support M1 natively!

**Comment by ThatGuySam** [comment]
Good catch! Update is live! 

https://doesitarm.com/app/notability/
