### ISSUE TITLE
Geogebra Classic 5

### ISSUE THREAD

**Issue by aungnay** [ThatGuySam/doesitarm#418]
**The official name of the app**
{Geogebra Classic 5}

**Is there a supported version available on a stable release channel?**
{Yes}

**Proposed App Status**
{Yes, works via Rosetta 2}

**Proposed App Category**
{Science and Research Software}

**An Official App Download Page**
{https://www.geogebra.org/download}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1810" alt="Screen Shot 2020-12-09 at 11 08 08 PM" src="https://user-images.githubusercontent.com/23125573/101720369-709e3a80-3a73-11eb-96a5-3e25f9416dcd.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/geogebra-classic-5/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
