### ISSUE TITLE
Github Classroom Assistant

### ISSUE THREAD

**Issue by aungnay** [ThatGuySam/doesitarm#419]
*The official name of the app**
{Github Classroom Assistant}

**Is there a supported version available on a stable release channel?**
{Yes}

**Proposed App Status**
{Yes, works via Rosetta 2}

**Proposed App Category**
{Productivity Tools}

**An Official App Download Page**
{https://classroom.github.com/assistant}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1798" alt="Screen Shot 2020-12-09 at 11 10 26 PM" src="https://user-images.githubusercontent.com/23125573/101720630-1a7dc700-3a74-11eb-9de7-b2a937d7bed8.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

This is good to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/github-classroom-assistant/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
