### ISSUE TITLE
LTspice

### ISSUE THREAD

**Issue by woolseyj** [ThatGuySam/doesitarm#421]
**The official name of the app**
LTspice

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
Unknown

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
Unknown

**An Official App Download Page**
https://www.analog.com/en/design-center/design-tools-and-calculators/ltspice-simulator.html

**Additional context**
I do not currently have an ARM based Mac, but am preemptively requesting a check for the LTspice app.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
The Architecture column is not available in Activity Monitor for my current Intel based Mac running Catalina.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to get a screenshot. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by woolseyj** [comment]
I can include the screenshots, but it will be Catalina on an Intel based Mac and the Architecture column will not be available in Activity Monitor. Do you still want me to upload those?  I assume you want to see that information on an M1 based Mac running Big Sur. Perhaps someone else can upload that information.

**Comment by ThatGuySam** [comment]
No. That comment's more of a general call out just in case a friendly internet stranger with an M1 finds this issue and wants to provide the screenshot.

**Comment by thunderstorm99** [comment]
**Proposed App Status**
✳️ Yes, works via Rosetta 2
![Screen Shot 2020-12-28 at 22 55 47](https://user-images.githubusercontent.com/3219279/103245337-23213900-4960-11eb-927c-85cb3166ec14.png)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/ltspice/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by woolseyj** [comment]
Thank you very much!

**Comment by kattaliraees** [comment]
Universal binary is available. Verified on LTSpice Version:17.0.36

<img width="1176" alt="Screen Shot 2022-05-04 at 4 48 32 AM" src="https://user-images.githubusercontent.com/574396/166613314-8e131254-9705-43d0-ac5c-2576b4fb37a2.png">
<img width="1304" alt="Screen Shot 2022-05-04 at 4 48 49 AM" src="https://user-images.githubusercontent.com/574396/166613319-3fedb6e6-34aa-4e3f-815f-87a750dd24d1.png">

**Comment by woolseyj** [comment]
Excellent news!

**Comment by ThatGuySam** [comment]
@kattaliraees Thanks for the update!

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by kattaliraees** [comment]
@ThatGuySam PR Submitted

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/ltspice/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
