### ISSUE TITLE
IntelliJ IDEA

### ISSUE THREAD

**Issue by richiksc** [ThatGuySam/doesitarm#422]
Replace the text inside the {}'s with your own. 

For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/358

**The official name of the app**
IntelliJ IDEA

**Is there a supported version available on a stable release channel?**
No

**Proposed New App Status**
✳️ Yes, works via Rosetta 2, with early adopter build with full native Apple Silicon support.

**Related Issue Tracker Link or discussion**
Source: https://youtrack.jetbrains.com/issue/JBR-2526#focus=Comments-27-4589077.0-0

**An Official App Download Page**
Download Native Preview Builds: https://youtrack.jetbrains.com/issue/JBR-2526#focus=Comments-27-4589077.0-0

**Comment by tonyunreal** [comment]
Solved in 716766d696f1362756b94574a594ab1bd3753c14 , PR waiting to be merged.

**Comment by RuiGao98** [comment]
IntelliJ IDEA ：✅ full native support, you can download from https://download.jetbrains.com/idea/ideaIU-203.6494-aarch64.dmg for ultimate or https://download.jetbrains.com/idea/ideaIC-203.6494-aarch64.dmg for community

**Comment by richiksc** [comment]
> IntelliJ IDEA ：✅ full native support, you can download from https://download.jetbrains.com/idea/ideaIU-203.6494-aarch64.dmg for ultimate or https://download.jetbrains.com/idea/ideaIC-203.6494-aarch64.dmg for community

That's a preview build. It has some issues, I'm using it right now. That's what this issue was - mentioned the preview build, added by @tonyunreal's PR

**Comment by RuiGao98** [comment]
> > IntelliJ IDEA ：✅ full native support, you can download from https://download.jetbrains.com/idea/ideaIU-203.6494-aarch64.dmg for ultimate or https://download.jetbrains.com/idea/ideaIC-203.6494-aarch64.dmg for community
> 
> That's a preview build. It has some issues, I'm using it right now. That's what this issue was - mentioned the preview build, added by @tonyunreal's PR

year, full native support at this time may not be very befitting,but support in m1 actually. By the way, zulu jdk and it match well

**Comment by ThatGuySam** [comment]
We'll wait until the Apple Silicon Native build hits the stable release channels so we're not promoting software that's not considered ready by the developer. 

https://www.jetbrains.com/idea/download/#section=mac

**Comment by tonyunreal** [comment]
https://youtrack.jetbrains.com/issue/JBR-2526#focus=Comments-27-4618621.0-0

The latest builds (2020.3.1 - 203.6682.168) were uploaded to their download server, public release imminent?

**Comment by richiksc** [comment]
> https://youtrack.jetbrains.com/issue/JBR-2526#focus=Comments-27-4618621.0-0
> 
> The latest builds (2020.3.1 - 203.6682.168) were uploaded to their download server, public release imminent?

Yes, I've been following that issue as well. I think we should wait until the public release is announced, however, and there is a link on the JetBrains website to update the status on this repo.

**Comment by junjieyuan** [comment]
https://www.jetbrains.com/idea/download/#section=mac

Available for Intel and Apple Silicon

**Comment by ThatGuySam** [comment]
Update is live! 

https://doesitarm.com/app/intellij-idea/
