### ISSUE TITLE
Ultimaker Cura

### ISSUE THREAD

**Issue by aungnay** [ThatGuySam/doesitarm#424]
**The official name of the app**
{Ultimaker Cura}

**Is there a supported version available on a stable release channel?**
{Yes}

**Proposed App Status**
{es, works via Rosetta 2}

**Proposed App Category**
{3D and Architecture}

**An Official App Download Page**
{https://ultimaker.com/software/ultimaker-cura}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="2058" alt="Screen Shot 2020-12-10 at 10 31 50 PM" src="https://user-images.githubusercontent.com/23125573/101858608-ebc92480-3b37-11eb-85e9-21c8a2132307.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Another banger! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/ultimaker-cura/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by ch4bes** [comment]
Newest version (5.0.0) compatible with M1

https://github.com/Ultimaker/Cura/releases/tag/5.0.0

"Upgrade from Qt5 to Qt6
Ultimaker Cura 5.0 is now compatible with Apple M1."

**Comment by ThatGuySam** [comment]
@ch4bes Thanks for the update! 

It seems like the binary is still Intel-based and being translated by Rosetta. 

Is there an alternative download link for the Apple Silicon native version? 
<img width="274" alt="Screen Shot 2022-05-21 at 2 19 26 PM" src="https://user-images.githubusercontent.com/2830379/169666337-c742a168-40da-4bf5-8689-656644a94963.png">
<img width="1680" alt="Screen Shot 2022-05-21 at 2 19 39 PM" src="https://user-images.githubusercontent.com/2830379/169666338-71b8b088-16f0-4438-9b07-3b044199df8c.png">

**Comment by ch4bes** [comment]
Bah, you're right. Looks like Ultimaker-Cura-5.0.0-mac.dmg is still Intel.

It's possible that by "compatible with M1" they mean "you can build a Universal binary from the source code". I could try compiling 5.0.0 from source and see if that works.
