### ISSUE TITLE
SeaDrive 2.0.9 not working 

### ISSUE THREAD

**Issue by steve1878** [ThatGuySam/doesitarm#426]
The current version of SeaDrive (2.0.9; a seafile client) does neither work with arm nor rosetta2:

https://forum.seafile.com/t/seadrive-2-0-8-is-released-support-for-macos-11/13199/25

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Status: 🚫 No, not yet supported only works on Intel-based Macs

Download Page: https://www.seafile.com/en/download/

We'll use that URL as a discussion link

**Comment by ThatGuySam** [comment]
This can now be added to the list. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/seadrive/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
