### ISSUE TITLE
Hex Fiend

### ISSUE THREAD

**Issue by tonyunreal** [ThatGuySam/doesitarm#429]
**The official name of the app**
Hex Fiend

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Yes, full native Apple Silicon support as of v2.14.0

**Proposed App Category**
Developer Tools

**An Official App Download Page**
https://github.com/HexFiend/HexFiend/releases

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Screen Shot 2020-12-13 at 7 51 11 AM](https://user-images.githubusercontent.com/3460639/101999485-723c5c80-3d18-11eb-9eaf-e3cb1af94016.png)
![Screen Shot 2020-12-13 at 7 51 17 AM](https://user-images.githubusercontent.com/3460639/101999487-78323d80-3d18-11eb-93bd-bb1306dc7676.png)

**Comment by ThatGuySam** [comment]
Look good! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.netlify.app/app/hex-fiend/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
