### ISSUE TITLE
Nova

### ISSUE THREAD

**Issue by matthewmorek** [ThatGuySam/doesitarm#43]
**The official name of the app**
Nova

**Proposed App Status**
⏹ Expected to be supported when Apple Silicon is available

**An Official App Download Link**
https://nova.app

**Additional context**
https://twitter.com/panic/status/1276630648250183680

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

This looks good!

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/nova/

Feel free to browse through the other issues to help with missing info on other apps.
