### ISSUE TITLE
FFmpeg

### ISSUE THREAD

**Issue by quhuanyu414** [ThatGuySam/doesitarm#430]
**The official name of the app**
FFmpeg

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
🚫 Not yet supported because of unsupported or broken dependencies on arm64: `rsvg`, `x264`, `libvpx`, `soxr`

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
https://trac.macports.org/ticket/61668

**An Official App Download Page**
https://ffmpeg.org/download.html

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/ffmpeg/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
