### ISSUE TITLE
Seafile 7.0.10

### ISSUE THREAD

**Issue by steve1878** [ThatGuySam/doesitarm#433]
**The official name of the app**
Seafile

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Yes, works via Rosetta 2

**Proposed App Category**
Productivity

**Related Issue Tracker Link or discussion**
https://www.seafile.com/en/roadmap/
https://forum.seafile.com/t/native-support-for-apple-silicon/13390

**An Official App Download Page**
https://www.seafile.com/en/download/

**Additional context**

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
[Silicon Info](https://github.com/steve1878/images_does_it_arm/blob/main/seafile_7.0.10.png)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/seafile/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
