### ISSUE TITLE
Monero Wallet

### ISSUE THREAD

**Issue by ftpmorph** [ThatGuySam/doesitarm#435]
**The official name of the app**
Monero GUI Wallet

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
✳️ Yes, works via Rosetta 2 with a few minor bugs

**Proposed App Category**
Productivity

**Related Issue Tracker Link or discussion**
GitHub page: https://github.com/monero-project/monero-gui
Official blog with new releases and changelogs: https://www.getmonero.org/blog/

**An Official App Download Page**
https://www.getmonero.org/downloads/
https://github.com/monero-project/monero-gui/releases

**Additional context**
It works well enough to be considered functional on Rosetta 2. There are occasional sudden crashes, usually right after entering the wallet password. But most of the time this does not happen and everything works the same as it would natively.

I have found that clicking buttons instead of hitting the enter key is a good way to avoid crashes.

Can confirm it also works with hardware wallets connected via a USB-C hub.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="246" alt="Screenshot 2020-12-14 at 11 03 15 am" src="https://user-images.githubusercontent.com/67348935/102074007-0501f780-3dfc-11eb-88f6-3d1219227b45.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.netlify.app/app/monero-gui-wallet/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
