### ISSUE TITLE
Tor Browser

### ISSUE THREAD

**Issue by ftpmorph** [ThatGuySam/doesitarm#436]
**The official name of the app**
Tor Browser

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
✳️ Yes, works via Rosetta 2 but with a few page crashes

**Proposed App Category**
Productivity

**Related Issue Tracker Link or discussion**
Official blog: https://blog.torproject.org/
Issue tracker for some pages causing tab crashes: https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40262

**An Official App Download Page**
https://www.torproject.org/download/

**Additional context**
Mostly works just fine but as noted above some pages cause the tab to crash. So far no one seems to know exactly what is triggering this issue but it's being looked into.

Native support likely a ways off as Firefox has to add support upstream first before Tor team can even begin work on an ARM build.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="246" alt="Screenshot 2020-12-08 at 8 09 10 am" src="https://user-images.githubusercontent.com/67348935/102074998-81e1a100-3dfd-11eb-84bd-4cdd3b38b6d5.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.netlify.app/app/tor-browser/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by Friscas** [comment]
Hey @ThatGuySam @ftpmorph 
First I want to start by saying sorry if I tagged you and that I'm commenting here, I'm not sure if I should open a new issue or if here is also ok! 

But it seems that the crashing problem was solved, so I think it is important to change the text that says: "Yes, works via Rosetta 2 but with a few page crashes"

Thanks! 

Here are the Sources:

Tor browser alpha: https://blog.torproject.org/new-release-tor-browser-105a7

Tor browser stable: https://blog.torproject.org/new-release-tor-browser-1008

Discussion:

https://gitlab.torproject.org/tpo/applications/tor-browser/-/issues/40262

**Comment by ThatGuySam** [comment]
@Friscas Thanks for the report! Using the original issue is perfectly fine. 

Update is now live! 

https://doesitarm.com/app/tor-browser/
