### ISSUE TITLE
TrashMe 3

### ISSUE THREAD

**Issue by webjib** [ThatGuySam/doesitarm#439]
**The official name of the app**
TrashMe 3

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
https://twitter.com/jibapps/status/1332269102526832641

**An Official App Download Page**
https://www.jibapps.com/apps/trashme3/

**Additional context**
No

<img width="727" alt="Capture d'écran 2020-12-14 à 15 13 06" src="https://user-images.githubusercontent.com/33569886/102091901-b6665480-3e1f-11eb-87a4-8fe0d6f30e9d.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

This is also good to go! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by webjib** [comment]
PR #477

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/trashme-3/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
