### ISSUE TITLE
Jump Desktop

### ISSUE THREAD

**Issue by badlion** [ThatGuySam/doesitarm#44]
The official name of the app
Jump Desktop

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by harryzcy** [comment]
Website: https://jumpdesktop.com/

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/jump-desktop/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
