### ISSUE TITLE
Displays

### ISSUE THREAD

**Issue by webjib** [ThatGuySam/doesitarm#440]
**The official name of the app**
Displays

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
https://twitter.com/jibapps/status/1338478515453386755

**An Official App Download Page**
https://www.jibapps.com/apps/displays/

**Additional context**
No

<img width="727" alt="Capture d'écran 2020-12-14 à 15 13 39" src="https://user-images.githubusercontent.com/33569886/102092161-09400c00-3e20-11eb-9c38-c2f679230e6f.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

This looks great! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by webjib** [comment]
PR #477

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/displays-for-mac/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
