### ISSUE TITLE
Windscribe

### ISSUE THREAD

**Issue by mahenzon** [ThatGuySam/doesitarm#442]
**The official name of the app**
Windscribe

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
:large_orange_diamond: Unknown, more info needed

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
https://windscribe.com/vpn-for-mac

**An Official App Download Page**
https://windscribe.com/download

**Additional context**
MacOS 10.11+ 

Haven't tried it myself yet

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks we need a screenshot. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by mahenzon** [comment]
Ok, as soon as I get a mac

**Comment by ThatGuySam** [comment]
@mahenzon All good! 

We have volunteers that will come through and test apps on these issues

**Comment by mahenzon** [comment]
Winscribe runs with Rozetta. Works
<img width="741" alt="Screenshot 2020-12-18 at 21 38 29" src="https://user-images.githubusercontent.com/20804158/102648952-7386e280-4179-11eb-9010-a4c3bb7535c6.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/windscribe/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
