### ISSUE TITLE
AppCleaner

### ISSUE THREAD

**Issue by SethuSenthil** [ThatGuySam/doesitarm#443]
**The official name of the app**
AppCleaner

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Yes, works via Rosetta 2 

**Proposed App Category**
Utilities

**Related Issue Tracker Link or discussion**
https://freemacsoft.net/appcleaner/

**An Official App Download Page**
https://freemacsoft.net/appcleaner/

**Additional context**
None

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

![image](https://user-images.githubusercontent.com/20134046/102144936-604fdc00-3e34-11eb-993d-ead153f13d4b.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/appcleaner/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by liuyuanOUC** [comment]
@ThatGuySam Hi, the status of AppCleaner may be wrong, as shown below:
![image](https://user-images.githubusercontent.com/27879832/107133486-99339b00-6923-11eb-9b50-eabb0e879272.png)
 It should be working via Rosetta 2.

**Comment by ThatGuySam** [comment]
@liuyuanOUC Good catch! You're absolutely right. It must have slipped through. 

I'll fix it now.

**Comment by ThatGuySam** [comment]
Fixed! 

https://doesitarm.com/app/appcleaner/

**Comment by liaojianjin** [comment]
Is there something wrong？It's on my M1.
![image](https://user-images.githubusercontent.com/29427459/107338637-bb314700-6af6-11eb-958e-53a893d1cfdc.png)

**Comment by liaojianjin** [comment]
AppCleaner Version is 3.6.0 (4070)

**Comment by ThatGuySam** [comment]
You're killing me smalls

**Comment by ThatGuySam** [comment]
App is now reFixed! 

https://doesitarm.com/app/appcleaner/
