### ISSUE TITLE
Logitech Options

### ISSUE THREAD

**Issue by ErikSwan** [ThatGuySam/doesitarm#444]
**The official name of the app**
[Logitech Options](https://www.logitech.com/en-us/product/options)

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Yes, works via Rosetta 2. Some users report issues with the Flow feature.

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
https://forums.macrumors.com/threads/does-logitech-options-works.2270516/

**An Official App Download Page**
https://www.logitech.com/en-us/product/options

**Additional context**

**Full Screenshot with the App and Activity Monitor (if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![image](https://user-images.githubusercontent.com/163976/102148249-5d032300-3e29-11eb-89c0-2788e92dd1ff.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/logitech-options/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
