### ISSUE TITLE
Microsoft Office 365

### ISSUE THREAD

**Issue by elibooklover** [ThatGuySam/doesitarm#446]
**The official name of the app**
Microsoft Office 365 

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**An Official App Download Page**
According to Microsoft Official Post, "If you have automatic updates turned on, you will start to receive these updates today. Otherwise, you can go to the Mac App Store and click the Updates tab, or with Microsoft AutoUpdate, you can go to your Office app’s Help menu and choose Check for Updates."

<img width="900" alt="updates" src="https://user-images.githubusercontent.com/32969240/102259780-297dd280-3ed5-11eb-8702-cf0699379a5d.png">

**Comment by elibooklover** [comment]
Microsoft Official Post: https://www.microsoft.com/en-us/microsoft-365/blog/2020/12/15/4-ways-microsoft-365-is-improving-the-experience-for-mac-users/

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/microsoft-office-365/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
