### ISSUE TITLE
Mendeley

### ISSUE THREAD

**Issue by Madhawa97** [ThatGuySam/doesitarm#448]
**The official name of the app**
Mendeley

**Proposed App Status**
🔶 Unknown, more info needed

**Proposed App Category**
Productivity Tools

**An Official App Download Page**
https://www.mendeley.com/download-desktop-new/macOS

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks we need a screenshot. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by Madhawa97** [comment]
okay sure. 3 weeks away from getting an M1 Mac

**Comment by ThatGuySam** [comment]
@Madhawa97 All good! 

I always leave that comment on issues because random people will come through and test apps.

**Comment by Madhawa97** [comment]
that sounds great

**Comment by thunderstorm99** [comment]
**Proposed App Status**
✳️ Yes, works via Rosetta 2 
![Screen Shot 2020-12-28 at 22 25 38](https://user-images.githubusercontent.com/3219279/103243939-b86dfe80-495b-11eb-8751-2450dee8ee2f.png)

**Comment by Madhawa97** [comment]
appreciate that @thunderstorm99

**Comment by Madhawa97** [comment]
![image](https://user-images.githubusercontent.com/70215958/103466830-b696a780-4d6e-11eb-961f-3653bd262f3b.png)
I get this error when connecting Mendeley with Microsoft Word (Native apple silicon version)
Seems like an issue in the Mendeley MS word plugin.

**Comment by thunderstorm99** [comment]
I can confirm this issue. There is a workaround:
Right click on Microsoft Word in Finder -> Get Info -> click on Open using Rosetta
![image](https://user-images.githubusercontent.com/3219279/103477385-bfaf6500-4dbe-11eb-8fda-6e7a5161863b.png)
After that the plugin works.

**Comment by Madhawa97** [comment]
@thunderstorm99  You're a genius 😃 Yes it's working that way. Thank you

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/mendeley/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
