### ISSUE TITLE
Th

### ISSUE THREAD

**Issue by darakshan** [ThatGuySam/doesitarm#449]
**The official name of the app**
Thunderbird

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Yes, works via Rosetta 2

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
https://bugzilla.mozilla.org/show_bug.cgi?id=1678775

**An Official App Download Page**
https://www.thunderbird.net/en-US/

**Additional context**

**Full Screenshot with the App and Activity Monitor(if self reporting)
<img width="1436" alt="Screen Shot 2020-12-15 at 8 07 36 PM" src="https://user-images.githubusercontent.com/2638451/102304094-767f9a00-3f11-11eb-842f-80ac00230050.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/thunderbird

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
