### ISSUE TITLE
ClashX 

### ISSUE THREAD

**Issue by hsing0527** [ThatGuySam/doesitarm#450]
[ClashX](https://github.com/yichengchen/clashX) is one of famous socket application on macOS.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks we need a screenshot. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

Alternatively, if there's an official announcement from the developer, that clearly states the current status, we can use that

**Comment by liuyuanOUC** [comment]
The official name of the app
ClashX Pro

Is there a supported build available on a public/release channel?
Yes

Proposed App Status
✅ Yes, Full Native Apple Silicon Support as of Version 1.31.1.1

Proposed App Category
VPN, Security, and Privacy

Related Issue Tracker Link or discussion
https://install.appcenter.ms/users/clashx/apps/clashx-pro/distribution_groups/public

![image](https://user-images.githubusercontent.com/27879832/107452649-8ec40c00-6b84-11eb-8b80-cff0e104a62b.png)


An Official App Download Page
https://install.appcenter.ms/users/clashx/apps/clashx-pro/distribution_groups/public

Full Screenshot with the App and Activity Monitor(if self reporting) or Silicon Info
None

**Comment by ThatGuySam** [comment]
Thanks, @liuyuanOUC! App is now live on the site! 

https://doesitarm.com/app/clashx/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
