### ISSUE TITLE
Wiznote

### ISSUE THREAD

**Issue by GerrieWell** [ThatGuySam/doesitarm#451]
**The official name of the app**
wiznote

**Is there a supported version available on a stable release channel?**
yes

**Proposed App Status**
🔶 Unknown, more info needed

**Proposed App Category**
note app

**An Official App Download Page**
https://www.wiz.cn/wiznote-mac.html
https://url.wiz.cn/u/mac

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is for someone with an M1 to get a screenshot. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by moffpage** [comment]
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/33549573/123586305-54db6580-d806-11eb-97ad-1bbd53820677.png">
![Uploading image.png…]()

**Comment by ThatGuySam** [comment]
Looks good @moffpage! 

We'll use the following status:
✳️ Yes, works via Rosetta 2 translation

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/wiznote/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
