### ISSUE TITLE
Dolphin

### ISSUE THREAD

**Issue by tonyunreal** [ThatGuySam/doesitarm#452]
**The official name of the app**
Dolphin

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
Yes, works via Rosetta 2

**Proposed App Category**
Entertainment and Media Apps

**An Official App Download Page**
https://dolphin-emu.org/download/

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Screen Shot 2020-12-17 at 12 14 28 PM](https://user-images.githubusercontent.com/3460639/102443585-10565c80-4062-11eb-9dc5-c004ccd20edf.png)
![Screen Shot 2020-12-17 at 12 14 45 PM](https://user-images.githubusercontent.com/3460639/102443594-164c3d80-4062-11eb-878d-fe791f6fa807.png)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/dolphin/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by tonyunreal** [comment]
Proposed PR adding Apple Silicon support: 
https://github.com/dolphin-emu/dolphin/pull/9441

When those changes are merged and native builds are out on their website, I'll submit a status change.

Alternatively, one can build from [the source](https://github.com/skylersaleh/dolphin) to run the native version already.
