### ISSUE TITLE
Paw

### ISSUE THREAD

**Issue by nfangxu** [ThatGuySam/doesitarm#453]
**The official name of the app**
Paw

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
🔶 Unknown, more info needed

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**

**An Official App Download Page**
https://paw.cloud/

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to get a tracker link to verify support or a screenshot. 

For the screenshot, be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by raphaelgurtner** [comment]
**Proposed App Status**
✳️ Runs via Rosetta with native support currently in development
according to the developers, see [reply on twitter](https://twitter.com/luckymarmot/status/1332614644654026755?s=20)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/paw/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by WeeJeWel** [comment]
Paw now supports M1 (v3.2.1)

**Comment by ThatGuySam** [comment]
Thanks, @WeeJeWel! 

Update is live! 

https://doesitarm.com/app/paw/
