### ISSUE TITLE
ForkLift

### ISSUE THREAD

**Issue by haennima** [ThatGuySam/doesitarm#455]
Replace the text inside the {}'s with your own. 

For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/358

**The official name of the app**
{ForkLift}

**Is there a supported version available on a stable release channel?**
{Yes/No}

**Proposed App Status**
{What's the current app status based off of current discussion or testing
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend}

**Proposed App Category**
{What category should the app go under}

**Related Issue Tracker Link or discussion**
{This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes.}

**An Official App Download Page**
{This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site.}

**Additional context**
{Add any other context or screenshots about the app request here.}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{As screenshot with Activity Monitor open showing the App's architecture type}

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by danielmeskin** [comment]
Figured I'd fill in the details: 

App status: ✳️

Category: Developer tools

Download link: https://download.binarynights.com/ForkLift3.zip

Silicon info screenshot: 
![CleanShot 2021-01-05 at 21 50 05](https://user-images.githubusercontent.com/33349740/103723404-fee8dc00-4f9f-11eb-9e77-c4068c3f51bc.png)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/forklift/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by Bambalazs** [comment]
ForkLift supports Apple Silicon since v3.5 ([2021-04-13](https://binarynights.com/versionhistory)).

<img width="337" alt="Screen Shot 2022-02-02 at 11 31 23" src="https://user-images.githubusercontent.com/6575518/152137322-50aa9ecb-3e2c-4428-bed2-41add074155c.png">

**Comment by ThatGuySam** [comment]
Thanks, @Bambalazs 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by amandaallissa** [comment]
@Bambalazs Thank you for your help! 
App is now live on the site! 

https://doesitarm.com/app/forklift/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
