### ISSUE TITLE
Insomnia

### ISSUE THREAD

**Issue by mahenzon** [ThatGuySam/doesitarm#456]
**The official name of the app**
I know it as `Insomnia`, but I visited official page and it's listed now as `Insomnia Core`, but there's also `Insomnia Designer`, and I'm not sure if these two have to be separate

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
:large_orange_diamond: Unknown, more info needed

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
repo https://github.com/Kong/insomnia
there's a MacOS Big Sur issue, but no mention of arm / M1: https://github.com/Kong/insomnia/issues/2860

**An Official App Download Page**
https://insomnia.rest/download/

**Additional context**
It's an electron app, likely it's super easy to migrate, maybe if not already

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

The next step is for someone with an M1 Mac to get a screenshot. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by mahenzon** [comment]
Works via rozetta 
<img width="852" alt="Screenshot 2020-12-18 at 21 53 51" src="https://user-images.githubusercontent.com/20804158/102650231-9f0acc80-417b-11eb-9862-b6a62a09251d.png">

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

For status, we'll say: ✳️ Yes, works via Rosetta 2

And also we'll link to that screenshot as verification

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
Apps are now live on the site! 

https://doesitarm.com/app/insomnia-designer/
https://doesitarm.com/app/insomnia-core/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by ThatGuySam** [comment]
Also looks like we can use this issue as a tracker for native support: https://github.com/Kong/insomnia/issues/2964
