### ISSUE TITLE
Infuse

### ISSUE THREAD

**Issue by tonyunreal** [ThatGuySam/doesitarm#458]
**The official name of the app**
Infuse

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
Not released to public yet, but the current alpha build runs via Rosetta 2

**Proposed App Category**
Entertainment and Media Apps

**Related Issue Tracker Link or discussion**
Annoucement Thread: https://community.firecore.com/t/infuse-macos-public-alpha-12-18-20/24328

**An Official App Download Page**
See the announcement link.

**Additional context**
Since alpha just came out yesterday, and the official download link is available to approved testers only (applying is free though), I feel there is need for a discussion thread here, feel free to report back with screenshots or issues (make sure you report them to the makers too).

In case you don't know, Infuse is a popular app on iOS and tvOS that plays your homebrew videos, ripped movies (ahem) and tv shows etc. It also has some basic levels of media management functionality like Plex, where it can automatically fetch metadata and thumbnails for your movies and shows from the Internet.

**Comment by tonyunreal** [comment]
Got both good and bad news. Good news is that I got into the alpha test, the email was sent to me almost instantly after applying. Bad news is the current alpha runs via Rosetta 2, aka not Apple Silicon optimized.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Screen Shot 2020-12-19 at 7 56 13 PM](https://user-images.githubusercontent.com/3460639/102688936-5adc0280-4235-11eb-9109-a3eeb215123d.png)
![Screen Shot 2020-12-19 at 7 56 21 PM](https://user-images.githubusercontent.com/3460639/102688943-60394d00-4235-11eb-84cf-9cefaf7e5d93.png)

**Comment by ThatGuySam** [comment]
That makes sense to me. 

Let's add it!
