### ISSUE TITLE
Wirecast

### ISSUE THREAD

**Issue by frankie567** [ThatGuySam/doesitarm#459]
**The official name of the app**
[Wirecast](https://www.telestream.net/wirecast/)

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
⏹ No, not working at all but support is in development

**Proposed App Category**
Video tools

**Related Issue Tracker Link or discussion**
* http://www.telestream.net/telestream-support/wire-cast/support.htm?accordion=faqBigSur#faqs
* https://telestreamforum.forumbee.com/t/83hmja8/is-anyone-running-wirecast-under-rosetta-2-on-an-m1-mac
* https://telestreamforum.forumbee.com/t/m1hmlf0/wirecast-on-new-macs

**An Official App Download Page**
https://www.telestream.net/wirecast/store.asp

**Additional context**
—

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

<img width="218" alt="Capture d’écran 2020-12-19 à 14 51 49" src="https://user-images.githubusercontent.com/1144727/102691032-d7f18280-4209-11eb-9bf4-92e0704ad35b.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/wirecast/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
