### ISSUE TITLE
OneNote

### ISSUE THREAD

**Issue by gwokhou** [ThatGuySam/doesitarm#460]
**The official name of the app**
Microsoft OneNote

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
None

**An Official App Download Page**
app Store

**Additional context**
None

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![image](https://user-images.githubusercontent.com/24861058/102694921-1cf3d400-425f-11eb-970c-8e15759d0f8d.png)

**Comment by aardWolf64** [comment]
Runs in native mode.

![image](https://user-images.githubusercontent.com/5569308/102788224-ea81ce00-4367-11eb-82d2-1ddeffaf4112.png)
