### ISSUE TITLE
Outlook

### ISSUE THREAD

**Issue by gwokhou** [ThatGuySam/doesitarm#461]
**The official name of the app**
Microsoft Outlook

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
None

**An Official App Download Page**
app Store

**Additional context**
None

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![image](https://user-images.githubusercontent.com/24861058/102695097-36e1e680-4260-11eb-815d-d089479014f3.png)

**Comment by aardWolf64** [comment]
Confirmed working.  Outlook Version 16.44 (20211301) is running natively.

![image](https://user-images.githubusercontent.com/5569308/102787737-2c5e4480-4367-11eb-8a86-15656bfd770d.png)

**Comment by aardWolf64** [comment]
Edited to remove personal info...  Runs natively with latest version.

![image](https://user-images.githubusercontent.com/5569308/102788115-c45c2e00-4367-11eb-81e1-9136e7de5191.png)
