### ISSUE TITLE
UUBooster

### ISSUE THREAD

**Issue by Sunnyyoung** [ThatGuySam/doesitarm#464]
**The official name of the app**

UUBooster

**Is there a supported version available on a stable release channel?**

Yes

**Proposed App Status**

✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**

Utilities

**Related Issue Tracker Link or discussion**

None

**An Official App Download Page**

https://uu.163.com

**Additional context**

None

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

![image](https://user-images.githubusercontent.com/5926284/102716571-aff04500-4317-11eb-831d-437483014765.png)

**Comment by ThatGuySam** [comment]
For status let's say: 

✅ Yes, Full Native Apple Silicon Support

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

This is ready to add. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/uu-booster/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
