### ISSUE TITLE
Filmora X now supports ARM

### ISSUE THREAD

**Issue by FilmoraMacOS** [ThatGuySam/doesitarm#465]
**The official name of the app**
{Wondershare Filmora}

**Is there a supported version available on a stable release channel?**
{Yes}

**Proposed New App Status**
{Yes, fully supported ARM and Intel Chip}

**Proposed New App Category**
{Photo & Video}

**Related Issue Tracker Link or discussion**
{Official post:
https://filmora.wondershare.com/filmora-supports-apple-arm.html

**An Official App Download Page**
https://apps.apple.com/us/app/filmora-video-editor/id1516822341?mt=12

![image](https://user-images.githubusercontent.com/76199179/102845233-0eb4dc00-4448-11eb-9c90-42082d9b397b.png)

**Comment by FilmoraMacOS** [comment]
#282

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/wondershare-filmora/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
