### ISSUE TITLE
Cryptomator

### ISSUE THREAD

**Issue by danielmeskin** [ThatGuySam/doesitarm#466]
**The official name of the app**
[Cryptomator](https://cryptomator.org)

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
🚫 Runs via Rosetta 2 but modifying files requires installing macFUSE due to an upstream issue with WebDAV.

**Proposed App Category**
?

**Related Issue Tracker Link or discussion**
[Apple Silicon crashing issue](https://github.com/cryptomator/cryptomator/issues/1419)

**An Official App Download Page**
https://cryptomator.org/downloads/

**Additional context**
It works through macFUSE but not with WebDAV. It's an upstream issue affecting all WebDAV connections so as soon as Apple fixes it it should be working fully. 

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

![CleanShot 2020-12-22 at 09 23 14](https://user-images.githubusercontent.com/33349740/102898400-73b40600-4437-11eb-9c81-794b9677f046.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/cryptomator/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
