### ISSUE TITLE
Skim PDF Reader

### ISSUE THREAD

**Issue by Harry1993** [ThatGuySam/doesitarm#468]
Replace the text inside the {}'s with your own. 

For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/358

**The official name of the app**
{Skim}

**Is there a supported version available on a stable release channel?**
{No}

**Proposed App Status**
{Yes, works via Rosetta 2, but an ARM64 version can be built locally via Xcode.}

**Proposed App Category**
{Productivity Tools}

**Related Issue Tracker Link or discussion**
{https://gist.github.com/Harry1993/399ae3f7cfc0e87f8bbe366b8200ce96}

**An Official App Download Page**
{}

**Additional context**
{}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{}

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks we need someone with an M1 to provide a screenshot. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by Harry1993** [comment]
@ThatGuySam Thanks for noticing. Here is the screenshot.

![Image 12-28-20 at 10 52 AM](https://user-images.githubusercontent.com/11852986/103233689-f0912500-48fa-11eb-9cd0-d75780fb0f23.jpg)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/skim-pdf-reader/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by erinacio** [comment]
<img width="739" alt="Screen Shot 2021-01-20 at 16 52 45" src="https://user-images.githubusercontent.com/15362012/105150616-f2d45100-5b3f-11eb-88c2-946ef3709a22.png">

Skim 1.6 was released with native support for apple silicon. No need to build locally now.

**Comment by Harry1993** [comment]
@erinacio Confirmed. Thanks.
