### ISSUE TITLE
Obsidian

### ISSUE THREAD

**Issue by syhily** [ThatGuySam/doesitarm#469]
**The official name of the app**
Obsidian

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, full native support as of v0.10.1

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
https://forum.obsidian.md/t/apple-arm-compatibility-apple-silicon/3965

**An Official App Download Page**
https://obsidian.md/download

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/obsidian/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
