### ISSUE TITLE
Ruby

### ISSUE THREAD

**Issue by maksimf** [ThatGuySam/doesitarm#47]
**The official name of the app**
Ruby

**Proposed App Status**
Can run well enough (latest version of Ruby 2.7 has been successfully ran with a few patches) 

**Related Issue Tracker Link or discussion**
https://bugs.ruby-lang.org/issues/17202

**An Official App Download Link**
https://www.ruby-lang.org/en/downloads/

**Comment by ThatGuySam** [comment]
Thanks for the request!

Do you know if the patched version is available through Homebrew?

**Comment by maksimf** [comment]
Unfortunately, I don't :(

**Comment by maksimf** [comment]
`2.7.2p137 (2020-10-01 revision 5445e0435260b449decf2ac16f9d09bae3cafe72)` and older should be fine

**Comment by maksimf** [comment]
Yep, after some research it looks like this is exactly the same version as the latest one which can be installed via homebrew. So, theoretically, latest ruby from homebrew should work fine

**Comment by ThatGuySam** [comment]
I dropped a comment on https://github.com/rvm/rvm/issues/4968 to get an official reponse

**Comment by maksimf** [comment]
A few things to clarify in case you're not familiar with Ruby infrastructure.

- rvm is not ruby it's just a version manager and it might be rvm issue, not Ruby (it might be Ruby's problem as well)
- the version in question in the RVM repo is 2.7.1, whereas my research has shown that only 2.7.2 has been successfully built on ARM

No pressure whatsoever just FYI

**Comment by ThatGuySam** [comment]
Yeah, I don't think I've even ever directly used ruby, unfortunately. 

I can seem to find where on that bug page they explicitly say ARM/Apple Silicon is supported even I know that what it's about. 

I want to provide a link that clearly states why we think the status of 2.7.2 is supported.

**Comment by ThatGuySam** [comment]
Perhaps this would be a good one to use
https://github.com/ruby/ruby/commit/23655e6de5ee989feb8c65c7061fe9a71579dc54

**Comment by tonyunreal** [comment]
Maybe use this page as proof? It seems 2.7.2 is building fine for the arm64 target.
https://ports.macports.org/port/ruby27/summary

**Comment by ThatGuySam** [comment]
I seem to be getting a 502 error when I try to load that page

**Comment by tonyunreal** [comment]
> 
> 
> I seem to be getting a 502 error when I try to load that page

Yeah I got that too sometimes, just hit refresh a couple of times and it should load.

**Comment by ThatGuySam** [comment]
@tonyunreal So are you thinking “✅ Yes, Full Native Apple Silicon Support v2.7.2”

**Comment by tonyunreal** [comment]
Yes I am. 

It would still be better if someone could confirm here with a screenshot though.

**Comment by ThatGuySam** [comment]
Confirmed working on Homebrew!

App is now live on the site! 

https://doesitarm.com/formula/ruby/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
