### ISSUE TITLE
DataGrip

### ISSUE THREAD

**Issue by Grrrolf** [ThatGuySam/doesitarm#470]
**The official name of the app**
DataGrip

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
 ✅  Yes, Full Native Apple Silicon Support

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
None.

**An Official App Download Page**

**Additional context**
[Release notes](https://blog.jetbrains.com/datagrip/2020/12/24/datagrip-2020-3-1/)
![image](https://user-images.githubusercontent.com/10052794/103107977-9286e800-4643-11eb-92f4-2f4336d7db90.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/datagrip/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
