### ISSUE TITLE
PDFZone

### ISSUE THREAD

**Issue by yellow8-vom** [ThatGuySam/doesitarm#471]
**The official name of the app**
PDFZone

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity

**Related Issue Tracker Link or discussion**
https://forums.macrumors.com/threads/pdfzone-3-batch-rename-your-pdf-files-based-on-their-content-automatically.2244765/?post=29368977#post-29368977

**An Official App Download Page**
https://apps.apple.com/app/pdfzone/id1215383084

**Additional context**
Native Apple Silicon support since v3.1

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![PDFZone](https://i.paste.pics/b94e24f7a357a9079904d5da3af819fb.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/pdfzone/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by yellow8-vom** [comment]
Thank you very much! 👍
