### ISSUE TITLE
KiCad

### ISSUE THREAD

**Issue by woolseyj** [ThatGuySam/doesitarm#472]
**The official name of the app**
KiCad

**Is there a supported version available on a stable release channel?**
Yes, but not for M1 based macOS.

**Proposed App Status**
Unknown

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
https://forum.kicad.info/t/kicad-on-apple-m1/26321

**An Official App Download Page**
https://kicad.org/download/macos/

**Additional context**
I do not currently have an ARM based Mac, but am preemptively requesting a check for the KiCad app.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
The Architecture column is not available in Activity Monitor for my current Intel based Mac running Catalina.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks we need someone with an M1 to provide a screenshot. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/kicad-eda/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by woolseyj** [comment]
Thank you very much!

**Comment by kattaliraees** [comment]
<img width="1502" alt="Screenshot 2023-02-03 at 5 06 10 AM" src="https://user-images.githubusercontent.com/574396/216475191-1967feff-9ff9-4f4c-8606-a031b2a4ae6f.png">

**Comment by ThatGuySam** [comment]
@kattaliraees 
Update is now live on the site! 

https://doesitarm.com/app/kicad-eda/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
