### ISSUE TITLE
ffWorks

### ISSUE THREAD

**Issue by YodaSpow** [ThatGuySam/doesitarm#473]
**The official name of the app**
ffWorks

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Version 2.2.1: For macOS 64bit 10.10 and higher (Intel and Apple Silicon)

**Proposed App Category**
Video and Motion Tools

**Related Issue Tracker Link or discussion**
Cant find a forum or discussion for this.

**An Official App Download Page**
https://www.ffworks.net/download.html

**Additional context**
I do not currently have an ARM based Mac, but am preemptively requesting a check for the ffWorks app.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
Thinking support for ffWorks might be a problem as it requires FFmpeg to run, and this has to be loaded separately:
Site mentions on the download page: 

New in version 2.2.1

- Improved GUI when running macOS 11 Big Sur
- Fixed issue when enabling ’Destination Folder same as Source’ and enabling ’Convert to sub folder’.
- Fixed issue enabling Hardware accelerated encoding.

Important!  ffWorks does NOT include a compiled FFmpeg file! You have to compile or download this yourself.

**Comment by stefcarlens** [comment]
Not sure what you are trying to achieve with this. Both FFworks and FFmpeg are available for native Apple Silicone.
Did you actually do some search for this???

**Comment by YodaSpow** [comment]
This for app request on the site: https://doesitarm.com
To be included here as it quite helpful for video tools and updates about Apple Mac new M1 chip which is ARM based now.

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/ffworks/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
