### ISSUE TITLE
WhatsApp Desktop ???

### ISSUE THREAD

**Issue by singhalrishi27** [ThatGuySam/doesitarm#479]
Does WhatsApp Desktop Works on Apple Silicon?

**Comment by steve1878** [comment]
The official name of the app
WhatsApp

Is there a supported version available on a stable release channel?
2.2049.10

Proposed App Status
✳️ Yes, works via Rosetta 2 as of v2.2049.10

Proposed App Category
Social and communication

Related Issue Tracker Link or discussion
None yet

An Official App Download Page
https://www.whatsapp.com/download/

Additional context
None yet

Full Screenshot with the App and Activity Monitor(if self reporting) or Silicon Info
https://github.com/steve1878/images_does_it_arm/blob/main/WhatsApp_2.2049.10.png

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/whatsapp/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
