### ISSUE TITLE
Android Studio

### ISSUE THREAD

**Issue by 7space7** [ThatGuySam/doesitarm#48]
**The official name of the app**
Android Studio

**An Official App Download Link**
https://developer.android.com/studio

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by iColdplay** [comment]
anyone?

**Comment by ThatGuySam** [comment]
Hey @iColdplay, 

Feel free to add any links you find related to the current status, otherwise, I do some research when I have time to get to this issue

**Comment by chen-shimu** [comment]
✳️ Yes, works via Rosetta 2 .

**Comment by chen-shimu** [comment]
> ✳️ Yes, works via Rosetta 2 .

but  the AVD Not available and
I think the app no fluent

**Comment by ThatGuySam** [comment]
Let’s see if we can get someone with an M1 to do a screenshot with Activity Monitor so we can see if it’s Rosetta

**Comment by chen-shimu** [comment]
![image](https://user-images.githubusercontent.com/54127641/99963753-3410e480-2dcd-11eb-9a16-181688374296.png)

**Comment by chen-shimu** [comment]
![image](https://user-images.githubusercontent.com/54127641/99963991-94078b00-2dcd-11eb-8aa7-b5dd9f6ce51d.png)
<img width="900" alt="5C3DFCA7-1770-4319-B593-B8A4107F462B" src="https://user-images.githubusercontent.com/54127641/99964029-a1bd1080-2dcd-11eb-81ba-19c93af4d0e1.png">

**Comment by chen-shimu** [comment]
<img width="900" alt="5C3DFCA7-1770-4319-B593-B8A4107F462B" src="https://user-images.githubusercontent.com/54127641/99964138-ce712800-2dcd-11eb-9a34-d297bbce3362.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/android-studio/

Feel free to browse through the other issues to help with missing info on other apps.

**Comment by hannesa2** [comment]
Android Studio sometimes freeze

**Comment by SethuSenthil** [comment]
I think it's important to note that you can't run any emulators yet or in the near future. (M1 MBP user here)

**Comment by hannesa2** [comment]
I created a Google ticket https://issuetracker.google.com/issues/173624439
Please star it, then you get informed on any change there and Google see how many people waiting for it 
<img width="330" alt="image" src="https://user-images.githubusercontent.com/3314607/100967275-22e37880-352f-11eb-8e8f-d2cb32b411fd.png">

**Comment by ThatGuySam** [comment]
Status updated and link added!

**Comment by SethuSenthil** [comment]
Android Emulators for apple silicon are now in preview so its possible to run most basic apps in the emulator. 
Link to post: https://androidstudio.googleblog.com/2020/12/android-emulator-apple-silicon-preview.html

**Comment by elliotsayes** [comment]
The emulator is now available in the AVD Manager: https://github.com/google/android-emulator-m1-preview

Is there any issue tracking Android Studio for Apple Silicon (native arm64)?

**Comment by ThatGuySam** [comment]
It looks like the are 2 issues on Google's issue tracking matching "Apple Silicon" and 22 issues matching "M1"

Android Studio "Apple Silicon" - https://issuetracker.google.com/issues?q=componentid:192708%20apple%20silicon
Android Studio "M1" - https://issuetracker.google.com/issues?q=componentid:192708%20m1

There doesn't seem to be a central task for native Apple SIlicon support, that I can find, but those issues should at least be a place to start.

**Comment by radko93** [comment]
There's an update from Google stating that there is some worki going on:
https://issuetracker.google.com/issues/179062806#comment13

**Comment by Jeyanthinath** [comment]
There is a canary build now available, supporting native m1 mac

https://androidstudio.googleblog.com/2021/04/android-studio-arctic-fox-canary-15.html

**Comment by hannesa2** [comment]
I tested it and it runs very fast after I cleaned up my repo `git clean -xdf` to remove Gradle Java link to an other java. Reopen project and tata ! ..... super fast ! (Before it was using x86 java for build)

The only problem is that the terminal is unusable now https://issuetracker.google.com/issues/188075900
