### ISSUE TITLE
Plogue Bidule

### ISSUE THREAD

**Issue by Kurville** [ThatGuySam/doesitarm#480]
**The official name of the app**
Plogue Bidule

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Full Native Support (Universal build)

**Proposed App Category**
Audio (Music)

**An Official App Download Page**
https://plogue.com/downloads.html

**Full Screenshot with the App and Activity Monitor (if self reporting)**

![bidule](https://user-images.githubusercontent.com/29205070/103933527-885bf380-50f1-11eb-80c5-b4734d92d614.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like we need someone with an M1 to provide a screenshot. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by Kurville** [comment]
Updated with screenshot.


Le 2021-01-07 13:05, « Sam Carlton » a écrit :


Thanks for the App Request!

Looks like we need someone with an M1 to provide a screenshot.

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version.

You can find an example on #358<https://github.com/ThatGuySam/doesitarm/issues/358>

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/plogue-bidule/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
