### ISSUE TITLE
GraphicConverter

### ISSUE THREAD

**Issue by Kurville** [ThatGuySam/doesitarm#483]
Replace the text inside the {}'s with your own. 

For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/358

**The official name of the app**
{GraphicConverter}

**Is there a supported version available on a stable release channel?**
{Yes}

**Proposed App Status**
{Full Native Support (Universal build)}

**Proposed App Category**
{Graphics (Photo Tools)}

**Related Issue Tracker Link or discussion**
{This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes.}

**An Official App Download Page**
{https://www.lemkesoft.de/en/products/graphicconverter/download/ }

**Additional context**
{Add any other context or screenshots about the app request here.}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{As screenshot with Activity Monitor open showing the App's architecture type}

**Comment by raphaelgurtner** [comment]
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/24231518/103333765-4981ca00-4a6f-11eb-8ca2-a283661997bd.png">

Universal Binary since [version 11.3.1](https://www.lemkesoft.de/en/products/graphicconverter/overview-of-new-features-and-versions/) . Can only report from an Intel mac, but Silicon ([https://github.com/DigiDNA/Silicon](https://github.com/DigiDNA/Silicon)) reports Universal Binary as well.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/graphicconverter/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
