### ISSUE TITLE
WebStorm

### ISSUE THREAD

**Issue by shatyuka** [ThatGuySam/doesitarm#484]
**The official name of the app**
WebStorm

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**An Official App Download Page**
https://www.jetbrains.com/webstorm/download/#section=mac

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/webstorm/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
