### ISSUE TITLE
PyCharm 2020.3.2 supports  Apple Silicon

### ISSUE THREAD

**Issue by ngloom** [ThatGuySam/doesitarm#485]
**The official name of the app**
Pycharm 

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
Yes, Full Native Apple Silicon Support

**Related Issue Tracker Link or discussion**
unknown

**An Official App Download Page**
https://www.jetbrains.com/pycharm/download/#section=mac

**Additional context**
https://blog.jetbrains.com/2020/12/30/pycharm-2020-3-2-supports-apple-silicon/

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info]
nope

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/pycharm/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
