### ISSUE TITLE
CodeRunner?

### ISSUE THREAD

**Issue by Juhnkerg** [ThatGuySam/doesitarm#486]
Replace the text inside the {}'s with your own. 

For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/358

**The official name of the app**
{What's the full official name of the app}

**Is there a supported version available on a stable release channel?**
{Yes/No}

**Proposed App Status**
{What's the current app status based off of current discussion or testing
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend}

**Proposed App Category**
{What category should the app go under}

**Related Issue Tracker Link or discussion**
{This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes.}

**An Official App Download Page**
{This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site.}

**Additional context**
{Add any other context or screenshots about the app request here.}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{As screenshot with Activity Monitor open showing the App's architecture type}

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by vincentardern** [comment]
**The official name of the app** Expandrive

**Is there a supported version available on a stable release channel?** Not sure.

**Proposed App Status** Has a Big Sur icon in the latest version, but not clear if AS is supported or not.

**Proposed App Category** Cloud files?

**Related Issue Tracker Link or discussion** https://www.expandrive.com/release-notes/expandrive/

**An Official App Download Page** https://www.expandrive.com/download-expandrive/

**Additional context** I can't check this myself yet.

**Full Screenshot with the App and Activity Monitor(if self reporting) or Silicon Info** I can't check this myself yet.

**Comment by iwa** [comment]
From what I have tested, the program seems to be running fine, via Rosetta 2

> ✳️ Yes, works via Rosetta 2

Download via [the official website](https://coderunnerapp.com) or Mac App Store apparently
_(tests on the web version)_

![Screen Shot 2021-03-24 at 19 37 51](https://user-images.githubusercontent.com/19956672/112365858-6d545500-8cd8-11eb-856e-e03fc5621b30.png)

**Comment by ThatGuySam** [comment]
Thanks @iwa! 

This is app is now Ready to Add! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/coderunner/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
