### ISSUE TITLE
SeaDrive 2.0.10

### ISSUE THREAD

**Issue by steve1878** [ThatGuySam/doesitarm#489]
Replace the text inside the {}'s with your own. 

For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/358

**The official name of the app**
SeaDrive

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
Yes, works via Rosetta 2 as of v2.0.10

**Related Issue Tracker Link or discussion**
https://forum.seafile.com/t/seadrive-2-0-8-is-released-support-for-macos-11/13199/25

**An Official App Download Page**
https://www.seafile.com/en/download/

**Additional context**
Corresponding pull request #488

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{As screenshot with Activity Monitor open showing the App's architecture type}

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/seadrive/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
