### ISSUE TITLE
Firefox

### ISSUE THREAD

**Issue by ecnelises** [ThatGuySam/doesitarm#49]
**The official name of the app**
Firefox

**An Official App Download Link**
- Stable: https://www.mozilla.org/firefox/new/
- Beta & nightly: https://www.mozilla.org/en-US/firefox/channel/desktop/

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

Is this an update to the existing page?
https://doesitarm.com/app/firefox/

**Comment by ecnelises** [comment]
Ah, just saw it. Thanks.
