### ISSUE TITLE
restic (backup software via Homebrew)

### ISSUE THREAD

**Issue by yonomitt** [ThatGuySam/doesitarm#492]
**The official name of the app**
restic

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
I believe it doesn't work at all, as it relies on Go

**Proposed App Category**
Homebrew, backup software

**Related Issue Tracker Link or discussion**
Restic: https://github.com/restic/restic/issues/3159
Go: https://github.com/golang/go/issues/42700

**An Official App Download Page**
Via Homebrew or:
https://restic.readthedocs.io/en/stable/020_installation.html

**Additional context**
This is available via Homebrew, but relies on Go to be compatible first.

**Comment by yonomitt** [comment]
I just noticed that on Homebrew's website for restic that they have an `arm64_big_sur` bottle for restic: https://formulae.brew.sh/formula/restic#default

It looks like this means an Apple Silicon binary will be installed directly (as opposed to building it).

Here is a screenshot of my installation output:

<img width="1241" alt="Screen Shot 2021-01-05 at 12 08 32" src="https://user-images.githubusercontent.com/8521453/103639521-c1a82e00-4f4e-11eb-8013-16efba7e7473.png">

**Comment by yonomitt** [comment]
Here's a screenshot of it in Activity Monitor showing that it runs natively:

<img width="659" alt="Screen Shot 2021-01-05 at 12 31 43" src="https://user-images.githubusercontent.com/8521453/103641410-008bb300-4f52-11eb-90d4-651073d026f5.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/restic/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
