### ISSUE TITLE
VisualGrep

### ISSUE THREAD

**Issue by dafi** [ThatGuySam/doesitarm#493]
**The official name of the app**
[VisualGrep](https://apps.apple.com/us/app/visualgrep/id597887722?mt=12)

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Utility, File Text Finder

**Related Issue Tracker Link or discussion**
[GitHub issue - Apple Silicon support](https://github.com/visualgrep/app/issues/46)

**An Official App Download Page**
[Mac App Store](https://apps.apple.com/us/app/visualgrep/id597887722?mt=12)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![am](https://user-images.githubusercontent.com/84500/103454998-91138a80-4ce9-11eb-9ac9-2909c0c6f838.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/visualgrep/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
