### ISSUE TITLE
WebTorrent

### ISSUE THREAD

**Issue by greensnow24** [ThatGuySam/doesitarm#494]
**The official name of the app**
 web torrent

**Is there a supported version available on a stable release channel?**
 No

**Proposed App Status**
 not ported to apple silicon yet 

**Proposed App Category**
 productivity tools 

**Related Issue Tracker Link or discussion**
 https://github.com/webtorrent/webtorrent/issues 

**An Official App Download Page**
 https://webtorrent.io/desktop/ 

**Additional context**
 webtorrent-cli can be installed using npm.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Next, we'll need someone with an M1 to provide a screenshot. 

This will tell us if the app works via Rosetta 2.

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by diddledan** [comment]
Works via Rosetta 2

<img width="1440" alt="Screenshot 2021-01-13 at 15 31 02" src="https://user-images.githubusercontent.com/147548/104472969-67ddde80-55b4-11eb-8bb2-6e9a95e530e2.png">

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.
