### ISSUE TITLE
Anki

### ISSUE THREAD

**Issue by bharadwaj6** [ThatGuySam/doesitarm#495]
**The official name of the app**
[Anki](https://apps.ankiweb.net)

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Yes, works via Rosetta 2

**Proposed App Category**
Productivity Tools

**An Official App Download Page**
https://apps.ankiweb.net

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1092" alt="Screenshot 2021-01-02 at 16 29 36" src="https://user-images.githubusercontent.com/1695154/103455968-b61ef200-4d17-11eb-954b-ad2aa884591f.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/anki/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by LapisLazulis** [comment]
2.1.50 added native support for M1 Macs.

https://betas.ankiweb.net/anki2.1.50.html

**Comment by bharadwaj6** [comment]
It's available in the stable version as of 2.1.52 available at their homepage: https://apps.ankiweb.net/

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/anki/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
