### ISSUE TITLE
Add Zwift

### ISSUE THREAD

**Issue by steve1878** [ThatGuySam/doesitarm#497]
Replace the text inside the {}'s with your own. 

For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/358

**The official name of the app**
Zwift

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Yes, works via Rosetta 2 as of v1.0 (25)

**Proposed App Category**
Entertainment and Media Apps

**Related Issue Tracker Link or discussion**
https://forums.zwift.com/t/m1-apple-silicon-compatibility/514491/81

**An Official App Download Page**
https://www.zwift.com/eu-de/download

**Additional context**
{Add any other context or screenshots about the app request here.}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
[Screenshot](https://raw.githubusercontent.com/steve1878/images_does_it_arm/main/zwift_1.0_25.png)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/zwift/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
