### ISSUE TITLE
Autocad works in Rosetta.

### ISSUE THREAD

**Issue by Mask3dMan** [ThatGuySam/doesitarm#499]
**The official name of the app**
AutoCad 2021

**Is there a supported version available on a stable release channel?**
Y

**Proposed New App Status**
Working in Rosetta

**Additional context**
Tested with heavy files. Works as expected.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
https://imgur.com/XolYDfq

**Comment by ThatGuySam** [comment]
Verification screenshot
![image](https://user-images.githubusercontent.com/2830379/103577015-a7604880-4e99-11eb-8611-407b41ea8a09.png)

**Comment by ThatGuySam** [comment]
Thanks for the Update Request @Mask3dMan 

Update is now live on the site! 

https://doesitarm.com/app/autocad/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
