### ISSUE TITLE
Vienna RSS

### ISSUE THREAD

**Issue by barijaona** [ThatGuySam/doesitarm#50]
**The official name of the app**
Vienna

**Proposed App Status**
✅ Full Native Apple Silicon Support 

**Related Issue Tracker Link or discussion**
https://forums.cocoaforge.com/viewtopic.php?f=18&t=26983

**An Official App Download Link**
https://github.com/ViennaRSS/vienna-rss/releases/latest
https://bintray.com/viennarss/vienna-rss/vienna-rss

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

This looks great!

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/vienna

Feel free to browse through the other issues to help with missing info on other apps.
