### ISSUE TITLE
Camo Studio

### ISSUE THREAD

**Issue by hlynursmari1** [ThatGuySam/doesitarm#500]
**The official name of the app**
Camo Studio

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity

**Related Issue Tracker Link or discussion**
Release notes: https://reincubate.com/support/camo/release-notes/#1.1.3.122

**An Official App Download Page**
https://reincubate.com/camo/

**Additional context**

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![camo_studio_running_on_apple_silicon](https://user-images.githubusercontent.com/7827436/103487466-9d890780-4dfd-11eb-849d-3f4c3c76d5c8.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/camo-studio/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
