### ISSUE TITLE
MongoKitten

### ISSUE THREAD

**Issue by Joannis** [ThatGuySam/doesitarm#502]
**The official name of the app**
[MongoKitten](https://apps.apple.com/us/app/id1484086700)

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Developer Tools

**An Official App Download Page**
[App Store](https://apps.apple.com/us/app/id1484086700)

**Additional context**
{Add any other context or screenshots about the app request here.}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1680" alt="Screenshot 2021-01-04 at 11 57 21" src="https://user-images.githubusercontent.com/1951674/103528338-0f0b9900-4e84-11eb-9bd1-cf9841385a98.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/mongokitten/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
