### ISSUE TITLE
brave browser

### ISSUE THREAD

**Issue by nsklaus** [ThatGuySam/doesitarm#503]
**The official name of the app**
{ [Brave](https://brave.com) }

**Is there a supported version available on a stable release channel?**
{Yes}

**Proposed App Status**
{✅ Yes, Full Native Apple Silicon Support}

**Proposed App Category**
{ browser }

**Comment by raphaelgurtner** [comment]
officially supported:

**An Official App Download Page**
[https://brave.com/#mac-options](https://brave.com/#mac-options)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/brave-browser/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
