### ISSUE TITLE
Qt (Homebrew Formula)

### ISSUE THREAD

**Issue by erinacio** [ThatGuySam/doesitarm#507]
**The official name of the app**
qt (as in homebrew-core)

**Is there a supported version available on a stable release channel?**
Yes (almost, with patch from homebrew maintainers)

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**Related Issue Tracker Link or discussion**
https://github.com/Homebrew/homebrew-core/pull/67170

**An Official App Download Page**
https://formulae.brew.sh/formula/qt

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

Qt is a framework, so I created a new hello world app and show it's architecture.

<img width="1401" alt="202117-5946" src="https://user-images.githubusercontent.com/15362012/103853797-dff66100-50e9-11eb-88f1-8d9d72b53fc8.png">

**Comment by ThatGuySam** [comment]
Good catch! 

Update is now live

https://doesitarm.com/formula/qt/

**Comment by erinacio** [comment]
> Good catch!
> 
> Update is now live
> 
> https://doesitarm.com/formula/qt/

The detailed description was not updated. It's still showing "Fails running find_sdk.py late in the build. (logs, full make log)
".

**Comment by ThatGuySam** [comment]
Looks like I need to modify the rendering rules. I'll add it to my to do list
