### ISSUE TITLE
TwistedWave

### ISSUE THREAD

**Issue by Kurville** [ThatGuySam/doesitarm#508]
**The official name of the app**
TwistedWave

**Is there a supported version available on a stable release channel?**
Yes (automatic update to universal build if beta check is enabled)

**Proposed App Status**
Native, universal build

**Proposed App Category**
Audio (music)

**An Official App Download Page**
https://twistedwave.com/mac

**Full Screenshot with the App and Activity Monitor**

![twistedwave](https://user-images.githubusercontent.com/29205070/103936683-bb07eb00-50f5-11eb-84ff-6d14b7a6de9e.png)

<img width="424" alt="tw2" src="https://user-images.githubusercontent.com/29205070/103937089-44b7b880-50f6-11eb-985f-12ff3fc71842.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/twistedwave/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
