### ISSUE TITLE
XLD

### ISSUE THREAD

**Issue by Kurville** [ThatGuySam/doesitarm#509]
**The official name of the app**
XLD

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Native, universal build

**Proposed App Category**
Audio (Music)

**Related Issue Tracker Link or discussion**
https://sourceforge.net/p/xld/tickets/

**An Official App Download Page**
https://sourceforge.net/projects/xld/

**Full Screenshot with the App and Activity Monitor**

![xld](https://user-images.githubusercontent.com/29205070/103939679-26ec5280-50fa-11eb-8a34-530d99eb9ea4.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/x-lossless-decoder-xld/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
