### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by iKrupp** [ThatGuySam/doesitarm#51]
**The official name of the app**
Slack

**An Official App Download Link**
https://slack.com/downloads/mac

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ThatGuySam** [comment]
Looks like Slack beta supports Apple Silicon natively
https://twitter.com/SlackEng/status/1326237727667314688

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/slack/

Feel free to browse through the other issues to help with missing info on other apps.

**Comment by tinymachine** [comment]
FYI the current stable release also works fine on my M1 MacBook Air via Rosetta 2, so I think the current status (`🚫 Not yet, but it's currently in beta`) isn't quite accurate. BTW thanks for all your work on this, @ThatGuySam!

**Comment by ThatGuySam** [comment]
@tinymachine Updated!

**Comment by zelliot** [comment]
I don't know when it switched over but Slack stable appears to be running natively on M1:
![image](https://user-images.githubusercontent.com/1056111/108442003-61750d80-72aa-11eb-8397-f8158712427c.png)

**Comment by ThatGuySam** [comment]
Update is live!

https://doesitarm.com/app/slack/
