### ISSUE TITLE
zbrush m1芯片软件测试

### ISSUE THREAD

**Issue by 1321wads** [ThatGuySam/doesitarm#512]

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by danielmeskin** [comment]
I haven't got a copy of zbush to test, so I'm going off the developer's information here. 

The official name of the app: Zbrush

Is there a supported version available on a stable release channel? Yes

Proposed App Status: ✳️

Proposed App Category: Photo and Graphic Tools

Related Issue Tracker Link or discussion: https://support.pixologic.com/article/447-support-for-apple-silicon

An Official App Download Page: http://pixologic.com/zbrush/downloadcenter/#

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/zbrush/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
