### ISSUE TITLE
Tuple.app request

### ISSUE THREAD

**Issue by austinbv** [ThatGuySam/doesitarm#514]
Replace the text inside the {}'s with your own. 

For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/358

**The official name of the app**
Tuple.app

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ 

**Proposed App Category**
developer-tools

**Related Issue Tracker Link or discussion**
{This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes.}

**An Official App Download Page**
{This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site.}

**Additional context**
{Add any other context or screenshots about the app request here.}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{As screenshot with Activity Monitor open showing the App's architecture type}

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Next we'll need someone with an M1 to provide a screenshot. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by austinbv** [comment]
![Activity monitor](https://imgur.com/a/w4vCsmp)

**Comment by austinbv** [comment]
![Tuple](https://i.imgur.com/PjnQWwX.png)

**Comment by ThatGuySam** [comment]
Thanks, @austinbv!

We'll use this for the download link: 
https://tuple.app/

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.
