### ISSUE TITLE
VisualDiffer

### ISSUE THREAD

**Issue by dafi** [ThatGuySam/doesitarm#515]
**The official name of the app**
[VisualDiffer](https://visualdiffer.com/)

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
[VisualDiffer issue tracker- Apple Silicon support](https://visualdiffer.com/mantis/view.php?id=334)

**An Official App Download Page**
[Mac App Store](https://apps.apple.com/us/app/visualdiffer/id412386481?mt=12)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![VisualDifferSilicon](https://user-images.githubusercontent.com/84500/104150940-d6b40f80-53db-11eb-85a4-88078f5801b0.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/visualdiffer/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
