### ISSUE TITLE
Does Navicat suport Apple silicon?

### ISSUE THREAD

**Issue by wejectchen** [ThatGuySam/doesitarm#516]
**The official name of the app**
Navicat Premium 15

**Is there a supported version available on a stable release channel?**
No information on official website
[https://www.navicat.com/](https://www.navicat.com/)

**Proposed App Status**
no information

**Proposed App Category**
Developer tool

**An Official App Download Page**
[https://www.navicat.com/en/download/navicat-premium](https://www.navicat.com/en/download/navicat-premium)

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

Looks like there's already an issue for this at #161.

Feel free to add any missing info there
