### ISSUE TITLE
Burn

### ISSUE THREAD

**Issue by Marc66** [ThatGuySam/doesitarm#518]
**The official name of the app**
Burn

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
https://burn-osx.sourceforge.io/Pages/English/news.html
https://sourceforge.net/p/burn-osx/news/

**An Official App Download Page**
https://burn-osx.sourceforge.io/Pages/English/home.html

**Additional context**
![burnwindowdata](https://user-images.githubusercontent.com/11850067/104294290-4cdd7280-54bf-11eb-82d4-7473f08dc673.png)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1977" alt="Capture d’écran 2021-01-12 à 10 16 09" src="https://user-images.githubusercontent.com/11850067/104294368-5f57ac00-54bf-11eb-89b6-e9c7090fab45.png">

**Comment by ThatGuySam** [comment]
This looks excellent!

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/burn-for-mac/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
