### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by iKrupp** [ThatGuySam/doesitarm#52]
**The official name of the app**
Telegram

**An Official App Download Link**
https://desktop.telegram.org/

**Comment by techfanseric** [comment]
👍

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ftpmorph** [comment]
I can add some details here...

**Is there a supported build available on a public/release channel?**

No.

**Proposed App Status**

Working perfectly via Rosetta 2 but no ARM build yet.

**Proposed App Category**

Social and communication.

**Tracker:**

Official blog: https://telegram.org/blog

**Official download link**

https://macos.telegram.org/

**Screenshot with Activity Monitor**

<img width="611" alt="Screenshot 2020-11-24 at 8 07 11 pm" src="https://user-images.githubusercontent.com/67348935/100145726-a991b900-2e90-11eb-8fc1-039706efb73d.png">

**Comment by ThatGuySam** [comment]
This is ready to add. 

* [Telegram](https://desktop.telegram.org/) - ✳️ Yes, works via Rosetta 2 - [Source](https://github.com/ThatGuySam/doesitarm/issues/52#issuecomment-733205746)

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/telegram/

Feel free to browse through the other [issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by KovalevArtem** [comment]
![image](https://user-images.githubusercontent.com/36500228/100552335-aedb7300-3297-11eb-8554-313e24f8f6ed.png)
https://t.me/tgstable/532

**Comment by ftpmorph** [comment]
I'll stick a PR in.

<img width="371" alt="Screenshot 2020-11-29 at 8 34 33 pm" src="https://user-images.githubusercontent.com/67348935/100552951-92810b80-3282-11eb-83ea-2a1d0d42da46.png">

<img width="246" alt="Screenshot 2020-11-29 at 8 34 46 pm" src="https://user-images.githubusercontent.com/67348935/100552965-a9276280-3282-11eb-8b92-53c01d017e16.png">
