### ISSUE TITLE
App request: Messenger

### ISSUE THREAD

**Issue by mingyli** [ThatGuySam/doesitarm#520]
**The official name of the app**
Facebook Messenger: <https://www.messenger.com/desktop>

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Yes, works via Rosetta 2

**Proposed App Category**
Social and Communication Apps

**Related Issue Tracker Link or discussion**
None that I can find

**An Official App Download Page**
<https://www.messenger.com/desktop>

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/5828246/104393406-3eac4800-54f9-11eb-9800-3f7d9e70c2bf.png">

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/facebook-messenger-desktop/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by ayechief** [comment]
v153 - still intel/rosetta

**Comment by quanghd96** [comment]
Native from 158.0.0.25.216 (391336574)
![image](https://user-images.githubusercontent.com/15941383/185838629-b95c2735-5750-463e-b7d0-7e0770641204.png)
