### ISSUE TITLE
MySQL 5.7 (homebrew)

### ISSUE THREAD

**Issue by yooouuri** [ThatGuySam/doesitarm#521]
**The official name of the app**
MySQL 5.7 (homebrew)

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**Related Issue Tracker Link or discussion**
https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/mysql@5.7.rb#L16
`arm64_big_sur` is available

**An Official App Download Page**
-

**Additional context**
1. brew install mysql@5.7
2. echo 'export PATH="/opt/homebrew/opt/mysql@5.7/bin:$PATH"' >> ~/.zshrc
3. open new terminal and the mysql command is available

![image](https://user-images.githubusercontent.com/12934957/104472239-09b4f980-55bc-11eb-81f1-28e429ac6250.png)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
> Darwin Youris-Mac-mini.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:40:21 PST 2020; root:xnu-7195.60.75~1/RELEASE_ARM64_T8101 arm64

![image](https://user-images.githubusercontent.com/12934957/104471885-a925bc80-55bb-11eb-8c7c-438954321dd7.png)

**Comment by ThatGuySam** [comment]
Good find! 

Update is now live

https://doesitarm.com/formula/mysql@5.7/
