### ISSUE TITLE
Royal TSX is Native support for Macs with Apple M1

### ISSUE THREAD

**Issue by wejectchen** [ThatGuySam/doesitarm#523]
**The official name of the app**
{Royal TSX}

**Is there a supported version available on a stable release channel?**
{Yes/No}

**Proposed App Status**
{ Native support }

**Proposed App Category**
{Developer Tools}

**Related Issue Tracker Link or discussion**
{https://royalapps.com/ts/mac/features-beta}

**An Official App Download Page**
{https://royalapps.com/ts/mac/features-beta}

**Additional context**
![image](https://user-images.githubusercontent.com/40900174/104672692-392e4800-571b-11eb-96b4-ac8d00510154.png)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![image](https://user-images.githubusercontent.com/40900174/104672729-4f3c0880-571b-11eb-917a-0749457954b2.png)

**Comment by ThatGuySam** [comment]
@wejectchen Thanks for the App Request! 

Any word on when support will come out of beta?

**Comment by wejectchen** [comment]
![image](https://user-images.githubusercontent.com/40900174/104980638-fed9e900-5a41-11eb-99f0-cef1483b2711.png)

**but Public beta now available ** 

Download page :  https://www.royalapps.com/ts/mac/features-beta

**Comment by ThatGuySam** [comment]
2022 yikes. We can post it with a link to the beta. 

Do we know if the stable release works via Rosetta 2?

**Comment by moffpage** [comment]
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/33549573/123576810-674ca380-d7f4-11eb-8e6a-7822e8cdd035.png">
Stable release 5.0 downloads as a Universal app and runs as a native app

**Comment by ThatGuySam** [comment]
Fantastic, @moffpage!

App is now live on the site! 

https://doesitarm.com/app/royal-tsx/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
