### ISSUE TITLE
VLC media player gained native support for Apple Silicon

### ISSUE THREAD

**Issue by fkuehne** [ThatGuySam/doesitarm#527]
Replace the text inside the {}'s with your own. 

For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/358

**The official name of the app**
VLC media player

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
Yes, Full Native Apple Silicon Support

**Related Issue Tracker Link or discussion**
https://www.videolan.org/news.html#news-2021-01-12

**An Official App Download Page**
https://www.videolan.org/vlc/download-macosx.html

**Additional context**
{Add any other context or screenshots about the app request here.}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
Will follow if needed.

**Comment by ThatGuySam** [comment]
@fkuehne Thanks for the report! 

Update is live! 

https://doesitarm.com/app/vlc/
