### ISSUE TITLE
Tunnelblick

### ISSUE THREAD

**Issue by iKrupp** [ThatGuySam/doesitarm#53]
**The official name of the app**
Tunnelblick

**An Official App Download Link**
https://tunnelblick.net/downloads.html

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/tunnelblick/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
