### ISSUE TITLE
Citrix Webex Meetings

### ISSUE THREAD

**Issue by davidebeaman** [ThatGuySam/doesitarm#530]
When installing via the Webex app, Citrix Webex meetings launches via Apple Silicon. 
<img width="377" alt="Screen Shot 2021-01-20 at 4 08 35 PM" src="https://user-images.githubusercontent.com/60242466/105235273-c74e6800-5b39-11eb-95f1-ddf79c904a8e.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/cisco-webex-meetings/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by imrefazekas** [comment]
The installer still requires Rosetta2!

**Comment by ThatGuySam** [comment]
@imrefazekas Is the app itself still native though?

**Comment by mngrant** [comment]
Unable to reproduce. I can't find any installer or DMG with Apple Silicon build. I've dug through the new Webex.app they deploy from https://www.webex.com/downloads but that includes the rebranded WebEx Teams app.

Can we document how this process works and what version?

**Comment by davidebeaman** [comment]
When downloading the standard Webex app, if you use Webex meetings, then it launches in a separate application, which is Apple Silicon, as noted above. It may depend on how your organization launches Webex meetings or Webex Teams. 
Either way, the silicon version is located at ~/Library/Application Support/WebEx Folder/MC_41.2.4.15

**Comment by mngrant** [comment]
No luck pulling from an existing machine.

Still not clear on deploy or install process from webex.com

The old PKG install (at the bottom of the download page) and current download DMG (top of download page) both require Rosetta to open.

When copying the App Support folder from a working install on my 2020 Mac Pro with version 41.2.4.15 it requires Rosetta as well.

![Image 2-10-21 at 4 04 PM](https://user-images.githubusercontent.com/68086927/107578678-a9fd3e80-6bb9-11eb-8ce1-0ed9a0c54fc7.jpg)
![Image 2-10-21 at 4 00 PM](https://user-images.githubusercontent.com/68086927/107578681-aa95d500-6bb9-11eb-92b7-d57119e1ed59.jpg)

**Comment by mngrant** [comment]
Got it!

The currently listed installers from webex.com/downloads are x86 only.

To get the Apple Silicon installer you must join a meeting in progress to then trigger the install. This downloads a different (smaller) PKG (Webex.pkg and is around 7.3MB) that installs without admin requirements and deploys to the MC_41.2.4.15 folder

Here is one from our subdomain - https://mono.webex.com/client/WBXclient-41.2.4-15/mac/arm64/Webex.pkg

I've tested other known domains (Apple's even -- https://appleinc.webex.com/) and those aren't working. I'm not sure what enables this download.

![Screen Shot 2021-02-10 at 4 08 50 PM](https://user-images.githubusercontent.com/68086927/107579668-17f63580-6bbb-11eb-8211-9396d525cb45.png)
