### ISSUE TITLE
kitty

### ISSUE THREAD

**Issue by gucheen** [ThatGuySam/doesitarm#531]
**The official name of the app**
kitty

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
https://github.com/kovidgoyal/kitty/issues/3238

**An Official App Download Page**
https://formulae.brew.sh/cask/kitty#default
https://github.com/kovidgoyal/kitty/releases

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![image](https://user-images.githubusercontent.com/1382472/105271204-0f20ce00-5bd2-11eb-97bd-a37f6b05a145.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by hedefalk** [comment]
I can't seem to get any pre-packaged arm64 for kitty?

I've tried

`arch -arm64 brew install --cask kitty`

as well as the dmg linked here. But it's all:


![image](https://user-images.githubusercontent.com/116520/110095135-deb97b80-7d9c-11eb-9828-237dffdcc752.png)

**Comment by gucheen** [comment]
@hedefalk my bad, actually it needs to be built from source to get a native arm64 binary of kitty.
As mentioned in https://github.com/kovidgoyal/kitty/issues/3238

**Comment by hedefalk** [comment]
> @hedefalk my bad, actually it needs to be built from source to get a native arm64 binary of kitty.
> As mentioned in [kovidgoyal/kitty#3238](https://github.com/kovidgoyal/kitty/issues/3238)

Yeah, I've been trying that too, but can't seem to get it right :)
