### ISSUE TITLE
Google Drive File System

### ISSUE THREAD

**Issue by hfcorriez** [ThatGuySam/doesitarm#534]
Replace the text inside the {}'s with your own. 

For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/358

**The official name of the app**
Google Drive File System

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
🚫 No, not yet supported only works on Intel-based Macs

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
https://9to5google.com/2021/01/22/google-drive-file-stream-m1/

**An Official App Download Page**
https://www.google.com/drive/download/

**Additional context**
It will publish at April

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{As screenshot with Activity Monitor open showing the App's architecture type}

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/google-drive-file-stream/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
