### ISSUE TITLE
Maccy-Lightweight clipboard manager for macOS

### ISSUE THREAD

**Issue by liuyuanOUC** [ThatGuySam/doesitarm#536]
Thanks @p0deje, the developer of Maccy, and hope more people like this amazing clipboard manager.

**The official name of the app**
Maccy

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
https://github.com/p0deje/Maccy/issues/199

**An Official App Download Page**
https://maccy.app/

**Additional context**
https://maccy.app/

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
None

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/maccy/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
