### ISSUE TITLE
XAMPP

### ISSUE THREAD

**Issue by Aaditya-Pyarla** [ThatGuySam/doesitarm#539]
Replace the text inside the {I have been working on PHP and it seems to be that XAMPP isn't yet supprted in Apple Silicon}'s with your own. 

**XAMPP**
XAMPP is a native sever for PHP and Perl in order to run a test websites and webApps

**There is no supported version for Apple Silicon**

**Not yet aware of any Stats about this server**

**Development & Developer Tools**

**There was no related issue**

**An Official App Download Page**

**Currently not having any context or screenshots**

I am really in need of that server in order to test my websites

**Comment by ThatGuySam** [comment]
Looks like it runs based on this video
https://www.youtube.com/watch?v=EbwWewsIs8s&feature=emb_title

Since they haven't mentioned anything about Apple Silicon in their release notes let's assume it running via Rosetta 2
https://www.apachefriends.org/blog.html
https://www.apachefriends.org/feed.xml

**Comment by ThatGuySam** [comment]
We'll use this as the download link
https://www.apachefriends.org/download.html

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/xampp/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
