### ISSUE TITLE
GIT

### ISSUE THREAD

**Issue by ryannathanwilson** [ThatGuySam/doesitarm#54]
The version control thing!

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

That sounds familiar. I’ll Google it to see if it’s popular enough. 


Also...

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ifsheldon** [comment]
No need to google, just see the first three letters of GitHub! Also, check the chart in this [tracking issue of homebrew](https://github.com/Homebrew/brew/issues/7857), which includes most of most-wanted libs and commandline tools that developers use

**Comment by ThatGuySam** [comment]
Looks like the homebrew guys aren't sure of the status yet either

**Comment by ThatGuySam** [comment]
Is that Terminal running via Rosetta 2 [Example](https://www.notion.so/Run-x86-Apps-including-homebrew-in-the-Terminal-on-Apple-Silicon-8350b43d97de4ce690f283277e958602)

**Comment by pawelostr** [comment]
Just tested, working in both arm terminal and Rosetta terminal. Also Github Desktop works (Under Rosetta)

**Comment by pawelostr** [comment]
> Just tested, working in both arm terminal and Rosetta terminal. Also Github Desktop works (Under Rosetta)

<img width="745" alt="Zrzut ekranu 2020-11-19 o 19 48 46" src="https://user-images.githubusercontent.com/26488603/99709979-48d53b80-2aa0-11eb-9d1b-ef1da21c9030.png">

**Comment by ThatGuySam** [comment]
That's just beautiful! 

Status: ✅ Yes, Full Native Apple Silicon Support

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
We'll use this as the download link
https://git-scm.com/download/mac

**Comment by ThatGuySam** [comment]
App is now live on the site!

https://doesitarm.com/app/git/

Feel free to browse through the other issues to help with missing info on other apps.

**Comment by richiksc** [comment]
@pawelostr Is that the version of Git that is bundled with Xcode, installed from Homebrew, or built from source? If it's the version of Git with Xcode, can you tell me the `git --version`? Usually the Xcode bundled versions are a few versions behind the latest, but maybe they updated it for Xcode 12.

**Comment by pawelostr** [comment]
@richiksc it's from Xcode, I didn't put too much thought in it, run git, prompted me to install I think Xcode CLI, I did, it runs.

I can't for sure tell if it's arm or x86 version running (what is Apple git-128?), but here's native Terminal:

<img width="592" alt="Zrzut ekranu 2020-11-23 o 08 15 04" src="https://user-images.githubusercontent.com/26488603/99936880-88cc4500-2d64-11eb-9ce5-dc6fde675895.png">

And Rosetta Terminal:

<img width="592" alt="Zrzut ekranu 2020-11-23 o 08 15 09" src="https://user-images.githubusercontent.com/26488603/99936911-9a155180-2d64-11eb-8136-e08c4c96f4ad.png">

**Comment by richiksc** [comment]
@pawelostr Alright, so it looks like it's running git v2.24, which is a few versions behind the latest v2.29. Apple-git is just their revision number, I'm guessing.

A really quick way to tell if a binary is Rosetta or native in terminal is to run

```bash
file $(which git)
```

**Comment by pawelostr** [comment]
@richiksc 

Im afraid the answer then is both ;)

<img width="711" alt="Zrzut ekranu 2020-11-23 o 08 26 30" src="https://user-images.githubusercontent.com/26488603/99937317-bb2a7200-2d65-11eb-8a22-c45771a0a6fd.png">

**Comment by richiksc** [comment]
@pawelostr that's great! It'll run natively in a standard terminal. I don't know the behavior of Rosetta terminal, however.

**Comment by pawelostr** [comment]
@richiksc I haven't really been using git or playing around with any tools (work to do + first Mac ever), but I've been using Homebrew (pretty sure it uses git) and a few tools in Rosetta terminal and so far it really was It Just Works™, so I'm really happy. I was a bit worried about Julia lang as it was the only cmd tool I needed that was in dmg, but I added some path to it somewhere and again - It Just Works™.

**Comment by jensmeindertsma** [comment]
@richiksc do you know how to update the bundled Git version to the latest version with Apple Silicon?

**Comment by richiksc** [comment]
> @richiksc do you know how to update the bundled Git version to the latest version with Apple Silicon?

@jensmeindertsma You can install the latest version natively with Homebrew.
