### ISSUE TITLE
iDrive Backup and Sync

### ISSUE THREAD

**Issue by vincentardern** [ThatGuySam/doesitarm#542]
**The official name of the app** iDrive Backup and Sync

**Is there a supported version available on a stable release channel?** System requirements are listed as 10.10 Yosemite, or greater. That implies that Big Sur is supported ~~but I personally cannot test~~ and it seems to be working for me.

**Proposed App Status** Working, app seems to be Apple Silicon native, but it might have components that are running through Rosetta 2...? See activity monitor.

**Proposed App Category** Backup apps, or utilities/productivity etc.

**Related Issue Tracker Link or discussion** https://www.idrive.com/release-info

**An Official App Download Page** https://www.idrive.com/online-backup-download

**Additional context** Has been working fine for me for a few days.

**Full Screenshot with the App and Activity Monitor(if self reporting) or Silicon Info** 
![screenshot](https://user-images.githubusercontent.com/4961411/107866441-d5439e80-6ed5-11eb-9d19-e9def58f31a1.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Next, we'll need someone with an M1 to provide a screenshot. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by vincentardern** [comment]
My M1 MBA has arrived and I've updated the original comment with new info.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/idrive/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
