### ISSUE TITLE
MongoDB doesn't have full native support yet

### ISSUE THREAD

**Issue by Endogen** [ThatGuySam/doesitarm#543]
**The official name of the app**
MongoDB

**Is there a supported version available on a stable release channel?**
No

**Proposed New App Status**
Yes, works via Rosetta 2

**Related Issue Tracker Link or discussion**
https://jira.mongodb.org/browse/SERVER-50115

**An Official App Download Page**
No M1 version available

**Additional context**
Currently MongoDB is listed with "Yes, Full Native Apple Silicon Support" which isn't true. Please correct it.

**Comment by ThatGuySam** [comment]
Thanks for the update! 

It is working in this video so he must be running it with Rosetta 2
https://www.youtube.com/watch?t=227&v=b_S3CjGRQis&feature=youtu.be

**Comment by Endogen** [comment]
Yes, he is running the terminal under Rosetta 2 and then can install MongoDB. But that means he is running MongoDB under Rosetta 2 also.

**Comment by ThatGuySam** [comment]
Updated! 

https://doesitarm.com/app/mongodb/

Good find! Feel free to browse around the site and report any other incorrect information you find!
