### ISSUE TITLE
Seashore 

### ISSUE THREAD

**Issue by leoplan2** [ThatGuySam/doesitarm#544]
**The official name of the app**
Seashore

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
✳️ Yes, works via Rosetta 2, an experimental M1 build is available

**Proposed App Category**
Photo and Graphic Tools

**Related Issue Tracker Link or discussion**
https://github.com/robaho/seashore/issues/139

**An Official App Download Page**
https://github.com/leoplan2/seashore/releases/tag/v2.5.10

**Additional context**
{Add any other context or screenshots about the app request here.}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1003" alt="Screen Shot 2021-02-02 at 13 47 56" src="https://user-images.githubusercontent.com/2043477/106654076-4346a800-655d-11eb-88b0-de923f134ae8.png">
<img width="246" alt="Screen Shot 2021-02-02 at 13 48 59" src="https://user-images.githubusercontent.com/2043477/106654181-683b1b00-655d-11eb-89d8-a8add1303e77.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/seashore/

I tweaked the verbiage a little so it stays relevant for future Apple Silicon processors (M2, M1X, M1Z, etc...)

Let me know when the native build is ready for prime time and we'll get the page updated. 

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by ThatGuySam** [comment]
@leoplan2 Looks like the creator of Seashore wants to support Apple Silicon but only has the capacity to do so after a rebuild in Swift, however, if the Github community wants to build and test a Universal build of the current version he would be willing to accept it as long as the quality is top-notch and it's thoroughly tested before he publishes it as to not damage his review reputation with Apple. 

https://github.com/robaho/seashore/issues/139#issuecomment-776329805

**Comment by ThatGuySam** [comment]
Updated for new Native Apple Silicon support! 

https://doesitarm.com/app/seashore
