### ISSUE TITLE
Visual Studio Code ARM support revoked from v1.53 

### ISSUE THREAD

**Issue by JeremyRitchie** [ThatGuySam/doesitarm#548]
**The official name of the app**
Visual Studio Code

**Is there a supported version available on a stable release channel?**
Noa

**Proposed New App Status**
Yes, works via Rosetta 2 (Native Apple Silicon Support via Insiders Build)

**Related Issue Tracker Link or discussion**
Release notes from 1.53:
https://code.visualstudio.com/updates/v1_53#_apple-silicon-insiders

**An Official App Download Page**
Insiders Build Link:
https://code.visualstudio.com/insiders/#osx

**Additional context**
{Add any other context or screenshots about the app request here.}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{As screenshot with Activity Monitor open showing the App's architecture type}

**Comment by tonyunreal** [comment]
https://github.com/microsoft/vscode/issues/106770#issuecomment-772789872

**Comment by ThatGuySam** [comment]
Updated! 

https://doesitarm.com/app/vs-code/
