### ISSUE TITLE
Waifu2x

### ISSUE THREAD

**Issue by leoplan2** [ThatGuySam/doesitarm#549]
**The official name of the app**
Waifu2x

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Photo and Graphic Tools

**Related Issue Tracker Link or discussion**

**An Official App Download Page**
https://github.com/nihui/waifu2x-ncnn-vulkan/releases/tag/20210102

**Additional context**
This is the Vulkan version of Waifu2x

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1090" alt="Screen Shot 2021-02-04 at 19 45 36" src="https://user-images.githubusercontent.com/2043477/106978265-8f424a00-6721-11eb-890b-89d65c0110f7.png">
<img width="1003" alt="Screen Shot 2021-02-04 at 19 46 51" src="https://user-images.githubusercontent.com/2043477/106978361-bdc02500-6721-11eb-986e-47600dc2fd7e.png">

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/waifu2x/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
