### ISSUE TITLE
Universal Build on hold.

### ISSUE THREAD

**Issue by compil3** [ThatGuySam/doesitarm#550]
**The official name of the app**
 [Visual Studio Code](https://code.visualstudio.com/) 

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✳️ Yes, works via Rosetta 2

**Related Issue Tracker Link or discussion**
https://github.com/microsoft/vscode/issues/106770#issuecomment-772789872 
  https://github.com/microsoft/vscode/issues/115646

**An Official App Download Page**
[https://code.visualstudio.com/Download](https://code.visualstudio.com/Download)

**Additional context**
There is a bug in macOS Big Sur 11.2 which affects nodejs, there is a fix in place and a Universal binary of VSCode is delayed for another iteration.

**Comment by ThatGuySam** [comment]
Updated! 

https://doesitarm.com/app/vs-code/
