### ISSUE TITLE
VS Code 1.53 does not arm

### ISSUE THREAD

**Issue by ameeno** [ThatGuySam/doesitarm#552]
**The official name of the app**
{VS Code}

**Is there a supported version available on a stable release channel?**
{No}

**Proposed New App Status**
{Yes, works via Rosetta 2 (Native for insiders 1.53)}

**Related Issue Tracker Link or discussion**
{
https://github.com/microsoft/vscode/issues/106770#issuecomment-774084371 
https://github.com/microsoft/vscode/issues/106770#issuecomment-774085589
}

**An Official App Download Page**
{Same as current}

**Additional context**
{previous to this version 1.53 works with rosetta as it is known, insiders works on arm as is known. doesitarm states v 1.53 stable works on arm. but MS pulled the darwin arm release until next version due to bug. therefor stable does not arm}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{As screenshot with Activity Monitor open showing the App's architecture type}
Screenshot below
<img width="1440" alt="Screenshot 2021-02-05 at 15 52 50" src="https://user-images.githubusercontent.com/388653/107056499-4db9a980-67ca-11eb-97f9-7bad2b53fcce.png">

**Comment by ThatGuySam** [comment]
Updated! 

https://doesitarm.com/app/vs-code/
