### ISSUE TITLE
Remote Buddy

### ISSUE THREAD

**Issue by felix-schwarz** [ThatGuySam/doesitarm#556]
**The official name of the app**
Remote Buddy

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Entertainment and Media Apps

**Related Issue Tracker Link or discussion**
https://www.iospirit.com/blog/2020/11/Remote-Buddy-2-Big-Sur-Apple-Silicon-Available

**An Official App Download Page**
https://www.iospirit.com/products/remotebuddy/download/

**Additional context**
![Bildschirmfoto 2021-02-06 um 17 12 51](https://user-images.githubusercontent.com/639669/107123580-9347a680-689e-11eb-98ab-86884f4acf20.png)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Bildschirmfoto 2021-02-06 um 17 10 46](https://user-images.githubusercontent.com/639669/107123559-6e533380-689e-11eb-87d9-f44130e3f6e6.png)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/remote-buddy/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
