### ISSUE TITLE
AppCleaner

### ISSUE THREAD

**Issue by mruszczyk** [ThatGuySam/doesitarm#559]
Replace the text inside the {}'s with your own. 

For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/358

**The official name of the app**
AppCleaner

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**Related Issue Tracker Link or discussion**
https://freemacsoft.net/appcleaner/

**An Official App Download Page**
https://freemacsoft.net/appcleaner/

**Additional context**
New update was posted today. Fully Apple Silicon Native.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1280" alt="Screen Shot 2021-02-08 at 4 45 35 PM" src="https://user-images.githubusercontent.com/236140/107285410-1c8ce380-6a2d-11eb-8987-502af78e4778.png">

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/appcleaner/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
