### ISSUE TITLE
rekordbox

### ISSUE THREAD

**Issue by jeroen-meijer** [ThatGuySam/doesitarm#560]
**The official name of the app**
rekordbox

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Yes, works via Rosetta 2 with native support currently in development

**Proposed App Category**
Music and Audio Tools (https://doesitarm.com/kind/music-and-audio-tools/)

**Related Issue Tracker Link or discussion**
https://www.pioneerdj.com/news/2020/compatibility-for-new-macs-with-m1-chip/

**An Official App Download Page**
https://rekordbox.com/download/

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![image](https://user-images.githubusercontent.com/14292245/107519431-8eda0100-6bb0-11eb-9a4d-3a2a44008642.png)
![image](https://user-images.githubusercontent.com/14292245/107519468-98636900-6bb0-11eb-9509-34823935278f.png)

**Comment by ThatGuySam** [comment]
Good find! Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
@jeroen-meijer I'm curious: Have you been able to test any of the other Pioneer DJ apps yet? 

This page has an extensive list of supported apps and hardware but it doesn't say if the app runs natively or with Rosetta 2 translation
https://www.pioneerdj.com/en-us/landing/support-for-macos-big-sur/

If I can get confirmation on the exact meaning of "Verification complete" I can list them for other people to find

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/rekordbox/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by jeroen-meijer** [comment]
@ThatGuySam Thanks for adding it to the repo, and apologies for not answering sooner. 😄 

I haven't tested any other Pioneer apps, since I only use rekordbox.
