### ISSUE TITLE
Microsoft Remote Desktop Client

### ISSUE THREAD

**Issue by Shambler2** [ThatGuySam/doesitarm#562]
The official name of the app
Remote Desktop Client for Mac

Proposed App Status
In progress, beta available here: (v10.6 or above) https://install.appcenter.ms/orgs/rdmacios-k2vy/apps/microsoft-remote-desktop-for-mac/distribution_groups/all-users-of-microsoft-remote-desktop-for-mac

Related Issue Tracker Link or discussion
Official post: https://www.alfredapp.com/blog/announcements/alfred-ready-for-apple-m1-chip/

An Official App Download Link
macOS App Store: https://apps.apple.com/au/app/microsoft-remote-desktop/id1295203466?mt=12

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like it is reported working via Rosetta 2
https://docs.microsoft.com/en-us/answers/questions/170727/micosoft-remote-desktop-and-silicon.html?childToView=220669#comment-220669

**Comment by ThatGuySam** [comment]
Status: 
✳️ Yes, works via Rosetta 2 with native support in beta

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/microsoft-remote-desktop/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
