### ISSUE TITLE
Google Backup and Sync

### ISSUE THREAD

**Issue by BelalShareb** [ThatGuySam/doesitarm#564]
**The official name of the app**
{Backup and Sync from Google}

**Is there a supported version available on a stable release channel?**
{Yes}

**Proposed New App Status**
{✳️ Yes, works via Rosetta 2}

**Related Issue Tracker Link or discussion**
{https://support.google.com/a/answer/7573023?hl=en }

**An Official App Download Page**
{https://www.google.com/drive/download/ }

**Additional context**
{It has a lot of processes running in the activity monitor for some reason}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info]
<img width="1440" alt="Screen Shot 2021-02-14 at 2 12 07 PM" src="https://user-images.githubusercontent.com/26521613/107876485-f05ee000-6ece-11eb-8e27-ba7a29adc2c4.png">

**Comment by ThatGuySam** [comment]
Thanks for the report! 

Update is now live on the site! 

https://doesitarm.com/app/google-backup-and-sync/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
