### ISSUE TITLE
AdGuard

### ISSUE THREAD

**Issue by danielmeskin** [ThatGuySam/doesitarm#565]
**The official name of the app**
AdGuard

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️

**Proposed App Category**
VPNs, Security, and Privacy

**Related Issue Tracker Link or discussion**
https://adguard.com/en/blog/big-sur-release-comment.html

**An Official App Download Page**
https://adguard.com/en/welcome.html

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="199" alt="CleanShot 2021-02-15 at 17 29 16@2x" src="https://user-images.githubusercontent.com/33349740/107998529-5a50b580-6fb3-11eb-8ba5-70429ad8e5ae.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/adguard/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by aayush2710** [comment]
Apple Silicon optimized version of AdGuard now available in beta channel. 

https://github.com/AdguardTeam/AdGuardForSafari/releases/tag/v1.9.14-beta

**Comment by amadejpapez** [comment]
> Apple Silicon optimized version of AdGuard now available in beta channel. 
> 
> 
> 
> https://github.com/AdguardTeam/AdGuardForSafari/releases/tag/v1.9.14-beta

@ThatGuySam This is correct. Since 1.9.19 (https://adguard.com/en/blog/adguard-1-9-19-for-safari.html) Adguard For Safari is a Universal app.

**Comment by ThatGuySam** [comment]
App update is now live on the site! 

https://doesitarm.com/app/adguard/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by amadejpapez** [comment]
Thank you! :D
