### ISSUE TITLE
Mullvad VPN

### ISSUE THREAD

**Issue by danielmeskin** [ThatGuySam/doesitarm#566]
**The official name of the app**
Mullvad VPN

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️

**Proposed App Category**
VPNs, Security, and Privacy

**An Official App Download Page**
https://mullvad.net/en/download/macos/

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="199" alt="CleanShot 2021-02-15 at 17 31 20@2x" src="https://user-images.githubusercontent.com/33349740/107998731-bc111f80-6fb3-11eb-85b1-668aabd589a4.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/mullvad-vpn/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
