### ISSUE TITLE
ffmpeg through homebrew installs without errors on Mac mini M1

### ISSUE THREAD

**Issue by muuvmuuv** [ThatGuySam/doesitarm#569]
Replace the text inside the {}'s with your own. 

For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/358

**The official name of the app**

ffmpeg

**Is there a supported version available on a stable release channel?**

Yes

**Proposed New App Status**

Not yet supported because of unsupported or broken dependencies on arm64: rsvg, x264, libvpx, soxr

**Related Issue Tracker Link or discussion**

None

**An Official App Download Page**

Through homebrew with `brew install ffmpeg`

**Additional context**

I was able to install it and use it without any errors or warnings. It uses all GPU cores on 100% and downloaded ARM builds on installation (as far as I saw it in the brew console output).

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

I was not able to capture one it was just to fast haha

**Comment by ThatGuySam** [comment]
Thanks for report! 

Update is now live on the site! 

https://doesitarm.com/app/ffmpeg/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
