### ISSUE TITLE
Proxyman

### ISSUE THREAD

**Issue by djerfy** [ThatGuySam/doesitarm#57]
**The official name of the app**
Proxyman

**Proposed App Status**
No but it's in progress

**Related Issue Tracker Link or discussion**
https://twitter.com/_nghiatran/status/1326867727034712064

**An Official App Download Link**
https://proxyman.io/

**Additional context**
None

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Do you know if there is a different link available that would show the very latest status?

**Comment by djerfy** [comment]
Related issues:
* Proxyman could not be updated on macOS Big Sur: https://github.com/ProxymanApp/Proxyman/issues/688
* Support ARM64 build: https://github.com/ProxymanApp/Proxyman/issues/686

**Comment by NghiaTranUIT** [comment]
To clarify, Proxyman is able to update and run on the latest macOS Big Sur. 

https://github.com/ProxymanApp/Proxyman/issues/688 is a bug from the OS. Restart would fix it 😄

**Comment by NghiaTranUIT** [comment]
@ThatGuySam @djerfy Good news that Proxyman has officially supported arm64 arch 🎉 

You can download the universal Proxyman build (arm64 and x84_64) from [Proxyman's dashboard](https://proxyman.io)

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by NghiaTranUIT** [comment]
All done here https://github.com/ThatGuySam/doesitarm/pull/100, thank you in advance @ThatGuySam 🎉

**Comment by ThatGuySam** [comment]
We're live!

https://doesitarm.com/app/proxyman/

<img width="1792" alt="Screen Shot 2020-11-14 at 12 51 55 PM" src="https://user-images.githubusercontent.com/2830379/99154819-5a6dac00-2678-11eb-9efd-9bec44fda5af.png">
