### ISSUE TITLE
TextSniper

### ISSUE THREAD

**Issue by twoperkg** [ThatGuySam/doesitarm#571]
**The official name of the app**
TextSniper

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
https://textsniper.app/release-notes

**An Official App Download Page**
https://textsniper.app/

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![image](https://user-images.githubusercontent.com/42322073/108384508-7b174600-7213-11eb-8add-863c60b069c2.png)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/textsniper/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
