### ISSUE TITLE
Pacifist - Partially working under Rosetta 2

### ISSUE THREAD

**Issue by Guddler** [ThatGuySam/doesitarm#573]
**The official name of the app**
[Pacifist](https://www.charlessoft.com)

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Yes, works via Rosetta 2

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
[Release notes maybe?](https://www.charlessoft.com/cgi-bin/pacifist_relnotes.cgi)

**An Official App Download Page**
https://www.charlessoft.com

**Additional context**
The application itself works fine under Rosetta 2 but the Quicklook Plugin does not recognise the product is registered. This is not unique to M1 or R2 however as it does the same on Intel.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

![Screenshot 2021-02-19 at 21 02 53](https://user-images.githubusercontent.com/5852361/108561429-2a2c4e00-72f6-11eb-9c13-2965ff253a47.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Next, we'll need someone with an M1 to provide a screenshot. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by Guddler** [comment]
@ThatGuySam  Added screenshot - I just wasn't on my M1 machine at the time I created the report

**Comment by ThatGuySam** [comment]
Perfect! Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/pacifist/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
