### ISSUE TITLE
GNU Octave

### ISSUE THREAD

**Issue by leoplan2** [ThatGuySam/doesitarm#574]
**The official name of the app**
GNU Octave
**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Science and Research Software

**Related Issue Tracker Link or discussion**

**An Official App Download Page**
https://formulae.brew.sh/formula/octave

**Additional context**
Available via Homebrew: https://formulae.brew.sh/formula/octave

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="961" alt="Screen Shot 2021-02-19 at 22 20 14" src="https://user-images.githubusercontent.com/2043477/108583662-a62b9380-7300-11eb-8db6-dfa016d45955.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/gnu-octave/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
