### ISSUE TITLE
Dash supports Apple silicon

### ISSUE THREAD

**Issue by cmhzc** [ThatGuySam/doesitarm#575]
**The official name of the app**
Dash

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**Related Issue Tracker Link or discussion**
https://blog.kapeli.com/

**An Official App Download Page**
https://kapeli.com/dash

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1279" alt="Screen Shot 2021-02-21 at 11 46 27" src="https://user-images.githubusercontent.com/20838961/108614987-92844800-743a-11eb-855e-d62c1cd81865.png">

**Comment by cmhzc** [comment]
App added in issue #225 

*Dash for macos* is used as the name on the website, [detail page](https://doesitarm.com/app/dash-for-macos/)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/dash-for-macos/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
