### ISSUE TITLE
Caddy

### ISSUE THREAD

**Issue by nehalvpatel** [ThatGuySam/doesitarm#577]
**The official name of the app**
Caddy

**Is there a supported version available on a stable release channel?**
Yes* (see below)

**Proposed App Status**
✳️ Yes, works via Rosetta 2

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
https://formulae.brew.sh/formula/caddy

**An Official App Download Page**
https://caddyserver.com/download

**Additional context**
It looks like the official website can generate M1 binaries, but the Homebrew listing only has x86 binaries.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
Installed using Homebrew:

<img width="1141" alt="Screen Shot 2021-02-21 at 11 20 49 AM" src="https://user-images.githubusercontent.com/159021/108632901-db3a0200-7436-11eb-94c4-e5c5e75dfa90.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! Looks like Homebrew is now listing Apple Silicon Support. We can list it as Rosetta 2 for now until we can get a screenshot that show's Apple Architecture for confirmation

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/caddy/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by nehalvpatel** [comment]
<img width="1141" alt="Screen Shot 2021-02-22 at 3 23 19 PM" src="https://user-images.githubusercontent.com/159021/108771895-e584fa80-7521-11eb-8927-46bb40e91f16.png">

I just tried installing it with my ARM installation of Homebrew, and it worked!

Let me know if this is sufficient or if you'd like me to create a new issue to get the website listing updated to indicate native support.

**Comment by ThatGuySam** [comment]
Updated! 

https://doesitarm.com/app/caddy/
