### ISSUE TITLE
Octave

### ISSUE THREAD

**Issue by zhangzhuang15** [ThatGuySam/doesitarm#578]
Replace the text inside the {}'s with your own. 

For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/358

**The official name of the app**
Octave

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
doesn't support

**Proposed App Category**
developer

**Related Issue Tracker Link or discussion**

**An Official App Download Page**
https://wiki.octave.org/Octave_for_macOS

**Additional context**

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

**Comment by ThatGuySam** [comment]
What's the difference between this and GNU Octave?
https://doesitarm.com/app/gnu-octave/

**Comment by harryzcy** [comment]
They are the same. From the link provided by @zhangzhuang15, you can go to the Homebrew page. And from there, it shows the website of GNU Octave shown on doesitarm site.

**Comment by harryzcy** [comment]
This issue says they will wait for the upstream to support m1. But now GNU Octave certainly has native support. So some testing on M1 is needed for now.

**Comment by moffpage** [comment]
Close this issue maybe?

**Comment by zhangzhuang15** [comment]
Okey.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ThatGuySam/doesitarm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月20日(星期天) 晚上11:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ThatGuySam/doesitarm] Octave (#578)





 
Close this issue maybe?

**Comment by ThatGuySam** [comment]
Closing this issue for now
