### ISSUE TITLE
Serato DJ Pro

### ISSUE THREAD

**Issue by gaspardmonnier** [ThatGuySam/doesitarm#58]
It would be nice to add Serato DJ Pro  : 
https://serato.com/dj/pro/downloads?systemrequirements#system-requirements

And its expansions Serato DVS, Serato FX and Serato P'n T : 
https://serato.com/dj/pro/expansions/dvs?dvs=dvs-ready
https://serato.com/dj/pro/expansions/fx
https://serato.com/dj/pro/expansions/pitchntimedj

**Comment by gaspardmonnier** [comment]
It would be nice to add Serato DJ Pro  : https://serato.com/dj/pro/downloads?systemrequirements#system-requirements
And its expansions Serato DVS, Serato FX and Serato P'n T : 
https://serato.com/dj/pro/expansions/dvs?dvs=dvs-ready
https://serato.com/dj/pro/expansions/fx
https://serato.com/dj/pro/expansions/pitchntimedj

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

Is there a link anywhere that provides the latest status or discussion on Apple Silicon support?

**Comment by gaspardmonnier** [comment]
Serato's users have opened a topic about that in the Serato forum : https://serato.com/forum/discussion/1761924#new

**Comment by hzylka** [comment]
@ThatGuySam Serato DJ Pro 2.5.0 & Serato DJ Lite 1.5.0 now support macOS computers with Apple M1 CPU’s

https://support.serato.com/hc/en-us/articles/360002139675-Mac-computers-with-ARM-based-M1-CPU-s-are-currently-not-supported-with-Serato-software-Beta-now-available-

**Comment by ThatGuySam** [comment]
It looks like it doesn't have a native Apple Silicon binary, so they must have fixed any issues with Rosetta 2 translation

**Comment by ThatGuySam** [comment]
<img width="1792" alt="Screen Shot 2021-04-16 at 12 27 47 PM" src="https://user-images.githubusercontent.com/2830379/115061756-2dcff180-9eaf-11eb-9be9-5dcba47fb51e.png">

**Comment by ThatGuySam** [comment]
Also, it looks like the beta of 2.5.5 doesn't have ARM Binaries either so it may be Rosetta 2 as well for now. 
<img width="1792" alt="Screen Shot 2021-04-16 at 12 36 36 PM" src="https://user-images.githubusercontent.com/2830379/115064102-25c58100-9eb2-11eb-8c50-19a342d344ae.png">

**Comment by ThatGuySam** [comment]
App is live! 

https://doesitarm.com/app/serato-dj-pro/

**Comment by ThatGuySam** [comment]
Feel free to comment on this issue for future updates as well
