### ISSUE TITLE
Trello

### ISSUE THREAD

**Issue by IchBinHannes** [ThatGuySam/doesitarm#581]
**The official name of the app**
Trello

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Yes, works via Rosetta 2

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
xxx

**An Official App Download Page**
https://apps.apple.com/de/app/trello/id1278508951?mt=12

**Additional context**
xxx

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

![Bildschirmfoto 2021-02-25 um 20 39 08](https://user-images.githubusercontent.com/79663802/109207578-951fce00-77a9-11eb-9715-ad831982e378.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/trello/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
