### ISSUE TITLE
Shadow

### ISSUE THREAD

**Issue by IchBinHannes** [ThatGuySam/doesitarm#584]
**The official name of the app**
Shadow

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Yes, works via Rosetta 2

**Proposed App Category**
?Virtual Machine?

**Related Issue Tracker Link or discussion**
Shadows Discord-Server

**An Official App Download Page**
https://shadow.tech/de/shadow-apps

**Additional context**
USB-over-IP is not available in Stable and Alpha M1 version but will be implemented in the future.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

![Bildschirmfoto 2021-02-25 um 21 26 53](https://user-images.githubusercontent.com/79663802/109212775-37db4b00-77b0-11eb-8ff7-c5573d11fbc4.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/shadow-for-macos/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by IchBinHannes** [comment]
Today they released the official Shadow app with M1 support (see here: [https://shadow.tech/shadow-apps/](url) ).

So #583 is no longer needed.

**Comment by ThatGuySam** [comment]
App Update is now live on the site! 

https://doesitarm.com/app/shadow-for-macos/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
