### ISSUE TITLE
Textmate

### ISSUE THREAD

**Issue by johnwylie70** [ThatGuySam/doesitarm#585]
**The official name of the app**
Textmate

**Is there a supported version available on a stable release channel?**
yes

**Proposed App Status**
Yes, Full Apple Silicon Support

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
{This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes.}

**An Official App Download Page**
https://macromates.com OR
https://github.com/textmate/textmate

**Additional context**

![](https://macromates.com/textmate/img/screenshot_1x_dark.png)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

![image](https://user-images.githubusercontent.com/1545002/109343590-7f6fde80-7865-11eb-89c0-ab42b8fdc4bf.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/textmate/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
