### ISSUE TITLE
foobar2000 is ready on Apple Silicon

### ISSUE THREAD

**Issue by liuyuanOUC** [ThatGuySam/doesitarm#586]
**The official name of the app**
foobar2000

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Music and Audio Tools

**Related Issue Tracker Link or discussion**
https://www.foobar2000.org/changelog-mac

**An Official App Download Page**
https://www.foobar2000.org/changelog-mac

**Additional context**
![image](https://user-images.githubusercontent.com/27879832/109371604-acada280-78e0-11eb-9aa0-4b2eac1a9569.png)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![image](https://user-images.githubusercontent.com/27879832/109371765-5db43d00-78e1-11eb-98c0-9adea2f90a7c.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

This looks great! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/foobar2000/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
