### ISSUE TITLE
Zettlr

### ISSUE THREAD

**Issue by nathanlesage** [ThatGuySam/doesitarm#587]
**The official name of the app**
[Zettlr](https://www.zettlr.com/) (repository: https://github.com/Zettlr/Zettlr)

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
Not applicable due to full Apple Silicon support

**An Official App Download Page**
https://www.zettlr.com/download

**Additional context**
Not applicable

**Full Screenshot with the App and Activity Monitor(if self reporting) or Silicon Info**

![image](https://user-images.githubusercontent.com/17251683/109384792-94914f80-78ef-11eb-8181-cb910b7d2358.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/zettlr/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
