### ISSUE TITLE
Hadolint

### ISSUE THREAD

**Issue by pzelnip** [ThatGuySam/doesitarm#588]
**The official name of the app**
[Hadolint](https://formulae.brew.sh/formula/hadolint)

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Runs via Rosetta 

**Proposed App Category**
??? I don't know what the app categories are

**Related Issue Tracker Link or discussion**
https://github.com/Homebrew/brew/issues/10744

**An Official App Download Page**
https://formulae.brew.sh/formula/hadolint

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/hadolint/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
