### ISSUE TITLE
Google Drive for Desktop m1 open beta

### ISSUE THREAD

**Issue by jacobrosenfeld** [ThatGuySam/doesitarm#589]
Replace the text inside the {}'s with your own. 

For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/358

**The official name of the app**
Google Drive for desktop

**Is there a supported version available on a stable release channel?**
No

**Proposed New App Status**
working in Open beta

**Related Issue Tracker Link or discussion**
https://support.google.com/a/answer/7577057?hl=en

**An Official App Download Page**
https://support.google.com/a/answer/7577057?hl=en

**Additional context**
{Add any other context or screenshots about the app request here.}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{As screenshot with Activity Monitor open showing the App's architecture type}
![image](https://user-images.githubusercontent.com/21108380/109979059-78fdbe80-7ccc-11eb-98e8-ec236509e711.png)

**Comment by ThatGuySam** [comment]
Thanks for the update! 

Listing is now updated
https://doesitarm.com/app/google-drive-for-desktop/

**Comment by DennyWeinberg** [comment]
I just installed Google Drive and the Activity Monitor tells me that it's Apple Architecture.
https://blog.google/products/drive/drive-for-desktop/

**Comment by ThatGuySam** [comment]
@DennyWeinberg Thanks for the update! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by DennyWeinberg** [comment]
Please do it

**Comment by ThatGuySam** [comment]
Verification
<img width="377" alt="Screen Shot 2021-08-10 at 12 30 53 PM" src="https://user-images.githubusercontent.com/2830379/128907121-5125cf85-f60a-4313-9cdb-6b2d23163eac.png">

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/google-drive-for-desktop/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
