### ISSUE TITLE
Cisco Webex

### ISSUE THREAD

**Issue by vabue** [ThatGuySam/doesitarm#59]
**The official name of the app**
Cisco Webex Meetings

**Proposed App Status**
No but it's in progress

**An Official App Download Link**
https://www.webex.com/downloads.html

**Additional context**
None

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by xanekka** [comment]
Works with Rosetta.

**Comment by ThatGuySam** [comment]
Perfect! Let's get a screenshot or a link to use as a source and we can go live. 

You can find a screenshot example on #176

**Comment by xanekka** [comment]
<img width="852" alt="Screen Shot 2020-11-20 at 11 26 40 PM" src="https://user-images.githubusercontent.com/11390681/99867504-1c94ea00-2b88-11eb-826a-f6575b9308c7.png">

**Comment by ThatGuySam** [comment]
Status: ✳️ Yes, works via Rosetta 2

**Comment by ThatGuySam** [comment]
This is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/cisco-webex-meetings/

Feel free to browse through the other issues to help with missing info on other apps.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/cisco-webex-meetings/

Feel free to browse through the other issues to help with missing info on other apps.
