### ISSUE TITLE
Visual Studio Code Updated to ARM

### ISSUE THREAD

**Issue by SethuSenthil** [ThatGuySam/doesitarm#590]
**The official name of the app**
Visual Studio Code

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
 Yes, Full Native Apple Silicon Support as of v1.54

**Related Issue Tracker Link or discussion**
https://code.visualstudio.com/updates/v1_54

**An Official App Download Page**
https://code.visualstudio.com/

**Additional context**
They are universal builds, download sizes may be larger. Users on M1 may need to redownload VS code from the website to get the Apple Silicon version, simply updating it via OTA doesn't seem to work ATM.
UPDATE: They got ARM installer now available for download

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

![image](https://user-images.githubusercontent.com/20134046/110045082-2944e480-7d18-11eb-8e69-c6f60cbe2cec.png)

**Comment by FutureMathematician** [comment]
Thank you, I just downloaded universal version and it's much faster! Thank god!

**Comment by FutureMathematician** [comment]
Is your mac overheating when running apple silicon version vscode?

**Comment by SethuSenthil** [comment]
> Is your mac overheating when running apple silicon version vscode?

Yeah, I had this issue too

**Comment by ThatGuySam** [comment]
Great find! 

Update is now live! 

https://doesitarm.com/app/vs-code/
