### ISSUE TITLE
Thunderbird Beta 87 Apple Silicon update

### ISSUE THREAD

**Issue by Andy-Ivanyuk** [ThatGuySam/doesitarm#591]
**The official name of the app**
[Thunderbird Beta](https://www.thunderbird.net/)

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support as of v87

**Related Issue Tracker Link or discussion**
[Bugzilla Tracker](https://bugzilla.mozilla.org/show_bug.cgi?id=1678775)

**An Official App Download Page**
[Thunderbird](https://www.thunderbird.net/)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![image](https://user-images.githubusercontent.com/33178570/110332529-18061b80-8029-11eb-9797-56a591ee8886.png)

**Comment by ThatGuySam** [comment]
Good find! 

Update is now live!
https://doesitarm.com/app/thunderbird/
