### ISSUE TITLE
Tinkerwell

### ISSUE THREAD

**Issue by leemcd56** [ThatGuySam/doesitarm#592]
**The official name of the app**
Tinkerwell

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Yes, works via Translation or Virtualization

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
- https://github.com/beyondcode/tinkerwell-community/issues/388 (Only related question so far)

**An Official App Download Page**
https://tinkerwell.app/

**Additional context**
Tinkerwell is a desktop application that allows for direct interaction with Laravel's Artisan console, as well as interacting with other PHP-based web apps.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Screen Shot 2021-03-08 at 15 11 38](https://user-images.githubusercontent.com/1885663/110382517-a1652000-8020-11eb-89fb-3bd27b7f883f.png)

**Comment by ThatGuySam** [comment]
Thanks for the request! 

App is now live on the site! 

https://doesitarm.com/app/tinkerwell/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
