### ISSUE TITLE
1Password now supports Apple Silicon

### ISSUE THREAD

**Issue by moogle19** [ThatGuySam/doesitarm#594]
**The official name of the app**
{What's the full official name of the app}
1Password 7

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**Related Issue Tracker Link or discussion**
https://app-updates.agilebits.com/product_history/OPM7

**An Official App Download Page**
https://c.1password.com/dist/1P/mac7/1Password-7.8.pkg

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Screenshot 2021-03-10 at 08 19 35](https://user-images.githubusercontent.com/792046/110591438-5b6f9f80-8179-11eb-8d55-d3a3e757d27f.png)

**Comment by KovalevArtem** [comment]
https://9to5mac.com/2021/03/09/1password-7-8-for-macos-now-runs-natively-on-apple-silicon-macs/

**Comment by ThatGuySam** [comment]
Good find! Updated!

https://doesitarm.com/app/1password/
