### ISSUE TITLE
qBittorrent

### ISSUE THREAD

**Issue by Andy-Ivanyuk** [ThatGuySam/doesitarm#595]
**The official name of the app**
[qBittorrent](https://www.qbittorrent.org/)

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
✳️ Runs via Rosetta

**Proposed App Category**
Torrent Clients

**Related Issue Tracker Link or discussion**
[Opened issue](https://github.com/qbittorrent/qBittorrent/issues/14379)

**An Official App Download Page**
[qBittorrent](https://www.qbittorrent.org/)

**Additional context**
There is no native support yet, but with rosetta works fine!

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![image](https://user-images.githubusercontent.com/33178570/110985695-6db62d00-8375-11eb-837f-75f868cec27d.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request, the app is now live on the site! 

https://doesitarm.com/app/qbittorrent/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
