### ISSUE TITLE
Celeste

### ISSUE THREAD

**Issue by iwa** [ThatGuySam/doesitarm#598]
**The official name of the app**
🍓 Celeste.app

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support, if following [this](https://github.com/AbeJellinek/celeste-on-m1).

**Proposed App Category**
Games

**An Official App Download Page**
No official binaries, you have to replace the internal files by yourself.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
Not tested yet, should be able in a week or so

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Since it doesn't work automatically out of the box, let use the following status: 
⏹ No, not yet but can be made to run with a work-around. 

And then we'll add the link to the celeste-on-m1 repo

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/celeste/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by iwa** [comment]
Nice, thank you!

**Comment by alanjcastonguay** [comment]
This appears to work out of the box now, without https://github.com/AbeJellinek/celeste-on-m1.

Installed with Steam, version 1.4.0.0 reported in-game, build 6458966 reported in Steam UI, ActivityMonitor.app shows Kind=Intel.

PS4 Controller over USB doesn't work by default. Need to Force Off in the Steam Big Picture UI, then Celeste can see the PS4 Controller fine. I don't think that's M1-specific, though.

The https://celeste.ink/wiki/Version_history for 1.4.0.0 says

> Updated to the latest version of FNA, introducing FNA3D. This means the FNA version can run DirectX on Windows and Metal on Mac

**Comment by pixelomer** [comment]
> > This appears to work out of the box now, without https://github.com/AbeJellinek/celeste-on-m1.
> > Installed with Steam, version 1.4.0.0 reported in-game, build 6458966 reported in Steam UI, ActivityMonitor.app shows Kind=Intel.
> > PS4 Controller over USB doesn't work by default. Need to Force Off in the Steam Big Picture UI, then Celeste can see the PS4 Controller fine. I don't think that's M1-specific, though.
> > The https://celeste.ink/wiki/Version_history for 1.4.0.0 says
> > > Updated to the latest version of FNA, introducing FNA3D. This means the FNA version can run DirectX on Windows and Metal on Mac
> 
> older versions works fine too through Rosetta 2 if i remember well, but I made this request to provide a better solution than relying on Rosetta celeste-on-m1 makes Celeste running natively, instead of emulating it

Your solution doesn't make the game run natively. Binaries in that repository are also Intel binaries.

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/celeste

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
