### ISSUE TITLE
Rhinoceros 3D

### ISSUE THREAD

**Issue by Vorotnikoff** [ThatGuySam/doesitarm#60]
Rhino3D

https://www.rhino3d.com/ - official site

https://www.rhino3d.com/download/rhino-for-mac/6/evaluation - to download trial version

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ThatGuySam** [comment]
From #232 

> Reference issue: #60
> Tracker: https://discourse.mcneel.com/t/apple-silicon-and-rhino-for-mac-the-work-continues/113164
> 
> as of Nov 24, 2020:
> Rhino 6, 7, and 8 for Mac are NOT SUPPORTED on Apple Silicon Macs with M1 processors.
> Rhino 6 will never be supported on Apple Silicon.
> Rhino 7 development to support Apple Silicon via Apple’s Rosetta Translation Environment 697 has started.
> Rhino 8 development to support Apple Silicon via Universal Binary 295 for both Intel and Apple Silicon has started.

**Comment by ThatGuySam** [comment]
We'll use the following status: 
✳️ Yes, works via Rosetta 2 translation

**Comment by ThatGuySam** [comment]
Actually, it looks like the following would be more appropriate for status: 
🚫 No, not yet supported only works on Intel-based Macs

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/rhinoceros-3d/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
