### ISSUE TITLE
App Request: Onivim2

### ISSUE THREAD

**Issue by jesstelford** [ThatGuySam/doesitarm#601]
**The official name of the app**
Onivim2

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Yes, works via Translation or Virtualization

**Proposed App Category**
Developer Tools

**Related Issue Tracker Link or discussion**
https://github.com/onivim/oni2/issues/2708

**An Official App Download Page**
https://v2.onivim.io/early-access-portal

**Additional context**
n/a

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

<img width="826" alt="Screen Shot 2021-03-18 at 12 44 40 pm" src="https://user-images.githubusercontent.com/612020/111560945-b80d3300-87e7-11eb-842a-eb608d05ed3c.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/onivim/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by jesstelford** [comment]
Thanks!

To be clear; the application's name is `Onivim2` (with the `2`) - `Onivim` is an entirely different project, not just the "previous version" unfortunately.

**Comment by ThatGuySam** [comment]
Fixed! 

https://doesitarm.com/app/onivim2/
