### ISSUE TITLE
App Request: Witch

### ISSUE THREAD

**Issue by jesstelford** [ThatGuySam/doesitarm#602]
**The official name of the app**
Witch

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
https://manytricks.com/witch/releasenotes/

**An Official App Download Page**
https://manytricks.com/witch/

**Additional context**
Since v4.3.7

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="778" alt="Screen Shot 2021-03-18 at 1 44 27 pm" src="https://user-images.githubusercontent.com/612020/111565785-1b02c800-87f0-11eb-91c8-c9b6efeb4aa8.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/witch-for-mac/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
