### ISSUE TITLE
App Request: Harvest

### ISSUE THREAD

**Issue by jesstelford** [ThatGuySam/doesitarm#604]
**The official name of the app**
Harvest

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
n/a

**An Official App Download Page**
https://www.getharvest.com/apps/mac

**Additional context**
n/a

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="451" alt="Screen Shot 2021-03-19 at 9 22 33 am" src="https://user-images.githubusercontent.com/612020/111705479-ded57300-8894-11eb-988e-5a674859e525.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/harvest-for-mac/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
