### ISSUE TITLE
App Request: Rocket

### ISSUE THREAD

**Issue by jesstelford** [ThatGuySam/doesitarm#605]
**The official name of the app**
Rocket

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
n/a

**An Official App Download Page**
https://matthewpalmer.net/rocket/

**Additional context**
Can only test the latest version (1.8.2), so not sure when support was added. But it works 👍

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="611" alt="Screen Shot 2021-03-19 at 9 46 56 am" src="https://user-images.githubusercontent.com/612020/111707571-696ba180-8898-11eb-82b4-55f42983a16f.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

We'll list this under System Tools for now. 

Productivity is the default misc category but I'm trying to not use it as much since there are so many apps already in it.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/rocket-for-mac/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
