### ISSUE TITLE
Unite for Mac not ready yet

### ISSUE THREAD

**Issue by wazar** [ThatGuySam/doesitarm#606]
**The official name of the app**
Unite for Mac

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✳️ Runs via Rosetta with native support currently in development

**Related Issue Tracker Link or discussion**
https://support.setapp.com/hc/en-us/articles/360017546359-Apps-from-Setapp-on-macOS-11-Big-Sur-and-Apple-silicon-M1-chips

**An Official App Download Page**
https://www.bzgapps.com/unite

**Additional context**
So the doesitarm page for this app reports it's M1 ready when it's still Intel based.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

https://i.imgur.com/OjGb1Fe.png

**Comment by ThatGuySam** [comment]
Thanks for catching that! 

I'm uploading your screenshot here as well for posterity. 

Will fix shortly

![OjGb1Fe](https://user-images.githubusercontent.com/2830379/111822468-d2abde80-88b1-11eb-9a55-e618d1b8a814.png)

**Comment by ThatGuySam** [comment]
Fix is now live! 

https://doesitarm.com/app/unite-for-mac/
