### ISSUE TITLE
App Request: Iriun Webcam

### ISSUE THREAD

**Issue by jesstelford** [ThatGuySam/doesitarm#607]
**The official name of the app**
Iriun Webcam

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Yes, works via Translation or Virtualization

**Proposed App Category**
Video Tools

**Related Issue Tracker Link or discussion**
n/a

**An Official App Download Page**
http://iriun.com/

**Additional context**
All works for me under Rosetta 2.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="641" alt="Screen Shot 2021-03-19 at 12 10 44 pm" src="https://user-images.githubusercontent.com/612020/111717679-a8a3ed80-88ac-11eb-8339-6ba32d3dd990.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

We'll put this under System Tools for now. 

There's probably a better way to make this more apparent, but Video and Motion Tools is more related to Video Editing and production. 

Maybe we can add descriptions or a new, more specific category later on.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/iriun-webcam/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
