### ISSUE TITLE
C

### ISSUE THREAD

**Issue by kode54** [ThatGuySam/doesitarm#608]
Replace the text inside the {}'s with your own. 

For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/358

**The official name of the app**
{What's the full official name of the app}

**Is there a supported version available on a stable release channel?**
{Yes/No}

**Proposed App Status**
{What's the current app status based off of current discussion or testing
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend}

**Proposed App Category**
{What category should the app go under}

**Related Issue Tracker Link or discussion**
{This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes.}

**An Official App Download Page**
{This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site.}

**Additional context**
{Add any other context or screenshots about the app request here.}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{As screenshot with Activity Monitor open showing the App's architecture type}

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by iwa** [comment]
c? you mean c language? if so, it's supported as macOS uses clang to compile C code, and clang has an arm64 version installed by default on M1 macs

![Screen Shot 2021-03-24 at 19 28 51](https://user-images.githubusercontent.com/19956672/112364770-2b76df00-8cd7-11eb-90e0-6b4509160813.png)

**Comment by ThatGuySam** [comment]
@iwa I think this was an accidental issue submission at first now I kind of just want to go with it. 

We already [LLVM Clang listed](https://doesitarm.com/app/llvm-clang/), is are there multiple distributions of C and LLVM is one of them?

**Comment by iwa** [comment]
as far as i know and understand, llvm is the codebase, and clang (the c compiler) is based on llvm, and as clang is open source, apple is editing and shipping its own version

if what i'm saying is right, then the llvm team is shipping binaries for the base version of clang, and apple is shipping its own modified clang version, through `xcode-select install` or Xcode directly

**Comment by ThatGuySam** [comment]
Sp for fun we could list: 
Apple Clang - ✅ Yes, Full Native Apple Silicon Support as v12.0.0

**Comment by kode54** [comment]
Oh, crap, I have no idea how this got submitted as just the empty template with one letter typed into the name. Closing, hahahahhahaha.
