### ISSUE TITLE
Cog.app (Audio Player for many formats)

### ISSUE THREAD

**Issue by kode54** [ThatGuySam/doesitarm#609]
Replace the text inside the {}'s with your own. 

For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/358

**The official name of the app**
{Cog}

**Is there a supported version available on a stable release channel?**
{Yes}

**Proposed App Status**
{Yes, Full Native Apple Silicon Support}

**Proposed App Category**
{Audio or Media Player}

**Related Issue Tracker Link or discussion**
{https://github.com/losnoco/cog}

**An Official App Download Page**
{https://cog.losno.co/download}

**Additional context**
{App has had Universal 2 builds since build 1149, the first version to drop macOS 10.8 support. Full functionality of the app has not been verified personally, and cannot be verified for at least a week or more until my new hardware arrives. You're welcome to put this entire submission on hold until then.}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{I cannot supply this yet, as I won't have an M1 Mac in my hands until the 2021-03-29 at the earliest.}

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Since the App Test is reporting the app as Native we don't need a physical Apple Silicon device to test for compatibility

<img width="1792" alt="Screen Shot 2021-03-22 at 12 36 55 PM" src="https://user-images.githubusercontent.com/2830379/112033531-81972700-8b0b-11eb-9e40-b4968e80d8c4.png">

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/cog-player/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
