### ISSUE TITLE
Krita

### ISSUE THREAD

**Issue by osvik** [ThatGuySam/doesitarm#610]
Replace the text inside the {}'s with your own. 

**The official name of the app**
[Krita](https://krita.org/en/) - Free and open source

**Is there a supported version available on a stable release channel?**

**Proposed App Status**
Maybe it works with Rosetta2

**Proposed App Category**
Photo tools

**Related Issue Tracker Link or discussion**
https://krita-artists.org/t/how-is-the-krita-on-the-apple-silicon-developer-kit-want-to-see-any-feedback/9558

**An Official App Download Page**

**Additional context**
Optional GPU:OpenGL 3.0 or higher

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Next, we'll need someone with an M1 to provide a screenshot. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by ThatGuySam** [comment]
Download Link: https://krita.org/en/download/krita-desktop/

**Comment by harryzcy** [comment]
It's reported that it crashes even with Rosetta 2.
https://www.reddit.com/r/krita/comments/kz1i4c/krita_crashing_on_new_file_apple_silicon_mac/

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/krita/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by JamesDrummond44** [comment]
Krita actually works fine on an M1 mac. That reddit post is 2 months old and personally don't think it can be used fairly as proof of it not functioning using Rosetta. Created a new file through the method in the post and there is no crash.

Imgur album with screenshots and activity monitor: https://imgur.com/a/04tEd88

**Comment by ThatGuySam** [comment]
Thanks, @JamesDrummond4! Good catch! 

Adding images here as well for posterity. 

![image](https://user-images.githubusercontent.com/2830379/113440658-75845280-93b2-11eb-97c1-f5de9d71f6a1.png)

![image](https://user-images.githubusercontent.com/2830379/113440743-9ba9f280-93b2-11eb-8ecc-b93b7087c6eb.png)

![image](https://user-images.githubusercontent.com/2830379/113440762-a2386a00-93b2-11eb-8202-e8e06fc7fc3c.png)

![image](https://user-images.githubusercontent.com/2830379/113440782-b2e8e000-93b2-11eb-8d4e-61c456944a7b.png)

**Comment by ThatGuySam** [comment]
Update is live! 

https://doesitarm.com/app/krita/

**Comment by Andy-Ivanyuk** [comment]
I have an update.

The official name of the app
Krita - Free and open source

Is there a supported version available on a stable release channel?
Yes

Proposed App Status
Works with M1 natively

Proposed App Category
Photo tools

Related Issue Tracker Link or discussion
https://krita-artists.org/t/can-krita-run-well-on-the-new-m1-macbook-air/21129

![image](https://user-images.githubusercontent.com/33178570/118943950-c64d0c00-b95c-11eb-955f-b535becfd24f.png)

**Comment by ThatGuySam** [comment]
Sure enough! 

<img width="1792" alt="Screen Shot 2021-05-21 at 1 02 02 PM" src="https://user-images.githubusercontent.com/2830379/119179801-fd8eec00-ba34-11eb-9169-07dfe73aaa3e.png">

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/krita/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
