### ISSUE TITLE
DeSmuME

### ISSUE THREAD

**Issue by iwa** [ThatGuySam/doesitarm#611]
**The official name of the app**
DeSmuME

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
✳️ Yes, works via Rosetta

**Proposed App Category**
Games / Emulator

**Related Issue Tracker Link or discussion**
Devs currently no longer support macOS releases

**An Official App Download Page**
http://desmume.org/download/

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Screen Shot 2021-03-24 at 19 36 15](https://user-images.githubusercontent.com/19956672/112365658-341be500-8cd8-11eb-8b74-8aa041a904ae.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/desmume/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
