### ISSUE TITLE
FSNotes

### ISSUE THREAD

**Issue by djhworld** [ThatGuySam/doesitarm#612]
**The official name of the app**

FSNotes

**Is there a supported version available on a stable release channel?**

Yes

**Proposed App Status**

* ✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**

Productivity Tool

**Related Issue Tracker Link or discussion**

N/A

**An Official App Download Page**

https://github.com/glushchenko/fsnotes/releases

**Additional context**

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

<img width="842" alt="image" src="https://user-images.githubusercontent.com/529730/112385152-2e79cb80-8ce7-11eb-86c5-f4452d7f5a35.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/fsnotes/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
