### ISSUE TITLE
psycopg2

### ISSUE THREAD

**Issue by Marion556** [ThatGuySam/doesitarm#615]
This is the error I get when I try to run psycopg2

It is apparently an issue with the M1 chip
<img width="903" alt="Screen Shot 2021-03-29 at 5 04 29 PM" src="https://user-images.githubusercontent.com/71854416/113014083-4e2b4c80-914a-11eb-84d6-b0f78f3250ef.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

So you're proposing the following status: 
🚫 No, not yet supported only works on Intel-based Macs

You can reference the App Request template here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ThatGuySam** [comment]
Look like there's a similar open issue here: 
https://github.com/psycopg/psycopg2/issues/1216

Also, there seems to be an issue installing; 
https://github.com/psycopg/psycopg2/issues/1200

**Comment by Marion556** [comment]
Thank you

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/psycopg2/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
