### ISSUE TITLE
Suggestion: add a tool for testing Apple Silicon support

### ISSUE THREAD

**Issue by harryzcy** [ThatGuySam/doesitarm#616]
[ascheck](https://github.com/harryzcy/ascheck) is a command-line app that iterates through all your apps and checks their Apple Silicon support. It should work both on Intel and Arm.

This CLI tool could speed up the checks by bulk testing. It would be great if it could be documented.

**Comment by harryzcy** [comment]
This tool tests the architecture app's code under the hood. If the app supports Arm, then the code for Arm will exist and thus should be detected. It can detect all the apps installed.
I'm not sure how the tool on doesitarm.com works. 
And Silicon Info only detects the running app.

**Comment by ThatGuySam** [comment]
Alright I've added a list of the different testing tools available, including ascheck
https://github.com/ThatGuySam/doesitarm#apple-silicon-testing-tools

**Comment by ThatGuySam** [comment]
Closing this issue
