### ISSUE TITLE
Step Two for Mac

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#619]
Replace the text inside the {}'s with your own. 

For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/358

**The official name of the app**
{Step Two}

**Is there a supported version available on a stable release channel?**
{Yes}

**Proposed New App Status**
{Yes, Full Native Support}

**Related Issue Tracker Link or discussion**
{}

**An Official App Download Page**
{steptwo.app}

**Additional context**
{Both application and Safari plugins have Apple Silicon support. Application installs as Universal Binary}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/113469677-58628900-9471-11eb-8bb4-d21744bf5b97.png">
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/33549573/113469703-92cc2600-9471-11eb-8a3a-cd692be05955.png">
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/33549573/113469704-9495e980-9471-11eb-8da7-5b2a29baa13e.png">
}

**Comment by ThatGuySam** [comment]
Thanks for the App Update! It's now live on the site! 

https://doesitarm.com/app/step-two-for-mac/

**Comment by moffpage** [comment]
Thank you!
