### ISSUE TITLE
Matlab

### ISSUE THREAD

**Issue by FutureMathematician** [ThatGuySam/doesitarm#62]
**The official name of the app**
Matlab

**Related Issue Tracker Link or discussion**

Rosetta 2:
An upcoming update for MATLAB R2020b will provide support for running MATLAB in Rosetta 2. Earlier releases of MATLAB are not supported on Apple Silicon. 
There are two products which are available on Intel-based Macs but are not compatible with the Rosetta 2 environment: Polyspace and Simulink Desktop Real-Time. 
Native Apple Silicon:
A version of MATLAB which runs natively on Apple Silicon is in development. This answer will be updated with more information as development progresses. 

https://www.mathworks.com/matlabcentral/answers/641925-is-matlab-supported-on-apple-silicon-macs

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by ThatGuySam** [comment]
Looks like someone in that discussion from the first comment is successfully running v9.9.0.1495850 on Apple SIlicon. 

We can go ahead and give this the following status: 
✳️ Yes, works via Rosetta 2 as of v9.9.0.1495850

**Comment by ThatGuySam** [comment]
Download Link
https://www.mathworks.com/products/get-matlab.html?s_tid=gn_getml

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/matlab/

Feel free to browse through the other issues to help with missing info on other apps.
