### ISSUE TITLE
OnyX

### ISSUE THREAD

**Issue by naxay07** [ThatGuySam/doesitarm#622]
**The official name of the app**
{OnyX}

**Is there a supported version available on a stable release channel?**
{Yes}

**Proposed App Status**
{✅ Yes, Full Native Apple Silicon Support}

**Proposed App Category**
{System Tools}

**Related Issue Tracker Link or discussion**
{https://titanium-software.fr/en/onyx.html}

**An Official App Download Page**
{https://titanium-software.fr/en/onyx.html}

**Additional context**
{Only macOS Big Sur version works on Apple Silicon, as mentioned on the official website}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{![Screen Shot 2021-04-04 at 12 44 12](https://user-images.githubusercontent.com/76769651/113504897-0dfe0c80-9544-11eb-99ce-52075c764f10.png)
![Screen Shot 2021-04-04 at 12 46 38](https://user-images.githubusercontent.com/76769651/113504899-0f2f3980-9544-11eb-929c-5406cb6643c1.png)}

**Comment by ThatGuySam** [comment]
Thanks for the App Request! This looks excellent! 

We'll also include the release notes link: 
https://titanium-software.fr/en/release_onyx.html

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/onyx-for-macos/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
