### ISSUE TITLE
CocoaPods now work natively without Rosetta2 translation layer

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#623]
Replace the text inside the {}'s with your own. 

For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/358

**The official name of the app**
CocoaPods

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
Yes, Full Native Apple Silicon Support

**Related Issue Tracker Link or discussion**
https://github.com/CocoaPods/CocoaPods/issues/9907

**An Official App Download Page**
cocoapods.org

**Additional context**
{Add any other context or screenshots about the app request here.}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{Don't have one sorry}

**Comment by LinusU** [comment]
(note that this `ethon` and `ffi` haven't been bumped in the lock-file that ships with 1.10.1, so it still isn't working in the last released version)

**Comment by ThatGuySam** [comment]
We'll keep an eye on https://github.com/CocoaPods/CocoaPods/pull/10576 and https://github.com/CocoaPods/CocoaPods/issues/9907 so we don't update it's status prematurely.

**Comment by LinusU** [comment]
If you do `brew install cocoapods` today it will run natively on M1, as of this PR: https://github.com/Homebrew/homebrew-core/pull/75035

That is with Ruby 2.7 though, it seems like it might never work with the built-in (deprecated by Apple) version of Ruby...

**Comment by moffpage** [comment]
Thanks! Great news ;)

**Comment by ThatGuySam** [comment]
We have a separate listing for Homebrew Coacoapods so for now we'll just link to that from the vanilla version until the above Issue and PR are resolved/they redo the build

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/cocoapods/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
