### ISSUE TITLE
Microsoft Remote Desktop

### ISSUE THREAD

**Issue by dvdsnchzIT** [ThatGuySam/doesitarm#625]
**The official name of the app**
Microsoft Remote Desktop

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**Related Issue Tracker Link or discussion**
• Added native support for Apple Silicon.

**An Official App Download Page**
https://apps.apple.com/au/app/microsoft-remote-desktop/id1295203466?mt=12

**Additional context**
10.6.0

**Comment by ThatGuySam** [comment]
Thanks for the report! 

Update is now live on the site:
https://doesitarm.com/app/microsoft-remote-desktop/
