### ISSUE TITLE
App Request: Snap Camera

### ISSUE THREAD

**Issue by chriskalos** [ThatGuySam/doesitarm#627]
**The official name of the app**
Snap Camera

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Video & Motion Tools

**Related Issue Tracker Link or discussion**
None available, update not documented

**An Official App Download Page**
https://snapcamera.snapchat.com/download/

**Additional context**
{Add any other context or screenshots about the app request here.}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![image](https://user-images.githubusercontent.com/9339301/115118186-bf705980-9faa-11eb-88f6-08e0fa031d66.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/snap-camera/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
