### ISSUE TITLE
Psycopg2

### ISSUE THREAD

**Issue by aimileus** [ThatGuySam/doesitarm#628]
**The official name of the app**
psycopg2

**Is there a supported version available on a stable release channel?**
Yes, I installed 2.8.6.

**Proposed New App Status**
✅ Native

**Related Issue Tracker Link or discussion**
The current linked issues provide some discussion. Although they have not been closed, there are a couple of people who had success installing and running psycopg2 without any workarounds.

**An Official App Download Page**
I installed it using `pip3 install psycopg2`, I had to install PostgreSQL via Homebrew (`brew install postgresql`). 

**Additional context**
I also installed the library from GitHub, and ran the test suite, which passed.
```
~/D/psycopg2 ((2_8_6)|…) $ python3 -c "import tests; tests.unittest.main(defaultTest='tests.test_suite')" --verbose
test_async_after_async (tests.test_async.AsyncTests) ... ok
test_async_callproc (tests.test_async.AsyncTests) ... ok
test_async_connection_error_message (tests.test_async.AsyncTests) ... ok
test_async_cursor_gone (tests.test_async.AsyncTests) ... ok
...
test_with_error (tests.test_with.WithCursorTestCase) ... ok
test_with_ok (tests.test_with.WithCursorTestCase) ... ok

----------------------------------------------------------------------
Ran 766 tests in 19.776s
```

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
Since this is a Python library, the app itself wiil not show up in Activity monitor, but running
```
$ ls /opt/homebrew/lib/python3.9/site-packages/psycopg2
__init__.py                   _psycopg.cpython-39-darwin.so extensions.py
__pycache__                   _range.py                     extras.py
_ipaddress.py                 compat.py                     pool.py
_json.py                      errorcodes.py                 sql.py
_lru_cache.py                 errors.py                     tz.py
$ file /opt/homebrew/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so 
/opt/homebrew/lib/python3.9/site-packages/psycopg2/_psycopg.cpython-39-darwin.so: Mach-O 64-bit bundle arm64
```
in the terminal gives a native/ARM library. The Homebrew provided Python is also ARM only (no universal binary).

**Comment by ThatGuySam** [comment]
Thanks for the report! 

There are currently 2 open issues for Apple SIlicon issues but things seem to work with Python 3 and/or other small workarounds

> Look like there's a similar open issue here:
> [psycopg/psycopg2#1216](https://github.com/psycopg/psycopg2/issues/1216)
> 
> Also, there seems to be an issue installing;
> [psycopg/psycopg2#1200](https://github.com/psycopg/psycopg2/issues/1200)


I'll go ahead and mark it as Native with workarounds until someone give a good justification for downgrading it's status.

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/psycopg2/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by nicholastulach** [comment]
> **An Official App Download Page**
> I installed it using `pip3 install psycopg2`, I had to install PostgreSQL via Homebrew (`brew install postgresql`).

I also had to install PostgreSQL via Homebrew, then ran `pip3 install psycopg2 --no-cache-dir` and that solved my issues (for now).
