### ISSUE TITLE
MacTex is now universal

### ISSUE THREAD

**Issue by exgphe** [ThatGuySam/doesitarm#629]
**The official name of the app**
MacTex

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**Related Issue Tracker Link or discussion**
http://www.tug.org/mactex/faq/index.html#qm08

**An Official App Download Page**
http://www.tug.org/mactex/mactex-download.html

**Additional context**
N/A

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="762" alt="Capture d’écran 2021-04-21 à 23 13 03" src="https://user-images.githubusercontent.com/14009450/115577592-25d0e100-a2f7-11eb-8e84-b97ca4c9126f.png">

**Comment by ThatGuySam** [comment]
Thanks for the update! 

The update is now live on the site! 

https://doesitarm.com/app/mactex/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
