### ISSUE TITLE
FL Studio

### ISSUE THREAD

**Issue by Arivval** [ThatGuySam/doesitarm#63]
**The official name of the app**
FL Studio

**An Official App Download Link**
https://www.image-line.com/fl-studio-download/

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by elChipardo** [comment]
**The official name of the app**
FL Studio

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
✳️ Yes, works via Rosetta 2 **ONLY for FL Studio version greater than 20.8 and might meet some performance issues**

**Proposed App Category**
Music and Audio tools

**Related Issue Tracker Link or discussion**
Official website: https://www.image-line.com
Source: https://support.image-line.com/action/knowledgebase/?ans=668

**An Official App Download Page**
https://www.image-line.com/fl-studio-download/

**Additional context**
⏹ Native version is in development (expected for Q2 2021)

**Comment by ThatGuySam** [comment]
For status let's simplify to: 
✳️ Yes, works via Rosetta 2 but may have performance issues

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by elChipardo** [comment]
Hi @ThatGuySam!

I’ll do it tmr. Thanks.

**Comment by ThatGuySam** [comment]
Good news! App is already live on the site! 

https://doesitarm.com/app/fl-studio/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by moffpage** [comment]
Hi! FL Studio has native Apple Silicon support from version 20.8.4:
Blog: https://support.image-line.com/action/knowledgebase/?ans=668
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/33549573/132121791-5238fd8f-c992-45a3-9dc4-1fe055860855.png">

Official website: https://www.image-line.com/fl-studio-download/
Direct macOS download link: https://support.image-line.com/redirect/flstudio20_mac_installer
<img width="427" alt="image" src="https://user-images.githubusercontent.com/33549573/132121835-a65a82d6-d4af-4fb3-9218-a0b102108cf4.png">

**Comment by ThatGuySam** [comment]
Good find @moffpage 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/fl-studio/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
