### ISSUE TITLE
AVTouchBar Native Apple Silicon Support

### ISSUE THREAD

**Issue by jake-fishtech** [ThatGuySam/doesitarm#630]
**The official name of the app**
AVTouchBar

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Fully native apple silicon support (however, needs a touch bar)

**Proposed App Category**
Music / Touch Bar

**Related Issue Tracker Link or discussion**
https://discord.gg/ZFw4XrGYQj

**An Official App Download Page**
https://www.avtouchbar.com

**Additional context**
Add any other context or screenshots about the app request here.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
Hi! I am the developer of AVTouchBar. I don't have a screen shot showing native support because I don't have an M1 mac, however, AVTouchBar is built to compile natively for apple silicon and I have plenty of M1 users. I would be happy to send you a license code to test the app yourself. Just shoot me an email at jake@avtouchbar.com and I'll get you a code. Thanks! Jake.

**Comment by ThatGuySam** [comment]
Hey @jake-fishtech nice to meet you and thanks for the report! 

We'll mark this as native for now until someone reports otherwise and can provide a screenshot

**Comment by jake-fishtech** [comment]
Nice to meet you too. And great - thanks Sam!

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/avtouchbar/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
