### ISSUE TITLE
Moonlight

### ISSUE THREAD

**Issue by exgphe** [ThatGuySam/doesitarm#631]
**The official name of the app**
Moonlight

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Entertainment and Media Apps

**Related Issue Tracker Link or discussion**
https://github.com/moonlight-stream/moonlight-qt/commit/ab25a9b8ee9ac20c0424a264461aceab26d2295e

**An Official App Download Page**
https://github.com/moonlight-stream/moonlight-qt/releases

**Additional context**
N/A

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

**Comment by exgphe** [comment]
I don't currently have an M1 Mac, waiting for others to add a screenshot if necessary.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks this app is reporting as Native via the [App Test](https://doesitarm.com/apple-silicon-app-test/) as well. 

<img width="1792" alt="Screen Shot 2021-04-26 at 11 36 58 AM" src="https://user-images.githubusercontent.com/2830379/116119348-f4a03a00-a683-11eb-877b-0cae92ed8c58.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/moonlight/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
