### ISSUE TITLE
Native Access 

### ISSUE THREAD

**Issue by kobiliusz** [ThatGuySam/doesitarm#633]
**The official name of the app**
Native Access

**Is there a supported version available on a stable release channel?**
No

**Proposed New App Status**
works on Rosetta (beta) - except for MassiveX

**Related Issue Tracker Link or discussion**
https://www.native-instruments.com/forum/forums/native-access.376/

**An Official App Download Page**
https://www.native-instruments.com/en/support/downloads/

**Additional context**
Native support is confirmed to be expected to be implemented this year https://www.native-instruments.com/forum/threads/ni-products-native-apple-sillicon-support.453297/#post-2087827

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
don't have one

**Comment by ThatGuySam** [comment]
Thanks for the report! Update is now live on the site! 

https://doesitarm.com/app/native-access/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
