### ISSUE TITLE
Amazon Music works with Rosetta2

### ISSUE THREAD

**Issue by ashwaniii** [ThatGuySam/doesitarm#634]
**The official name of the app**
Amazon Music

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✳️ Yes, works via Rosetta 2

**Related Issue Tracker Link or discussion**
NA

**An Official App Download Page**
https://music.amazon.com/EU/help/apps

**Additional context**
Version: 8.4.0.2249
![image](https://user-images.githubusercontent.com/33101255/116493166-c016c300-a8bb-11eb-8ec7-d81d6f3c2568.png)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![image](https://user-images.githubusercontent.com/33101255/116493231-e3417280-a8bb-11eb-8754-e0fce902d722.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/amazon-music/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by okachobi** [comment]
It does not work flawlessly.  The audio for HD Audio files pauses and cuts out repeatedly, even with files are stored locally (eliminating any network issues).   When I had an Intel mac it did not do this.
