### ISSUE TITLE
Android Studio officially supports Apple Silicon now

### ISSUE THREAD

**Issue by cristan** [ThatGuySam/doesitarm#635]
**The official name of the app**
Android Studio

**Is there a supported version available on a stable release channel?**
No (not on the stable release channel, but there is a preview version now)

**Proposed New App Status**
Preview version available starting at Arctic Fox Canary 15.

**Related Issue Tracker Link or discussion**
https://issuetracker.google.com/issues/179062806

**An Official App Download Page**
https://developer.android.com/studio/preview/index.html

**Additional context**
https://androidstudio.googleblog.com/2021/04/android-studio-arctic-fox-canary-15.html

**Comment by ThatGuySam** [comment]
Thanks for the report! App has been updated! 

https://doesitarm.com/app/android-studio/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by aman3014** [comment]
Arctic Fox is now in Beta 🎉
