### ISSUE TITLE
Spark Mail App - App Request

### ISSUE THREAD

**Issue by milo526** [ThatGuySam/doesitarm#636]
This might or might not be a duplicate of https://github.com/ThatGuySam/doesitarm/issues/28 however since that author does not seem to respond I opted to create a new issue following the proper template.

**The official name of the app**
Spark

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Yes, works via Rosetta 2

**Proposed App Category**
Productivity tools (its a mail client)

**Related Issue Tracker Link or discussion**
No useful issue tracker, last known state derived from tweet: https://twitter.com/SparkMailApp/status/1352653636581679104?s=20
Current state reported from personal experience

**An Official App Download Page**
https://sparkmailapp.com/download

**Additional context**
{Add any other context or screenshots about the app request here.}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Schermafbeelding 2021-05-02 om 22 28 50](https://user-images.githubusercontent.com/5261909/116826731-c8aa1a80-ab95-11eb-9fb3-04466ffe60ad.png)

Screenshot of the application self is not included since i'd rather not share my mails :P Let me know if you still need it or if this is enough.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/spark-mail/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by rmgomez** [comment]
Starting from v2.10.0 **Spark Mail** has added Apple Silicon Support

Official Twitter Link: https://twitter.com/SparkMailApp/status/1410624085072175110

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Full Screenshot with the App and Activity Monitor(if self reporting) or Silicon Info**
![spark-mail-m1](https://user-images.githubusercontent.com/158403/126775574-a6580774-b80a-4369-aa4c-48232278baae.png)

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/spark-mail/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
