### ISSUE TITLE
Add SheepShaver

### ISSUE THREAD

**Issue by AwesumIndustrys** [ThatGuySam/doesitarm#637]
**The official name of the app**
SheepShaver

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Developer Tools

**An Official App Download Page**
https://www.emaculation.com/forum/viewtopic.php?f=20&t=7360

**Comment by ThatGuySam** [comment]
Thanks for the App Request! App is now live on the site! 

https://doesitarm.com/app/sheepshaver/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
