### ISSUE TITLE
HCL Notes

### ISSUE THREAD

**Issue by Shanduur** [ThatGuySam/doesitarm#638]
**The official name of the app**
HCL Notes

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
🔶 Unknown, more info needed

**Proposed App Category**
Productivity

**Related Issue Tracker Link or discussion**
https://domino-ideas.hcltechsw.com/ideas/NTS-I-1496

**An Official App Download Page**
https://www.hcltechsw.com/products/nd

**Additional context**
N/A

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
N/A

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/hcl-notes/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
