### ISSUE TITLE
Update on Affinity Designer Support Version 1.8.6 is Fully Optimized for Apple M1

### ISSUE THREAD

**Issue by lpez** [ThatGuySam/doesitarm#64]
Affinity Photo, Affinity Designer, Affinity Publisher. All are fully optimized for Apple M1 according to the release notes.

![Screen Shot 2020-11-12 at 1 35 00 PM](https://user-images.githubusercontent.com/1802976/98968023-ed2d1000-24eb-11eb-8d93-8d1fb68c85f0.png)
Here's a link about it:

**Comment by ThatGuySam** [comment]
Thanks for the update!

I'm adding some extra links for context

Version 1.8.6 Release Notes
https://forum.affinity.serif.com/index.php?/topic/127202-affinity-suite-for-macos-186-release-notes/

Press Release
https://affinity.serif.com/en-us/press/newsroom/affinity-apps-accelerate-with-macos-big-sur-and-native-m1-support/

**Comment by ThatGuySam** [comment]
Updates are live!

https://doesitarm.com/app/affinity-designer/
https://doesitarm.com/app/affinity-photo/
https://doesitarm.com/app/affinity-publisher/
