### ISSUE TITLE
Shutter Encoder is now compatible with Apple Silicon (video/audio/image converter)

### ISSUE THREAD

**Issue by paulpacifico** [ThatGuySam/doesitarm#642]
**The official name of the app**
Shutter Encoder

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Yes, Full Native Apple Silicon Support

**Proposed App Category**
Video audio image converter

**Related Issue Tracker Link or discussion**
https://www.shutterencoder.com/changelog.html

**An Official App Download Page**
https://www.shutterencoder.com/en/#downloads

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![SE_Silicon](https://user-images.githubusercontent.com/46673657/117440758-c8fb3a80-af34-11eb-9a31-b86cf87e8e27.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! The App is now live on the site! 

https://doesitarm.com/app/shutter-encoder/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
