### ISSUE TITLE
Sndcpy

### ISSUE THREAD

**Issue by steliosaa** [ThatGuySam/doesitarm#645]
**The official name of the app**
{Sndcpy}

**Is there a supported version available on a stable release channel?**
{No}

**Proposed App Status**
{Unknown}

**Proposed App Category**
{Utilities}

**Related Issue Tracker Link or discussion**
{Unknown}

**An Official App Download Page**
{ https://github.com/rom1v/sndcpy }

**Additional context**
{Cast audio from an android device to your mac}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{As screenshot with Activity Monitor open showing the App's architecture type}

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

We've added a listing to the site for people to check and report on any updates on this: 

https://doesitarm.com/app/sndcpy/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by steliosaa** [comment]
The official name of the app
{Sndcpy}

Is there a supported version available on a stable release channel?
{No}

Proposed App Status
{Working}

Proposed App Category
{Utilities}

Related Issue Tracker Link or discussion
{https://github.com/rom1v/sndcpy/issues/131}

An Official App Download Page
{ https://github.com/rom1v/sndcpy }

Additional context
{Cast audio from an android device to your mac}

Full Screenshot with the App and Activity Monitor(if self reporting) or Silicon Info
{
![image](https://user-images.githubusercontent.com/26743665/118009070-06edc980-b34e-11eb-9c3a-2634bb3be636.png)
It works although not able to adjust the volume for some reason
}

**Comment by ThatGuySam** [comment]
Since this software is a shell script on the macOS side and Terminal is already a native Apple Silicon app I'm going to say we can call Sndcpy Native to Apple Silicon as it has no apparent issues currently: 
✅ Yes, Native Apple Silicon Support

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/sndcpy/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
