### ISSUE TITLE
Adobe Audition now supports M1 natively

### ISSUE THREAD

**Issue by exgphe** [ThatGuySam/doesitarm#646]
**The official name of the app**
Adobe Audition

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**Related Issue Tracker Link or discussion**
https://helpx.adobe.com/audition/user-guide.html/audition/using/whats-new/2021-1.ug.html

**An Official App Download Page**
https://www.adobe.com/products/audition.html

**Additional context**
N/A

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
N/A

**Comment by ThatGuySam** [comment]
Thanks for the report! Update is now live on the site! 

https://doesitarm.com/app/adobe-audition/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
