### ISSUE TITLE
TurboTax

### ISSUE THREAD

**Issue by coldnrainy** [ThatGuySam/doesitarm#647]
**The official name of the app**
TurboTax

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Runs via Rosetta with no immediate plans for native support

**Proposed App Category**
Productivity tools

**Related Issue Tracker Link or discussion**
[Forum discussion link](https://ttlc.intuit.com/community/taxes/discussion/re-turbotax-deluxe-under-macos-bigsur-on-macbook-air-apple-m1-chip-turbotax-app-doesn-t-open/01/2273549#M815580)

**An Official App Download Page**
[Downloads](https://turbotax.intuit.com/personal-taxes/cd-download/)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
Not available yet

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/turbotax/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
