### ISSUE TITLE
add DEVONthink 3

### ISSUE THREAD

**Issue by kklobe** [ThatGuySam/doesitarm#65]
**The official name of the app**
DEVONthink 3

**Proposed App Status**
Full native support as of 3.5.2

**Related Issue Tracker Link or discussion**
Blog post: https://www.devontechnologies.com/blog/20200814-devonthink-352

**An Official App Download Link**
https://www.devontechnologies.com/download/

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/devonthink

Feel free to browse through the other issues to help with missing info on other apps.
