### ISSUE TITLE
Potplayer

### ISSUE THREAD

**Issue by Jiyuuneko** [ThatGuySam/doesitarm#650]
**The official name of the app**
{Potplayer}

**Is there a supported version available on a stable release channel?**
{No}

**Proposed App Status**
{Unknown}

**Proposed App Category**
{Entertainment and Media Apps}

**Related Issue Tracker Link or discussion**
{}

**An Official App Download Page**
{https://potplayer.daum.net/}

**Additional context**
{Can it work with Madvr filter?}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{}

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Does this app have a macOS version?

**Comment by moffpage** [comment]
No, it doesn't. Why even open an issue on this? I think it should be closed.

**Comment by ThatGuySam** [comment]
@moffpage I kind of agree. 

If someone wants to test this with Parallels or some other virtualization I'll be happy to open this up again, but for now, it's closed.
