### ISSUE TITLE
draw.io - Native Support

### ISSUE THREAD

**Issue by BenAChilds** [ThatGuySam/doesitarm#651]
**The official name of the app**
draw.io

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
Yes, Full Native Apple Silicon Support

**Related Issue Tracker Link or discussion**
https://github.com/jgraph/drawio-desktop/releases/tag/v14.6.13

**An Official App Download Page**
https://github.com/jgraph/drawio-desktop/releases/

**Additional context**
None

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="743" alt="Screen Shot 2021-05-19 at 12 30 16 pm" src="https://user-images.githubusercontent.com/37315633/118747779-ff727700-b89d-11eb-8ccf-d394dbc16895.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/drawio/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
