### ISSUE TITLE
Magnet had Apple Silicon support in 2020

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#652]
**The official name of the app**
{Magnet}

**Is there a supported version available on a stable release channel?**
{Yes}

**Proposed New App Status**
{✅ Yes, Full Native Apple Silicon Support}

**Related Issue Tracker Link or discussion**
{Nope}

**An Official App Download Page**
{https://itunes.apple.com/WebObjects/MZStore.woa/wa/viewSoftware?id=441258766&mt=12}

**Additional context**
{<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/118759630-30997a00-b893-11eb-98bd-151721c4a1b2.png">}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{<img width="1190" alt="image" src="https://user-images.githubusercontent.com/33549573/118759682-4eff7580-b893-11eb-9100-a84675ca2338.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/118759678-4d35b200-b893-11eb-927a-d0b5db5d1391.png">}

**Comment by ThatGuySam** [comment]
Good catch! Thanks for the report! 

Update now live on the site! 

https://doesitarm.com/app/magnet-for-mac/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
