### ISSUE TITLE
ntfs-3g has Apple Silicon Support

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#654]
**The official name of the app**
ntfs-3g

**Is there a supported version available on a stable release channel?**
Unknown

**Proposed New App Status**
🔶 Unknown, more info needed

**Related Issue Tracker Link or discussion**
None yet

**An Official App Download Page**
http://macntfs-3g.blogspot.com/2010/10/ntfs-3g-for-mac-os-x-2010102.html?m=1

**Additional context**

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
None yet

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Is there a less sketchy download page that we can use? 

This directs me to a fake Mac App Store which then sent me to a page to update Flash Player. 

<img width="1792" alt="Screen Shot 2021-05-19 at 12 33 21 PM" src="https://user-images.githubusercontent.com/2830379/118858368-b5d65c00-b89e-11eb-91f6-cb74cf5d1a1f.png">

<img width="1792" alt="Screen Shot 2021-05-19 at 12 33 14 PM" src="https://user-images.githubusercontent.com/2830379/118858380-b8d14c80-b89e-11eb-9b01-30e92e7d1b34.png">

Also, which version of NTFS 3G is this? Is there a secondary site that explains it?

**Comment by moffpage** [comment]
Hi! Yeah, very sorry about that. I don't even know where to start damn :D
How about Wikipedia?) Referring to this page: https://en.wikipedia.org/wiki/NTFS-3G 
"NTFS-3G was introduced by one of the senior Linux NTFS developers, Szabolcs Szakacsits, in July 2006. The developers of NTFS-3G later formed a company, Tuxera Inc., to further develop the code. NTFS-3G is now the free "community edition", while Tuxera NTFS is the proprietary version."
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/33549573/120473601-02568700-c3c9-11eb-90a3-4e2a7c0b21ea.png">

Linux man page for NTFS-3G: https://linux.die.net/man/8/ntfs-3g refers to Tuxera's website for support as well:
<img width="875" alt="image" src="https://user-images.githubusercontent.com/33549573/120474961-9f65ef80-c3ca-11eb-96ad-b30cc6fcd669.png"> 


 "NTFS-3G is an open-source cross-platform implementation of the Microsoft Windows NTFS file system with read/write support. NTFS-3G often uses the FUSE file system interface, so it can run unmodified on many different operating systems." from Wikipedia, if we go to OS X FUSE GitHub: https://github.com/osxfuse/osxfuse/wiki/NTFS-3G
<img width="903" alt="image" src="https://user-images.githubusercontent.com/33549573/120475239-eb189900-c3ca-11eb-88a0-2f6f1752ec2e.png">

Tuxera's own website https://www.tuxera.com/company/open-source/ states:
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/33549573/120475427-287d2680-c3cb-11eb-984a-f8da9016cc8c.png">
<img width="577" alt="image" src="https://user-images.githubusercontent.com/33549573/120475447-2dda7100-c3cb-11eb-957f-953c369e27c1.png">
The second image shows a button that has a download link for macOS: https://sourceforge.net/projects/ntfs-3g/
As well as https://macntfs-3g.blogspot.com:
<img width="587" alt="image" src="https://user-images.githubusercontent.com/33549573/120475663-7a25b100-c3cb-11eb-9b5d-426fa0a5917e.png">

**Comment by moffpage** [comment]
@ThatGuySam Any more info needed?

**Comment by ThatGuySam** [comment]
I see a lot of links but I can't seem to find anywhere to download binaries or installable apps. 

What is there a direct download link to a file we can test for compatibility?

**Comment by moffpage** [comment]
"The second image shows a button that has a download link for macOS: https://sourceforge.net/projects/ntfs-3g/"

**Comment by ThatGuySam** [comment]
Maybe I'm missing something obvious but I'm still not seeing a place to download a binary

https://sourceforge.net/projects/ntfs-3g/

<img width="1792" alt="Screen Shot 2021-06-09 at 10 43 53 AM" src="https://user-images.githubusercontent.com/2830379/121386761-d3339e80-c90f-11eb-9452-3b58689d2df8.png">

**Comment by moffpage** [comment]
http://macntfs-3g.blogspot.com/2010/10/ntfs-3g-for-mac-os-x-2010102.html?m=1



Download link: http://sourceforge.net/projects/catacombae/files/NTFS-3G%20for%20Mac%20OS%20X/2010.10.2/ntfs-3g-2010.10.2-macosx.dmg/download

**Comment by ThatGuySam** [comment]
Okay, I was able to download that package.

Itt looks like the ntfs-3g binary only supports i386 and ppc architectures. 

If it works on Apple Silicon it would likely be via Rosetta 2 since it has no arm64 architecture support. 

For now I'm going to go ahead and list it as: 
🔶 App has not yet been reported to be native to Apple Silicon

<img width="682" alt="Screen Shot 2021-06-09 at 12 05 11 PM" src="https://user-images.githubusercontent.com/2830379/121399110-ba30ea80-c91b-11eb-8744-0e1a679bea9c.png">

**Comment by ThatGuySam** [comment]
Actually, it looks like ntfs-3g has already been listed via Homebrew: 
https://doesitarm.com/formula/ntfs-3g/

**Comment by moffpage** [comment]
Damn. I’m gonna check if it’s the other binary if installed via Homebrew (probably not, anyway seems like it wasn’t supported for almost 10 years lmao).

**Comment by ThatGuySam** [comment]
Closing this issue
