### ISSUE TITLE
Sublime Text 4 (build moved to stable channel)

### ISSUE THREAD

**Issue by milo526** [ThatGuySam/doesitarm#656]
Replace the text inside the {}'s with your own. 

**The official name of the app**
Sublime Text 4

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
Yes, Full Native Apple Silicon Support

**Related Issue Tracker Link or discussion**
https://www.sublimetext.com/blog/articles/sublime-text-4

**An Official App Download Page**
https://www.sublimetext.com

**Additional context**
[The currently reported state](https://doesitarm.com/app/sublime-text/) specifies the build that introduced native support; 
Today Sublime Text 4 got a public release, which makes this app supported on a stable channel.

I propose to change the accompanying text to "as of Sublime Text 4"

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
I don't believe this to be necessary; the build is still the same (see provided download link); this build simply moved to a stable channel.

**Comment by ThatGuySam** [comment]
Gotchu fam: https://doesitarm.com/app/sublime-text/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
