### ISSUE TITLE
Swann HomeSafe View

### ISSUE THREAD

**Issue by BenAChilds** [ThatGuySam/doesitarm#657]
**The official name of the app**
Swann HomeSafe View

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Yes, works via Translation or Virtualization

**Proposed App Category**
VPNs, Security, and Privacy

**Related Issue Tracker Link or discussion**
https://support.swann.com/s/article/NcSSjCM8VF

**An Official App Download Page**
https://support.swann.com/s/article/NcSSjCM8VF

**Additional context**
Swann are very lacking with their change logs and updates. Current version is 1.4.17 and works via Intel virtualizaton. It is unknown the status of their ARM native development.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="785" alt="Screen Shot 2021-05-22 at 11 27 33 am" src="https://user-images.githubusercontent.com/37315633/119210807-b155b180-baf1-11eb-8f7e-4dc6c7c58664.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/homesafe-view/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
