### ISSUE TITLE
Cisco Packet Tracer

### ISSUE THREAD

**Issue by Madhawa97** [ThatGuySam/doesitarm#658]
**The official name of the app**
Cisco Packet Tracer

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Runs via Rosetta 

**Proposed App Category**
Uncategorized

**Related Issue Tracker Link or discussion**
not found

**An Official App Download Page**
https://www.netacad.com/courses/packet-tracer

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1680" alt="Screenshot 2021-05-22 at 08 54 41" src="https://user-images.githubusercontent.com/70215958/119213456-cecc5080-badc-11eb-872d-9161bda2aaa8.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/cisco-packet-tracer/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by louise-annee** [comment]
Hello, I can't run Packet Tracer on my Mac m3 Pro. When installed, I run the app, then a window appears with "Would you like to run multi-user when application starts?", and whether I press "Yes" or "No", the app closes and nothing else happens. 
I tried with previous versions and it's the same.

**Comment by zampierilucas** [comment]
I have the same issue as @louise-annee on an M1 Max, the latest version, 8.2.2 atm, crashed on opening, fortunately I was able to find version 8.0.1 on arquive.org, https://archive.org/details/cisco-packet-tracer-801, and that is works fine.
