### ISSUE TITLE
Foxit reader

### ISSUE THREAD

**Issue by Madhawa97** [ThatGuySam/doesitarm#659]
**The official name of the app**
Foxit Reader

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Runs via Rosetta

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Link or discussion**
not found

**An Official App Download Page**
https://apps.apple.com/lk/app/foxit-reader/id1032155965?mt=12

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1680" alt="Screenshot 2021-05-22 at 13 01 37" src="https://user-images.githubusercontent.com/70215958/119218433-e1a34d00-bafd-11eb-9a91-99949d0754cc.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/foxit-reader/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by Madhawa97** [comment]
You're welcome 💪🏼
