### ISSUE TITLE
add BBEdit

### ISSUE THREAD

**Issue by kklobe** [ThatGuySam/doesitarm#66]
**The official name of the app**
BBEdit

**Proposed App Status**
Full native support as of 13.5

**Related Issue Tracker Link or discussion**
Release notes: https://www.barebones.com/support/bbedit/notes-13.5.html

**An Official App Download Link**
https://www.barebones.com/products/bbedit/download.html

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/bbedit/

Feel free to browse through the other issues to help with missing info on other apps.

![IMG_0111](https://user-images.githubusercontent.com/2830379/99193115-7c306700-273c-11eb-8eef-937b44f5249a.png)
