### ISSUE TITLE
Samsung Portable SSD for T7 | T7 touch

### ISSUE THREAD

**Issue by Madhawa97** [ThatGuySam/doesitarm#660]
**The official name of the app**
Samsung Portable SSD for T7 | T7 touch

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Uncategorized

**An Official App Download Page**
https://www.samsung.com/semiconductor/minisite/ssd/download/portable/

**Additional context**

1. Get the version called "Portable SSD Software 1.0 for Mac (The macOS Big Sur user's only)"
2. Users may need to change the Security Policy for "Macintosh HD" to "Reduced security" in order to work.
Guide:  https://s3.ap-northeast-2.amazonaws.com/global.semi.static/Troubleshooting+Guide+for+macOS+Compatibility+Official_Rev.1.1.pdf

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1680" alt="Screenshot 2021-05-22 at 13 26 15" src="https://user-images.githubusercontent.com/70215958/119219892-69d92080-bb05-11eb-8c9c-9be6082d9f58.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/samsung-portable-ssd/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by Madhawa97** [comment]
You're welcome 💪🏼

**Comment by Madhawa97** [comment]
You're welcome 💪🏼

**Comment by Madhawa97** [comment]
You're welcome 💪🏼
