### ISSUE TITLE
Infuse is now native on M1

### ISSUE THREAD

**Issue by exgphe** [ThatGuySam/doesitarm#661]
**The official name of the app**
Infuse

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**Related Issue Tracker Link or discussion**
https://community.firecore.com/t/infuse-macos-public-beta-updated-5-5-21/24328

**An Official App Download Page**
https://apps.apple.com/app/infuse-7/id1136220934

**Additional context**
N/A

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
N/A

**Comment by moffpage** [comment]
That's great news!

**Comment by ThatGuySam** [comment]
Thanks for the report @exgphe!

Update is now live on the site! 

https://doesitarm.com/app/infuse/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
