### ISSUE TITLE
Shotcut

### ISSUE THREAD

**Issue by foxmean** [ThatGuySam/doesitarm#662]
**The official name of the app**
Shotcut

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
 ✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Video and Motion Tools

**Related Issue Tracker Link or discussion**
Not found

**An Official App Download Page**
https://shotcut.org/download/

**Full Screenshot with the App and Activity Monitor**
<img width="1440" alt="Screen Shot 2021-05-23 at 02 11 40" src="https://user-images.githubusercontent.com/13077459/119238358-3b426080-bb6c-11eb-9b53-3fceea5aa3d5.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/shotcut/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
