### ISSUE TITLE
Scrivener 3

### ISSUE THREAD

**Issue by LucasCampos** [ThatGuySam/doesitarm#663]
**The official name of the app**
Scrivener 3

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity

**An Official App Download Page**
https://www.literatureandlatte.com/scrivener/download

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

<img width="1553" alt="image" src="https://user-images.githubusercontent.com/2735358/119239254-2522a900-bb48-11eb-9dab-9a76e495d9b0.png">

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/2735358/119239265-366bb580-bb48-11eb-80f8-59c8cdf79b56.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/scrivener/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
