### ISSUE TITLE
TrashMe 3

### ISSUE THREAD

**Issue by MdZaf** [ThatGuySam/doesitarm#664]
**✅ Yes, native apple silicon support**

**The official name of the app**
TrashMe 3

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Full Native Apple Silicon Support

**Proposed App Category**
System Tools

**Related Issue Tracker Link or discussion**
none

**An Official App Download Page**
https://www.jibapps.com/apps/trashme3/

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="265" alt="image" src="https://user-images.githubusercontent.com/84469113/119261469-9c0f7e80-bbe8-11eb-87f3-8e8ff6479e9c.png">
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/84469113/119261494-bba6a700-bbe8-11eb-8d09-f90592031de2.png">
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/84469113/119261507-c95c2c80-bbe8-11eb-8280-039f2eb959d2.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/trashme-3/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
