### ISSUE TITLE
Folx

### ISSUE THREAD

**Issue by MdZaf** [ThatGuySam/doesitarm#665]
**The official name of the app**
{Folx}

**Is there a supported version available on a stable release channel?**
{No}

**Proposed App Status**
{✳️ Runs via Rosetta with native support not reported to be in development}

**Proposed App Category**
{Productivity}

**An Official App Download Page**
{https://mac.eltima.com/download-manager.html}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/84469113/119261700-9cf4e000-bbe9-11eb-80f6-bb55f53336e3.png">
}

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/folx/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
