### ISSUE TITLE
Speedtest by Ookla

### ISSUE THREAD

**Issue by MdZaf** [ThatGuySam/doesitarm#666]
**The official name of the app**
{Speedtest by Ookla}

**Is there a supported version available on a stable release channel?**
{Yes}

**Proposed App Status**
{✅ Yes, native apple silicon support}

**Proposed App Category**
{System Tools}

**An Official App Download Page**
{https://apps.apple.com/ae/app/speedtest-by-ookla/id1153157709?mt=12}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{<img width="1414" alt="image" src="https://user-images.githubusercontent.com/84469113/119261845-4b008a00-bbea-11eb-849f-e8331d5c0374.png">}

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/speedtest-by-ookla/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
