### ISSUE TITLE
TP-LINK DECO

### ISSUE THREAD

**Issue by MdZaf** [ThatGuySam/doesitarm#667]
**The official name of the app**
Tp Link - DECO
**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Native apple silicon support (iPadOS app)

**Proposed App Category**
Productivity

**An Official App Download Page**
https://apps.apple.com/ae/app/tp-link-deco/id1186159417

**Additional context**
Window is not resizable

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/84469113/119262089-07f2e680-bbeb-11eb-9eb7-c0eb5f196d12.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/tp-link-deco/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
