### ISSUE TITLE
GEMS CONNECT

### ISSUE THREAD

**Issue by MdZaf** [ThatGuySam/doesitarm#668]
**The official name of the app**
GEMS CONNECT

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, native apple silicon support

**Proposed App Category**
Productivity

**An Official App Download Page**
https://apps.apple.com/ae/app/gems-connect/id1462613346

**Additional context**
iPadOS application, not resizable windows

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/84469113/119262190-61f3ac00-bbeb-11eb-8c38-6ef13fbaf006.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/gems-connect/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
