### ISSUE TITLE
Elmedia Player Support

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#669]
**The official name of the app**
Elmedia Player

**Is there a supported version available on a stable release channel?**
{No}

**Proposed New App Status**
✳️ Yes, works via Translation or Virtualization

**Related Issue Tracker Link or discussion**
nothing

**An Official App Download Page**
https://www.elmedia-video-player.com

**Additional context**

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/119291531-6d3ceb00-bc70-11eb-8ad6-1a9fe0427608.png">

**Comment by moffpage** [comment]
Lmao that's actually more like an app request than an update, do I need to resubmit it? Please don't force :DDD. Thanks for building this amazing service and community around it

**Comment by ThatGuySam** [comment]
This is fine for now, but in the future, your screenshot will need to include Activity Monitor so we can verify that the app is launchable and runs under Rosetta 2 translation

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/elmedia-player/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by jenslys** [comment]
Elmedia is now natively compatible with Apple M1.
Sources:
- https://www.elmedia-video-player.com/
- https://apps.apple.com/us/app/elmedia-video-player/id1044549675?mt=12

**Comment by moffpage** [comment]
Great!

**Comment by moffpage** [comment]
@jenslys maybe you could issue a website update?
