### ISSUE TITLE
add Hopper Disassembler

### ISSUE THREAD

**Issue by kklobe** [ThatGuySam/doesitarm#67]
**The official name of the app**
Hopper Disassembler

**Proposed App Status**
Full native support as of 4.6.0

**Related Issue Tracker Link or discussion**
Blog post: https://www.hopperapp.com/blog/?p=263

**An Official App Download Link**
https://www.hopperapp.com/download.html

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/hopper-disassembler

Feel free to browse through the other issues to help with missing info on other apps.
