### ISSUE TITLE
Apollo One Update

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#670]
**The official name of the app**
ApolloOne

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**Related Issue Tracker Link or discussion**
there are, but they're all finished

**An Official App Download Page**
https://apps.apple.com/us/app/apolloone-photo-video-viewer/id1044484672?mt=12

**Additional context**
<img width="262" alt="image" src="https://user-images.githubusercontent.com/33549573/119270710-d5171580-bc1f-11eb-906e-afa8f42d38c3.png">
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/33549573/119270718-d7796f80-bc1f-11eb-9898-33d5611580c9.png">

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{<img width="1187" alt="image" src="https://user-images.githubusercontent.com/33549573/119291857-0835c500-bc71-11eb-8cad-a4db7d22509e.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/119291852-066c0180-bc71-11eb-940b-36e0fe9581dd.png">}

**Comment by moffpage** [comment]
This one ain't an update but a request too lmao

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/apolloone/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
