### ISSUE TITLE
balenaEtcher Support

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#671]
```
**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support
```
**The official name of the app**
{balenaEtcher}

**Is there a supported version available on a stable release channel?**
{Yes}

**Proposed App Status**
{✅ Yes, Full Native Apple Silicon Support}

**Proposed App Category**
{Utilities}

**Related Issue Tracker Link or discussion**
{https://forums.balena.io/t/development-on-apple-silicon/185450}

**An Official App Download Page**
{https://www.balena.io/etcher/}

**Additional context**
{For some reason they haven't updated the status on their forum ¯\_(ツ)_/¯ }

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{<img width="1191" alt="image" src="https://user-images.githubusercontent.com/33549573/119292336-ff91be80-bc71-11eb-8276-5b90b179e86b.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/119292331-fdc7fb00-bc71-11eb-9306-4e17693f21b5.png">}

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/balenaetcher/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by AngelofWoe** [comment]
The Universal / M1 version of balenaEtcher was removed and only the Intel version is still available for download.

**Comment by ThatGuySam** [comment]
Thanks for the update! 

It is now live on the site! 

https://doesitarm.com/app/balenaetcher/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
