### ISSUE TITLE
PDFpen

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#672]
```
**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support
```
**The official name of the app**
PDFpen

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity

**Related Issue Tracker Link or discussion**

**An Official App Download Page**
https://pdfpen.com/pdfpen/
https://pdfpen.com/pdfpen/download/

**Additional context**
There's also a Pro version that also has Apple Silicon support

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/33549573/119292923-2e5c6480-bc73-11eb-962f-8e1943fccaee.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/119292924-30262800-bc73-11eb-86be-d6c46f693abb.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/pdfpen/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
