### ISSUE TITLE
PDFpenPro

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#673]
```
**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support
```
**The official name of the app**
{PDFPenPro}

**Is there a supported version available on a stable release channel?**
{Yes}

**Proposed App Status**
{✅ Yes, Full Native Apple Silicon Support}

**Proposed App Category**
{Productivity}

**Related Issue Tracker Link or discussion**
{}

**An Official App Download Page**
{https://pdfpen.com/pdfpenpro/
https://pdfpen.com/pdfpen/download/}

**Additional context**
{}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{<img width="1187" alt="image" src="https://user-images.githubusercontent.com/33549573/119293069-809d8580-bc73-11eb-9c8c-bbeffe521572.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/119293078-82ffdf80-bc73-11eb-8833-18c966bae8ec.png">}

**Comment by ThatGuySam** [comment]
We'll say this one counts as both since these apps are usually built from the same binaries: 
https://doesitarm.com/app/pdfpen/
