### ISSUE TITLE
Reeder 5

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#674]
**The official name of the app**
Reeder 5

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**Related Issue Tracker Link or discussion**

**An Official App Download Page**
https://reederapp.com
https://itunes.apple.com/app/id1529448980

**Additional context**
https://appleinsider.com/articles/21/02/05/state-of-apple-silicon---half-of-the-most-popular-mac-apps-still-need-rosetta
<img width="874" alt="image" src="https://user-images.githubusercontent.com/33549573/119294100-86946600-bc75-11eb-810d-c70d78e59281.png">
https://maconarm.com/app/reeder

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
Can't provide that because the app is only available through purchasing and I'm not interested in that, however it seems like it has Apple Silicon support (refer to additional context)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/reeder/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
