### ISSUE TITLE
Expandrive

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#675]
**The official name of the app**
ExpanDrive

**Is there a supported version available on a stable release channel?**
No

**Proposed New App Status**
✳️ Yes, works via Translation or Virtualization

**Related Issue Tracker Link or discussion**

**An Official App Download Page**
https://www.expandrive.com/desktop/

**Additional context**

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1186" alt="image" src="https://user-images.githubusercontent.com/33549573/119294665-cc056300-bc76-11eb-8864-a73b7e8e4c1f.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/119294662-cad43600-bc76-11eb-8ad4-5a619fdce49e.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/expandrive/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
