### ISSUE TITLE
Dashlane

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#676]
**The official name of the app**
{Dashlane}

**Is there a supported version available on a stable release channel?**
{No}

**Proposed New App Status**
{✳️ Yes, works via Translation or Virtualization}

**Related Issue Tracker Link or discussion**
{https://www.reddit.com/r/Dashlane/comments/k3fwt4/dashlane_for_m1/
<img width="914" alt="image" src="https://user-images.githubusercontent.com/33549573/119298148-3cfc4900-bc7e-11eb-8f1d-e122d0225ffb.png"> seems like we might never have an update}

**An Official App Download Page**
{https://www.dashlane.com}

**Additional context**
{Dashlane is weird. It has a desktop app, but if we believe the commented on the reddit forum (I'm not interested in finding their marketing material where they say explicitly they're gonna migrate to an online-based system, maybe they were somewhat it forever, but in general seems like it's an online service). It has two Safari browser extensions:
<img width="349" alt="image" src="https://user-images.githubusercontent.com/33549573/119298769-7d0ffb80-bc7f-11eb-8d25-8b1f1f103a40.png">
<img width="344" alt="image" src="https://user-images.githubusercontent.com/33549573/119298775-800aec00-bc7f-11eb-9f72-fd1dc4d148e2.png">
one of which has Apple Silicon support and the other one doesn't. They're also listen on App Store with different IAP options:
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/33549573/119298795-8b5e1780-bc7f-11eb-8f07-e9888a0e86de.png">
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/33549573/119298797-8d27db00-bc7f-11eb-80b2-9fa7989c850f.png">
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/33549573/119298804-90bb6200-bc7f-11eb-9c53-4e747239964b.png">
<img width="1118" alt="image" src="https://user-images.githubusercontent.com/33549573/119298818-97e27000-bc7f-11eb-83bb-282cd82d6371.png">
 which is strange. I made an account with basic plan which limits me to a single device usage, I couldn't somehow log in to my account in the desktop app (Desktop App Preferences -> Account -> Download an existing account (tapped and nothing happens, just dismisses the window and that's it) and from one of the extensions, but the other one worked:
<img width="376" alt="image" src="https://user-images.githubusercontent.com/33549573/119298728-68336800-bc7f-11eb-94f9-4d189e588061.png">
<img width="408" alt="image" src="https://user-images.githubusercontent.com/33549573/119298730-69649500-bc7f-11eb-8849-998a4ea210e3.png">
Also, it seemed like the desktop app came with an extension, but it removed itself from Safari extensions list when I got a notification that an update is available:
<img width="378" alt="image" src="https://user-images.githubusercontent.com/33549573/119298918-cd875900-bc7f-11eb-84bb-27c5e7a80715.png">
I then downloaded two Safari extensions and wrote this issue}

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
{<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/119298253-76cd4f80-bc7e-11eb-84b8-dd59fdfec4b8.png"> - This is the desktop app
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/33549573/119298293-877dc580-bc7e-11eb-9364-21cb4d1858d6.png"> - Desktop app + Safari Extension that doesn't have Apple Silicon support (aka just "Dashlane" Safari extensions)
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/33549573/119298322-9ebcb300-bc7e-11eb-8759-815c745c3386.png"> - Safari extension that HAS Apple Silicon support ("Dashlane for Safari" Safari Extension)}

**Comment by ThatGuySam** [comment]
It seems as though Dashlane has partially updated their app but is still working on getting the core parts working Natively. 

For now, let's say Rosetta 2 translation until they have all of their main application pieces running native: 
✳️ Yes, works via Rosetta 2 translation

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/dashlane/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by bradw** [comment]
Dashlane is no longer a desktop app. They have committed to being purely a browser extension platform and have said they are outright not updating the app any longer. You'd have a hard job even finding a download for the app as the website will just prompt you to install the extension.

For that reason I don't see why it should exist on doesitarm, and certainly shouldn't be labeled as working via Rosetta because in reality it works on Apple Silicon if you're using a browser built for it. 

Since OP "wasn't interested" in finding evidence of Dashlane saying this, I spent 5 minutes of my life finding it: 
https://blog.dashlane.com/web-first-faq/

**Comment by ThatGuySam** [comment]
We are in summer 2021 and that is a date they mention as starting to drop support for the desktop app so I've gone ahead and upgraded it to native: 

https://doesitarm.com/app/dashlane/
