### ISSUE TITLE
MYOB Account Edge Pro

### ISSUE THREAD

**Issue by GW61** [ThatGuySam/doesitarm#678]
What's the full official name of the app
MYOB Account Edge Pro v16

Yes or No
No

What's the current app status based off of current discussion or testing
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend
N/A

What category should the app go under
Productivity Tools

This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes.
None

This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site. 
https://download.myob.com/au/AccountEdge/16.0.0/AccountEdge_Pro_v16.dmg.zip?_ga=2.7702258.1700005420.1621993797-254355686.1617690577

Add any other context or screenshots about the app request here. 
x86 32bit app on Mojave now needed on M1 Big Sur

A screenshot with Activity Monitor open showing the App's architecture type. Example: #358
To Come

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by moffpage** [comment]
https://www.myob.com/au/accounting-software/accountedge
<img width="602" alt="image" src="https://user-images.githubusercontent.com/33549573/123587708-7ccbc880-d808-11eb-9753-52dcf8eb217a.png">

**Comment by ThatGuySam** [comment]
That's helpful to know. 

We'll use the following status:
🚫 No, not yet supported only works on Intel-based Macs

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/accountedge-pro/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
