### ISSUE TITLE
Boom3D now native :--)

### ISSUE THREAD

**Issue by wazar** [ThatGuySam/doesitarm#679]
The official name of the app
Boom3D

Is there a supported build available on a public/release channel?
Yes

Proposed App Status
✅ Yes, Full Native Apple Silicon Support

Proposed App Category
Audio EQ and 3D surround

An Official App Download Page
https://www.globaldelight.com/boom/

Full Screenshot with the App and Activity Monitor(if self reporting) or Silicon Info
https://i.imgur.com/rWqeVon.png
![boom](https://user-images.githubusercontent.com/16022906/120105987-8acff000-c15b-11eb-97a5-731044075c85.png)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/boom-3d/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
