### ISSUE TITLE
Update on OpenJDK Support

### ISSUE THREAD

**Issue by kklobe** [ThatGuySam/doesitarm#68]
Here's a link about it: 

https://github.com/microsoft/openjdk-aarch64/releases/tag/16-ea%2B10-macos

**Comment by ThatGuySam** [comment]
Thanks for update! 

Here's a press release from another issue
https://www.azul.com/press_release/azul-announces-support-of-java-builds-of-openjdk-for-apple-silicon/

**Comment by kklobe** [comment]
Great! Just wanted to add the update with a link to actual bits.

**Comment by ThatGuySam** [comment]
Updated!

https://doesitarm.com/app/openjdk/
