### ISSUE TITLE
AdLock

### ISSUE THREAD

**Issue by ArinaGridasova** [ThatGuySam/doesitarm#680]
**The official name of the app**
[AdLock](https://adlock.com/)

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Links or discussion**
https://adlock.com/blog/adlock-for-m1-chip/

**An Official App Download Page**
https://adlock.com/adlock-for-macos/

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![AdLockM1](https://user-images.githubusercontent.com/48602417/120300367-87ac3f80-c2d4-11eb-9ca4-2a83debf7f9e.png)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/adlock/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
