### ISSUE TITLE
melonDS

### ISSUE THREAD

**Issue by AwesumIndustrys** [ThatGuySam/doesitarm#681]
**The official name of the app**
melonDS

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Emulators

**Related Issue Tracker Links or discussion**
https://github.com/Arisotura/melonDS

**An Official App Download Page**
http://melonds.kuribo64.net/downloads.php

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/melonds/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
