### ISSUE TITLE
Reveal

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#682]
**The official name of the app**
Reveal

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Developer Tools

**Related Issue Tracker Links or discussion**
none, but they post release notes: https://revealapp.com/updates/28/ (they brought support for Apple Silicon in v28, v29 updated the design and made the app run faster and smoother

**An Official App Download Page**
https://revealapp.com
https://revealapp.com/free-trial/

**Additional context**
<img width="438" alt="image" src="https://user-images.githubusercontent.com/33549573/120427827-7591d600-c394-11eb-8b6b-eba04645427e.png">
<img width="905" alt="image" src="https://user-images.githubusercontent.com/33549573/120427821-7460a900-c394-11eb-8c6c-71cdf2227b5c.png">

P.S. they gotta update the binaries being downloaded through Homebrew, cause right now it downloads v26 which lacks new macOS Big Sur 11 compatible design and Apple Silicon support.
<img width="644" alt="image" src="https://user-images.githubusercontent.com/33549573/120428157-fbae1c80-c394-11eb-9773-81133ae5e8ee.png">

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/33549573/120428378-58113c00-c395-11eb-9074-84ccb95adac0.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/120428376-56e00f00-c395-11eb-90d2-9ccbce1d9814.png">

P.S. finally a new rounded corners square icon! Lovely)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/reveal-app/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
