### ISSUE TITLE
Logitech G Hub/lghub/Logi GHub

### ISSUE THREAD

**Issue by Hello9999901** [ThatGuySam/doesitarm#683]
Replace each second line your own text. 

**The official name of the app**
Logitech G Hub
sometimes called lghub or Logi GHub

**Is there a supported version available on a stable release channel?**
No

**Proposed New App Status**
✳️ Yes, works via Translation or Virtualization
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend

**Related Issue Tracker Links or discussion**
https://isapplesiliconready.com/app/Logitech%20G%20HUB

**An Official App Download Page**
https://www.logitechg.com/en-us/innovation/g-hub.html

**Additional context**
This app is sometimes buggy and requires a restart of the computer to work sometimes.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Screen Shot 2021-06-05 at 10 33 55 AM](https://user-images.githubusercontent.com/61983584/120895115-8a1adc00-c5e9-11eb-96e7-460824bf1b42.png)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

Logitech G HUB

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
