### ISSUE TITLE
Colibri

### ISSUE THREAD

**Issue by drummingdemon** [ThatGuySam/doesitarm#684]
Replace each second line your own text. 

For a great example issue check out #358

--------- Delete this line and everything above it before submitting ---------

**The official name of the app**
Colibri

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Music and Audio Tools

**Related Issue Tracker Links or discussion**

**An Official App Download Page**
[Mac AppStore](https://itunes.apple.com/us/app/colibri/id1178295426?ls=1&mt=12)

**Additional context**

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1215" alt="Screenshot 2021-06-06 at 17 36 48" src="https://user-images.githubusercontent.com/286512/120930524-e49d6080-c6ed-11eb-9c90-e337d92df4a4.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

App is now live on the site! 

https://doesitarm.com/app/colibri/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
