### ISSUE TITLE
Roblox

### ISSUE THREAD

**Issue by MischievousMoo** [ThatGuySam/doesitarm#685]
**The official name of the app**
Roblox
Roblox Player

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
✳️ Yes, works via Translation or Virtualization

**Proposed App Category**
Entertainment and Media Apps
Games

**Related Issue Tracker Links or discussion**
https://www.reddit.com/r/macgaming/comments/lymrje/running_roblox_on_the_m1_macbook_pro/

**An Official App Download Page**
https://www.roblox.com/games/54865335/view?rbxp=70385145

**Additional context**
Click play to download.
Shift + F5 in Roblox to view FPS.
Graphics can be adjusted by hitting Escape > Settings > Graphics Mode and Graphics Quality.
In the Roblox game Ultimate Driving: Westover Islands, it is most laggy in Westover.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/roblox-player/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
