### ISSUE TITLE
Roblox Studio

### ISSUE THREAD

**Issue by MischievousMoo** [ThatGuySam/doesitarm#686]
**The official name of the app**
Roblox Studio

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
🔶 Unknown, more info needed

**Proposed App Category**
Entertainment and Media Apps
Games

**Related Issue Tracker Links or discussion**
https://talk.macpowerusers.com/t/roblox-and-roblox-studio-on-the-m1-chip/20372

**An Official App Download Page**
https://www.roblox.com/create?rbxp=70385145

**Additional context**
Click Start Creating to download Roblox Studio.
Click + New in the top left corner to create a new game
Choose a baseplate
Use right-click drag, middle-click drag, scroll, and W, A, S, D, and E, Q, to move around

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/robloxstudio/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
