### ISSUE TITLE
AppCode

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#687]
**The official name of the app**
AppCode

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Developer Tools

**Related Issue Tracker Links or discussion**
https://youtrack.jetbrains.com/issue/OC-20291

**An Official App Download Page**
https://www.jetbrains.com/objc/download/?_ga=2.34284833.1069855302.1609076624-340071760.1603709570

**Additional context**
https://blog.jetbrains.com/objc/2021/01/appcode-2020-3-1/

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1275" alt="image" src="https://user-images.githubusercontent.com/33549573/120957610-d1cf6e00-c777-11eb-9c99-0f40b4a4bb7f.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/120957607-d09e4100-c777-11eb-8bc9-2b8536bcafec.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/appcode/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
