### ISSUE TITLE
MPS

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#688]
**The official name of the app**
MPS

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Developer Tools

**Related Issue Tracker Links or discussion**

**An Official App Download Page**
https://www.jetbrains.com/mps/download/#section=mac

**Additional context**
https://blog.jetbrains.com/mps/2021/02/apple-silicon-support-comes-to-jetbrains-mps-2020-3-1/
https://www.jetbrains.com/mps/whatsnew/
<img width="815" alt="image" src="https://user-images.githubusercontent.com/33549573/120957819-2d99f700-c778-11eb-9632-043558f1e51b.png">

https://mobile.twitter.com/jetbrains_mps/status/1359101583640961025
<img width="599" alt="image" src="https://user-images.githubusercontent.com/33549573/120957847-3c80a980-c778-11eb-9091-44e07280f342.png">

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1268" alt="image" src="https://user-images.githubusercontent.com/33549573/120957997-8e293400-c778-11eb-8b3e-52804fc917f9.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/120957993-8cf80700-c778-11eb-8980-4d08c584ebc2.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/jetbrains-mps/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
