### ISSUE TITLE
Rider

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#689]
**The official name of the app**
Rider

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support (in Early Access Preview version)

**Proposed App Category**
Developer Tools

**Related Issue Tracker Links or discussion**
https://youtrack.jetbrains.com/issue/RIDER-54092

**An Official App Download Page**
https://www.jetbrains.com/rider/download/ - Rosetta 2 (or Toolbox app)
https://download.jetbrains.com/rider/JetBrains.Rider-2021.2-EAP2-212.3724.19.Checked-aarch64.dmg - this is the official link (can find it in YouTrack discussion listed above)

**Additional context**
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/33549573/120961029-d8151880-c77e-11eb-91bd-49c05a0d7912.png">
<img width="333" alt="image" src="https://user-images.githubusercontent.com/33549573/120961025-d77c8200-c77e-11eb-9b16-2c5c8370e974.png">
Even though 2021.2 EAP 2 is available through Toolbox, the binary is executable Rosetta-only.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/33549573/120962239-275c4880-c781-11eb-86c7-b4dc5785e474.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/120962238-262b1b80-c781-11eb-965d-0c48bea90a91.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/jetbrains-rider/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by tomchilvers** [comment]
Rider is now optimized for M1 outside of EAP. See https://www.jetbrains.com/rider/download/#section=mac

**Comment by hanssens** [comment]
Confirmed with @tomchilvers report: Rider officially supports an ARM build since [2021.3+ and higher](https://www.jetbrains.com/rider/whatsnew/). So the _in Early Access Preview version_ can be omitted.

**Comment by ThatGuySam** [comment]
@tomchilvers @hanssens Thanks for the update! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
Update is now live on the site! Thanks, @tomchilvers and @hanssens!

https://doesitarm.com/app/jetbrains-rider/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
