### ISSUE TITLE
Add typora

### ISSUE THREAD

**Issue by ifsheldon** [ThatGuySam/doesitarm#69]
**The official name of the app**
Typora

**Proposed App Status**
Popular markdown editor available on Windows and Mac OS. Runs fine with Rosseta

**Related Issue Tracker Link or discussion**
This [issue](https://github.com/typora/typora-issues/issues/3989)

**An Official App Download Link**
No download for native build yet

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by syhily** [comment]
The [latest](https://typora.io/dev_release.html) Typora already has a native M1 build.
Download link is [here](https://typora.io/download/Typora-0.9.9.36.2.dmg).

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/typora/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
