### ISSUE TITLE
LINE now runs natively as a Universal app

### ISSUE THREAD

**Issue by JuNkY14257** [ThatGuySam/doesitarm#690]
Replace each second line your own text. 

**The official name of the app**
LINE

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
https://doesitarm.com/app/line/
https://isapplesiliconready.com/app/LINE

**An Official App Download Page**
https://apps.apple.com/th/app/line/id539883307?mt=12
https://line.me/en/

**Additional context**
The app now works flawlessly. No more lagging and the app uses significantly less RAM and energy than before.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1072" alt="Screen Shot 2564-06-07 at 18 09 31" src="https://user-images.githubusercontent.com/85490680/121007001-c1d97d80-c7bb-11eb-9649-1800e135c3d7.png">
<img width="377" alt="Screen Shot 2564-06-07 at 18 03 16" src="https://user-images.githubusercontent.com/85490680/121006068-ab7ef200-c7ba-11eb-92f0-2327bce2e5b0.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

App is now live on the site! 

https://doesitarm.com/app/line-for-macos/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
