### ISSUE TITLE
Colibri DAC DSD Test

### ISSUE THREAD

**Issue by drummingdemon** [ThatGuySam/doesitarm#691]
**The official name of the app**
Colibri DAC DSD Test

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Music and Audio Tools

**Related Issue Tracker Links or discussion**

**An Official App Download Page**
[Mac AppStore](https://itunes.apple.com/us/app/colibri-dac-dsd-test/id1455508413?ls=1&mt=12)

**Additional context**

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Screenshot 2021-06-07 at 22 34 36](https://user-images.githubusercontent.com/286512/121084126-91f0a100-c7e0-11eb-96cc-f1b7b968e160.png)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/colibri-dac-dsd-test/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
