### ISSUE TITLE
VRay 5 (rendering) for SketchUp works in apple M1 silicon?

### ISSUE THREAD

**Issue by shahiiid** [ThatGuySam/doesitarm#692]
Hello!! My name is shahid and i m an architect. I need new PC so i don't decide in between apple m1 or intel so can you please test this software so this can help me to decide wich one should i need to buy.

**Comment by ThatGuySam** [comment]
Hello Shahid! Thanks for the App Request! 

The next step is to collect the missing info. 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add what's missing as you find it. 

You can reference what all it needs here: 
[App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by moffpage** [comment]
<img width="536" alt="image" src="https://user-images.githubusercontent.com/33549573/123597065-aee32780-d814-11eb-8f34-a56a2470f676.png">
<img width="652" alt="image" src="https://user-images.githubusercontent.com/33549573/123597073-b0aceb00-d814-11eb-90a4-7f32e07249f9.png">

Idk where that info came from though:
<img width="760" alt="image" src="https://user-images.githubusercontent.com/33549573/123597055-ab4fa080-d814-11eb-8872-0a08cc0535d6.png">

**Comment by ThatGuySam** [comment]
We'll use the following title:
VRay for SketchUp

We'll use the following status:
🚫 No, not yet supported but supported is in development

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/vray-for-sketchup/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
