### ISSUE TITLE
shellcheck with full native apple silicon support

### ISSUE THREAD

**Issue by aduffner** [ThatGuySam/doesitarm#693]
**The official name of the app**
shellcheck

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
https://github.com/koalaman/shellcheck/issues/2162
and more ...

**An Official App Download Page**
https://github.com/koalaman/shellcheck/releases

**Additional context**
<img width="768" alt="Bildschirmfoto 2021-06-09 um 10 36 05" src="https://user-images.githubusercontent.com/47379999/121331952-a8e5df00-c917-11eb-928c-1f72b6862259.png">

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="710" alt="Bildschirmfoto 2021-06-09 um 10 33 57" src="https://user-images.githubusercontent.com/47379999/121331998-b26f4700-c917-11eb-95eb-81131ca5d34a.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! App is now live on the site! 

https://doesitarm.com/app/shellcheck/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
