### ISSUE TITLE
Pure Data

### ISSUE THREAD

**Issue by Morpheu5** [ThatGuySam/doesitarm#694]
**The official name of the app**
Pd (Pure Data)

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Yes, works via Rosetta and builds as Apple Silicon

**Proposed App Category**
Music Tools, Developer Tools

**Related Issue Tracker Links or discussion**
Build status: https://github.com/pure-data/pure-data/issues/1251

**An Official App Download Page**
http://puredata.info/downloads/pure-data

**Additional context**
N/A

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![image](https://user-images.githubusercontent.com/411507/121337267-43442380-c914-11eb-841e-75d6242c4607.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! App is now live on the site! 

https://doesitarm.com/app/pure-data/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
