### ISSUE TITLE
Docker does not have full native Apple Silicon support yet

### ISSUE THREAD

**Issue by kesara** [ThatGuySam/doesitarm#695]
Replace each second line your own text. 

**The official name of the app**
Docker

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
Yes, works via Rosetta 2

**Related Issue Tracker Links or discussion**
https://docs.docker.com/docker-for-mac/apple-silicon/#system-requirements

**An Official App Download Page**
https://docs.docker.com/docker-for-mac/apple-silicon/

**Additional context**
You must install Rosetta 2 as some binaries are still Darwin/AMD64. The app doesn't work out of the box if Rosetta 2 is not stalled.

**Comment by ThatGuySam** [comment]
Good catch! Update is now live on the site! 

https://doesitarm.com/app/docker/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
