### ISSUE TITLE
helpers/build-app-list.js

### ISSUE THREAD

**Issue by a0960909060** [ThatGuySam/doesitarm#696]
Replace each second line your own text. 

For a great example issue check out #358

--------- Delete this line and everything above it before submitting ---------

**The official name of the app**
What's the full official name of the app

**Is there a supported version available on a stable release channel?**
Yes or No

**Proposed App Status**
What's the current app status based off of current discussion or testing
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend

**Proposed App Category**
What category should the app go under

**Related Issue Tracker Links or discussion**
This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes.

**An Official App Download Page**
This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site. 

**Additional context**
Add any other context or screenshots about the app request here. 

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
A screenshot with Activity Monitor open showing the App's architecture type. Example: #358

**Comment by ThatGuySam** [comment]
Hello @a0960909060, 

Thanks for creating a new issue! 

Is this an App Request it a code related issue?

**Comment by moffpage** [comment]
Why even consider examining this issue lol?

**Comment by ThatGuySam** [comment]
Closing this issue for now
