### ISSUE TITLE
Sleep Warden

### ISSUE THREAD

**Issue by drummingdemon** [ThatGuySam/doesitarm#697]
**The official name of the app**
Sleep Warden

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
System Tools

**Related Issue Tracker Links or discussion**

**An Official App Download Page**
[Mac AppStore](https://apps.apple.com/us/app/sleep-warden/id1571743175)

**Additional context**

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Screenshot 2021-06-11 at 14 56 37](https://user-images.githubusercontent.com/286512/121689721-416d9200-cac5-11eb-9854-e81e08236a4c.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/sleep-warden/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
