### ISSUE TITLE
OCaml 4.12 native

### ISSUE THREAD

**Issue by aimileus** [ThatGuySam/doesitarm#698]
**The official name of the app**
OCaml

**Is there a supported version available on a stable release channel?**
Yes, OCaml 4.12

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
https://github.com/ocaml/ocaml/releases/tag/4.12.0

**An Official App Download Page**
Supported by at least Homebrew: https://ocaml.org/docs/install.html#macOS.

**Comment by ThatGuySam** [comment]
Thanks for the Report! Update is now live on the site! 

https://doesitarm.com/app/ocaml/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
