### ISSUE TITLE
Microsoft OneDrive

### ISSUE THREAD

**Issue by stjep** [ThatGuySam/doesitarm#699]
**The official name of the app**
Microsoft OneDrive

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✳️ Yes, works via Translation or Virtualization

**An Official App Download Page**
https://www.microsoft.com/en-au/microsoft-365/onedrive/online-cloud-storage

**Additional context**
[Native version coming later this year.](https://techcommunity.microsoft.com/t5/microsoft-onedrive-blog/microsoft-works-to-ensure-a-great-onedrive-experience-on-apple/ba-p/2400803?fbclid=IwAR16Kpp8XirFHM4zzLw7cqKvjCwrmdgTMbF_wLpyBBFGult96v3H5G0_0ws)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
On an M1 MacBook Pro:
![Screen Shot 2021-06-14 at 4 11 37 pm](https://user-images.githubusercontent.com/3305421/121847012-46cc1600-cd2b-11eb-8f52-2e66eba1e8ac.png)

**Comment by ThatGuySam** [comment]
Thanks for the Report! Update is now live on the site! 

https://doesitarm.com/app/microsoft-onedrive/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by jaimecosme** [comment]
Onedrive is available for Apple Silicon

![Captura de pantalla 2022-04-09 a las 9 00 49](https://user-images.githubusercontent.com/8482613/162560822-7eebc60d-44b2-4ce1-af53-0685f4290463.png)

**Comment by ThatGuySam** [comment]
@jaimecosme Thanks for the update! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/microsoft-onedrive/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by ireinhart** [comment]
App Store Version is now M1 native, too.
