### ISSUE TITLE
Ivory II

### ISSUE THREAD

**Issue by melgu** [ThatGuySam/doesitarm#700]
**The official name of the app**
Ivory II

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
No, not working at all but support is in development

**Proposed App Category**
Music and Audio Tools

**Related Issue Tracker Links or discussion**

**An Official App Download Page**
https://www.synthogy.com/index.php/support/updates/mac

**Additional context**
Support has been promised since the announcement of Apple Silicon, but not a single update yet.
Running under Rosetta is not an option as it is a plug-in for Logic Pro, which itself should run natively.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
Not a screenshot, but the developer Synthogy says so itself [[1]](https://www.synthogy.com/index.php/support/updates/mac).

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/ivory-ii/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
