### ISSUE TITLE
Tensorflow

### ISSUE THREAD

**Issue by TommyIX** [ThatGuySam/doesitarm#701]
**The official name of the app**
Tensorflow

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
Tensorflow-Metal Plugin official page: https://developer.apple.com/metal/tensorflow-plugin/

**An Official App Download Page**
Also in https://developer.apple.com/metal/tensorflow-plugin/

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="736" alt="截屏2021-06-15 08 47 11" src="https://user-images.githubusercontent.com/55588115/121976816-2d70ab80-cdb7-11eb-91bf-7f7700d2e701.png">

**Comment by ThatGuySam** [comment]
It's probably not very accurate to say *Full* Native support. 

Let's go with:
✅ Yes, Initial Native Apple Silicon Support via Apple's Metal Plugin

And then we'll update it when Native ARM/Apple Silicon compatibility is available through the official distribution channels.

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/tensorflow/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by stephanobryan** [comment]
I've done as follows on macOS 11.4 (Even though the ref says "OS Requirements macOS 12.0+"), python==3.8.2 and worked [ref: https://developer.apple.com/metal/tensorflow-plugin/]:
1. Create a venv on x86 terminal, i.e. Rosetta Terminal (see: https://dev.to/courier/tips-and-tricks-to-setup-your-apple-m1-for-development-547g)
i.e. Environment Setup:
x86 : AMD
Create venv: python3 -m venv ~/PATH/tensorflow-metal (Substitute PATH with your real PATH)
Activate the venv: source ~/PATH/tensorflow-metal/bin/activate
Update pip: python -m pip install -U pip

2. Install any library/package you need. For instance:
For instance: pip install matplotlib jupyterlab

3. Install base tensorflow:
python -m pip install tensorflow-macos

4. Install metal plugin:
python -m pip install tensorflow-metal

Good Luck & Cheers!
