### ISSUE TITLE
EndNote 20

### ISSUE THREAD

**Issue by danielp982** [ThatGuySam/doesitarm#704]
**The official name of the app**
Endnote 20

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**An Official App Download Page**
[30-day trial link](https://endnote.com/downloads/30-day-trial)

**Additional context**
[Release notes](https://support.clarivate.com/Endnote/s/article/EndNote-20-Release-Notes?language=en_US)

**Note:** Currently, the Does it ARM website lists EndNote X9. Clarivate (the developers) have since replaced this with EndNote 20 (similar to Office Releases). Not sure whether you wish to treat this as a separate product or not, if so I can create another issue specifically for X9 (runs via Rosetta).

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1156" alt="Screen Shot 2021-06-20 at 12 01 01 pm" src="https://user-images.githubusercontent.com/36717696/122659858-4fa36880-d1bf-11eb-8600-e43cd8ddcb05.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Would you say there is a slower adoption of EndNote 20? 
If so we can go ahead and create a separate listing for X9 for those that may not be able to upgrade just yet.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/endnote/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by danielp982** [comment]
Thanks for the addition!

I don't think it's a bad idea to include a separate listing for X9. I'm not an EndNote expert, but my assumption is that there's still a few organisations that haven't upgraded their license. My university took around 6 months to offer EndNote 20 from when it was first released, and still provide download links for both versions.

I'm happy to provide screenshots for X9 if needed.

**Comment by ThatGuySam** [comment]
Let's go ahead and get that screenshot so we we can list both

**Comment by danielp982** [comment]
Alright, here's the latest version of EndNote X9. Loads and runs fine under Rosetta.

<img width="1279" alt="Screen Shot 2021-06-24 at 2 13 25 pm" src="https://user-images.githubusercontent.com/36717696/123201631-66ff9000-d4f6-11eb-8179-fbc6a5b99518.png">

**Comment by ThatGuySam** [comment]
Listing for X9 is live! 

https://doesitarm.com/app/endnote-x9/
