### ISSUE TITLE
FS-UAE

### ISSUE THREAD

**Issue by danielktdoranie** [ThatGuySam/doesitarm#706]
Replace each second line your own text. 

(FS-UAE is a popular Amiga emulator application) 

**The official name of the app**
FS-UAE
**Is there a supported version available on a stable release channel?**
Yes
**Proposed New App Status**
Full Native Apple Silicon Support
**Related Issue Tracker Links or discussion**
https://fs-uae.net/2021/06/09/builds-for-macos-arm64-m1-apple-silicon-have-arrived/comment-page-1?unapproved=1015254&moderation-hash=7ab3b3425385d84f331ec6d4faa54ff7#comment-1015254
**An Official App Download Page**
https://fs-uae.net/2021/06/09/builds-for-macos-arm64-m1-apple-silicon-have-arrived/comment-page-1?unapproved=1015254&moderation-hash=7ab3b3425385d84f331ec6d4faa54ff7#comment-1015254
**Additional context**
Add any other context or screenshots about the app request here. 

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
As screenshot with Activity Monitor open showing the App's architecture type. 
[https://files.catbox.moe/77lgl8.png](url)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Adding your screenshot here for better visibility. 

![image](https://user-images.githubusercontent.com/2830379/122807383-23581c80-d291-11eb-852a-599a8fd9cf05.png)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/fs-uae/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
