### ISSUE TITLE
Android File Transfer

### ISSUE THREAD

**Issue by evrika-kazakhstan** [ThatGuySam/doesitarm#707]
**The official name of the app**
Android File Transfer

**Is there a supported version available on a stable release channel?**
No

**Proposed New App Status**
✳️ Yes, works via Translation or Virtualization

**Related Issue Tracker Links or discussion**
https://forums.macrumors.com/threads/does-android-file-transfer-app-work-on-apple-silicon-mac.2288198/

**An Official App Download Page**
https://www.android.com/filetransfer/

**Additional context**

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1270" alt="image" src="https://user-images.githubusercontent.com/86355964/123375419-9079f380-d5aa-11eb-9a22-3f782380ac54.png">
![Uploading image.png…]()

**Comment by ThatGuySam** [comment]
Thanks for the App Request! App is now live on the site! 

https://doesitarm.com/app/android-file-transfer/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
