### ISSUE TITLE
Update Avid Pro Tools

### ISSUE THREAD

**Issue by MonkeyOliver** [ThatGuySam/doesitarm#708]
Replace each second line your own text. 

**The official name of the app**
Avid Pro Tools

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✳️ Yes, it works via Rosetta 2

**Related Issue Tracker Links or discussion**
[Official Article](https://avid.secure.force.com/pkb/articles/en_US/Compatibility/macOS-Big-Sur-Support)

**An Official App Download Page**
Unknown

**Additional context**
![image](https://user-images.githubusercontent.com/24616039/123407215-49a5f100-d5de-11eb-92a7-e2ff71c21018.png)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
As screenshot with Activity Monitor open showing the App's architecture type.

**Comment by ThatGuySam** [comment]
Thanks for the report! Update is now live on the site! 

https://doesitarm.com/app/avid-pro-tools/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
