### ISSUE TITLE
Ableton Live

### ISSUE THREAD

**Issue by photovirus** [ThatGuySam/doesitarm#71]
**The official name of the app**
Ableton Live

**Proposed App Status**
✳️ Can run well enough via Rosetta or some other caveat

**Related Issue Tracker Link or discussion**
https://forum.ableton.com/viewtopic.php?f=1&t=240993&p=1783349&hilit=apple+silicon#p1783349

**An Official App Download Link**
https://ableton.com

**Additional context**
Press release of one of the plugins states they've run their plugin in Ableton without issues: https://neuraldsp.com/blogs/news/macos-big-sur-and-apple-silicon-compatibility
Which means they've got Ableton itself running on Apple Silicon

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

This is some helpful info so I'm going to merge it into #13
