### ISSUE TITLE
Request App "FreeCAD"

### ISSUE THREAD

**Issue by Hello9999901** [ThatGuySam/doesitarm#711]
**The official name of the app**
FreeCAD

**Is there a supported version available on a stable release channel?**
Yes, but only x86 versions so far

**Proposed App Status**
Yes, works via Translation or Virtualization

**Proposed App Category**
Developer/Productivity

**Related Issue Tracker Links or discussion**
https://github.com/FreeCAD/FreeCAD

**An Official App Download Page**
https://www.freecadweb.org/downloads.php

**Additional context**

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
A screenshot with Activity Monitor open showing the App's architecture type. Example: #358
### Activity Monitor Screenshot
<img width="636" alt="Screen Shot 2021-06-28 at 10 56 02 AM" src="https://user-images.githubusercontent.com/61983584/123658515-cd8af380-d7ff-11eb-93f0-b8c618c30ef5.png">

### Silicon Info Screenshot
<img width="208" alt="Screen Shot 2021-06-28 at 11 00 46 AM" src="https://user-images.githubusercontent.com/61983584/123658886-1e9ae780-d800-11eb-9989-b00dbde4e8ce.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! App is now live on the site! 

https://doesitarm.com/app/freecad/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
