### ISSUE TITLE
Electric

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#712]
**The official name of the app**
Electric

**Is there a supported version available on a stable release channel?**
No

**Proposed New App Status**
Doesn't work at all on macOS? 

**Related Issue Tracker Links or discussion**

**An Official App Download Page**
https://www.staticfreesoft.com/productsFree.html

**Additional context**
Can you please force people to provide more details about the app. Like which "Electric" app needs to be included in doesitarm.com? Is it the one by Static Free Software? 

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
No screenshots, app cannot be run on both Intel and Apple Silicon Macs, gives me an exception when running jar (`java -jar ~/path/to/electricBinary-9.07.jar`)
<img width="694" alt="image" src="https://user-images.githubusercontent.com/33549573/123733292-0b9a1d00-d8bd-11eb-8a5f-3bd00d0c3bb3.png">

**Comment by ThatGuySam** [comment]
@moffpage Good find! 

Are you saying we could update the "New App Request" template?

**Comment by ThatGuySam** [comment]
We list the app with the following name: 
Electric by Static Free Software

We'll use the following status:
🚫 No, not yet supported only works on Intel-based Macs

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/electric-by-static-free-software/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
