### ISSUE TITLE
GraphiQL

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#713]
**The official name of the app**
GraphiQL

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
Yes, works via Translation or Virtualization

**Proposed App Category**
Developer Tools

**Related Issue Tracker Links or discussion**

**An Official App Download Page**
https://www.electronjs.org/apps/graphiql
https://github.com/skevy/graphiql-app/releases

**Additional context**

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1382" alt="image" src="https://user-images.githubusercontent.com/33549573/123733409-400dd900-d8bd-11eb-9ad7-9d08655ad961.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/123733407-3edcac00-d8bd-11eb-8814-0feb37408a64.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/graphiql/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
