### ISSUE TITLE
LaCie RAID Manager

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#715]
**The official name of the app**
LaCie RAID Manager

**Is there a supported version available on a stable release channel?**
No

**Proposed New App Status**
✳️ Yes, works via Translation or Virtualization

**Related Issue Tracker Links or discussion**

**An Official App Download Page**
https://www.lacie.com/support/downloads/

**Additional context**
Installation requires different setup for Apple Silicon Macs: https://www.lacie.com/support/kb/how-to-change-startup-disk-security-settings-on-an-apple-silicon-mac/

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/33549573/124058280-e1766580-da4a-11eb-869c-e001c3301255.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/124058282-e20efc00-da4a-11eb-8e01-5016018c5f83.png">

**Comment by ThatGuySam** [comment]
This looks excellent! 

We'll use the following status:
✳️ Yes, works via Rosetta 2 translation

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/lacie-raid-manager/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
