### ISSUE TITLE
Spotify Beta M1 support

### ISSUE THREAD

**Issue by Andy-Ivanyuk** [ThatGuySam/doesitarm#716]
**The official name of the app**
Spotify

**Is there a supported version available on a stable release channel?**
No

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
https://community.spotify.com/t5/Live-Ideas/Desktop-Developer-Add-support-for-Apple-Silicon-ARM64-on-Mac/idc-p/5229838#M226146

**An Official App Download Page**
[You can download this Beta app from here](https://download.scdn.co/SpotifyBetaARM64.dmg)

**Additional context**
![image](https://user-images.githubusercontent.com/33178570/124194567-7d4ab480-dad1-11eb-91d8-5c16b781e0e1.png)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![image](https://user-images.githubusercontent.com/33178570/124194709-c00c8c80-dad1-11eb-8443-95b1806d1e87.png)

**Comment by ThatGuySam** [comment]
Good find! 

I've added the beta link to the Spotify listing. 

https://doesitarm.com/app/spotify/

Feel free to comment on this issue once Native Support drops into the stable channel.
