### ISSUE TITLE
VueScan

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#717]
**The official name of the app**
VueScan

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity

**Related Issue Tracker Links or discussion**

**An Official App Download Page**
https://www.hamrick.com

**Additional context**
<img width="453" alt="image" src="https://user-images.githubusercontent.com/33549573/124210808-e4865a00-db0d-11eb-8a58-bd7234e4bc94.png">
https://www.hamrick.com/blog/vuescan-on-apple-silicon.html
<img width="727" alt="image" src="https://user-images.githubusercontent.com/33549573/124210848-f9fb8400-db0d-11eb-9efa-c06099aa7775.png">

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/33549573/124210861-fff16500-db0d-11eb-88aa-5f0f240343cc.png">
<img width="377" alt="image" src="https://user-images.githubusercontent.com/33549573/124210856-fe27a180-db0d-11eb-8243-686e64110e5a.png">

**Comment by ThatGuySam** [comment]
Great work! 

We'll use the following status:
✅ Yes, Full Native Apple Silicon Support

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/vuescan/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
