### ISSUE TITLE
iterm not showing up in search

### ISSUE THREAD

**Issue by ibraheemdev** [ThatGuySam/doesitarm#72]
iterm [is in the readme](https://github.com/ThatGuySam/doesitarm/blob/master/README.md#developer-tools), but it does not show up when searching on the website

**Comment by ThatGuySam** [comment]
It looks like the line was formatted incorrectly 

You should be able to search and go to it now
https://doesitarm.com/app/iterm/

**Comment by ibraheemdev** [comment]
👍  Awesome site btw
