### ISSUE TITLE
WriteMapper

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#720]
WriteMapper had Apple Silicon support from version 3.0, actually. Your website states it has one from 3.0.3.
<img width="313" alt="image" src="https://user-images.githubusercontent.com/33549573/124859016-e9954e80-dfd0-11eb-8b49-5b1d9af22dc7.png">

**Comment by ThatGuySam** [comment]
Updated! 

https://doesitarm.com/app/writemapper/
