### ISSUE TITLE
Find Any File

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#721]
It actually has support since 2.3:
<img width="260" alt="image" src="https://user-images.githubusercontent.com/33549573/126024391-152aa0a4-766e-4156-b1f6-046b9fa023e7.png">
Source: https://apps.tempel.org/FindAnyFile/

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/find-any-file/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
