### ISSUE TITLE
mono-mdk

### ISSUE THREAD

**Issue by ICHx** [ThatGuySam/doesitarm#722]
Replace each second line your own text. 

**The official name of the app**
What's the full official name of the app? 
Brew formula: mono-mdk

**Is there a supported version available on a stable release channel?**
Yes
Version: 
```bash
  ~ mono --version
Mono JIT compiler version 6.12.0.122 (2020-02/c621c35ffa0 Wed Feb 10 00:51:43 EST 2021)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
  ~ file $(which mono)
/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono: Mach-O 64-bit executable x86_64
  ~ 
```

**Proposed New App Status**
Yes, Runnable on Rosetta

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
As screenshot with Activity Monitor open showing the App's architecture type. 
<img width="909" alt="圖片" src="https://user-images.githubusercontent.com/11556527/126063546-d9c4bf64-80d7-4e8c-bb02-bd401eff9f10.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/mono-mdk/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
