### ISSUE TITLE
Adobe Premiere Pro

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#723]
**The official name of the app**
Adobe Premiere Pro 

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
https://helpx.adobe.com/download-install/kb/apple-silicon-m1-chip.html

**An Official App Download Page**
https://www.adobe.com/products/premiere.html#mini-plans-web-cta-premiere-pro-card

**Additional context**
<img width="764" alt="image" src="https://user-images.githubusercontent.com/33549573/126369520-0e7a211b-10fb-48ba-b4c8-396f73f06036.png">
<img width="706" alt="image" src="https://user-images.githubusercontent.com/33549573/126369529-2ad80dfb-bf4d-412d-8d43-55da2dab69db.png">

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
Unfortunately I don't have an Apple Silicon Mac right now, might check in a retail store in a near future if that' necessary and nobody else tries to attach the screenshots.

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/premiere-pro/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
