### ISSUE TITLE
MySQL Community Server is Full Native Apple Silicon Support now

### ISSUE THREAD

**Issue by phper08** [ThatGuySam/doesitarm#724]
Replace each second line your own text. 

**The official name of the app**
MySQL Community Server

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✳️ Yes, works via Rosetta 2

**Related Issue Tracker Links or discussion**
https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-26.html

**An Official App Download Page**
https://dev.mysql.com/downloads/mysql/

**Additional context**
![image](https://user-images.githubusercontent.com/13127645/126455990-86ebfeb4-73c9-4f7d-985a-e0b17782c319.png)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
None

**Comment by ThatGuySam** [comment]
Thanks for the update request! 

Uodate is now live on the site! 

https://doesitarm.com/app/mysql-community-server/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
