### ISSUE TITLE
BetterZip

### ISSUE THREAD

**Issue by HilbertGilbertson** [ThatGuySam/doesitarm#725]
**The official name of the app**
BetterZip

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
Yes, Full Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
[https://macitbetter.com/blog/BetterZip-5.1/](https://macitbetter.com/blog/BetterZip-5.1/)

**An Official App Download Page**
This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site. 

**Additional context**
N/A

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![CleanShot 2021-07-22 at 17 49 43@2x](https://user-images.githubusercontent.com/24899023/126677487-634a647c-11f9-4d7a-9963-e2867ecbfe41.png)

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/betterzip/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
