### ISSUE TITLE
DaisyDisk?

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#726]
**The official name of the app**
DaiyDisk

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**Related Issue Tracker Links or discussion**

**An Official App Download Page**
daisydiskapp.com

**Additional context**
https://doesitarm.com/app/daisydisk/

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
It was reported as an app having support:
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/33549573/126729022-a9373704-3d66-4146-adc6-c674f476ef5b.png">

**Comment by ThatGuySam** [comment]
Look like it's reporting a false negative when the newest binary is Intel-only

**Comment by a0960909060** [comment]
亂三小

從我的iPhone 傳送

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/daisydisk/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
