### ISSUE TITLE
Mullvad VPN has Apple Silicon Support

### ISSUE THREAD

**Issue by jycadman** [ThatGuySam/doesitarm#727]
**The official name of the app**
Mullvad VPN

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
https://github.com/mullvad/mullvadvpn-app/releases/tag/2021.4

**An Official App Download Page**
https://mullvad.net/en/download/macos/ 

**Additional context**
N/A

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![mullvad-arms](https://user-images.githubusercontent.com/85986065/126749094-ad937f03-07c8-4fd6-beae-916377e4779f.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/mullvad-vpn/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
