### ISSUE TITLE
Genymontion

### ISSUE THREAD

**Issue by qiutian00** [ThatGuySam/doesitarm#729]
**The official name of the app**
Genymontion

**Is there a supported version available on a stable release channel?**
No 

**Proposed App Status**
No, Genymotion Desktop is not compatible with ARM CPUs, such as Apple Silicon, yet.

**Proposed App Category**
Android develop

**Related Issue Tracker Links or discussion**
No, Can visit [article](https://support.genymotion.com/hc/en-us/articles/360017897157?input_string=genymotion+may+cannot+run+on+mac+m1+chips)

**An Official App Download Page**
https://www.genymotion.com/download/

**Additional context**
![image](https://user-images.githubusercontent.com/24382500/126856684-000c41e5-d9f2-49ca-a52c-9d01a20b7f6f.png)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
todo

**Comment by ThatGuySam** [comment]
Thanks for the App Request! It's is now live on the site! 

https://doesitarm.com/app/genymotion/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by qiutian00** [comment]
Tanks.
