### ISSUE TITLE
Add Haskell (GHC)

### ISSUE THREAD

**Issue by ibraheemdev** [ThatGuySam/doesitarm#73]
**The official name of the app**
Haskell (GHC)

**Proposed App Status**
🚫 Not yet supported only works on Intel-based Macs

**Related Issue Tracker Link or discussion**
https://gitlab.haskell.org/ghc/ghc/-/issues/18664

**An Official App Download Link**
https://www.haskell.org/platform/mac.html

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

This is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/haskell/

Feel free to browse through the other issues to help with missing info on other apps.

**Comment by marslicy** [comment]
It can work on M1 macs now

**Comment by ThatGuySam** [comment]
@marslicy Great! Any links or screenshots we can use as verification?

**Comment by marslicy** [comment]
> @marslicy Great! Any links or screenshots we can use as verification?

Just on the website of Haskell, there is a download link for M1 users.

![image](https://user-images.githubusercontent.com/67776815/115954385-07ced080-a4f1-11eb-9d44-c5851047d6cc.png)

**Comment by ThatGuySam** [comment]
Update is live! 

https://doesitarm.com/app/haskell/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by absurd** [comment]
@ThatGuySam It looks like the Apple Silicon specific installation instructions here invoke Rosetta 2: [https://www.haskell.org/ghcup/](https://www.haskell.org/ghcup/)

Discussion here: [https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/101](https://gitlab.haskell.org/haskell/ghcup-hs/-/issues/101).

@marslicy was there something else that you were seeing?

**Comment by ThatGuySam** [comment]
Downgrading Haskell to Rosetta 2 for now until more info comes in. 

https://doesitarm.com/app/haskell/
