### ISSUE TITLE
LibreOffice

### ISSUE THREAD

**Issue by swcrazyfan** [ThatGuySam/doesitarm#730]
<img width="1095" alt="Screen Shot 2021-07-24 at 3 15 09 PM" src="https://user-images.githubusercontent.com/79735340/126860767-f1dd287e-eea7-428f-a8aa-c948a6ba3187.png">
Replace each second line your own text. 

**The official name of the app**
LibreOffice

**Is there a supported version available on a stable release channel?**
No

**Proposed New App Status**
Yes, Full Native Support

**Related Issue Tracker Links or discussion**
https://dev-builds.libreoffice.org/pre-releases/mac/aarch64/

**An Official App Download Page**
This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site. 

**Additional context**
They plan to release the full version in August, apparently. However, I'm currently using it on my M1 MacBook Pro without any issues.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
Here is a screenshot showing LibreOffice is running natively.

**Comment by ThatGuySam** [comment]
Good find! Update is now live on the site! 

https://doesitarm.com/app/libreoffice/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
