### ISSUE TITLE
Chromium for M1

### ISSUE THREAD

**Issue by yooouuri** [ThatGuySam/doesitarm#732]
**The official name of the app**
Chromium

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
Development builds are available for M1!

**Proposed App Category**
Web browsers

**An Official App Download Page**
https://commondatastorage.googleapis.com/chromium-browser-snapshots/index.html?prefix=Mac_Arm/

Or

```
brew install chromium --cask --no-quarantine
```

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

![image](https://user-images.githubusercontent.com/12934957/126899817-fa4c8a95-4857-4d3d-91c3-a37ba2addb0a.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! App is now live on the site! 

https://doesitarm.com/app/chromium/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
