### ISSUE TITLE
TI Connect CE

### ISSUE THREAD

**Issue by todd-lm** [ThatGuySam/doesitarm#733]
**The official name of the app**
TI Connect CE
**Is there a supported version available on a stable release channel?**
Yes
**Proposed New App Status**
✳️ Yes, works via Rosetta 2
**Related Issue Tracker Links or discussion**
I can't find any changelog or something like that online but this is the main app page: https://education.ti.com/en/products/computer-software/ti-connect-ce-sw
**An Official App Download Page**
https://education.ti.com/en/software/details/en/68CEDD34FDC94622B4DBD173E6A0D8C3/swticonnectcesoftwareformacintosh
**Additional context**
I just tested it on my M1 MacBook Air and everything works well. I also used a usb-c to USB adapter to connect to a TI-84 Plus calculator and it worked without any issues.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1050" alt="Screen Shot 2021-07-27 at 12 07 11 PM" src="https://user-images.githubusercontent.com/12956729/127188675-bd418f6c-e205-433c-bb3d-4e40261b6e54.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! App is now live on the site! 

https://doesitarm.com/app/ti-connect-ce/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by Thebro57** [comment]
For some reason, it doesn't look like it works anymore. 

I tried opening it at first, and it popped up with a "app refused to open" error. I kept on trying until it just "can't find the file".

I noticed I hadn't updated to Rosetta 2, so I did and got the same results. Maybe it's the update 6.0 of the app? What version did you download originally?
