### ISSUE TITLE
Julia Language 1.7.0 Beta 3 now macOS ARM Native

### ISSUE THREAD

**Issue by docdoctor** [ThatGuySam/doesitarm#734]
Source: https://julialang.org/downloads/

Download Link:  https://julialang-s3.julialang.org/bin/mac/aarch64/1.7/julia-1.7.0-beta3-macaarch64.dmg

Tested and verified on Mac M1 Mini, macOS 11.5.1

**Comment by moffpage** [comment]
Sam requires to screenshots be provided

**Comment by docdoctor** [comment]
![Screen Shot 2021-08-02 at 11 57 26 AM](https://user-images.githubusercontent.com/2363364/127890043-d2429138-abb8-45ef-a69e-fb968ccca224.png)

**Comment by ThatGuySam** [comment]
This looks excellent! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/julia-language/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by PallHaraldsson** [comment]
The Julia github you link to still open, and has e.g. this comment:

"With 1.7.0-beta3 out with a build for M1, maybe more people are going to try it out. So far, the main issue I've seen are some weird and hard-to-reduce-to-a-minimal-example crashes referencing ntuple at ./ntuple.jl:0, see the bug report: #41440."

So, you can run Julia, but it's not yet stable, nor a supported platform.
