### ISSUE TITLE
NordVPN

### ISSUE THREAD

**Issue by josephazrak** [ThatGuySam/doesitarm#736]
Replace each second line your own text. 

**The official name of the app**
NordVPN IKE

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
https://apps.apple.com/us/app/nordvpn-ike-unlimited-vpn/id1116599239
Check the Update Log

**An Official App Download Page**
https://apps.apple.com/us/app/nordvpn-ike-unlimited-vpn/id1116599239?mt=12

**Additional context**
App Update log reads:
_We’re happy to announce that NordVPN now runs natively on M1 Macs! Flex the performance boost of Apple's powerful silicon chip while securing yourself online with the fastest VPN on the planet. Woah, now that’s one speedy combination. And just to clarify – the app continues to run at its best on Intel-based Macs. No matter the chip, we got you covered._

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="744" alt="screen" src="https://user-images.githubusercontent.com/17184955/127972871-444dbc31-24a6-4fd1-a819-88e293a35c8b.png">

**Comment by ThatGuySam** [comment]
Thanks for the update! Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by josephazrak** [comment]
Thanks, @ThatGuySam! Submitted as PR #737

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/nordvpn/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
