### ISSUE TITLE
ProtonMail Bridge

### ISSUE THREAD

**Issue by AwlsomeAlex** [ThatGuySam/doesitarm#738]
**The official name of the app**
[ProtonMail Bridge](https://protonmail.com/bridge/)

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Runs via Rosetta

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Links or discussion**
None

**An Official App Download Page**
https://protonmail.com/bridge/

**Additional context**

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1680" alt="ProtonMail" src="https://user-images.githubusercontent.com/11639639/128182058-35ef0d39-0c4f-473b-a014-5aef8418e81c.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/protonmail-bridge/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
