### ISSUE TITLE
Caffeinated

### ISSUE THREAD

**Issue by moffpage** [ThatGuySam/doesitarm#739]
**The official name of the app**
Caffeinated

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
Utilities

**Related Issue Tracker Links or discussion**
nope

**An Official App Download Page**
https://caffeinated.app

**Additional context**
<img width="971" alt="image" src="https://user-images.githubusercontent.com/33549573/128263431-39063f4e-026d-49b3-a5be-16b7f5f6ad3e.png">

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="897" alt="image" src="https://user-images.githubusercontent.com/33549573/128263444-9237f1c3-e597-4d2a-a4d5-fa170f490717.png">

Sorry, as I said I ain't got no M1 Mac for now, so either wait for a proof from the community or just update the info right when you see it, Sam!)

**Comment by ThatGuySam** [comment]
Looks good! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by moffpage** [comment]
Great news you have a separate issue template for that, however it ain't available from your website (it only lists app update or new app request afaik)

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/caffeinated/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
