### ISSUE TITLE
Aseprite

### ISSUE THREAD

**Issue by r3vert** [ThatGuySam/doesitarm#740]
**The official name of the app**
Aseprite

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
Works via Rosseta 2

**An Official App Download Page**
[Download Page](https://www.aseprite.org/)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info]**

<img width="1440" alt="asprite+activitymoniter" src="https://user-images.githubusercontent.com/68307669/128546472-43efd732-c2cd-4dc6-9083-6716d8017e87.png">

**Comment by ThatGuySam** [comment]
Looks good! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
Updae is now live on the site! 

https://doesitarm.com/app/aseprite/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
