### ISSUE TITLE
Eclipse 4.20 did not release an apple silicon version

### ISSUE THREAD

**Issue by marcscode90** [ThatGuySam/doesitarm#741]

**Comment by marcscode90** [comment]
Only the SDK has the arm 64 version

**Comment by ThatGuySam** [comment]
Pardon my ignorance: What's the difference between Eclipse and the SDK? 

Also, what's the download URL for non-SDK Eclipse that we should be testing?

**Comment by marcscode90** [comment]
This is the file I downloaded from the official eclipse website: eclipse-jee-2021-06-R-macosx-cocoa-x86_64.dmg and the info of the file looks like this:

<img width="261" alt="info" src="https://user-images.githubusercontent.com/83283835/129451454-af697c19-6fc8-4ddf-ac4e-96faef2f2cfe.png">

which it says intel, not universal or apple silicon.

On Twitter, a developer left a message like this:

<img width="592" alt="twitter" src="https://user-images.githubusercontent.com/83283835/129451557-ae09d9ce-a38d-4574-87e1-ad792ff87f17.png">

**Comment by ThatGuySam** [comment]
Okay, so it sounds like there's "Eclipse IDE" and "Eclipse IDE SDK" which [comes with the app's source code
](https://www.eclipse.org/forums/index.php/t/170725/#:~:text=Eclipse%20is%20often%20used%20to,in%20the%20integrated%20help%20system.)

I'm going to update the page to: 
✳️ Yes, runs via Rosetta 2 translation and natively for SDK 

Here is the link to that tweet: https://twitter.com/howlger/status/1405221822191357958

And the download page he links: https://download.eclipse.org/eclipse/downloads/drops4/R-4.20-202106111600/#EclipseSDK

**Comment by ThatGuySam** [comment]
IDE listing is now updated on the site! 

https://doesitarm.com/app/eclipse-ide/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
