### ISSUE TITLE
Bitwarden now runs natively on Apple Silicon

### ISSUE THREAD

**Issue by thomasfchang** [ThatGuySam/doesitarm#742]
**The official name of the app**
Bitwarden

**Is there a supported version available on a stable release channel?**

Yes

**Proposed New App Status**
Native on Apple Silicon (Tested Mac App Store version myself)

**Related Issue Tracker Links or discussion**

https://community.bitwarden.com/t/apple-silicon-compatibility/15606

**Comment by ThatGuySam** [comment]
Thanks for the update! It's is now live on the site! 

https://doesitarm.com/app/bitwarden/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
