### ISSUE TITLE
Pkgsrc is M1 Native

### ISSUE THREAD

**Issue by danielktdoranie** [ThatGuySam/doesitarm#743]
Pkgsrc is M1 native. Works well. 

https://pkgsrc.joyent.com/install-on-osx/

<img width="347" alt="Screenshot 2021-08-16 at 14 26 24" src="https://user-images.githubusercontent.com/69985694/129571751-50ad07f7-48e3-48ed-aec0-6d0c70951d71.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/pkgsrc/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by a0960909060** [comment]
從我的iPhone 傳送
