### ISSUE TITLE
VeraCrypt and macFUSE are M1 native!

### ISSUE THREAD

**Issue by danielktdoranie** [ThatGuySam/doesitarm#744]
Post from VeraCrypt 

https://github.com/veracrypt/VeraCrypt/issues/813#issuecomment-899121386

<img width="955" alt="Screenshot 2021-08-16 at 16 36 29" src="https://user-images.githubusercontent.com/69985694/129590136-845dfdf5-8f9d-410c-a3f5-447e110558d7.png">

Link to download VeraCrypt

https://sourceforge.net/projects/veracrypt/files/VeraCrypt%20Nightly%20Builds/VeraCrypt_1.24-Update9-Beta-21-08-15.dmg/download

macFUSE (is needed to use VeraCrypt)

https://github.com/osxfuse/osxfuse/releases

<img width="1089" alt="Screenshot 2021-08-16 at 16 35 35" src="https://user-images.githubusercontent.com/69985694/129590018-ca755d88-4009-4a90-8947-02f621895dd5.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Updates! 

macFUSE looks to be Apple Silicon Native but VeraCrypt is beta so it may not be totally to say "VeraCrypt works on Apple SIlicon" until support is out of beta

**Comment by ThatGuySam** [comment]
macFUSE is now live on the site! 

https://doesitarm.com/app/macfuse/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by danielktdoranie** [comment]
Hi Sam,

You may want to update VeraCrypt to NATIVE, as it is now native M1. On the site it is currently Rosetta 2.

Cheers,

Dan

**Comment by ThatGuySam** [comment]
The beta you provided the link for is native but the version they list on the site is an Intel-only Binary

https://www.veracrypt.fr/en/Downloads.html

Typically we don't list the app as Native until it has a Native version on a stable release channel. 

Is there a particular reason you feel it should be listed before?

**Comment by danielktdoranie** [comment]
Yeah it works perfectly and people need VeraCrypt. The more people that use it, the more the dev will be inclined to update it too

**Comment by ThatGuySam** [comment]
That's a good point. 

However, I don't know that I want to skew the message simply to drive usage for an app. 

Eventually, it will get a stable M1 release so we don't have to rush the process.

**Comment by danielktdoranie** [comment]
It is up to you but it is stable

**Comment by ThatGuySam** [comment]
Thanks for the patience on this! Update is now live on the site! 

https://doesitarm.com/app/veracrypt/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by ThatGuySam** [comment]
@rakleed Hopefully this does get lost in your notifications but I just wanted to specifically give you huge thanks for all the Pull Requests and work. 

This stuff goes a long way in helping keep this information up to date and benefit Apple users and all the people they support in their tech work. 

Thank you.
