### ISSUE TITLE
Suspicious Package Apple Silicon Support

### ISSUE THREAD

**Issue by CarlosVallsCiscar** [ThatGuySam/doesitarm#746]
Replace each second line your own text. 

**The official name of the app**
Suspicious Package

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support

**Related Issue Tracker Links or discussion**

**An Official App Download Page**
[Download URL](https://mothersruin.com/software/SuspiciousPackage/get.html)

**Additional context**
From [release notes page](https://mothersruin.com/software/SuspiciousPackage/relnotes.html) 
> Released on March 7, 2021
> Runs natively on Apple Silicon Macs.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

**Comment by ThatGuySam** [comment]
Thanks for the App Request! App is now live on the site! 

https://doesitarm.com/app/suspicious-package/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
