### ISSUE TITLE
Tableau Desktop works via Rosetta 2 on Apple Silicon

### ISSUE THREAD

**Issue by pads1** [ThatGuySam/doesitarm#752]
**The official name of the app**
Tableau Desktop

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✳️ Yes, works via Translation or Virtualization

**Related Issue Tracker Links or discussion**
https://community.tableau.com/s/topic/0TO4T000000pcgPWAQ/apple-silicon-m1

**An Official App Download Page**
https://www.tableau.com/products/desktop
(Free download with 14-day free trial)

**Comment by ThatGuySam** [comment]
Good find! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
Status: 
✳️ Yes, works via Rosetta 2 Translation

**Comment by ThatGuySam** [comment]
Rosetta 2 Verification 

[Source](https://community.tableau.com/s/feed/0D54T00000T9x7sSAB)

![image](https://user-images.githubusercontent.com/2830379/133896573-6b59fae3-5b3a-4dea-8bdd-fed40c754fbe.png)

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/tableau-desktop/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
