### ISSUE TITLE
HistoryHound works natively on Apple Silicon

### ISSUE THREAD

**Issue by pads1** [ThatGuySam/doesitarm#756]
**The official name of the app**
HistoryHound

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
System Tools

**An Official App Download Page**
https://www.stclairsoft.com/HistoryHound/
(Free download with 30-day free trial)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
A screenshot with Silicon Info open showing the App's architecture type.
<img width="214" alt="Screen Shot 2021-08-28 at 2 19 07 PM" src="https://user-images.githubusercontent.com/23331269/131208411-78b610fd-5eb0-4c95-8919-ae0f63ac68f0.png">

**Comment by ThatGuySam** [comment]
This looks excellent! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/historyhound/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
