### ISSUE TITLE
Jettison works natively on Apple Silicon

### ISSUE THREAD

**Issue by pads1** [ThatGuySam/doesitarm#757]
**The official name of the app**
Jettison

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support

**Proposed App Category**
System Tools

**An Official App Download Page**
https://www.stclairsoft.com/Jettison/
(Free download with 15-day free trial)

**Full Screenshot with the App and Activity Monitor(if self reporting) or Silicon Info**
A screenshot with Silicon Info open showing the App's architecture type.
<img width="214" alt="Screen Shot 2021-08-28 at 2 24 19 PM" src="https://user-images.githubusercontent.com/23331269/131208552-0db2637b-4976-417d-9f6e-6c96473978d5.png">

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/jettison/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
