### ISSUE TITLE
Kaleidoscope

### ISSUE THREAD

**Issue by HilbertGilbertson** [ThatGuySam/doesitarm#758]
**The official name of the app**
Kaleidoscope

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Yes, works via Rosetta 2 Translation

**Proposed App Category**
Developer Tools

**Related Issue Tracker Links or discussion**
[https://kaleidoscope.app/release-notes](https://kaleidoscope.app/release-notes)

**An Official App Download Page**
[https://kaleidoscope.app/download](https://kaleidoscope.app/download)

**Additional context**
Developer promises to be working on Silicon support as part of an [upcoming version 3](https://blog.kaleidoscope.app/2021/07/29/you-want-it-darker/)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="207" alt="screenshot" src="https://user-images.githubusercontent.com/24899023/131846873-5a9a46be-b0eb-47b5-855c-9d6eed7d9659.png">

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
Status:
✳️ Yes, works via Rosetta 2 Translation

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/kaleidoscope/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
