### ISSUE TITLE
WeChat

### ISSUE THREAD

**Issue by miceputil** [ThatGuySam/doesitarm#759]
**The official name of the app**
WeChat

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Full Native Apple Silicon Support (version 3.2.0)

**Proposed App Category**
Social and communication

**Related Issue Tracker Links or discussion**
https://github.com/ThatGuySam/doesitarm/issues/369

**An Official App Download Page**
https://mac.weixin.qq.com/?t=mac
(Totally free)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![MainUI](https://user-images.githubusercontent.com/53089496/132288631-51565a56-0eaa-447f-9cad-73096b192746.JPG)
![silicoInfo](https://user-images.githubusercontent.com/53089496/132288649-d8e82193-8aa1-4ffb-b95b-f10bebee1fbd.JPG)

**Comment by ThatGuySam** [comment]
Status:
✅ Yes, Native Apple Silicon Support as of v3.2.0

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/wechat/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
