### ISSUE TITLE
Nix can arm

### ISSUE THREAD

**Issue by domenkozar** [ThatGuySam/doesitarm#760]
Replace each second line your own text. 

**The official name of the app**
Nix

**Is there a supported version available on a stable release channel?**
No

**Proposed New App Status**
Yes, Full Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
https://github.com/NixOS/nixpkgs/issues/95903#issuecomment-914061347

**An Official App Download Page**
https://nix.dev/tutorials/install-nix#macos

**Additional context**
Add any other context or screenshots about the app request here. 

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
As screenshot with Activity Monitor open showing the App's architecture type.

**Comment by ThatGuySam** [comment]
✅ Yes, Full Native Apple Silicon Support (version 3.2.0)

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/nixos/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
