### ISSUE TITLE
WeChat 3.2.0 is available on Mac App Store now

### ISSUE THREAD

**Issue by ccming** [ThatGuySam/doesitarm#761]
Replace each second line your own text. 

**The official name of the app**
What's the full official name of the app? 

**Is there a supported version available on a stable release channel?**
Yes or No

**Proposed New App Status**
What's the current app status based off of current discussion or testing
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend

**Related Issue Tracker Links or discussion**
This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes. 

**An Official App Download Page**
This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site. 

**Additional context**
Add any other context or screenshots about the app request here. 

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
As screenshot with Activity Monitor open showing the App's architecture type.

**Comment by ThatGuySam** [comment]
We've got it in the queue to add https://github.com/ThatGuySam/doesitarm/issues/759

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/wechat/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
