### ISSUE TITLE
CodeKit does actually ARM

### ISSUE THREAD

**Issue by anobjectn** [ThatGuySam/doesitarm#766]
**The official name of the app**
CodeKit

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
Yes, Full Native Apple Silicon support was added in Version 3.14.2, released 12 February 2021

**Related Issue Tracker Links or discussion**

**An Official App Download Page**
https://codekitapp.com

**Additional context**

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

**Comment by ThatGuySam** [comment]
Thanks for the update! It's is now live on the site! 

https://doesitarm.com/app/codekit/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
