### ISSUE TITLE
Spotify M1 native released Sept 14

### ISSUE THREAD

**Issue by rabotond** [ThatGuySam/doesitarm#768]
Replace each second line your own text. 

**The official name of the app**
Spotify 

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
Yes, Full Native Apple Silicon Support 

**Related Issue Tracker Links or discussion**
https://community.spotify.com/t5/Implemented-Ideas/Desktop-Add-support-for-Apple-Silicon-ARM64-on-Mac/idc-p/5259725/highlight/true#M60236

**An Official App Download Page**
https://www.spotify.com/download/mac/

**Additional context**

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![image](https://user-images.githubusercontent.com/8861905/133406663-a39894da-6c1c-4bf8-ba95-e72fb85fa90e.png)

**Comment by HilbertGilbertson** [comment]
A big update indeed! While not a universal app, seems the universal Spotify Installer for Mac now determines the host and downloads either Intel or Silicon build. Beta no longer needed :)

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/spotify/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
