### ISSUE TITLE
Acrobat Reader DC - Full M1 Native support

### ISSUE THREAD

**Issue by Najarin321** [ThatGuySam/doesitarm#769]
Replace each second line your own text. 

**The official name of the app**
Acrobat Reader DC

**Is there a supported version available on a stable release channel?**
Yes. version 21.007.20091

**Proposed New App Status**
Yes, Full Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes. 

**An Official App Download Page**
https://get.adobe.com/br/reader/

**Additional context**
To enable m1 support after install: https://helpx.adobe.com/acrobat/kb/apple-silicon-m1-processor-support.html

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
As screenshot with Activity Monitor open showing the App's architecture type.

**Comment by ThatGuySam** [comment]
Thanks for the report! Update is now live on the site! 

https://doesitarm.com/app/acrobat-reader/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
