### ISSUE TITLE
Qt

### ISSUE THREAD

**Issue by GainSury** [ThatGuySam/doesitarm#77]
**The official name of the app**
Qt 6.0

**Proposed App Status**
Not yet, but it's currently in development. 

**Related Issue Tracker Link or discussion**
https://bugreports.qt.io/browse/QTBUG-85279

**An Official App Download Link**
This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site.
https://www.qt.io/download

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by GainSury** [comment]
Download Link is added.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/formula/qt/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
