### ISSUE TITLE
Merlin Project Express

### ISSUE THREAD

**Issue by FryMac** [ThatGuySam/doesitarm#773]
**The official name of the app**
Merlin Project Express 8.0.1

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
Yes, Full Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes. 

**An Official App Download Page**
https://www.projectwizards.net/en/merlin-project-express

**Additional context**
<img width="512" alt="MerlinProjectExpress" src="https://user-images.githubusercontent.com/79668365/133973137-9b22df71-d481-4d31-be0e-dd14add2bfe8.png">

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
As screenshot with Activity Monitor open showing the App's architecture type.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by FryMac** [comment]
Hello @ThatGuySam,

I'm a littlebit confused. Merlin Project Express is showing up as Rosetta 2 (incorrect), when you click on it, you can see the two App Bundles as M1 native (which is correct), but still confusing, as Merlin Project Express is a slimmed version of Merlin Project. So we speak here about two different apps. Could you please help to solve that? Thanks :)

**Comment by ThatGuySam** [comment]
Thanks for the report and pull request! Update is now live on the site! 

https://doesitarm.com/app/merlin-project-express/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
