### ISSUE TITLE
Merlin Project

### ISSUE THREAD

**Issue by FryMac** [ThatGuySam/doesitarm#774]
**The official name of the app**
Merlin Project

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Yes, Full Native Apple Silicon Support

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Links or discussion**
This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes.

**An Official App Download Page**
https://www.projectwizards.net/en/merlin-project

**Additional context**
<img width="512" alt="MerlinProject" src="https://user-images.githubusercontent.com/79668365/133974289-de2fa779-3009-4dbc-9835-8bc9d8c20b44.png">

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
A screenshot with Activity Monitor open showing the App's architecture type. Example: #358

**Comment by ThatGuySam** [comment]
Thanks for the Request! Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/merlin-project/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
