### ISSUE TITLE
System Watcher

### ISSUE THREAD

**Issue by HEXOGEN616** [ThatGuySam/doesitarm#793]
**The official name of the app**
System Watcher

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Yes, Full Native Apple Silicon Support

**Proposed App Category**
System Tools

**Related Issue Tracker Links or discussion**
This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes.

**An Official App Download Page**
https://apps.apple.com/us/app/system-watcher/id1269106895?mt=12

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![image](https://user-images.githubusercontent.com/18118386/137872284-ac7c037d-3818-4c25-a2c3-19c95079901d.png)

**Comment by a0960909060** [comment]
從我的iPhone 傳送
