### ISSUE TITLE
DBeaver M1/ARM support as of v21.2.2

### ISSUE THREAD

**Issue by thebandit** [ThatGuySam/doesitarm#796]
**The official name of the app**
DBeaver

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
Yes, Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
https://dbeaver.io/2021/10/03/dbeaver-21-2-2/
https://github.com/dbeaver/dbeaver/issues/12441

**An Official App Download Page**
https://dbeaver.io/download/

**Additional context**
Support added in version 21.2.2 (Oct-03-2021).

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
No M1 to test with unfortunately.

**Comment by n0thing2speak** [comment]
does ue verion support m1 native ? Feel that the money spent is not supported to :(

**Comment by ThatGuySam** [comment]
@n0thing2speak Yes, DBeaver should be native to M1 as of version 21.2.2

https://doesitarm.com/app/dbeaver/
