### ISSUE TITLE
Affinity Designer

### ISSUE THREAD

**Issue by lpez** [ThatGuySam/doesitarm#8]
Most likely it will work at launch since it has already been ported to iPad, but would like to get it on the list, as well as the entire Affinity Suite: Affinity Photo, Affinity Publisher & Affinity Designer

**Comment by ThatGuySam** [comment]
Yeah, I believe they mentioned it in the Mac unveil today. 

I'll go back and see if I can find the clip

**Comment by lpez** [comment]
min 22:31 Affinity Publisher

**Comment by ThatGuySam** [comment]
Found it https://youtu.be/5AwdkGKmZ0I?t=1349

Did they show it running on a screen at any point?

**Comment by lpez** [comment]
Nope, only talking

**Comment by ThatGuySam** [comment]
Is this an Affinity App? 

https://youtu.be/5AwdkGKmZ0I?t=1415

**Comment by ThatGuySam** [comment]
Added Affinity Designer and Affinity Publisher

https://doesitarm.com/app/affinity-designer/

https://doesitarm.com/app/affinity-publisher/
