### ISSUE TITLE
VyprVPN

### ISSUE THREAD

**Issue by mdriess** [ThatGuySam/doesitarm#801]
**The official name of the app**
VyprVPN

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Native Apple Silicon Support

**Proposed App Category**
VPNs, Security, and Privacy

**Related Issue Tracker Links or discussion**
https://www.vyprvpn.com/blog/vyprvpn-supports-apple-m1-chip

**An Official App Download Page**
https://www.vyprvpn.com/vpn-apps/vpn-for-mac

**Additional context**

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

**Comment by ThatGuySam** [comment]
Thanks for the App Request! App is now live on the site! 

https://doesitarm.com/app/vyprvpn/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
