### ISSUE TITLE
Dreamweaver is now native

### ISSUE THREAD

**Issue by exgphe** [ThatGuySam/doesitarm#802]
**The official name of the app**
Dreamweaver

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
https://helpx.adobe.com/dreamweaver/kb/dreamweaver-for-apple-silicon.html

**An Official App Download Page**
https://creativecloud.adobe.com/apps/all/dreamweaver/installation

**Additional context**
N/A

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
TODO

**Comment by ThatGuySam** [comment]
@exgphe Good catch! Update is now live on the site! 

https://doesitarm.com/app/dreamweaver/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
