### ISSUE TITLE
OverSight is now Native

### ISSUE THREAD

**Issue by ivaquero** [ThatGuySam/doesitarm#803]
See https://objective-see.com/products/changelogs/OverSight.txt

**Comment by ThatGuySam** [comment]
Thanks for the update! It's now live on the site! 

https://doesitarm.com/app/oversight/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
