### ISSUE TITLE
App request: Polypane

### ISSUE THREAD

**Issue by Kilian** [ThatGuySam/doesitarm#805]
**The official name of the app**
Polypane

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
:white_check_mark:  Yes, Native Apple Silicon Support

**Proposed App Category**
Developer Tools

**Related Issue Tracker Links or discussion**
https://polypane.app/docs/changelog/

**An Official App Download Page**
https://github.com/firstversionist/polypane/releases

**Additional context**
n/a

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
I don't have an ARM mac myself, but I do make a universal build  :upside_down_face:

**Comment by ThatGuySam** [comment]
Thanks for the App Request! App is now live on the site! 

https://doesitarm.com/app/polypane/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
