### ISSUE TITLE
CoppeliaSim works with Rosetta

### ISSUE THREAD

**Issue by mijalapenos** [ThatGuySam/doesitarm#808]
**The official name of the app**
CoppeliaSim

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✳️ Yes, works via Translation or Virtualization

**Related Issue Tracker Links or discussion**
https://forum.coppeliarobotics.com/viewtopic.php?f=7&t=9301&p=36398#p36398

**An Official App Download Page**
https://www.coppeliarobotics.com/downloads

**Full Screenshot with the App and Activity Monitor**
<img width="1440" alt="Screenshot 2021-11-04 at 22 06 17" src="https://user-images.githubusercontent.com/7550379/140420069-4f0d84af-8bfd-4e5a-b913-340972b4dd3a.png">

**Comment by ThatGuySam** [comment]
Thanks for App Request! App is now live on the site! 

https://doesitarm.com/app/coppeliasim/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
