### ISSUE TITLE
Angry IP Scanner

### ISSUE THREAD

**Issue by ElFerminador** [ThatGuySam/doesitarm#809]
**The official name of the app**
Angry IP Scanner

**Is there a supported version available on a stable release channel?**
No

**Proposed App Status**
Yes, works via Translation or Virtualization

**Proposed App Category**
"System Tools" or "VPN, Security and Privacy"

**Related Issue Tracker Links or discussion**
https://github.com/angryip/ipscan/issues

**An Official App Download Page**
https://angryip.org/download/#mac

**Additional context**
n/a

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![angry-ip-scanner_rosetta](https://user-images.githubusercontent.com/22541329/140530052-1841b652-f4d7-441e-8564-3a09b4a0b404.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! App is now live on the site! 

https://doesitarm.com/app/angry-ip-scanner/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
