### ISSUE TITLE
Krisp Mac 1.28.7 - Native support on M1 chip jeu. 28 oct. 2021

### ISSUE THREAD

**Issue by benjaminathlan** [ThatGuySam/doesitarm#810]
https://whatsnew.krisp.ai

**Comment by ThatGuySam** [comment]
Thanks for the request! App is now live on the site! 

https://doesitarm.com/app/krisp/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
