### ISSUE TITLE
Update info about Mutagen

### ISSUE THREAD

**Issue by u-maxx** [ThatGuySam/doesitarm#812]
**What's the full official name of the app?**
Mutagen

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
Yes, Native Apple Silicon Support as of v0.12.0 

**Related Issue Tracker Links or discussion**
https://github.com/ThatGuySam/doesitarm/issues/762

**An Official App Download Page**
https://mutagen.io/documentation/introduction/installation
https://github.com/mutagen-io/mutagen/releases/tag/v0.12.0

**Additional context**

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
As screenshot with Activity Monitor open showing the App's architecture type. 
![image](https://user-images.githubusercontent.com/2717220/140608782-876b2577-8451-4cc0-ab98-ad014ac85beb.png)

**Comment by ThatGuySam** [comment]
Thanks for your patience! I'm working on getting caught up on these. 

Update is now live on the site! 

https://doesitarm.com/app/mutagen/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
