### ISSUE TITLE
App request: qpdf

### ISSUE THREAD

**Issue by chryxc** [ThatGuySam/doesitarm#813]
**The official name of the app**
qpdf

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Native Apple Silicon Support

**Proposed App Category**
"Productivity Tools"

**Related Issue Tracker Links or discussion**
https://github.com/qpdf/qpdf/issues

**An Official App Download Page**
https://sourceforge.net/projects/qpdf/files/
https://github.com/qpdf/qpdf/releases

**Additional context**
n/a

**Full Screenshot with the App and Activity Monitor (if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
I don't have an Apple Silicon Mac

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Next, we'll need someone with an M1 to provide a screenshot. 

Be sure to include the App, Activity Monitor showing the app details, and About this Mac so we can see the exact OS version. 

You can find an example on #358

**Comment by chryxf** [comment]
#### Installed qpdf via homebrew
![Screenshot 2021-12-13 qpdf](https://user-images.githubusercontent.com/61791353/145745149-b9d4f7ea-4b24-4028-bf6f-ea8a550f1517.jpg)

**Comment by ThatGuySam** [comment]
Looks good!

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/qpdf/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
