### ISSUE TITLE
TinkerTool

### ISSUE THREAD

**Issue by Madhawa97** [ThatGuySam/doesitarm#814]
**The official name of the app**
TinkerTool

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Native Apple Silicon Support

**Proposed App Category**
System tools

**An Official App Download Page**
https://www.bresink.com/osx/0TinkerTool/download.php

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![image](https://user-images.githubusercontent.com/70215958/141011844-fc780759-647d-4b9c-9ad9-0f3af8ee7c75.png)

**Comment by Madhawa97** [comment]
why is this issue still open?

**Comment by ThatGuySam** [comment]
Thanks for the update!

It is now live on the site! 

https://doesitarm.com/app/tinkertool/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
