### ISSUE TITLE
Topaz Labs Video Enhance AI

### ISSUE THREAD

**Issue by ArguingMeadows** [ThatGuySam/doesitarm#815]
**The official name of the app**
What's the full official name of the app
Topaz Labs Video Enhance AI
**Is there a supported version available on a stable release channel?**
Yes or No
Yes
**Proposed App Status**
What's the current app status based off of current discussion or testing
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend
Yes, Native Apple Silicon Support
**Proposed App Category**
What category should the app go under
Video
**Related Issue Tracker Links or discussion**
This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes.
https://community.topazlabs.com/t/video-enhance-v2-6-0/27636/3
**An Official App Download Page**
This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site. 
https://community.topazlabs.com/t/video-enhance-v2-6-0/27636/3
**Additional context**
Add any other context or screenshots about the app request here. 

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
A screenshot with Activity Monitor open showing the App's architecture type. Example: #358

**Comment by ThatGuySam** [comment]
Thanks for the request! 

App is now live on the site! 

https://doesitarm.com/app/topaz-video-enhance-ai/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
