### ISSUE TITLE
Sonic Visualizer

### ISSUE THREAD

**Issue by cameronbosch** [ThatGuySam/doesitarm#817]
**The official name of the app**
Sonic Visualiser

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
Yes, Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
[Sonic Visualiser on Does It ARM?](https://doesitarm.com/app/sonic-visualiser/)

**An Official App Download Page**
[Download Link](https://www.sonicvisualiser.org/download.html)

**Additional context**
As of version 4.4, the app is a universal binary (it supports both Intel and Apple Silicon in one binary).

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info] (https://github.com/billycastelli/Silicon-Info)**
<img width="265" alt="Screen Shot 2021-11-16 at 8 59 23 PM" src="https://user-images.githubusercontent.com/72839795/142095513-2f3d9c85-6326-43ce-bb08-305e90f12a69.png">

**Comment by ThatGuySam** [comment]
Thanks for the update! It's now live on the site! 

https://doesitarm.com/app/sonic-visualiser/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
