### ISSUE TITLE
Splice

### ISSUE THREAD

**Issue by cameronbosch** [ThatGuySam/doesitarm#818]
Replace each second line with your own text. 

**The official name of the app**
Splice

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
Yes, works via Rosetta 2

**Related Issue Tracker Links or discussion**
N/A

**An Official App Download Page**
[Download Splice](https://splice.com/download)

**Additional context**
This app works, not sure if all of the plugins work though; haven't been able to throughly test them out (apart from Serum, which does work fine via Rosetta 2)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="263" alt="Screen Shot 2021-11-16 at 9 05 32 PM" src="https://user-images.githubusercontent.com/72839795/142096254-9ddd5f49-876e-45b0-a1ce-b08f559c4c0d.png">

**Comment by ThatGuySam** [comment]
Thanks for the update! It's is now live on the site! 

https://doesitarm.com/app/splice/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
