### ISSUE TITLE
n-track Studio

### ISSUE THREAD

**Issue by cameronbosch** [ThatGuySam/doesitarm#819]
Replace each second line your own text. 

**The official name of the app**
n-Track Studio

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
Yes, Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
N/A

**An Official App Download Page**
[Download n-track Studio](https://ntrack.com/download.php)

**Additional context**
Works fine, although I only used the free trial.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

<img width="262" alt="Screen Shot 2021-11-16 at 9 24 09 PM" src="https://user-images.githubusercontent.com/72839795/142105481-687211da-f42c-4fb0-ae74-b545c97995a6.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/n-track-studio/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
