### ISSUE TITLE
Skitch

### ISSUE THREAD

**Issue by froboy** [ThatGuySam/doesitarm#821]
**The official name of the app**
Skitch

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Yes, works via Translation or Virtualization

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Links or discussion**
None that I know of.

**An Official App Download Page**
https://evernote.com/products/skitch

**Additional context**
Dev is relatively dormant... but we can dream...

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info]**

<img width="780" alt="Screen Shot" src="https://user-images.githubusercontent.com/238201/142714655-dd67b1c1-301a-4069-b5c8-98c113239c55.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/skitch/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
