### ISSUE TITLE
Element Desktop is Apple Silicon Native

### ISSUE THREAD

**Issue by danielktdoranie** [ThatGuySam/doesitarm#823]
Replace each second line your own text. 

**The official name of the app**
Element Desktop

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
What's the current app status based off of current discussion or testing
✅ Yes, Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes. 

**An Official App Download Page**
https://www.element.io/get-started#download

**Additional context**
Add any other context or screenshots about the app request here. 

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
Yo, not installing either of those. :-) Y'all just gonna have to trust me. I don't have Rosetta 2 installed (and never will). I have also sent you a few confirmed apps to date.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/element/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
