### ISSUE TITLE
Discord Canary now M1 native

### ISSUE THREAD

**Issue by HilbertGilbertson** [ThatGuySam/doesitarm#825]
**The official name of the app**
Discord

**Is there a supported version available on a stable release channel?**
No

**Proposed New App Status**
✳️ Yes, works via Rosetta 2 with native support in beta

**Related Issue Tracker Links or discussion**
[Feedback thread](https://support.discord.com/hc/en-us/community/posts/360052558393-Discord-on-Apple-M1-Devices?page=15)

**An Official App Download Page**
[https://discord.com/api/download/canary?platform=osx](https://discord.com/api/download/canary?platform=osx)

**Additional context**
Discord native M1 support is now available in the Canary build. While this is not as yet a stable release update, it is worth listing the link to download the Canary build.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="988" alt="CleanShot 2021-11-25 at 01 52 46@2x" src="https://user-images.githubusercontent.com/24899023/143360988-56d0a40f-4d58-45a9-b023-ada3928c376b.png">

**Comment by ThatGuySam** [comment]
Thanks for the update!! It's is now live on the site! 

https://doesitarm.com/app/discord/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
