### ISSUE TITLE
balenaEtcher Support Removed

### ISSUE THREAD

**Issue by AngelofWoe** [ThatGuySam/doesitarm#827]
**The official name of the app**
balenaEtcher

**Is there a supported version available on a stable release channel?**
No, it was removed

**Proposed New App Status**
Yes, works via Translation or Virtualization

**Related Issue Tracker Links or discussion**
https://github.com/balena-io/etcher/issues/3593
https://github.com/balena-io/etcher/issues/3520

**An Official App Download Page**
The Apple Silicon download / Universal application download was removed.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

Freshly downloaded and installed from the only available macOS download links (https://github.com/balena-io/etcher/releases and https://www.balena.io/etcher/)
<img width="379" alt="Screen Shot 2021-11-26 at 19 32 44" src="https://user-images.githubusercontent.com/6075018/143664126-5327ea79-fe9c-4efb-a193-42c51411badf.png">
<img width="956" alt="Screen Shot 2021-11-26 at 19 33 29" src="https://user-images.githubusercontent.com/6075018/143664147-c77f2239-cc2e-4505-883d-8565c52d7048.png">

**Comment by ThatGuySam** [comment]
Thanks for the update! 

It is now live on the site! 

https://doesitarm.com/app/balenaetcher/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
