### ISSUE TITLE
POPO

### ISSUE THREAD

**Issue by Codeprh** [ThatGuySam/doesitarm#828]
**The official name of the app**
POPO

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Full Native Apple Silicon Support (version 3.25.8)

**Proposed App Category**
Social and communication

**Related Issue Tracker Links or discussion**
[officialWebsite](https://popo.netease.com/history.html)

**An Official App Download Page**
https://popo.netease.com/

**Additional context**
![image](https://user-images.githubusercontent.com/18324300/143982776-86db00bd-d4ea-4595-b078-65fdf3515586.png)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![image](https://user-images.githubusercontent.com/18324300/143982765-af3e2c45-13bb-427b-9ea8-a202bfeba413.png)
![image](https://user-images.githubusercontent.com/18324300/143983736-615d27e3-4ad0-44b4-a83f-a70017802c22.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/netease-popo/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
