### ISSUE TITLE
App Request: HiddenApp

### ISSUE THREAD

**Issue by designbyadrian** [ThatGuySam/doesitarm#829]
**The official name of the app**
[HiddenApp](https://hiddenapp.com)

**Is there a supported version available on a stable release channel?**
No, but support might send you the beta version if you ask nicely.

**Proposed App Status**
✳️ Intel running Rosetta, Apple Silicon version in late-stage beta, according to support.

**Proposed App Category**
Security, Theft Prevention

**Related Issue Tracker Links or discussion**
[Help Articles | Release Notes](https://help.hiddenapp.com/collection/17-update-release-notes)

**An Official App Download Page**
_Locked behind login_

**Additional context**
 The app is closed source and runs in a hidden process. I've contacted support and hoping for a response soon.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
TBC

_Updated: 2021-12-02_

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/hiddenapp/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
