### ISSUE TITLE
Tex Live

### ISSUE THREAD

**Issue by yanmarvin** [ThatGuySam/doesitarm#83]
**The official name of the app**
Tex Live

**Proposed App Status**
According to https://email.esm.psu.edu/pipermail/macosx-tex/2020-July/057120.html, Tex Live has been compiled for Apple Silicon and the result is good. 

**Related Issue Tracker Link or discussion**
https://email.esm.psu.edu/pipermail/macosx-tex/2020-July/057120.html

**An Official App Download Link**
The Tex Live binaries for Apple Silicon are not available on website yet.

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

Is this the same app as #95?

**Comment by yanmarvin** [comment]
Yes. It is the same app. Thanks.
