### ISSUE TITLE
Ableton Live 11

### ISSUE THREAD

**Issue by anarchylimes** [ThatGuySam/doesitarm#834]
Replace each second line your own text. 

**The official name of the app**
Ableton Live 11

**Is there a supported version available on a stable release channel?**
No

**Proposed New App Status**
What's the current app status based off of current discussion or testing
Yes, Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
https://www.ableton.com/en/blog/live-111-apple-silicon-support-now-in-public-beta/

**An Official App Download Page**
None so far

**Additional context**
Currently in public beta but will be supported in 11.1 stable release

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/46380964/144263711-238df4af-8ace-462e-8c2f-576cbf547d0d.png">
<img width="202" alt="image" src="https://user-images.githubusercontent.com/46380964/144264145-fd96ba00-8296-4ba8-9c5b-47992bd1ebed.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/ableton/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
