### ISSUE TITLE
CheatSheet (Native support for M1)

### ISSUE THREAD

**Issue by JuNkY14257** [ThatGuySam/doesitarm#835]
Replace each second line your own text. 

**The official name of the app**
CheatSheet

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
https://www.mediaatelier.com/CheatSheet/ 

**An Official App Download Page**
https://www.mediaatelier.com/CheatSheet/ 

**Additional context**
None

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="377" alt="Screen Shot 2564-12-02 at 10 34 39" src="https://user-images.githubusercontent.com/85490680/144355308-707bd970-a45d-4782-a3ed-e97e3aaae2c3.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/cheatsheet/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
