### ISSUE TITLE
Docker Desktop no longer requires Rosetta 2

### ISSUE THREAD

**Issue by rakleed** [ThatGuySam/doesitarm#837]
https://docs.docker.com/desktop/mac/release-notes/#docker-desktop-430

**Comment by ThatGuySam** [comment]
Thanks for the update!

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
Thanks for the patience on this! Update is now live on the site! 

https://doesitarm.com/app/docker/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
