### ISSUE TITLE
OpenRCT2 builds are universal

### ISSUE THREAD

**Issue by janisozaur** [ThatGuySam/doesitarm#839]
**The official name of the app**
OpenRCT2

**Is there a supported version available on a stable release channel?**
Yes - but they're just releases

**Proposed New App Status**
✅ Yes, Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
https://github.com/OpenRCT2/OpenRCT2/pull/15411

**An Official App Download Page**
https://openrct2.io/

**Additional context**
None

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
https://user-images.githubusercontent.com/17731933/133886266-f8cfb26c-8ef4-4c2c-b574-c0da7a182845.png

**Comment by ThatGuySam** [comment]
Thanks for the update! 

It is now live on the site! 

https://doesitarm.com/app/openrct2/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
