### ISSUE TITLE
AutoCAD

### ISSUE THREAD

**Issue by holymonson** [ThatGuySam/doesitarm#84]
**The official name of the app**
AutoCAD

**Proposed App Status**
🚫 Not yet supported only works on Intel-based Macs

**Related Issue Tracker Link or discussion**
https://forums.autodesk.com/t5/autocad-for-mac-forum/apple-silicon/m-p/9652836

**An Official App Download Link**
None

**Additional context**
None

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

We can just use the product page as the Download Link
https://www.autodesk.com/products/autocad/overview?plc=ACDIST&term=1-YEAR&support=ADVANCED&quantity=1

**Comment by ThatGuySam** [comment]
This is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/autocad

Feel free to browse through the other issues to help with missing info on other apps.
