### ISSUE TITLE
Burp Suite released a version for M1 Macs

### ISSUE THREAD

**Issue by fusuyfusuy** [ThatGuySam/doesitarm#840]
**The official name of the app**
Burp Suite 

**Is there a supported version available on a stable release channel?**
Yes

**An Official App Download Page**
https://portswigger.net/burp/releases/professional-community-2021-12

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.
