### ISSUE TITLE
Canva now has native M1 support!

### ISSUE THREAD

**Issue by JuNkY14257** [ThatGuySam/doesitarm#843]
**The official name of the app**
Canva 

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Native Apple Silicon Support

**An Official App Download Page**
https://www.canva.com/download/mac/

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="377" alt="Screen Shot 2564-12-13 at 22 39 36" src="https://user-images.githubusercontent.com/85490680/145850020-6cd36ea5-aacf-4914-a6ad-884f76c8247e.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! App is now live on the site! 

https://doesitarm.com/app/canva/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
