### ISSUE TITLE
HP Easy Start

### ISSUE THREAD

**Issue by FakeHeaven** [ThatGuySam/doesitarm#844]
**The official name of the app**
HP Easy Start

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
Yes, Native Apple Silicon Support

**An Official App Download Page**
https://123.hp.com/gb/en/devices/setup

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Silicon Info](https://i.imgur.com/5FkKGsM.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/hp-easy-start/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
