### ISSUE TITLE
LNMP ?

### ISSUE THREAD

**Issue by AlphaWong** [ThatGuySam/doesitarm#85]
php nginx mysql redis RabbitMQ are quite common for development.

Any news for them?

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm not sure on the whole stack but you can usually find Apple Silicon discussion in the respective Repos for each library

**Comment by ThatGuySam** [comment]
Closing this for now. Feel free to open new issues for each respective library

Also here are the site listings for each: 
https://doesitarm.com/formula/php/
https://doesitarm.com/formula/nginx/
https://doesitarm.com/formula/mysql/
https://doesitarm.com/app/redis/
https://doesitarm.com/formula/rabbitmq/
