### ISSUE TITLE
Postico

### ISSUE THREAD

**Issue by cyranix** [ThatGuySam/doesitarm#851]
**The official name of the app**
Postico

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Yes, Native Apple Silicon Support

**Proposed App Category**
Developer Tools

**Related Issue Tracker Links or discussion**
https://github.com/jakob/Postico/issues/740 — testing discussion
https://github.com/jakob/Postico/issues/762 — readiness confirmed

**An Official App Download Page**
https://eggerapps.at/postico/
(also available on App Store)

**Additional context**
See [changelog entry for v1.5.15](https://eggerapps.at/postico/docs/v1.5.15/changelist.html):

> Postico is now a universal binary with native code for Apple Silicon

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

<img width="1289" alt="Screen Shot 2021-12-29 at 22 36 31" src="https://user-images.githubusercontent.com/161077/147727710-ea650347-40b6-4e18-a9d9-67e6d27e00fc.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by cyranix** [comment]
PR is up: https://github.com/ThatGuySam/doesitarm/pull/855

**Comment by ThatGuySam** [comment]
Thanks for the patience on this! Update is now live on the site! 

https://doesitarm.com/app/postico/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
