### ISSUE TITLE
Signal (Desktop)

### ISSUE THREAD

**Issue by ThunderFD** [ThatGuySam/doesitarm#853]
**The official name of the app**
Signal

**Is there a supported version available on a stable release channel?**
Yes (since 5.27.0)

**Proposed New App Status**
✅ Yes, Native Apple Silicon Support**

**An Official App Download Page**
https://github.com/signalapp/Signal-Desktop/releases
or
https://signal.org/de/download/

**Additional context**
If Signal was already installed, auto update updated to Intel version on the latest update, but will apparently update to the Apple Silicon verion on the next automatic update.
Manual Downloads of the latest version already install with Apple Silicon support though.

**Full Screenshot with the App and Activity Monitor**
<img width="747" alt="Screenshot 2022-01-06 at 11 03 21" src="https://user-images.githubusercontent.com/17814079/148365935-b5c00035-f3c5-48e9-9292-56e68d2b7398.png">

**Comment by ThatGuySam** [comment]
Thanks for the update!

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
Thanks for the patience on this! Update is now live on the site(finally)! 

https://doesitarm.com/app/signal/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
