### ISSUE TITLE
Dropbox beta native support for Apple silicon (M1)

### ISSUE THREAD

**Issue by nagahama-chris** [ThatGuySam/doesitarm#856]
**The official name of the app**
Dropbox

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
Dropbox native support for Mac computers with Apple silicon (M1) processors is now available in beta to all users who have opted into Dropbox’s early releases program. 

**An Official App Download Page**
https://help.dropbox.com/zh-cn/installs-integrations/apple-silicon-support

**Comment by ThatGuySam** [comment]
Thanks for the patience on this! Update is now live on the site! 

https://doesitarm.com/app/dropbox/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
