### ISSUE TITLE
TeamViewer

### ISSUE THREAD

**Issue by acelibin** [ThatGuySam/doesitarm#86]
**The official name of the app**
TeamViewer

**An Official App Download Link**
https://www.teamviewer.com/en-us/

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by oliverlinsenmaier** [comment]
https://community.teamviewer.com/t5/Insider-Build-Information/macOS-15-12-4/m-p/107492#M44

**Comment by ThatGuySam** [comment]
@oliverlinsenmaier Any idea how long it takes the insider builds to hit the public channels?

**Comment by oliverlinsenmaier** [comment]
This should be today. :)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/teamviewer/

Feel free to browse through the other issues to help with missing info on other apps.

**Comment by KovalevArtem** [comment]
https://www.teamviewer.com/en/apple-silicon-support/
