### ISSUE TITLE
Beardie (Fork of BeardedSpice)

### ISSUE THREAD

**Issue by tomchilvers** [ThatGuySam/doesitarm#868]
**The official name of the app**
[Beardie](https://github.com/Stillness-2/beardie)

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Native Apple Silicon Support reported

**Proposed App Category**
System Tools

**Related Issue Tracker Links or discussion**
https://github.com/Stillness-2/beardie/issues/18

**An Official App Download Page**
https://github.com/Stillness-2/beardie/releases/latest

**Additional context**
Beardie is a fork of BeardedSpice, an application used to change what the media keys do on Mac devices.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1512" alt="Screenshot 2022-01-24 at 12 45 42" src="https://user-images.githubusercontent.com/66132512/150785342-4b528ad7-22b4-44f0-9600-45c0ba646703.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! Update is now live on the site! 

https://doesitarm.com/app/beardie/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
