### ISSUE TITLE
Coloban

### ISSUE THREAD

**Issue by pikil** [ThatGuySam/doesitarm#87]
**The official name of the app**
Coloban

**Proposed App Status**
Native support is currently in development, will be supporting closer to December as reported

**Tags**
Productivity tools, Communication tools

**Related Issue Tracker Link or discussion**
https://forum.coloban.com/

**An Official App Download Link**
https://www.coloban.com/download

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Do you know if there's a specific discussion we can link to for the tracker?

**Comment by pikil** [comment]
Sure, please see below, sorry...

https://forum.coloban.com/index.php?u=/topic/21/new-arm-based-apple-computers

**Comment by ThatGuySam** [comment]
That's perfect! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by pikil** [comment]
Hi Sam,
Sure, that's no problem at all :) Have just done that.

Cheers!

**Comment by ThatGuySam** [comment]
We're live!

https://doesitarm.com/app/coloban/
