### ISSUE TITLE
App Request: Adobe DNG Converter 

### ISSUE THREAD

**Issue by jonathandhn** [ThatGuySam/doesitarm#870]
**The official name of the app**
Adobe DNG Converter 

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Native Apple Silicon Support

**Proposed App Category**
Photo

**An Official App Download Page**
[adobe-dng-converter](https://helpx.adobe.com/camera-raw/using/adobe-dng-converter.html) 

![cp](https://user-images.githubusercontent.com/55917666/151272943-56686724-a826-4bde-a44f-fee9811e567e.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! App is now live on the site! 

https://doesitarm.com/app/adobe-dng-converter/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
