### ISSUE TITLE
Ableton Live Apple Silicon Support

### ISSUE THREAD

**Issue by ramirober** [ThatGuySam/doesitarm#873]
**The official name of the app**
Ableton Live

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
Yes, Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
https://www.ableton.com/en/blog/free-live-11-1-update-apple-silicon-support-out-now/

**An Official App Download Page**
https://www.ableton.com/

**Additional context**
None

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Captura de Pantalla 2022-02-03 a la(s) 16 08 50](https://user-images.githubusercontent.com/47870721/152412184-50d3b08b-a255-474b-bc2b-134671765493.png)

**Comment by ThatGuySam** [comment]
Thanks for the update! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by TRUBDUBZ** [comment]
Ahh i was just coming to add this! great idea. I have a lot of other .vst plugins that work well on my M1 but im new to git so im struggling on adding to these repos.. if anyone would be able to assist i would really appreciate!

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/ableton/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
