### ISSUE TITLE
RescueTime

### ISSUE THREAD

**Issue by schlenks** [ThatGuySam/doesitarm#876]
**The official name of the app**
[RescueTime Listing](https://doesitarm.com/app/rescuetime/)

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Native Apple Silicon Support

**An Official App Download Page**
[RescueTime Download](https://www.rescuetime.com/rtx/download)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
Activity Monitor showing RescueTime processes:
![image](https://user-images.githubusercontent.com/69008/152643483-f8cd849d-dfd9-4f8a-b55f-4e14089c363b.png)

**Comment by ThatGuySam** [comment]
@schlenks Betterr late than never!

App is now live on the site! 

https://doesitarm.com/app/rescuetime

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
