### ISSUE TITLE
BetterTouchTool

### ISSUE THREAD

**Issue by gershik** [ThatGuySam/doesitarm#88]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**The official name of the app**
BetterTouchTool

**Proposed App Status**
✅ Yes, fully supported as of v3.502

**Related Issue Tracker Link or discussion**
https://community.folivora.ai/

**An Official App Download Link**
https://folivora.ai/

**Comment by ThatGuySam** [comment]
Thanks for the App Request!

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
Thanks for the Pull Request! App is now live on the site! 

https://doesitarm.com/app/bettertouchtool/

Feel free to browse through the other issues to help with missing info on other apps.

<img width="1792" alt="Screen Shot 2020-11-14 at 5 13 26 PM" src="https://user-images.githubusercontent.com/2830379/99158828-c95cfc00-269c-11eb-8ef0-d0b5971b3ae1.png">
