### ISSUE TITLE
UTM

### ISSUE THREAD

**Issue by Madhawa97** [ThatGuySam/doesitarm#880]
**The official name of the app**
UTM

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Native Apple Silicon Support

**Proposed App Category**
Developer Tools

**Related Issue Tracker Links or discussion**

**An Official App Download Page**
https://mac.getutm.app/

**Additional context**

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1680" alt="Screenshot 2022-02-10 at 18 11 19" src="https://user-images.githubusercontent.com/70215958/153410680-dbd1a5bf-e791-4419-abf5-cdf751f9dea3.png">

**Comment by Madhawa97** [comment]
If I wanted to create a PR, do I need to wait till an issue receives the "Ready to Add" flair?

**Comment by Madhawa97** [comment]
You're welcome Sam. Sure I'll do that way.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/utm/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
