### ISSUE TITLE
Pareto Security

### ISSUE THREAD

**Issue by zupo** [ThatGuySam/doesitarm#884]
**The official name of the app**
Pareto Security

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Native Apple Silicon Support

**Proposed App Category**
[VPNs, Security, and Privacy](https://github.com/ThatGuySam/doesitarm/blob/master/README.md#vpns-security-and-privacy)

**Related Issue Tracker Links or discussion**
Not relevant, we had native Apple Silicon support since we launched back in July.

**An Official App Download Page**
https://paretosecurity.com/pricing

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

Note that `Architecture` column is now `Kind`, and `Apple` indicates Apple Silicon.

![image](https://user-images.githubusercontent.com/311580/154124650-e622976e-5fed-4c1b-9cb1-d38d79c39a27.png)

**Comment by zupo** [comment]
Sure thing! Here we go: https://github.com/ThatGuySam/doesitarm/pull/900

**Comment by ThatGuySam** [comment]
@zupo App is now live on the site! 

https://doesitarm.com/app/pareto-security/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
