### ISSUE TITLE
NVIDIA GeForce NOW

### ISSUE THREAD

**Issue by rakleed** [ThatGuySam/doesitarm#889]
**The official name of the app**
NVIDIA GeForce NOW

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✳️ Yes, works via Translation or Virtualization

**Related Issue Tracker Links or discussion**

**An Official App Download Page**
*The same*

**Additional context**
Apparently in the changelog it was reported that the application works correctly through Rosetta 2.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![2022-02-17_14-23-04](https://user-images.githubusercontent.com/19418601/154471893-c3c7cda6-0638-426c-b292-738a855dcd2e.png)

**Comment by ThatGuySam** [comment]
Thanks for the update! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/nvidia-geforce-now
`✅ Yes, Full Native Apple Silicon Support as of v2.0.27`

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
