### ISSUE TITLE
Paraview

### ISSUE THREAD

**Issue by LucasCampos** [ThatGuySam/doesitarm#89]
**The official name of the app**
Paraview

**Proposed App Status**
Seems to be building on Intel Big Sur according to this [YouTube video](https://www.youtube.com/watch?v=CQvmLns6L-E)

**Related Issue Tracker Link or discussion**
Could not find anything. Closest was [this thread](https://www.paraview.org/pipermail/paraview/2010-January/015482.html) about building for ARM from about 10 years ago.

**An Official App Download Link**
https://www.paraview.org/download/

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

We'll keep looking and see if we can find a solid source to establish the current status

**Comment by ThatGuySam** [comment]
@harryzcy Good find! 

App is now live on the site! 

https://doesitarm.com/app/paraview/

Feel free to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by SettNegro** [comment]
Now the app is fully working natively from version 5.10 RC
<img width="1728" alt="Screenshot 2021-11-01 at 18 53 53" src="https://user-images.githubusercontent.com/31413993/139717565-963ece9c-ce62-4193-96ec-fee0cff4da45.png">
1

**Comment by ThatGuySam** [comment]
@SettNegro Good catch! Update is now live on the site! 

https://doesitarm.com/app/paraview/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
