### ISSUE TITLE
Ableton Live 11 Suite

### ISSUE THREAD

**Issue by TRUBDUBZ** [ThatGuySam/doesitarm#896]
**The official name of the app**
What's the full official name of the app
Ableton Live 11 Suite
**Is there a supported version available on a stable release channel?**
Yes or No
Yes
**Proposed App Status**
What's the current app status based off of current discussion or testing
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend
I dont see anything about the program on this site. but i did run it through the compatibility test and 
**Proposed App Category**
What category should the app go under
Music and Audio Tools
**Related Issue Tracker Links or discussion**
This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes.
https://help.ableton.com/hc/en-us/articles/115001261150-Mac-Compatibility-with-Live
**An Official App Download Page**
This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site. 
https://help.ableton.com/hc/en-us/articles/211934625-Latest-Live-Version-
**Additional context**
Add any other context or screenshots about the app request here. 

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
A screenshot with Activity Monitor open showing the App's architecture type. Example: #358
![Screen Shot 2022-02-27 at 7 59 35 AM](https://user-images.githubusercontent.com/95402733/155887562-a5b00a62-fba7-4cd8-802b-c97604111fa1.png)

**Comment by TRUBDUBZ** [comment]
![Screen Shot 2022-02-27 at 7 54 34 AM](https://user-images.githubusercontent.com/95402733/155887390-29b6d8ed-37da-437f-a030-9660698d9e8b.png)

**Comment by ThatGuySam** [comment]
Thanks for the update! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by TRUBDUBZ** [comment]
> Owner

i apologize this is one of the first times ive used github. would you mind walking me though that?

**Comment by ThatGuySam** [comment]
You’ll go to the README and make the edit and then submit it as a Pull Request. 

https://github.com/ThatGuySam/doesitarm/blob/master/README.md

Once the Pull Request is submitted we can deploy it immediately if everything looks good. 

https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/creating-an-issue-or-pull-request#creating-a-pull-request

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/ableton/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
