### ISSUE TITLE
Asana native support (also known as Electron Asana) 

### ISSUE THREAD

**Issue by ocre12** [ThatGuySam/doesitarm#899]
Replace each second line your own text. 

**The official name of the app**
Asana

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
None found, only noticed in the Activity monitor that the app was running as an Apple chip based one.

**An Official App Download Page**
https://asana.com/download

**Additional context**
Tried on a MacBook Pro M1 (2021)

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1728" alt="Capture d’écran 2022-03-02 à 09 33 00" src="https://user-images.githubusercontent.com/55391067/156324829-de729b10-de78-4bad-be93-0416bf8bfa36.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/asana/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by matthewruzzi** [comment]
It still says "App has not yet been reported to be native to Apple Silicon". 

![Image](https://github.com/user-attachments/assets/2672cbea-d19f-435e-8df6-a963331c38bc)
