### ISSUE TITLE
Sublime Text

### ISSUE THREAD

**Issue by prajwalrao** [ThatGuySam/doesitarm#9]
It should most likely work as there used to a working Linux ARM beta available.

**Comment by ThatGuySam** [comment]
Is there a public issue or tracker you've found?

**Comment by ThatGuySam** [comment]
It looks like they were testing Mac ARM builds in August

https://forum.sublimetext.com/t/arm-build/5882/88

**Comment by ThatGuySam** [comment]
It's up!

https://doesitarm.com/app/sublime-text/
