### ISSUE TITLE
Update on Microsoft Office 365 Support

### ISSUE THREAD

**Issue by jrb545** [ThatGuySam/doesitarm#90]
Office 365 apps will run under Rosetta 2 as of the current November release version 16.43.20110804.

The Universal App versions of the Office 365 apps are currently only available on the MAU Beta Channel, starting with version 16.44.20111100.

Here's a link about it: https://macadmins.software/silicon/

**Comment by ThatGuySam** [comment]
Thanks for the update! 

I'll put it on my to-do list

**Comment by ThatGuySam** [comment]
Update is live!

https://doesitarm.com/app/microsoft-office-365/

<img width="1792" alt="Screen Shot 2020-11-13 at 7 19 49 PM" src="https://user-images.githubusercontent.com/2830379/99134912-6fe5c600-25e5-11eb-8f12-04d6aa280304.png">
