### ISSUE TITLE
Hoplite Key Manager

### ISSUE THREAD

**Issue by RICCIARDI-Adrien** [ThatGuySam/doesitarm#904]
**The official name of the app**
Hoplite Key Manager

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Yes, Native Apple Silicon Support

**Proposed App Category**
VPNs, Security, and Privacy

**Related Issue Tracker Links or discussion**
https://hoplitekeymanager.com/download/archives/desktop-application/#platforms_compatibility

**An Official App Download Page**
https://hoplitekeymanager.com/index.php?page=download

**Additional context**
Apple Silicon compatibility starts with app version 1.3

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Capture d'écran](https://user-images.githubusercontent.com/4292857/156935490-b29d7b2e-3c66-44ae-a6a4-3b7e758ae65d.png)

**Comment by RICCIARDI-Adrien** [comment]
![Capture d’écran 2022-03-13 à 14 28 44](https://user-images.githubusercontent.com/4292857/158071895-994e09e5-8c17-44c5-b4dc-399ba87f279d.png)

**Comment by ThatGuySam** [comment]
Thanks for the App Request! Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/hoplite-key-manager/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
