### ISSUE TITLE
Microsoft OneDrive

### ISSUE THREAD

**Issue by fz1b** [ThatGuySam/doesitarm#906]
**The official name of the app**
Microsoft OneDrive

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
https://techcommunity.microsoft.com/t5/microsoft-onedrive-blog/apple-silicon-support-in-ga-and-kfm-for-macos-in-public-preview/ba-p/3215671

**An Official App Download Page**
https://support.microsoft.com/en-us/office/onedrive-release-notes-845dcf18-f921-435e-bf28-4e24b95e5fc0#OSVersion=Mac

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="888" alt="Screen Shot 2022-03-12 at 4 35 32 PM" src="https://user-images.githubusercontent.com/24773864/158039878-19539a8e-7093-401b-b31d-9feaf2998c96.png">

**Comment by ThatGuySam** [comment]
Thanks for the update! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/microsoft-onedrive/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
