### ISSUE TITLE
Discord 

### ISSUE THREAD

**Issue by donavanbecker** [ThatGuySam/doesitarm#907]
Discord just released an update for the Official Discord app, which now supports Apple Silicon. 

**The official name of the app**
What's the full official name of the app? 

Discord

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
What's the current app status based off of current discussion or testing
Yes, Native Apple Silicon Support

**An Official App Download Page**
https://discord.com

**Additional context**
Add any other context or screenshots about the app request here. 

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
As screenshot with Activity Monitor open showing the App's architecture type. 

<img width="1727" alt="Screen Shot 2022-03-17 at 4 52 01 PM" src="https://user-images.githubusercontent.com/9875439/158900684-0a8d22a9-d7f3-4ff4-b305-fe0362330859.png">

**Comment by danieljaffe** [comment]
Can also confirm! Yay!

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/discord/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
