### ISSUE TITLE
Tidal

### ISSUE THREAD

**Issue by Timwun** [ThatGuySam/doesitarm#915]
**The official name of the app**
TIDAL

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
Does support M1

**Related Issue Tracker Links or discussion**
#314 

**An Official App Download Page**
https://tidal.com/download

**Additional context**
NA

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

<img width="1173" alt="grafik" src="https://user-images.githubusercontent.com/13067978/160232578-d4c21cfd-a17a-4313-a95d-adf52848056f.png">

**Comment by ThatGuySam** [comment]
Thanks for the update! 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by Timwun** [comment]
Sure! Will do in few hours :)

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/tidal/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
