### ISSUE TITLE
Please add PyPy3

### ISSUE THREAD

**Issue by SichangHe** [ThatGuySam/doesitarm#916]
**The official name of the app**
PyPy3

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✳️ Yes, works via Translation or Virtualization

**Proposed App Category**
Developer Tools, Homebrew

**Related Issue Tracker Links or discussion**
https://foss.heptapod.net/pypy/pypy/-/issues/3283

**An Official App Download Page**
https://www.pypy.org/download.html

Normally:

```shell
brew install pypy3
```

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
A screenshot with Activity Monitor open showing the App's architecture type. Example: #358
![image](https://user-images.githubusercontent.com/84777573/160275223-8d532a17-1f36-441e-ada1-ee580b6c37cb.png)

**Comment by SichangHe** [comment]
[Mac meets Arm64](https://www.pypy.org/posts/2020/12/mac-meets-arm64-940822335619099039.html) from the PyPy team.

Seemingly, they are not porting PyPy to Arm Mac yet.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/pypy3/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
