### ISSUE TITLE
Xojo

### ISSUE THREAD

**Issue by jkleroy** [ThatGuySam/doesitarm#92]
**The official name of the app**
Xojo

**Proposed App Status**
In progress

**Related Issue Tracker Link or discussion**
Official post: https://blog.xojo.com/2020/11/10/apple-silicon-and-big-sur-support-coming-in-xojo-2020r2/

**An Official App Download Link**
https://www.xojo.com/download/

**Additional context**
Developer Tools category

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/xojo

Feel free to browse through the other issues to help with missing info on other apps.

**Comment by jkleroy** [comment]
Actually, Xojo works correctly using Rosetta.

**Comment by ThatGuySam** [comment]
@jkleroy Great! Can you share a link or a screenshot so I can add it as a the source

**Comment by ThatGuySam** [comment]
@Gam3sFan Thanks for the tip! Update is now live on the site! 

https://doesitarm.com/app/xojo/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
