### ISSUE TITLE
DeSmuME update

### ISSUE THREAD

**Issue by sh4tteredd** [ThatGuySam/doesitarm#929]
**The official name of the app**
DeSmuME

**Is there a supported version available on a stable release channel?**
No

**Proposed New App Status**
With the latest build arm64 is fully compatible

**An Official App Download Page**
http://desmume.org/download/

<img width="255" alt="Screenshot 2022-04-18 at 11 49 49" src="https://user-images.githubusercontent.com/55893559/163791622-fd943044-69f2-4a30-b758-f6b893544d02.png">
<img width="193" alt="Screenshot 2022-04-18 at 11 52 58" src="https://user-images.githubusercontent.com/55893559/163791632-69d326c6-1c6e-4f3f-9ce3-d55e0de6821b.png">

**Comment by ThatGuySam** [comment]
Is there an official arm64 download link? 

In theory, it's Apple Silicon Native but most users aren't going to know how to build a binary and if the developer doesn't provide an official link then we can't provide a safe link for people to download.

**Comment by sh4tteredd** [comment]
yeah, its on the webpage, the link is [Mac Fat Binary: April 2, 2022 Build](https://drive.google.com/uc?export=download&id=1858ZPCpZBnaAXfX0nHSQZ1kahpgeRjau)

<img width="493" alt="Screenshot 2022-05-07 at 21 22 29" src="https://user-images.githubusercontent.com/55893559/167268867-21f9d865-5905-4523-b625-097dc76bba50.png">

**Comment by ThatGuySam** [comment]
@sh4tteredd Ah my bad, I completely missed that. 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by sh4tteredd** [comment]
yes yes, no hurry, thanks

**Comment by ThatGuySam** [comment]
Update is now live on the site! 

https://doesitarm.com/app/desmume

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
