### ISSUE TITLE
Nix

### ISSUE THREAD

**Issue by domenkozar** [ThatGuySam/doesitarm#93]
For a great example issue check out https://github.com/ThatGuySam/doesitarm/issues/31

**The official name of the app**
Nix

**Proposed App Status**
Not working, although there is progress made.

**Related Issue Tracker Link or discussion**
https://github.com/NixOS/nixpkgs/issues/95903

**An Official App Download Link**
https://nixos.org/download.html

**Additional context**
Add any other context or screenshots about the app request here.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

I'm currently working on getting to all the requests, however, if you'd like help push things along feel free to add context based on the [App Request Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/ISSUE_TEMPLATE/app-request-template.md)

**Comment by domenkozar** [comment]
That's what my issue uses, I'm a bit confused.

**Comment by ThatGuySam** [comment]
Yeah, it's just missing a download link we can provide to people

**Comment by domenkozar** [comment]
I've added the link so that once it's working it can be promoted.
