### ISSUE TITLE
Rambox

### ISSUE THREAD

**Issue by saenzramiro** [ThatGuySam/doesitarm#931]
**The official name of the app**
Rambox

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
Yes, Native Apple Silicon Support

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Links or discussion**
https://github.com/orgs/ramboxapp/projects/5?fullscreen=true
https://twitter.com/TadashiOkoshi/status/1516952398325219328

**An Official App Download Page**
https://rambox.app/download/macos

**Additional context**
Add any other context or screenshots about the app request here. 

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![image](https://user-images.githubusercontent.com/2694669/164546059-dd4ead8c-835f-4ce7-8785-5f752a816cb0.png)
![image](https://user-images.githubusercontent.com/2694669/164546273-66666a69-db31-4cb2-8cde-5c8318122f9d.png)

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/rambox/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
