### ISSUE TITLE
Microsoft Teams ARM support (Beta)

### ISSUE THREAD

**Issue by paradoxally** [ThatGuySam/doesitarm#932]
**The official name of the app**
Microsoft Teams

**Is there a supported version available on a stable release channel?**
No, ARM support is currently in beta.

**Proposed New App Status**
Yes, Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
Office update history: https://docs.microsoft.com/en-us/officeupdates/update-history-beta-channel
Press release: https://9to5mac.com/2022/04/25/microsoft-teams-apple-silicon-mac/

**An Official App Download Page**
https://statics.teams.cdn.office.net/production-osx/1.5.00.11505/Teams_osx.pkg

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Silicon App](https://user-images.githubusercontent.com/1304041/165177306-adab8d6f-4ec7-419e-9b0e-a463fd1c8a8b.png)

**Comment by ItzLevvie** [comment]
Hi,

I'm the developer of https://github.com/ItzLevvie/MicrosoftTeams-msinternal for tracking various Microsoft Teams rings.

This should be on hold for now as it currently isn't in beta. These internal builds include various bugs that can hamper your workflow.

Please wait for our company to announce this officially - I'm speaking from a contractor perspective as people.

Thank you.

**Comment by paradoxally** [comment]
Hello @ItzLevvie,

Thanks for informing me regarding how Microsoft update their software.

Indeed, I followed MacRumors forums on M1 support and the 9to5Mac press release, and thought the M1 version was in beta.

Funnily enough, you mention that the internal builds have more issues but my experience has been anything but that. It's complete breath of fresh air on the Beta compared to the atrocious performance of the Intel (stable) version.

Either way, it's a great (and long overdue) step forward.

Thanks.

**Comment by ThatGuySam** [comment]
@ItzLevvie We'll keep the status as is for the time being. 

Feel free to comment on this issue when there is an Official Beta or Full release of Teams that is both Apple Silicon Native and Microsoft approved.

**Comment by affeldt28** [comment]
It's official. Native Apple Silicon support.
https://learn.microsoft.com/en-us/officeupdates/teams-admin#september-22-2022

**Comment by ThatGuySam** [comment]
@affeldt28 Thanks for the update! 

Looks like we're ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
@affeldt28 @ItzLevvie Microsoft Teams is now reported as native!

https://doesitarm.com/app/microsoft-teams

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
