### ISSUE TITLE
SecureCRT.app

### ISSUE THREAD

**Issue by arnohub** [ThatGuySam/doesitarm#933]
**The official name of the app**
SecureCRT.app

**Is there a supported version available on a stable release channel?**
✅ This app is natively compatible with Apple Silicon!

**Proposed New App Status**
What's the current app status based off of current discussion or testing
You can check the different statused here:https://www.vandyke.com/products/securecrt/history.txt

**An Official App Download Page**
https://www.vandyke.com/cgi-bin/releases.php?product=securecrt

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="892" alt="Snipaste_2022-05-01_14-01-04" src="https://user-images.githubusercontent.com/49862797/166134264-587eb81b-45c8-4de9-80a1-f3e8741271dc.png">

**Comment by ThatGuySam** [comment]
Thanks for the update!

We're now live on the site! 

https://doesitarm.com/app/securecrt/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
