### ISSUE TITLE
Sophos Home

### ISSUE THREAD

**Issue by affeldt28** [ThatGuySam/doesitarm#936]
**The official name of the app**
[Sophos Home](https://home.sophos.com)

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Native Apple Silicon Support

**Proposed App Category**
VPN, Security, and Privacy

**Related Issue Tracker Links or discussion**
https://support.home.sophos.com/hc/en-us/articles/360052382272-Installing-Sophos-Home-on-M1-Silicon-Apple-computers-ARM-

**An Official App Download Page**
https://my.sophos.com/download

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1440" alt="Bildschirmfoto 2022-05-06 um 09 33 11" src="https://user-images.githubusercontent.com/45835050/167087637-7926cfc7-f7a7-41e7-8bec-30972ab2226d.png">

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/sophos-home/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
