### ISSUE TITLE
Update on Chrome Support

### ISSUE THREAD

**Issue by mumchristmas** [ThatGuySam/doesitarm#94]
Here's a link about it: https://developer.apple.com/forums/thread/657657

**Comment by ThatGuySam** [comment]
Thanks for the update! 

I've got it on my to-do list now

**Comment by ThatGuySam** [comment]
Update is live!

https://doesitarm.com/app/chrome/

<img width="1792" alt="Screen Shot 2020-11-13 at 7 11 04 PM" src="https://user-images.githubusercontent.com/2830379/99134613-247ee800-25e4-11eb-9b6d-db23dc4efcee.png">
