### ISSUE TITLE
QQ音乐(QQ Music)

### ISSUE THREAD

**Issue by PiraticAshin** [ThatGuySam/doesitarm#941]
**The official name of the app**
QQ音乐(QQ Music)

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
✅ Yes, Native Apple Silicon Support

**An Official App Download Page**
https://y.qq.com/download/mac.html?part=1&ADTAG=YQQ

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1162" alt="image" src="https://user-images.githubusercontent.com/36768731/169533971-fbdabd02-650e-4960-885c-ab3ddedf860f.png">
<img width="246" alt="image" src="https://user-images.githubusercontent.com/36768731/169534461-df97ae01-a39d-414a-9983-12489b301081.png">

**Comment by ConnHowe** [comment]
@ThatGuySam

**Comment by kswssnwe16** [comment]
还好

**Comment by ThatGuySam** [comment]
@ConnHowe @PiraticAshin Thanks for the update! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/qq

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
