### ISSUE TITLE
TG Pro 2.69 was actually still x64

### ISSUE THREAD

**Issue by iam3ddy** [ThatGuySam/doesitarm#946]
Replace each second line your own text. 

**The official name of the app**
What's the full official name of the app? 
TG Pro
**Is there a supported version available on a stable release channel?**
Yes or No
No
**Proposed New App Status**
What's the current app status based off of current discussion or testing
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend
not native ARM
**Related Issue Tracker Links or discussion**
This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes. 

**An Official App Download Page**
This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site. 

**Additional context**
Add any other context or screenshots about the app request here. 

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
As screenshot with Activity Monitor open showing the App's architecture type. 

<img width="792" alt="CleanShot 2022-05-28 at 06 19 06@2x" src="https://user-images.githubusercontent.com/21017389/170795843-bedaa0cf-22c3-4212-b613-0bb34e870ce9.png">

**Comment by ThatGuySam** [comment]
Can you elaborate? 

It shows up as Universal when you open its info in finder and they reported it as Apple Silicon Native in Release Notes

https://www.tunabellysoftware.com/tgpro/releasenotes/#stacks_in_1077

<img width="265" alt="Screen Shot 2022-06-04 at 1 38 38 PM" src="https://user-images.githubusercontent.com/2830379/172021271-ecea7f8b-37b2-4710-86c3-56826c522db2.png">

**Comment by ThatGuySam** [comment]
Closing this for now
