### ISSUE TITLE
Taskade

### ISSUE THREAD

**Issue by johnxie** [ThatGuySam/doesitarm#953]
**The official name of the app**
[Taskade](https://taskade.com)

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Native Apple Silicon Support

**Proposed App Category**
Productivity Tools

**Related Issue Tracker Links or discussion**
[Reddit](https://www.reddit.com/r/Taskade/comments/lmwhs5/mac_app_now_supports_apple_m1_chip/) and [Blog](https://www.taskade.com/blog/org-chart-view-ios-android-apple-m1-windows-apps-updates/)

**An Official App Download Page**
https://www.taskade.com/downloads

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="634" alt="Screen Shot 2022-06-29 at 1 54 28 PM" src="https://user-images.githubusercontent.com/792088/176542946-69c1c74d-60bb-4048-81b8-fb8cf64aceee.png">

P.S. It looks like https://doesitarm.com/app/taskade/ is available but it is missing the download link and is not listed under the [Productivity Tools category](https://github.com/ThatGuySam/doesitarm#productivity-tools). Thanks!

**Comment by ThatGuySam** [comment]
Thanks for the update! App is now live on the site! 

https://doesitarm.com/app/taskade

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
