### ISSUE TITLE
Hatsune Miku: Project DIVA Mega Mix+ v1.0.2 works with Parallels Desktop v17.1.4 (51567)

### ISSUE THREAD

**Issue by OwenTruong** [ThatGuySam/doesitarm#959]
**The official name of the app**
Hatsune Miku: Project DIVA Mega Mix+

**Is there a supported version available on a stable release channel?**
Yes, Mega Mix+ v1.0.2 works with Parallels Desktop v17.1.4 (51567) and Windows 11 ARM Beta Build 22598 as of 07/25/22. 

**Proposed App Status**
✳️ Yes, works via Translation or Virtualization

**Proposed App Category**
Entertainment and Media Apps

**Related Issue Tracker Links or discussion**
N/A

**An Official App Download Page**
https://store.steampowered.com/app/1761390/Hatsune_Miku_Project_DIVA_Mega_Mix/

**Additional context**
Mega Mix+ v1.0.2 does not work on the most recent release of Crossover as of 07/25/22. First issue that came up was to change the Wine configuration from Windows 7 to Windows 10. The second issue was that after switching to Windows 10 for Wine, the game crashes at the loading screen.

Also, game runs 59-60fps (1440p) on my M1 MBA in loading and select screen. When playing a song like Hibana (one of the more gpu intensive songs), fps drops and ranges between 30-55fps (1440p). Fps is capped at 60fps unless one installs a mod.

07/26/22: After more testing, with DOF Remover (DOF - Depth of Field) and High Refresh Rate Mod, most songs average 70-90fps and with Hibana's lowest being 70fps on a 1440p144 monitor.

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**

![Screen Shot 2022-07-25 at 10 33 59 AM (2)](https://user-images.githubusercontent.com/44269025/180802640-200bc098-86f0-4fda-8df9-f84b546482ad.png)

<img width="1275" alt="Screen Shot 2022-07-25 at 10 33 07 AM" src="https://user-images.githubusercontent.com/44269025/180802669-8280a05f-f60a-4f33-bbf3-18a83919820b.png">

**Comment by amandaallissa** [comment]
Hello, 
Thank you for reaching out about this app. 
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise we'll add it when time permits.

**Comment by DekoMoon** [comment]
Sweet!

**Comment by ThatGuySam** [comment]
@OwenTruong Thanks for the request! App is now live on the site! 

https://doesitarm.com/app/hatsune-miku-project-diva-mega-mix

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
