### ISSUE TITLE
homebrew

### ISSUE THREAD

**Issue by nighto** [ThatGuySam/doesitarm#96]
**The official name of the app**
homebrew

**Proposed App Status**
Not yet supported, but work is going on

**Related Issue Tracker Link or discussion**
https://github.com/Homebrew/brew/issues/9082

**An Official App Download Link**
https://brew.sh

**Additional context**
Used by developers to install dependencies, and heavy-users to install tools on cli.

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

Is this an update to the current status?

https://doesitarm.com/app/homebrew/

**Comment by ThatGuySam** [comment]
I'm going to close this issue for now. 

Feel free to open it again if there's an update that we to report. 

Also, feel free to browse through the other issues to help with missing info

**Comment by tonyunreal** [comment]
Apple Silicon support is now official with [Homebrew 3.0.0](https://brew.sh/2021/02/05/homebrew-3.0.0/). 

This doesn't change the current situation though, as you still need to have two installations (one arm64 and one x64) of Homebrew on the same machine, the Homebrew team merely recognized this as an official solution in the new release. See [this blog post](https://soffes.blog/homebrew-on-apple-silicon) on how to do this properly.

Some of the bottles are still intel only at the moment, so I don't think the status on doesitarm needs to change to "native", as doing so would probably mislead people into believing they either don't need a separate local repo for intel binaries, or everything just simply works as Apple Silicon native.
