### ISSUE TITLE
MongoDB 6.0.0 fully supports Apple Sillicon

### ISSUE THREAD

**Issue by andrecastropaiva** [ThatGuySam/doesitarm#962]
Replace each second line your own text. 

**The official name of the app**
What's the full official name of the app? 
MongoDB

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
What's the current app status based off of current discussion or testing
✅ Yes, Native Apple Silicon Support

**Related Issue Tracker Links or discussion**
This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes. 

**An Official App Download Page**
[This is so that when the App is ready for Apple SiIlicon users can quickly download the app from an official site. ](https://www.mongodb.com/try/download/community)

**Additional context**
Add any other context or screenshots about the app request here. 

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
As screenshot with Activity Monitor open showing the App's architecture type.

**Comment by amandaallissa** [comment]
Hi, 
Thank you for reaching out about this app.
Looks like this is ready to go.

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise we'll add it when time permits.
