### ISSUE TITLE
EasyFind does not work on Apple Silicon

### ISSUE THREAD

**Issue by Stokestack** [ThatGuySam/doesitarm#965]
Replace each second line your own text. 

**The official name of the app**
EasyFind

**Is there a supported version available on a stable release channel?**
Yes

**Proposed New App Status**
Not working

**Related Issue Tracker Links or discussion**
https://discourse.devontechnologies.com/t/no-search-result-in-easyfind/70639

**An Official App Download Page**
This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site. 

**Additional context**
I searched the exact same two files with the same version of EasyFind on Intel and an M1. The expected contents were found on Intel, but not on Apple Silicon. Screen shots attached. This has been reported to the publisher.

<img width="694" alt="EasyFindNope" src="https://user-images.githubusercontent.com/196304/187766018-403df5c3-e9c8-4563-a7ae-719ff5374d6b.png">

**Comment by ThatGuySam** [comment]
@Stokestack Update is now live on the site! 

https://doesitarm.com/app/easyfind

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by Stokestack** [comment]
I should have come back to update this; it turns out to be an ill-advised default in EasyFind if I remember correctly. I don't think it's actually platform-related.

**Comment by ThatGuySam** [comment]
Ah, okay, thanks for the correction. I'll switch it back
