### ISSUE TITLE
it's arm now

### ISSUE THREAD

**Issue by ayechief** [ThatGuySam/doesitarm#966]
<img width="809" alt="image" src="https://user-images.githubusercontent.com/10886930/188080525-9ea8e37d-ef77-4f88-a6aa-4fd67379c85b.png">
<img width="284" alt="image" src="https://user-images.githubusercontent.com/10886930/188080580-95df3ada-c4c6-430d-bd5a-a9f43303b95b.png">

**Comment by ThatGuySam** [comment]
Thanks for the update! It's now live on the site! 

https://doesitarm.com/app/facebook-messenger-desktop

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
