### ISSUE TITLE
HuionTablet

### ISSUE THREAD

**Issue by Madhawa97** [ThatGuySam/doesitarm#969]
**The official name of the app**
HuionTablet

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Native Apple Silicon Support

**Proposed App Category**
System Tools

**An Official App Download Page**
https://www.huion.com/index.php?m=content&c=index&a=lists&catid=16&myform=2&down_title1=HS611&down_os=macOS&down_type=Driver&category=undefined

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
![Screenshot 2022-09-02 at 01 35 41](https://user-images.githubusercontent.com/70215958/188232318-06bf4cbc-cd80-474e-b2cf-888df642e9d1.jpeg)

**Comment by ThatGuySam** [comment]
@Madhawa97 Thanks for the App Request! 
App is now live on the site! 

https://doesitarm.com/app/huiontablet

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.

**Comment by Madhawa97** [comment]
Awesome!
