### ISSUE TITLE
Velja

### ISSUE THREAD

**Issue by Madhawa97** [ThatGuySam/doesitarm#970]
**The official name of the app**
Velja

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Native Apple Silicon Support

**Proposed App Category**
Productivity Tools

**An Official App Download Page**
https://apps.apple.com/us/app/velja/id1607635845?mt=12

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1680" alt="Screenshot 2022-09-05 at 01 29 31" src="https://user-images.githubusercontent.com/70215958/188333478-4f5bd4a2-1728-4c33-a0c3-cb6bd4a065e8.png">

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/velja

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
