### ISSUE TITLE
Later

### ISSUE THREAD

**Issue by Madhawa97** [ThatGuySam/doesitarm#971]
**The official name of the app**
Later

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Native Apple Silicon Support

**Proposed App Category**
Productivity Tools

**An Official App Download Page**
https://getlater.app

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1680" alt="Screenshot 2022-09-05 at 01 36 41" src="https://user-images.githubusercontent.com/70215958/188333817-ac89cb80-8391-473d-9966-8559e6ceecf1.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/later

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
