### ISSUE TITLE
GoodNotes

### ISSUE THREAD

**Issue by Madhawa97** [ThatGuySam/doesitarm#972]
**The official name of the app**
GoodNotes

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Native Apple Silicon Support

**Proposed App Category**
Productivity Tools

**An Official App Download Page**
https://apps.apple.com/app/apple-store/id1444383602?pt=525432&ct=goodnotes.com&mt=8

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1497" alt="Screenshot 2022-09-05 at 02 41 12" src="https://user-images.githubusercontent.com/70215958/188333864-7d5dff9a-3d72-40f8-af90-cd3079c2e3c2.png">

**Comment by ThatGuySam** [comment]
Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
