### ISSUE TITLE
forticlient works on arm m1, i just did it

### ISSUE THREAD

**Issue by mchyzer** [ThatGuySam/doesitarm#973]
Replace each second line your own text. 

**The official name of the app**
What's the full official name of the app? 
Forticlient VPN client

**Is there a supported version available on a stable release channel?**
Its the free version but i assume the supported one works too

**Proposed New App Status**
What's the current app status based off of current discussion or testing
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend

Works

**Related Issue Tracker Links or discussion**
This can be an Issue from a public repo related to the app (Github, Bitbucket, Gitlab, etc...) or a public discussion forum of some kind. Basically, some kind of resources that can be checked for status changes. 

**An Official App Download Page**
This is so that when the App is ready for Apple SIlicon users can quickly download the app from an official site. 

https://www.fortinet.com/support/product-downloads#vpn

**Additional context**
Add any other context or screenshots about the app request here. 

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
As screenshot with Activity Monitor open showing the App's architecture type. 

![image](https://user-images.githubusercontent.com/4495069/189356537-6994738c-9197-4ea6-ad8b-cdeba820dc68.png)

**Comment by mchyzer** [comment]
7.0.7.0245

**Comment by ThatGuySam** [comment]
@mchyzer Thanks for the update! We're now live on the site! 

https://doesitarm.com/app/forticlient

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
