### ISSUE TITLE
Updated info - Splashtop Business ver.3.5.2.1 now can run natively on M1 mac without rossetta

### ISSUE THREAD

**Issue by steffichuang** [ThatGuySam/doesitarm#974]
**The official name of the app**
Splashtop Business

**Is there a supported version available on a stable release channel?**
Yes 

**Proposed New App Status**
What's the current app status based off of current discussion or testing
Splashtop Business app ver.3.5.2.1 has M1 native support

**Related Issue Tracker Links or discussion**
https://support-splashtopbusiness.splashtop.com/hc/en-us/articles/360052579572-Does-Splashtop-support-Apple-Silicon-M1-Mac-

**An Official App Download Page**
https://www.splashtop.com/tw/downloads

**Additional context**
Add any other context or screenshots about the app request here. 

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
https://support-splashtopbusiness.splashtop.com/hc/en-us/articles/360052579572-Does-Splashtop-support-Apple-Silicon-M1-Mac-

**Comment by ThatGuySam** [comment]
Thanks for the App Request! 

App is now live on the site! 

https://doesitarm.com/app/splashtop-business

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
