### ISSUE TITLE
BuhoCleaner

### ISSUE THREAD

**Issue by AskFeeds** [ThatGuySam/doesitarm#981]
**The official name of the app**
BuhoCleaner

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Native Apple Silicon Support

**Proposed App Category**
**[System Tools](https://github.com/ThatGuySam/doesitarm#system-tools)**

**Related Issue Tracker Links or discussion**
**[Version release note](https://www.drbuho.com/buhocleaner/download)**

**An Official App Download Page**
**[Download](https://www.drbuho.com/buhocleaner/download)**

**Full Screenshot with the App and Activity Monitor**
<img width="1072" alt="Screen_Shot_2022-10-19_at_3_27_23_PM" src="https://user-images.githubusercontent.com/33158015/196625664-cdf16f5f-5285-4640-bfed-adbea1901c5b.png">

**Comment by ThatGuySam** [comment]
@AskFeeds 
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise, I'll add it when time permits.

**Comment by ThatGuySam** [comment]
@AskFeeds 
App is now live on the site! 

https://doesitarm.com/app/buhocleaner

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
