### ISSUE TITLE
OpenVPN Connect

### ISSUE THREAD

**Issue by selchukdursun** [ThatGuySam/doesitarm#984]
Replace each second line your own text. 

**The official name of the app**
What's the full official name of the app? 
OpenVPN 3.4.0

**Is there a supported version available on a stable release channel?**
Yes

https://forums.openvpn.net/viewtopic.php?t=32414

**Comment by ThatGuySam** [comment]
@SuperEdison 
Thanks for the App Request! 

Looks like this is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise, I'll add it when time permits.

**Comment by affeldt28** [comment]
<img width="1028" alt="Bildschirmfoto 2023-07-04 um 22 04 13" src="https://github.com/ThatGuySam/doesitarm/assets/45835050/46a4e059-ae3f-4b73-b481-56a5ad6991a5">
<img width="396" alt="Bildschirmfoto 2023-07-04 um 22 04 23" src="https://github.com/ThatGuySam/doesitarm/assets/45835050/fe373572-ca4a-471b-b141-0f58a004e3a3">

**Comment by ThatGuySam** [comment]
@affeldt28 Thanks for the Pull Request! Update is now live on the site! 

https://doesitarm.com/app/openvpn-connect

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
