### ISSUE TITLE
CrossOver

### ISSUE THREAD

**Issue by EddaAkikusa** [ThatGuySam/doesitarm#99]
**The official name of the app**
CrossOver

**Proposed App Status**
Runs via Rosetta.
But may not be available in native.

**Related Issue Tracker Link or discussion**
[Official Blog](https://www.codeweavers.com/blog/jwhite/2020/11/10/its-great-to-live-in-interesting-times)

**An Official App Download Link**
[Homepage(Login needed)](https://www.codeweavers.com/)
[CrossOver 20.0.2](http://media.codeweavers.com/pub/crossover/cxmac/demo/crossover-20.0.2.zip)

**Comment by ThatGuySam** [comment]
Thanks for the App Reuqest! 

For status, we'll say: ✅ Yes, it works via Rosetta 2

**Comment by ThatGuySam** [comment]
This is ready to go. 

Feel free to make a pull request using the [App Addition Template](https://github.com/ThatGuySam/doesitarm/blob/master/.github/PULL_REQUEST_TEMPLATE/app_addition_template.md) otherwise I'll add it when time permits.

**Comment by ThatGuySam** [comment]
Apple is live! 

https://doesitarm.com/app/crossover/

Thanks for the pull request!

**Comment by KovalevArtem** [comment]
M1 Macs can now run Windows apps and games through CrossOver 20
https://9to5mac.com/2020/11/18/m1-macs-can-now-run-windows-apps-and-games-through-crossover-20/
https://www.codeweavers.com/blog/jwhite/2020/11/18/okay-im-on-the-bandwagon-apple-silicon-is-officially-cool
