### ISSUE TITLE
RunJS

### ISSUE THREAD

**Issue by lukehaas** [ThatGuySam/doesitarm#991]
**The official name of the app**
RunJS

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
✅ Yes, Native Apple Silicon Support as of v1.14.0

**Proposed App Category**
Developer Tools

**Related Issue Tracker Links or discussion**
https://github.com/lukehaas/RunJS/blob/master/CHANGELOG.md#version-1140---21-february-2021

**An Official App Download Page**
https://runjs.app

**Additional context**

![Screenshot 2022-11-21 at 10 49 35](https://user-images.githubusercontent.com/741344/203032662-774bc349-80a2-4000-9b4f-cd6cf7b37155.png)

**Full Screenshot with the App and Activity Monitor**

![Screenshot 2022-11-21 at 10 54 22](https://user-images.githubusercontent.com/741344/203032930-6d0dfbac-a157-4202-b14d-d3a5871c1e83.png)

**Comment by lukehaas** [comment]
PR raised here: https://github.com/ThatGuySam/doesitarm/pull/992

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/runjs

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
