### ISSUE TITLE
Schedulist

### ISSUE THREAD

**Issue by robertherber** [ThatGuySam/doesitarm#993]
**The official name of the app**
Schedulist

**Is there a supported version available on a stable release channel?**
Yes

**Proposed App Status**
What's the current app status based off of current discussion or testing
You can check the different statused here: https://github.com/ThatGuySam/doesitarm/blob/master/README.md#legend

**Proposed App Category**
Productivity

**An Official App Download Page**
https://apps.apple.com/se/app/schedulist-to-do-planner/id1568459470?l=en

**Full Screenshot with the App and Activity Monitor(if self reporting) or [Silicon Info](https://github.com/billycastelli/Silicon-Info)**
<img width="1209" alt="Screenshot 2022-11-21 at 14 44 59" src="https://user-images.githubusercontent.com/1467411/203083755-06ab5e42-2cc0-458f-939c-f81cfbf22be3.png">

**Comment by ThatGuySam** [comment]
App is now live on the site! 

https://doesitarm.com/app/schedulist

Feel free to comment on this issue for any future updates. 

Until then, you're welcome to browse through the other [M1 Issues](https://github.com/ThatGuySam/doesitarm/issues?q=is%3Aopen+is%3Aissue+label%3A%22Needs+M1+Testing%22) to help with missing info on other apps.
